### ISSUE TITLE
PDF tagging: ToC uses L instead of a TOCI

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1000]
The ToC uses L instead of a TOCI (maybe developers are HTML people?)

From https://github.com/metanorma/mn2pdf/issues/201

**Comment by Intelligent2013** [comment]
XSLT:
```xml
<fo:block role="TOCI">
...
  <fo:list-block>
  ...
    <fo:list-item>
      <fo:list-item-label end-indent="label-end()">
        <fo:block>
          <xsl:value-of select="@section"/>
        </fo:block>
      </fo:list-item-label>
      <fo:list-item-body start-indent="body-start()">
        <fo:block ...>
...
      </fo:list-item-body>
    </fo:list-item>
  </fo:list-block>
</fo:block>
```
`L` inside `TOCI`:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/aa2ddb65-bc8f-4165-b3c1-ed91d31ebc64)

Apache FOP creates `L`, `LI`, ... automatically for `list-block`, ... elements.
I'll investigate how to dismiss it.

**Comment by Intelligent2013** [comment]
Expected tags structure:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/50764bd2-13d5-46cb-bb6b-76a6b3f6448b)

**Comment by Intelligent2013** [comment]
From https://xmlgraphics.apache.org/fop/2.8/accessibility.html:
`FOP provides a default mapping of Formatting Objects to elements from that standard set. For example, fo:page-sequence is mapped to ‘Part’, fo:block is mapped to ‘P’, fo:list-block to ‘L’, etc.`

FOP creates very deep structure:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/fc7b1988-cc07-4ba1-97cb-b89aab836642)
for each XSL-FO element. But we need only `TOC`->`TOCI`->`Link`.
In the Apache FOP there isn't feature to skip/omit the role (there is `role="artifact" to skip whole element). So, I see preliminary two options to adapt Apache FOP:
- allow `role=""` 
- introduce FOP extension `fox:skip-role="true"`
In this case the tag will be omitted in the structure tree.
Both options need time to deep into FOP sources.

**Comment by Intelligent2013** [comment]
`role="SKIP"` added. The XSL-FO element with `role="SKIP"` will be omitted in the tags structure tree.
