### ISSUE TITLE
PDF tagging: Lists are getting tagged as paragraphs and not lists

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1002]
Lists are getting tagged as paragraphs and not lists

From: https://github.com/metanorma/mn2pdf/issues/201

**Comment by Intelligent2013** [comment]
Current tagging:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/137d7612-3ed5-4996-b078-cd01cd92114c)

**Comment by Intelligent2013** [comment]
Done:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/3af0d939-d403-4274-b65c-c1f99bb73270)

**Comment by Intelligent2013** [comment]
Tags for bibliographic items flattened, but we need the tags post-processing for merging the sequence of substrings:

![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a79110e3-031a-4b2c-8cab-3da7ab08d348)

**Comment by Intelligent2013** [comment]
The tags tree looks so:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/5d550197-b3f9-424a-b37a-7f197062b4ae)
because each text  container relates to the object (XSL-FO element):
```
<fo:list-item-body start-indent="body-start()">
	<fo:block role="SKIP">
		<fo:inline role="SKIP" font-size="75%">
			<fo:inline role="SKIP" font-size="133.33333333333334%">B</fo:inline>ERNER<fo:inline role="SKIP" font-size="133.33333333333334%"> </fo:inline>
			<fo:inline role="SKIP" font-size="133.33333333333334%">D</fo:inline>
			<fo:inline role="SKIP" font-size="133.33333333333334%">.</fo:inline>
			<fo:inline role="SKIP" font-size="133.33333333333334%">L</fo:inline>
			<fo:inline role="SKIP" font-size="133.33333333333334%">.</fo:inline>
			<fo:inline role="SKIP" font-size="133.33333333333334%">,</fo:inline>
			<fo:inline role="SKIP" font-size="133.33333333333334%"> </fo:inline>
			<fo:inline role="SKIP" font-size="133.33333333333334%">&amp;</fo:inline>
			<fo:inline role="SKIP" font-size="133.33333333333334%"> </fo:inline>
			<fo:inline role="SKIP" font-size="133.33333333333334%">B</fo:inline>ROWN<fo:inline role="SKIP" font-size="133.33333333333334%"> </fo:inline>
			<fo:inline role="SKIP" font-size="133.33333333333334%">J</fo:inline>
			<fo:inline role="SKIP" font-size="133.33333333333334%">.</fo:inline>
		</fo:inline> Protein nitrogen combustion method collaborative study I. Comparison with Smalley total Kjeldahl nitrogen and combustion results. <fo:inline font-style="italic">J. Am. Oil Chem. Soc.</fo:inline> 1994, <fo:inline font-weight="bold">
			<fo:inline keep-together.within-line="always">71</fo:inline>
		</fo:inline> (11) pp 1291-1293</fo:block>
</fo:list-item-body>
```
We can't merge the text nodes in the tags tree without modifying the objects structure (as I understood). So, the neighboring *XSL-FO elements* `<fo:inline role="SKIP" font-size="133.33333333333334%"` should be merged.

**Comment by Intelligent2013** [comment]
Done:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/9f486a28-70b6-444f-9962-68ff1754548a)

Note: Two text chunks `B` and `ERNER` due small caps text:
```xml
<fo:inline font-size="133.33333333333334%" role="SKIP">B</fo:inline>ERNER
```

- [ ] Next task is skipping `Span` tags inside `Lbody`.

**Comment by Intelligent2013** [comment]
No need to skip the `Span` tags inside `LBody` because:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/4bef0f36-111a-46bc-a38c-aecf9629fc76)
