### ISSUE TITLE
PDF tagging: Some bad semantics: footnote, P tags, etc

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1003]
Various other bad semantics here and there e.g. footnote indicator marked as “Note”, various P tags covering >1 para, invalid reading order in various places seemingly associated with cross-document links, etc.

From: https://github.com/metanorma/mn2pdf/issues/201

**Comment by Intelligent2013** [comment]
Example `P` in `P`:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/1ee7fec3-5882-4627-8178-9bfb661aedff)

This occurs due the block element `note` inside the block element `p`:
```xml
<p id="_24f2eb3c-d04a-ae7f-b7f6-d7508208e30d">The mass fraction of extraneous matter and defective kernels in husked and milled rice, whether or not parboiled, determined in accordance with <xref target="AnnexA">
		<span class="citeapp">Annex A</span>
	</xref>, shall not be greater than the values specified in <xref target="table1">
		<span class="citetbl">Table 1</span>
	</xref>.<note id="_37eebd65-fcfd-1ff3-167d-42106bc02dc2">
		<name>NOTE</name>
		<p id="_cffbd604-0bed-6331-229b-1db2259caaa8">Lower mass fractions of moisture are sometimes needed for certain destinations depending on the climate, duration of transport and storage. For further details, see <xref type="inline" target="ISO6322-1">ISO 6322-1</xref>, <xref type="inline" target="ISO6322-2">ISO 6322-2</xref> and <xref type="inline" target="ISO6322-3">ISO 6322-3</xref>.</p>
	</note>
</p>
```

The `fo:block` for `note` should be marked with `role="Note"`.

**Comment by Intelligent2013** [comment]
> The `fo:block` for `note` should be marked with `role="Note"`.

No, it's wrong.

From `Tagged PDF Best Practice Guide:`:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/e87eeb51-8b05-4fae-8fec-36e19939a0fd)

I.e. `note` should be moved after `p` (outside of `p`). I have to fully refactored the XSLT (with more testing, visual checking, etc.)

**Comment by Intelligent2013** [comment]
May be there is more simple solution - post-processing PDF tags tree editing via PDFBox after Apache FOP PDF generation. I'll study it.

**Comment by Intelligent2013** [comment]
`Div...Div`:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/ceecb83b-2045-481f-a3c7-41ee14502f36)
occurs due the helper `fo:block-container` for alignment:
```xml
<fo:block-container margin-left="0mm">
	<fo:block-container margin-left="0mm" margin-right="0mm">
```
To do:
- [ ] add `role="SKIP"` for such `fo:block-container`s

**Comment by Intelligent2013** [comment]
- [ ] empty tags should be removed
For instance:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/10317d77-cf49-4266-9f0d-d436d2f1e15f)

These empty tags occurs due empty XSL-FO elements `fo:block`, by two reason:
- `fo:block` intended for PDF layout
- `fo:block` doesn't contain the text by some condition

There are two approach to remove empty tags:
- don't add such tags, or pre-process tags tree - need deep dive into Apache FOP sources
- add `role="SKIP"` for `fo:block` if it doesn't contain text - need big XSL-FO refactoring
1st approach is more preferable, because in XSL-FO there are a lot of workaround solutions for Apache FOP issues.

**Comment by Intelligent2013** [comment]
> empty tags should be removed

In Apache FOP there is a special attribute:
> To remove empty fo:blocks from the structure tree, you can set the keep-empty-tags to false.
`<accessibility keep-empty-tags="false">true</accessibility>`

Added.

**Comment by Intelligent2013** [comment]
Current footnote tags:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/10d4c758-a7fd-480f-93ab-a9f36c7b3101)

Expected structure:
```
<P> {
	<Reference> {
		<Lbl>
		}
	<Note> {
		<Lbl>
		<P>
	}
}
```

**Comment by Intelligent2013** [comment]
Tags tree for footnotes almost done:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/7d971be6-9a7f-4392-b80b-92af19856dcc)


By some reason, Apache FOP adds the tag `Div` for `fo:block-container` (marked with `role="SKIP"`):
```xml
<fo:footnote-body role="Note">
	<fo:block-container text-indent="0" start-indent="0" role="SKIP">
		<fo:block font-weight="normal" font-style="normal" text-indent="0" start-indent="0" font-size="10pt" margin-bottom="12pt" role="SKIP">
			<fo:inline keep-with-next.within-line="always" padding-right="3mm" role="Lbl" id="footnote_en_1_2">2)</fo:inline>
			<fo:inline role="P">Formerly denoted as 15 % (<fo:inline role="SKIP" keep-together.within-line="always">m/m</fo:inline>).</fo:inline>
		</fo:block>
	</fo:block-container>
</fo:footnote-body>
```

**Comment by Intelligent2013** [comment]
- [ ] the inner cover page tags tree contains nested 5 `Div`s:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/2813203a-1cd0-410c-9e8f-f9617073d5f9)

**Comment by Intelligent2013** [comment]
- [ ] wrong tags structure for Figure:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/76cd719b-d3bd-4500-a02d-9e2f8bc6b69d)

Expected:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/e496baaf-61b8-4c57-922f-87972f0867f9)

**Comment by Intelligent2013** [comment]
- [ ] each Bibliography item represents as a standalone list (`L`) with one list item (`LI`):
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/15ebe5f4-5d8a-4b8f-99db-21ba1d36e5f8)

**Comment by Intelligent2013** [comment]
- [ ] outer `Div` for list `L`:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/279d4003-5003-4319-a301-89be711c79fc)

**Comment by Intelligent2013** [comment]
- [ ] `P` inside `H1`:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/3f981a56-efe7-4fb9-a54a-87ffb843f5a1)

**Comment by Intelligent2013** [comment]
- [ ] empty `Span` between section number and title
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/219c2aa9-b8f7-4374-9ec3-906198b867aa)

**Comment by Intelligent2013** [comment]
- [ ] wrong tags structure for term title
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/311821c9-57c6-4b64-8063-f0bcf19f8132)

**Comment by Intelligent2013** [comment]
- [ ] wrong `Span` tag instead of `P` for inline paragraph:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a70e2a01-a1a0-43ba-b636-8e2c88df7212)

**Comment by Intelligent2013** [comment]
`Note` moved under the paragraph:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/f72f5fa9-90cb-456e-9b62-6d18d6dbeaf3)
