### ISSUE TITLE
Add line numbers

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1004]
Source: https://github.com/metanorma/mn2pdf/issues/201

As titled, for testing purposes.

**Comment by ronaldtse** [comment]
We also need to add source code and source code with line numbers to the iso rice document to demonstrate.

**Comment by Intelligent2013** [comment]
ISO XSLT updated for the line numbering feature. To render line numbers, add the document attribute:
```adoc
:presentation-metadata-linenumbers: true
```
PDF rendering example:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/f0daaa88-2e58-4005-88cb-615085003c18)


Source code with line numbers (`linenumbers`):
```adoc
[source,ruby,linenumbers]
--
puts "Hello, world."
%w{a b c}.each do |x|
  puts x
end
--
```

PDF rendering example:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/d6839fdf-3194-4cbc-9f3c-fa207380af6f)


PDF generated for `mn-samples-iso\sources\international-standard\rice-en.final.adoc` (with updates mentioned above):
[rice-en.final.presentation.pdf](https://github.com/metanorma/metanorma-iso/files/11621567/rice-en.final.presentation.pdf)

@ronaldtse Is that enough?

**Comment by ronaldtse** [comment]
@Intelligent2013 can we document this on metanorma.org and produce a blog post on it? Thanks!
