### ISSUE TITLE
Concept mention support of disambiguation of "domain" for 2 concepts with the same designation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1021]
In ISO 10303-2, there is:
* the generic concept in Clause 3 called "expression" (no domain)
* the EXPRESS ENTITY in Clause 5 called "expression" (with a domain of "resource: mathematical_functions_schema")

In Clause 5, which is all about EXPRESS ENTITYs, when I want to refer to "expression" I want the second one.

Currently, our concept mention syntax does not support disambiguating these two entries:
```
... {{expression}}
```

This might just refer to the first entry, but the user cannot know which entry it will refer to.

We need a way to disambiguate with the domain, such as:
```
... {{<resource: mathematical_functions_schema> expression}}
```

or the first (empty domain)

```
... {{<> expression}}
```

**Comment by ReesePlews** [comment]
@ronaldtse that is very interesting;  

if i am understanding this comment correctly, how is this issue typically handled in the body of the document? i dont recall ever seeing  "domain" notation "<>" used outside of clause 3, and i dont think that adding clause 3 term numbers is used or allowed outside of clause 3.

that is a very interesting issue and  i can see where this would really create some ambiguities.   

in a digital document, i guess it could be possible to "clarify these differences" using some type of "mouse over" technique but that is not possible in a paper version.

i will continue to monitor this;

**Comment by opoudjis** [comment]
> i dont recall ever seeing "domain" notation "<>" used outside of clause 3, and i dont think that adding clause 3 term numbers is used or allowed outside of clause 3.

Of course not, but concept cross-references do apply within Clause 3, and the disambiguating domain is going to be needed in there, even if the term clause number is provided.

I'm not going to implement {{<> X}}: {{X}} on its own will refer to a term without a domain.

**Comment by opoudjis** [comment]
Will abort if any two preferred designations are the same, and are not disambiguated by domain.

**Comment by ronaldtse** [comment]
> I'm not going to implement `{{<> X}}`: `{{X}}` on its own will refer to the term without a domain.

This kind of makes sense but this means that all previous concept mentions that referred to a term with domain will now fail:

```
=== foo
domain:[x]

...

== Text

{{foo}} => will fail
```

**Comment by opoudjis** [comment]
I'll add the term without the domain as a synonym, if the term is not otherwise ambiguous. I've got the rest of this working, but that will need to wait until the weekend, when I work again.
