### ISSUE TITLE
Missing xref in concept

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1029]
Source issue: https://github.com/metanorma/mnconvert/issues/398

The source document: https://github.com/metanorma/iso-iec-smart-terms

### Old Presentation XML (generated on Jan 27, 2023):

Semantic part:
- `refterm` contains the term `body`
- there is `xref` with `@target`
```xml
	<semantic__concept>
		<semantic__refterm>body</semantic__refterm>
		<semantic__renderterm>body</semantic__renderterm>
		<semantic__xref target="semantic__term-body"/>
	</semantic__concept>.</semantic__p>
</semantic__termnote>
```

Presentation part:
- there is `xref` with clause's number
```xml
<termnote id="_bfb979a4-45cc-ca7a-c742-7d4998469fd9">
	<name>Note 3 to entry</name>
	<p id="_f249ecbf-6d9c-eac8-ecb6-c5bcc501a713">A standardization process is typically established by consensus and approved by a recognized 
                        <em>body</em>(
                        <xref target="term-body">
			<span class="citesec">4.2.1</span>
		</xref>).</p>
</termnote>
```

### New (generated today):
Semantic part
- `refterm` contains `domain` value + term `body`
- no `xref`
```xml
       <semantic__concept>
	<semantic__refterm>&#x3c;responsible for standards and regulations&#x3e; body</semantic__refterm>
	<semantic__renderterm>body</semantic__renderterm>
	</semantic__concept>.</semantic__p>
</semantic__termnote>
```

Presentation part - just `<em>body</em>`:
```xml
<termnote id="_c488ff57-c12a-703c-1196-5cf6b307ae69">
	<name>Note 3 to entry</name>
	<p id="_6399a754-cb1d-bf29-93dc-ff9a5d0169b8">A standardization process is typically established by consensus and approved by a recognized 
		<em>body</em>.</p>
</termnote>
```

**Comment by opoudjis** [comment]
I've been forced to do significant refactoring of terms processing recently: https://github.com/metanorma/metanorma-iso/issues/1021.

Both behaviours are possible, but wrong: they would apply if this were the second time "body" were mentioned in the term, and if there were two "body" terms defined with different domains. Since neither is the case, this is a bug.

**Comment by Intelligent2013** [comment]
@opoudjis thanks!
