### ISSUE TITLE
(HTML) ISO 10303-49 Table of contents order incorrect

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1043]
From @anermina at https://github.com/metanorma/iso-10303-detached-docs/issues/196

> New HTML lists Annex B first and then Annex A in the Table of contents 

<img width="311" alt="image" src="https://github.com/metanorma/metanorma-iso/assets/11865/98c1e5f0-7543-4ec7-a6c2-9c81edd2b5dd">

Possibly related to:
* https://github.com/metanorma/metanorma-ogc/issues/597 
* https://github.com/metanorma/metanorma-itu/issues/469
* https://github.com/metanorma/metanorma-standoc/issues/816

**Comment by opoudjis** [comment]
Fixed by https://github.com/metanorma/metanorma-ogc/issues/597

![Screenshot 2023-11-12 at 17 18 57](https://github.com/metanorma/metanorma-iso/assets/1911039/19088ebc-623f-4e69-a14b-c9160f11d828)
