### ISSUE TITLE
Feature request: Encode "Corrected date" on ISO cover page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1045]
From https://github.com/metanorma/iso-iec-2382/issues/3

Original:
<img width="482" alt="Screenshot 2023-11-10 at 4 56 23 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/973d7b79-10c7-4031-a847-a8bd0bdf47f7">

Encoded:
<img width="502" alt="Screenshot 2023-11-10 at 4 56 38 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/0aed011e-3788-436f-a2e7-5fe85e3d61d4">

This issue also existed on ISO/IEC 27001:2022.

**Comment by opoudjis** [comment]
We indeed have provision for date updated, but not date corrected. I do not at all want to extend the typology of dates, but it is true that updated is assumed to refer to new editions, and this is a version incorporating corrigenda, so it does not rise to the level of an update.

This will have implications for @andrew2net

**Comment by opoudjis** [comment]
The markup is the document attribute `:date-corrected: 2022-10`
