### ISSUE TITLE
(all outputs) Provide ISO/IEC logos and footer on dual-logo documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1046]
From: https://github.com/metanorma/iso-iec-2382/issues/4

ISO/IEC 2382 is an "ISO/IEC" document which means there needs to be two logos and the footer message should also reflect "ISO/IEC":

Original:
<img width="542" alt="Screenshot 2023-11-10 at 4 56 58 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/8e320a4f-5a05-47c2-abcf-941c8037db0e">
<img width="631" alt="Screenshot 2023-11-10 at 4 58 19 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/030386d6-b306-4303-8135-2a1f707f25e6">

Encoded:
<img width="479" alt="Screenshot 2023-11-10 at 4 57 42 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/188d0607-7a5f-4f05-809c-f462f967c125">
<img width="598" alt="Screenshot 2023-11-10 at 4 58 25 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/3d77c494-3bfe-4299-bf02-5ccf328069c1">

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/iso-iec-2382/issues/4
Related issue: https://github.com/metanorma/metanorma.org/issues/725

**Comment by opoudjis** [comment]
ISO HTML does not include logos, and neither does ISO DOC. So nothing for me to action until they do. Issue is done.
