### ISSUE TITLE
PDF: References of "ISO/IEC" has prefix running into document number

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1047]
https://github.com/metanorma/iso-iec-2382/issues/6

PDF:
<img width="599" alt="Screenshot 2023-11-10 at 5 06 16 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/f5cbf046-85de-44be-97b6-70b2f4f40add">

HTML:
<img width="951" alt="Screenshot 2023-11-10 at 5 08 34 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/31e1609b-7987-4a07-a2e5-66ade12930bd">

**Comment by Intelligent2013** [comment]
This fixed fixed here https://github.com/metanorma/iso-iec-2382/issues/6 a month ago.
Let me check again.

**Comment by Intelligent2013** [comment]
Yes, fixed:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a8a234c1-b82a-4bb2-bb43-0ef935e4e2b4)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
