### ISSUE TITLE
Add date corrected to front page

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#1048]
Follow-on from https://github.com/metanorma/metanorma-iso/issues/1045

There will now be `<date type="corrected">` in ISO documents. The text "correction version" will be expected in the front page if it is present. I will provide that in localisation strings as "corrected_version".

**Comment by Intelligent2013** [comment]
Done:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/1460be90-7e1f-4a8a-aeb9-54bbd12673c1)
