### ISSUE TITLE
French: lacks the "Normative references" clause (HTML, PDF) (ISO/IEC 2382)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1053]
From https://github.com/metanorma/iso-iec-2382/issues/17

Metanorma does not fully recognize that the "Normative references" section in French:

HTML:
<img width="999" alt="Screenshot 2023-11-16 at 8 50 53 PM" src="https://github.com/metanorma/metanorma-iso/assets/11865/118fba7d-6794-48a9-860d-d11638686591">

PDF:
<img width="951" alt="Screenshot 2023-11-16 at 8 27 01 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/0a7df5d1-b989-4ff6-a32a-b5886d149447">

Encoding:
```adoc
[bibliography]
[title="Normative references"]
== Références normatives
```

**Comment by opoudjis** [comment]
Markup error
