### ISSUE TITLE
French version: in PDF, the Bibliography clause title is rendering with a `[_bibliography]` prefix, and not using the French "Bibliographie" title

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1054]
From https://github.com/metanorma/iso-iec-2382/issues/18

HTML: using the French title, but missing all bibliographic entries.

<img width="1233" alt="Screenshot 2023-11-16 at 8 34 17 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/8a1c88cc-32ce-4b7c-b683-98b5909d4a4e">

PDF: using the English title, provides entries, but has an unwanted prefix of `[_bibliography]` in the clause title
<img width="944" alt="Screenshot 2023-11-16 at 8 33 59 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/bc0f0832-039f-42dc-a789-247a16ac9834">

**Comment by opoudjis** [comment]
Markup error.
