### ISSUE TITLE
French version: Terms and definitions clause not recognized; no boilerplate

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1055]
From https://github.com/metanorma/iso-iec-2382/issues/19

English HTML:
<img width="1059" alt="Screenshot 2023-11-16 at 8 46 53 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/41634e64-e5c0-4992-88f7-2b1d2b4ab235">

French HTML:
<img width="1045" alt="Screenshot 2023-11-16 at 8 47 10 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/d9032ba7-99ad-426f-999c-13941e61c2ba">

Encoding:

```adoc
[title="Terms and definitions"]
== Termes et définitions

[glossarist,./../concepts,concepts]
----
{% assign target_lang = "fre" %}
{% for concept in concepts %}
{% include "concept" %}
{% endfor %}
----
```

**Comment by opoudjis** [comment]
Markup error.

I daresay, user error. Also, RTMFM. https://www.metanorma.org/author/topics/document-format/sections/#fixed-section-names It's heading=, not title=
