### ISSUE TITLE
(PDF) Copyright section "run-in" of the publisher name and year

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1059]
<img width="823" alt="Screenshot 2023-11-25 at 4 05 14 PM" src="https://github.com/metanorma/metanorma-iso/assets/11865/c44fa062-f9c7-4e4b-883a-239b52bbf9c2">

**Comment by Intelligent2013** [comment]
@ronaldtse this issue occurs due the line
```xml
 <xsl:strip-space elements="*"/>
```
in https://github.com/metanorma/isodoc/blob/main/lib/isodoc/presentation_function/bibdata.rb. The XSLT removes the spaces between the elements.
The presentation XML after preprocess XSLT doesn't contain space between `span`:
```xml
<boilerplate>
    <copyright-statement>
      <clause id="_copyright_protected_document" inline-header="false" obligation="normative">
        <title depth="1">COPYRIGHT PROTECTED DOCUMENT</title>
        <p id="boilerplate-year">© <span class="std_publisher">ISO</span><span class="std_docNumber">2016</span></p>
```

I've added `&#xa0;` in the source boilerplate in https://github.com/metanorma/metanorma-iso/pull/1060.

@opoudjis is this properly solution?

**Comment by opoudjis** [comment]
I actually had solved it as 

````
<p id="boilerplate-year">© <span class="std_publisher">ISO&nbsp;</span><span class="std_docNumber">2016</span></p>
````

to prevent any swallowing up of spaces between tags. I'll pop that in now.
