### ISSUE TITLE
Re-consider need to abort due to duplicated preferred terms

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1065]
[ISO 5598](https://github.com/metanorma/iso-5598) is a trilingual document, English, French and German.

It happens that in English, all preferred terms are unique (due to ISO DIR 2 requirements), but in French and German, it contains multiple duplicated preferred terms.

* https://github.com/metanorma/iso-5598/issues/7
* https://github.com/metanorma/iso-5598/issues/8

Personally I think there are reasons for these duplications, for example, look at this:

English:
```
[[term_3.2.571]]
==== pressure gauge

device that measures and indicates gauge pressure (3.2.346)

[[term_3.2.577]]
==== pressure-measuring instrument

device that measures and indicates the level, variations and differences of pressure (3.2.560)
```

German:
```
[[term_3.2.571]]
==== Druckmessgerät

[%metadata]
grammar::
gender::: neuter

Gerät zum Messen und Anzeigen von Überdruck (3.2.346)

[[term_3.2.577]]
==== Druckmessgerät

[%metadata]
grammar::
gender::: neuter

Gerät zum Messen und Anzeigen der Druckhöhe, Druckveränderung und Druckdifferenz
```

If in German the words for "pressure gauge" and "pressure measuring instrument" are the same, then we are not in a position to say that is wrong.

While one might say that ISO DIR 2 says:
> "Only one definition per terminological entry is allowed. If a term is used to define more than one concept, a separate terminological entry shall be created for each concept and the domain shall be included in angle brackets before the definition."

But if the two terms have the same domain (or no domain) in English, are we to separate into new domains in French or German?

It is a known fact that different languages expresses concepts differently. Moreover, in a dictionary one word can have multiple definitions.

This same issue also happens in ISO/IEC 2382:
* https://github.com/metanorma/iso-iec-2382/issues/22

Perhaps this is a common vocabulary dataset issue?

Also FYI @ReesePlews

**Comment by ReesePlews** [comment]
@ronaldtse i believe ISO 10241-1 clause 6.2.6 Homographs and antonyms talks about this issue. it suggests when _these type of homographs cannot be avoided, homographs shall be defined in separate terminological entries. a cross reference in a note to entry between these entries can be useful._  however that adds complexity dealing with the note to keep the xref or not.   not sure if this is what you were looking for or not. i am not familiar with such duplicated multilingual terms. this does not happen, in my understanding in asian languages as the pictograms would be different, but i dont have much experience in this area.

**Comment by ronaldtse** [comment]
Thank you @ReesePlews for pointing that out! I think the answer is definitive now, in 6.2.6 they provided an example where the French preferred term is duplicated (as in homographs representing two different concepts).

There is a special treatment for the "Note to entry", where the language that contains a homograph will need a particular "Note to entry" for cross-referencing, and the language where the homograph does not exist will need a "Note to entry" as a placeholder.

Definition of a "homograph":
<img width="796" alt="Screenshot 2023-12-06 at 6 38 00 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/658a9f98-d31c-4956-88ff-990640999de3">

Recognition that "homographs" exist:
<img width="800" alt="Screenshot 2023-12-06 at 6 37 46 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/5848c613-2fda-4a61-aee5-9665aafe4d18">

Avoid homographs:
<img width="795" alt="Screenshot 2023-12-06 at 6 38 51 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/d5caf799-0efb-4b13-afed-d29c7c59713d">

Homographs in different languages are accepted (even in the same domain):
<img width="812" alt="Screenshot 2023-12-06 at 6 39 21 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/89326437-99c5-4477-8f13-feb41d20503e">

**Comment by opoudjis** [comment]
OK, the abort becomes a warning.

We do need a notion of severity in warnings, as some warnings are clearly more important than others, and I don't want a warning about homographs to be missed. I'm already suppressing display of grammar errors, but I am inclined to introduce 3 severity levels, abort on 1, display 2, and not display 3.

**Comment by opoudjis** [comment]
Thank you @ReesePlews and @ronaldtse , very helpful to see the chapter and verse on this

**Comment by opoudjis** [comment]
Want to get rid of the separate `@fatalerror` variable, and abort on all severity 1 log errors. (They are almost all in standoc.)

**Comment by opoudjis** [comment]
Holding off on escalating style warnings in child flavours, except for IETF, which is more finicky because its output needs to be XML validated:

* No matching review for cref
* Image other than SVG
* IETF: unrecognised working group
