### ISSUE TITLE
Broken HTML TOC in ISO documents (e.g. ISO 10303-41)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1068]
<img width="1324" alt="Screenshot 2023-12-06 at 4 27 32 PM" src="https://github.com/metanorma/metanorma-iso/assets/11865/72cb5e5b-193b-4940-934d-e4c02f51be9d">

To reproduce.
In https://github.com/metanorma/iso-10303-srl/ :

```sh
$ bundle exec metanorma documents/resources/fundamentals_of_product_description_and_support/document.adoc
```

**Comment by opoudjis** [comment]
Ugh, I really thought the repeated fixed I'd done to force line-breaks into the HTML in preprocessing would enable me to sort these by line number, but this is repeatedly proving much too fragile, so I'm just going to sort them by h level + order, redoing the algorithm.

**Comment by opoudjis** [comment]
No, I had fixed this along those lines, but the fix is in github. Trying that.

**Comment by opoudjis** [comment]
Yes, it is working fine now. @ronaldtse You need to get isodoc and metanorma-iso to get this working properly. Releaase is tomorrow, though I might be held up a day or so.

**Comment by opoudjis** [comment]
![Screenshot 2023-12-10 at 18 56 09](https://github.com/metanorma/metanorma-iso/assets/1911039/e53d4320-3bea-4503-8075-b741d0efc282)
