### ISSUE TITLE
PDF: Implement new 2024 ISO layouts [IS, FDIS, DIS, IWA, PSDO] (need layout option to switch between old/new layouts)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1079]
Received from ISO/CS today.

## New Visual Identity and Layout for ISO Publications and Drafts  

We would like to inform you about changes to the cover pages of ISO deliverables.

To align with ISO's new visual identity launched at the Annual Meeting 2022 in Abu Dhabi, ISO/CS provides you with a fresh layout for ISO publications and drafts that undergo balloting by ISO/CS.

The key modifications include:
* Introduction of a new visual identity for cover and back pages, incorporating a grid design and the Inter font
* Implementation of colored logos for publications, with the use of grey for drafts
* Centered pages, along with headers, footers, and page numbers centered within the content
* Inclusion of a language reference in headers, indicated by a 2-letter code (e.g., en for English, fr for French).

These changes apply only to the layout of the **PDF version of ISO publications and ISO drafts**. There will be no alterations made to the XML format.

We are pleased to announce that this new layout will be implemented commencing in the year 2024.

We trust that these enhancements will contribute to an improved experience for users and distributors alike. Should you have any questions or require further information, please do not hesitate to reach out to Marie-Noëlle Bourquin, Head of Production.

Best regards, 

Marco Rossi 
Standardization and Technical Policy Director

## Layouts

* [Samples new layout final.docx](https://github.com/metanorma/metanorma-iso/files/13997475/Samples.new.layout.final.docx)

* [2024-iso-new-pdf-layout.pdf](https://github.com/metanorma/metanorma-iso/files/13997474/2024-iso-new-pdf-layout.pdf) "Sample of layout for an International Standard (cover page, back page and internal centered layout)"

I've extracted out the content from the Word file for clarity purposes, shown below.

### Cover page for a draft for DIS ballot

<img width="341" alt="image1" src="https://github.com/metanorma/metanorma-iso/assets/11865/baa8e47e-a536-4f2f-b071-0f0b2820ad21">

### A technical page in a draft for DIS ballot

<img width="342" alt="image2" src="https://github.com/metanorma/metanorma-iso/assets/11865/a07acafe-0b08-4b43-a7fa-ae0498c1ddd1">

### Cover page for a draft for FDIS ballot

<img width="340" alt="image3" src="https://github.com/metanorma/metanorma-iso/assets/11865/9decb548-ca6f-4b90-93da-7db7d188fa3d">

### Back page for a draft for FDIS ballot
<img width="340" alt="image4" src="https://github.com/metanorma/metanorma-iso/assets/11865/1ac25f20-7d72-4bd3-9820-93891998a972">

### Cover page for an International Standard
<img width="341" alt="image5" src="https://github.com/metanorma/metanorma-iso/assets/11865/6bbb9eaa-ff1f-4c53-a836-dc4737c88a13">

### Back page for an International Standard
<img width="341" alt="image6" src="https://github.com/metanorma/metanorma-iso/assets/11865/09ade7ce-6255-440c-a502-79a44ac9e12d">

### Cover page for a Technical Report
<img width="341" alt="image7" src="https://github.com/metanorma/metanorma-iso/assets/11865/caef01c3-ab4a-48cd-bcc9-23166624a6b9">

### Back page for a Technical Report
<img width="340" alt="image8" src="https://github.com/metanorma/metanorma-iso/assets/11865/04a19698-aa3e-4adc-88ee-92c767d94346">

### Cover page for an IWA
<img width="341" alt="image9" src="https://github.com/metanorma/metanorma-iso/assets/11865/997c679d-96fd-4fde-a0f1-c6bc5f4f09a3">

### Back page for an IWA
<img width="342" alt="image10" src="https://github.com/metanorma/metanorma-iso/assets/11865/72d2c2d0-a30e-4531-bde7-d8193032789a">

### Cover page for a standard developped under a PSDO agreement (with partners)
<img width="341" alt="image11" src="https://github.com/metanorma/metanorma-iso/assets/11865/6b93e41c-91b6-4ae1-8f4a-27223ef271ae">

### Back page for a standard developped under a PSDO agreement (with partners)

<img width="341" alt="image12" src="https://github.com/metanorma/metanorma-iso/assets/11865/0d7e4c17-44c0-4a01-9137-addacdfb5007">

### Page 1 technical for a standard developed under a PSDO agreement (with partners)
<img width="340" alt="image13" src="https://github.com/metanorma/metanorma-iso/assets/11865/77828fca-ceae-4d33-8e97-3c08692a887b">

### A technical page for a standard developed under a PSDO agreement (with partners)

<img width="341" alt="image14" src="https://github.com/metanorma/metanorma-iso/assets/11865/2bdea8d0-4bbc-419e-a27d-b82b1dbd3b98">

**Comment by Intelligent2013** [comment]
Besides the modifications mentioned in the initial post there are a few changes:
- text color - dark grey (`rgb(35,31,32)`)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/69f59c2c-b7d9-407f-99c3-2e6878e879aa)

(currently color in `black`)

- font-size is `10.5pt` (currently, `11pt`)
- page left/right margins are `18.7mm` both (currently, `25mm` and `12.5mm`, odd/even pages)

- main section first page header has thick border and `International Standard`
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/72cabbd9-9e8e-449a-a03a-fe2f2eda5442)

currently, capitalized `INTERNATIONAL STANDARD`:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a6fafc95-f57a-472c-a8a6-ed620dd8ed9d)

- blue underlined text `www.iso.org`:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/121a3ce5-7252-4939-a965-679ceb1b6183)

currently, `copyright@iso.org`:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/8932fce2-7cf9-44ff-a0ef-21a30fe6c46a)

**Comment by Intelligent2013** [comment]
ISO XSLT generally updated in https://github.com/metanorma/mn-native-pdf/pull/641.

But need additional updates after fixing these issues:
https://github.com/metanorma/metanorma-iso/issues/1080
https://github.com/metanorma/metanorma-iso/issues/1082

**Comment by ronaldtse** [comment]
@Intelligent2013 is this done? both #1080 and #1082 are done. Thanks.

**Comment by Intelligent2013** [comment]
@ronaldtse done.

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

**Comment by ronaldtse** [comment]
@Intelligent2013 could you please help provide screenshots to show the results of documents like the specification did? Thanks.

**Comment by Intelligent2013** [comment]
Examples :
- DIS
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/47677d0d-26f7-4c09-a25f-f788bdcc660a)

![image](https://github.com/metanorma/metanorma-iso/assets/5559926/ab4bb8cd-f83a-4439-a3fe-c66adf9b1367)

- FDIS
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/fb52fc62-6ebf-4125-ab09-d918d286aedf)

![image](https://github.com/metanorma/metanorma-iso/assets/5559926/34b221a2-8698-4458-827b-42b5b3a653c3)

- International Standard
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/496d69bf-9ae0-4b03-b8ae-6f08a5485639)


![image](https://github.com/metanorma/metanorma-iso/assets/5559926/abee17ce-0613-486f-9c19-f4463777e153)


- International Workshop Agreement
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a38a160d-0399-4a9f-a3ac-4c702e39cbcc)


- ISO/IEC
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a4b5dd86-07bb-4719-87c5-7524e3f4f775)

![image](https://github.com/metanorma/metanorma-iso/assets/5559926/63637802-4e4e-4da0-91c0-bff2fbb67499)


![image](https://github.com/metanorma/metanorma-iso/assets/5559926/bd8b03a3-9c6d-41c8-960c-15a83953db1b)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

**Comment by Intelligent2013** [comment]
The reference layouts from the initial post give the common approach only. The exact layout found in the PDF in https://github.com/metanorma/metanorma-iso/issues/1134.
Need revise the XSLT.

**Comment by Intelligent2013** [comment]
ISO XSLT updated for the cover page, last page and clause titles for layout 2024. Further changes will be actioned in https://github.com/metanorma/metanorma-iso/issues/1134.
