### ISSUE TITLE
New layouts: support alternative PDF layout specification

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1080]
With today's announcement of new ISO PDF layouts, we will need a way of specifying usage of the old / new layouts which will be necessary in embedding of documents.

In OGC, we already differentiate the layouts based on publication date.

It seems the opportune time to enable PDF layout selection for Metanorma.

Dependency of #1079 .

**Comment by opoudjis** [comment]
Document scheme attribute, surely

**Comment by opoudjis** [comment]
@Intelligent2013 I am going to realise this through the `:document-schema:` attribute, which we have not had to use in ISO until now. Assume the new 2024 value is the default value. If we want the older rendering, `:document-schema:` will need to be "legacy". (I'll refine that if it ever becomes necessary.) I will pass that value to you as `//metanorma-extension/presentation-metadata[name = 'document-schema']/value`.

**Comment by ronaldtse** [comment]
@opoudjis can we not use "legacy" but an actual name/date for the layout?

**Comment by opoudjis** [comment]
> @opoudjis can we not use "legacy" but an actual name/date for the layout?

I'm happy to, but what  value, @ronaldtse ? "2023"?

**Comment by ronaldtse** [comment]
The previous Cambria layout is from 2013, so let's say "2013".

**Comment by opoudjis** [comment]
Forcing 2024 as the default value, and populating it.

**Comment by ronaldtse** [comment]
Thanks!
