### ISSUE TITLE
Support document attribute for the link to the feedback about the standard

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1082]
Source issue:
https://github.com/metanorma/metanorma-iso/issues/1079

As titled.

New ISO PDF layout specification contains the QR code with to the the feedback about the standard:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/daa3ed67-85b5-4ff0-ba9d-9dd424f3ac3a)

**Comment by opoudjis** [comment]
It's semantic metadata, so:

`:semantic-metadata-feedback-link: http://www.example.com`

Which renders as:

````
<metanorma-extension>
<semantic-metadata>
<feedback-link>http://www.example.com</feedback-link>
</semantic-metadata>
...
````

**Comment by ronaldtse** [comment]
Ho

> It's semantic metadata, so:
> 
> `:semantic-metadata-feedback-link: http://www.example.com`
> 
> Which renders as:
> 
> ```
> <metanorma-extension>
> <semantic-metadata>
> <feedback-link>http://www.example.com</feedback-link>
> </semantic-metadata>
> ...
> ```

@opoudjis is there any reason it is not a proper document attribute? Thanks.

**Comment by opoudjis** [comment]
The profusion of "proper" document attributes is an excessive maintenance burden.
