### ISSUE TITLE
Technical Report: wrong docidentifiers

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1086]
The source issue: https://github.com/metanorma/metanorma-iso/issues/1079

The source document: https://github.com/metanorma/mn-samples-iso/tree/main/sources/technical-report

The `docidentifier`'s look wrong - `-.0`:
```xml
<docidentifier type="ISO">ISO/TR 29166-.0:2011</docidentifier>
<docidentifier type="iso-reference">ISO/TR 29166-.0:2011(E)</docidentifier>
<docidentifier type="URN">urn:iso:std:iso:tr:29166:-:stage-60.60.v0:en</docidentifier>
<docidentifier type="iso-undated">ISO/TR 29166-.0</docidentifier>
<docidentifier type="iso-with-lang">ISO/TR 29166-.0:2011(en)</docidentifier>
```

![image](https://github.com/metanorma/metanorma-iso/assets/5559926/cd5d5dae-1db7-4c18-92db-8790727044fd)

**Comment by ronaldtse** [comment]
Is this related to pubid-ISO?

**Comment by opoudjis** [comment]
Yes, those IDs are generated by pubid-iso. Let me replicate...

**Comment by opoudjis** [comment]
It's me. The template has an empty partnumber attribute, for the purposes of illustration, and I'm passing it to pubid; I'll suppress it if empty.

**Comment by ronaldtse** [comment]
@opoudjis is it possible to directly use pubid output instead of having an additional "template"? Thanks.

**Comment by opoudjis** [comment]
I have no idea what you are talking about. By template, I meant the same document being compiled, which has annotated document attributes.

**Comment by ronaldtse** [comment]
Ah by "template" you mean values filling a set of hash keys. Okay. Also, accepting empty parameters seem like a bug in pubid-iso as well.

**Comment by opoudjis** [comment]
Sorry, I did use a bad term there: what I meant was just the asciidoctor template header. I agree about it being a bug, but I will just sanitise the input my side.
