### ISSUE TITLE
Historical PDF layout: 1989 to 2012 (1989 to 2011 old logo, 2012 new logo)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1092]
This is the common layout we are all grown used to, from 1989 to 2012.

All preview files from iTeh and IEC:

1989 to 2011 (old ISO logo):
[ISO-14792-2011.pdf](https://github.com/metanorma/metanorma-iso/files/14191281/ISO-14792-2011.pdf)
[ISO-7010-2011-Amd-7-2016.pdf](https://github.com/metanorma/metanorma-iso/files/14191282/ISO-7010-2011-Amd-7-2016.pdf)
[ISO-9-1995.pdf](https://github.com/metanorma/metanorma-iso/files/14191283/ISO-9-1995.pdf)
[ISO-4-1997.pdf](https://github.com/metanorma/metanorma-iso/files/14191287/ISO-4-1997.pdf)
[ISO-9000-2005.pdf](https://github.com/metanorma/metanorma-iso/files/14191288/ISO-9000-2005.pdf)
[ISO-13485-2003.pdf](https://github.com/metanorma/metanorma-iso/files/14191289/ISO-13485-2003.pdf)
[ISO-5978-1990.pdf](https://github.com/metanorma/metanorma-iso/files/14191290/ISO-5978-1990.pdf)
[info_isoiec9573{ed1.0}en.pdf](https://github.com/metanorma/metanorma-iso/files/14191291/info_isoiec9573.ed1.0.en.pdf)
[ISO-1985-1998.pdf](https://github.com/metanorma/metanorma-iso/files/14191293/ISO-1985-1998.pdf)
[ISO-105-C01-1989.pdf](https://github.com/metanorma/metanorma-iso/files/14191294/ISO-105-C01-1989.pdf)
[info_isoiec8631{ed2.0}en.pdf](https://github.com/metanorma/metanorma-iso/files/14191295/info_isoiec8631.ed2.0.en.pdf)

From 2012, ISO changed their logo:
[info_isoiec30170{ed1.0}en.pdf](https://github.com/metanorma/metanorma-iso/files/14191301/info_isoiec30170.ed1.0.en.pdf)

And from the latter half of 2012, ISO changed the layout to the one we know now:
[ISO-19005-3-2012.pdf](https://github.com/metanorma/metanorma-iso/files/14191304/ISO-19005-3-2012.pdf)

**Comment by Intelligent2013** [comment]
@ronaldtse I've looked at this PDF and found that there aren't clear common styles in them to separate just by date between 1989 and 2012.

## ToC styles

- ISO/IEC 8631:1989
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/35b8e2e5-10c9-446e-87c0-fd060230a945)

- ISO/IEC/TR 9573:1988
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/39f550b5-ae69-48e7-9897-65820fbf20ce)

- ISO 1985: 1998
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/d64c59a9-9f0b-4193-8eb0-fd48eda94df0)

- ISO 13485:2003
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/25467b6c-10e9-498e-b4de-667a0d186988)

- ISO 9000:2005
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/d2619f0e-3008-4af6-9690-7f766e652e16)

- ISO/IEC 30170:2012
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/4334bd66-9dd5-4ee1-a749-56271ccb9fcc)

## Page header

- ISO/IEC/TR 9573 (1988-12-01)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/280b49e2-6768-400b-94e3-ac68ec9bbfdf)

- ISO/IEC 8631 (1989-08-01, note: spaces around `:`)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a91aa48c-911c-4b93-8140-4e3ccc68100e)


## Font sizes

- ISO/IEC/TR 9573 (1988-12-01)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/4550e56a-d184-4c08-b7fb-f8c0af67b90e)

- ISO/IEC 8631 (1989-08-01)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/b3674111-0069-4e7e-a422-8700d1ff3bea)



## Logo
- ISO/IEC 8631 (1989-08-01)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/f406b438-5a01-42b7-a6b5-830c538aafe9)

- ISO 4:1997
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/63fbe24f-d94e-4967-a5d9-6fb67b0481cc)

- ISO 14792:2011 (2011-03-15)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/05cd9cb1-b1eb-492e-8738-18e556431a55)


- ISO/IEC 30170 (2012-04-15)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/887d82b8-66ae-45ad-b0aa-141ce4704af8)


- ISO 19005-3:2012 (2012-10-15, note: old logo as in 2011 year)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/6dfefb04-75fa-4bd9-9246-56d80c9a3405)


## Main sections header (with and without copyright sign)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/8d632631-2226-4b96-9b0d-05317374a047)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/e865de36-9fd6-4435-966d-1e9039d4f2a5)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/240bf169-5bed-4315-a4d0-7248699c7977)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/24434f7f-24c2-491f-855d-250760f5322a)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/b9b095c3-0972-4954-abf5-65adc5c838c2)

This isn't a full list of the differences, of course.

I have a question. The old PDFs published already. Further amendments publish with new style. What is the main goal to support the historical PDF layouts?

**Comment by ronaldtse** [comment]
It is quite clear that layouts were not very much standardized across documents. I think the best way is for you just to choose the most reasonable presentation for each element and go with it. 

The purpose of implementing historical PDF layouts is just so that we can publish an old document in a similar presentation. There are occasions where we need to publish the same content in the same layout, without actually updating the contents of the document, therefore using the same identifier as the original. The point is that we cannot use the new layout to publish an old document without changing the identifier.

**Comment by ronaldtse** [comment]
Here's a full document found on the Internet so we can see how the pages end.

http://www.ydylstandards.org.cn/static/down/pdf/IS%20ISO_R%201115-1969_7500.pdf

**Comment by ronaldtse** [comment]
Here's a complete document that is dual-logo ISO / IDF published and hosted by the IDF:
* [IDF 21](https://www.fil-idf.org/wp-content/uploads/woocommerce_uploads/Publications/Sold/Standards/English/IDF-021---ISO-6731-2010-e.pdf)

**Comment by Intelligent2013** [comment]
Logo:
- 1989 to 1992
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/1fcc5732-4eb6-40fd-ad1a-fadb5d146648)
Note: 2nd is old IEC logo

- 1993 to 2011
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/5f7bb568-8142-4e0a-896e-e92312923e6a)

- 2012
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/1690855e-2f3d-4188-b000-a5467ea51176)

**Comment by Intelligent2013** [comment]
- [ ] documents from 1989 to 1998
    - [ ] preface pages with big margins
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/edf8dac6-aaba-4e04-911d-f714449629ac)
   - [ ] copyright in footer on first preface page
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/467f7251-193a-403e-bf11-4c971b3e8fe6)
- [ ] documents from 1999
   - [ ] PDF disclaimer (see non English disclaimer in https://standards.iteh.ai/catalog/standards/iso/535273ec-aa79-46c1-9b20-72524e5f1ff8/iso-9001-2000)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/7029d243-7d26-4dcb-ace1-d4a20c99a246)

- [ ] some documents in two-columns layout, so need support it (similar to BSI/PAS documents)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/fcd85aef-e881-4fbc-9b2e-b34193fe0739)

**Comment by Intelligent2013** [comment]
Table doesn't spanned across columns:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/d3b66f65-8885-4984-9fe5-a0cc30085eac)

because table block isn't top-level element (inside `fo:block`):
```xml
<fo:block id="_2">
	...
	<fo:block-container margin-left="0mm" margin-right="0mm" font-size="9pt" margin-bottom="8pt" role="SKIP" span="all">
		<fo:table id="table1" table-omit-footer-at-break="true" table-layout="fixed" border="1pt solid black" width="100%" border-top="1pt solid black">
```
and Apache FOP doesn't support `span="all"` for non-top elements.

**Comment by Intelligent2013** [comment]
The same issue for Annex title:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a0537847-e3ac-405b-9391-8318ca88861a)

Need ISO XSLT refactoring.

**Comment by Intelligent2013** [comment]
Two column layout support added for 1989 layout in ISO XSLT.
(`:presentation-metadata-layout-columns: 2` in document.adoc, similar to PAS documents)

Next tasks: 
- [ ] support additional docidentifier in ISO XSLT (https://github.com/metanorma/metanorma-iso/issues/1104)
- [ ] add copyright text for 1989 layout into metanorma-iso boilerplate

**Comment by Intelligent2013** [comment]
ISO XSLT updated.
How to enable 1989 to 2012 layout:
```
:document-scheme: 1989
```
