### ISSUE TITLE
New doctype: "committee document"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1093]
A "committee document" has been requested by several users who wish to use the structure of Metanorma for ISO internal documents for committee use.

This need is similar to ITU's "Temporary Document" and "Contribution" needs which serve the same purpose as ISO's N-documents:
* https://github.com/metanorma/metanorma-itu/issues/375

It differs from a normal ISO standard in the following ways:

* Structural requirements: a "committee document" likely contains less requirements, so the "Technical Report" structure should suffice.
* The document type would be "Committee Document" instead of "International Standard", etc.
* PubID: The pubid would be an N-document number, currently specified with the attribute `:tc-docnumber`, in the form of e.g. `ISO/TC 184/SC 4 N1234` (see https://github.com/relaton/relaton-iso/#isotc-184sc-4-important-n-documents) or `ISO/TC 184/SC 4/TF 1 N1`.
    * For the Committee Document, we would use `:docnumber` for this PubID (an ISO committee document with only an N-number), and omit `:tc-docnumber:` (which is only used for an ISO draft standard that also has an N-number)
    * The `pubid-iso` gem supports N-document PubIDs.

Originally from @stuartgalt :
* https://github.com/metanorma/annotated-express-report/issues/9

> But when I edited the metadata and run the workflow it looks like it is kind of hard coded to make a standard.  What needs to changed to make this a modest formal committee document or something similar.
> When I looked for documentation about the metanorma metadata I was unable to figure out how to set tc_docnumber and doctype etc.  Is there a schema or some documentation on this?

**Comment by opoudjis** [comment]
@Intelligent2013 Am generating Presentation XML for https://github.com/metanorma/annotated-express-report/tree/main/sources/report-part-41 and sending it to you to generate cover page, but the PDF output already looks plausible to me...

**Comment by Intelligent2013** [comment]
ISO XSLT reads the value from `doctype language="..."` if exists, otherwise from `doctype` without lang, with removing `-` additionally.

In the committee `document.presentation.xml` there is one doctype  only:
```

		<ext>
			<doctype>committee-document</doctype>
...
```

From Technical Report presentation XML:
```xml
		<ext>
			<doctype language="">technical-report</doctype>
			<doctype language="en">Technical Report</doctype>
```

@opoudjis could you add `<doctype language="en">Committee Document</doctype>` please?

**Comment by opoudjis** [comment]
Typo in YAML.

**Comment by Intelligent2013** [comment]
Ok, fixed:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/bf9dfc64-2d2a-46b1-867a-518489130745)

@opoudjis thanks!

**Comment by stuartgalt** [comment]
Could I see the metadata at the top of the file that was used to generate the above screenshot?  When I changed [https://github.com/metanorma/annotated-express-report/tree/main/sources/report-part-41](https://github.com/metanorma/annotated-express-report/tree/main/sources/report-part-4) 1 to call out a committee-document I was getting ISO 1 instead of ISO/TC 184/SC 4 N1.   In a perfect world it would read "ISO/TC 184/SC 4/TF 1 N1"

**Comment by opoudjis** [comment]
`:doctype: committee-document`, but you need to pull metanorma-iso from github to see it (Gemfile: `:gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "main"`), and I don't know that the PDFs are even pushed to github yet. 

Otherwise, release is Monday.

**Comment by opoudjis** [comment]
As far as I can tell, this is done, but I'll leave this open until @stuartgalt confirms it works for him on Tuesday.

**Comment by ronaldtse** [comment]
The `:docnumber:` is not properly used / rendered / encoded.

The ideal N-document scope is "ISO/TC 184/SC 4/TF 1", **not** "ISO/TC 184/SC 4".

I tried two cases:
* only using the N-number in `docnumber`
* specifying the full N-number scope

## Only N-number

Code:
```adoc
= SMRL Innovation -- Modernizing the ISO 10303 authoring and publication processes
:docnumber: 1
...
:technical-committee-number: 184
:technical-committee: Industrial Automation Systems and Integration
:subcommittee-number: 4
:subcommittee: Industrial Data
:workgroup-number: 1
:workgroup-type: TF
...
```

Output:
"ISO/TC 184/SC 4 N1" (which has the wrong scope)
<img width="617" alt="Screenshot 2024-02-21 at 5 58 17 PM" src="https://github.com/metanorma/metanorma-iso/assets/11865/1cca1f3f-5baa-4bbf-9a31-a3ce2d7cddfa">

## With full scope

Code:
```adoc
= SMRL Innovation -- Modernizing the ISO 10303 authoring and publication processes
:docnumber: ISO/TC 184/SC 4/TF 1 N1
...
:technical-committee-number: 184
:technical-committee: Industrial Automation Systems and Integration
:subcommittee-number: 4
:subcommittee: Industrial Data
:workgroup-number: 1
:workgroup-type: TF
...
```

Output:
"ISO/TC 184/SC 4 NISO/TC 184/SC 4/TF 1 N1"
<img width="622" alt="Screenshot 2024-02-21 at 6 01 25 PM" src="https://github.com/metanorma/metanorma-iso/assets/11865/330d3eb5-4f6c-4408-825d-fdfa3fa9522c">

## Conclusion

Please provide a way to encode the "N-number context" separate from the "authorship".

This is because a sub-group can also publish using a higher-level N-number. The "N-number" is the "distribution group", not the "authorship group".

## Additional issues

The top left should say "Committee Document", not "Technical Committee".
<img width="1083" alt="Screenshot 2024-02-21 at 6 03 10 PM" src="https://github.com/metanorma/metanorma-iso/assets/11865/415c46fa-9eeb-4905-9807-3c96bd6678a4">

**Comment by Intelligent2013** [comment]
ISO XSLT renders the values so:
- document identifier
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/1a75a53d-bcd1-4b18-b6b0-acbffa450e89)

from `/iso-standard/bibdata/docidentifier[@type = 'iso-undated']`.
The Presentation XML instance example: 
```xml
<docidentifier type="iso-undated">ISO/TC 184/SC 4 NISO/TC 184/SC 4/TF 1 N1</docidentifier>
```
It isn't the XSLT issue.

- reference number
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/0653240d-dbca-4afb-9724-2a3630f53c2d)
from `/iso-standard/bibdata/docidentifier[@type = 'iso-with-lang']`.
The Presentation XML instance example: 
```xml
<docidentifier type="iso-with-lang">ISO/TC 184/SC 4 NISO/TC 184/SC 4/TF 1 N1(en)</docidentifier>
```
It isn't the XSLT issue.

- > The top left should say "Committee Document", not "Technical Committee".

![image](https://github.com/metanorma/metanorma-iso/assets/5559926/1ca05272-72e5-4efa-a616-094395e3dc43)

ISO XSLT renders the value from `stagename`:
```
	<ext>
		<doctype language="">committee-document</doctype>
		<doctype language="en">Committee Document</doctype>
		...
		<stagename abbreviation="TC">Technical Committee</stagename>
	</ext>
</bibdata>
```
Looks like for `committee-document` doctype I have to get the value from `doctype[@language]`. I'll fix it.

**Comment by opoudjis** [comment]
> specifying the full N-number scope

The `:docnumber:` is explicitly intended for building up identifiers by component. If you want to supply the complete identifier, use `:docidentifier:` instead:

````
= SMRL Innovation -- Modernizing the ISO 10303 authoring and publication processes
:docidentifier: ISO/TC 184/SC 4/TF 1
:technical-committee-number: 184
:technical-committee: Industrial Automation Systems and Integration
:subcommittee-number: 4
:subcommittee: Industrial Data
:workgroup-number: 1
:workgroup-type: TF
...
````

generates `<docidentifier type="ISO">ISO/TC 184/SC 4/TF 1</docidentifier>`

That satisfies your requirement:

> Please provide a way to encode the "N-number context" separate from the "authorship".

**Comment by Intelligent2013** [comment]
> The top left should say "Committee Document", not "Technical Committee".

ISO XSLT updated in https://github.com/metanorma/metanorma-iso:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/e4521087-78e0-4839-a91d-2bf680eaf480)

**Comment by opoudjis** [comment]
I hadn't included the workgroup number in the IDs, because I didn't realise it was a requirement. Adding.

**Comment by opoudjis** [comment]
````
= SMRL Innovation -- Modernizing the ISO 10303 authoring and publication processes
:docnumber: 1
:technical-committee-number: 184
:technical-committee: Industrial Automation Systems and Integration
:subcommittee-number: 4
:subcommittee: Industrial Data
:workgroup-number: 1
:workgroup-type: TF
:doctype: committee-document
````

now generates in Presentation XML:

````
<docidentifier type="ISO">ISO/TC 184/SC 4/TF 1 N1</docidentifier>
<docidentifier type="iso-reference">ISO/TC 184/SC 4/TF 1 N1(E)</docidentifier>
<docidentifier type="URN">urn:iso:doc:iso:tc:184:sc:4:tf:1:1:en</docidentifier>
<docidentifier type="iso-undated">ISO/TC 184/SC 4/TF 1 N1</docidentifier>
<docidentifier type="iso-with-lang">ISO/TC 184/SC 4/TF 1 N1(en)</docidentifier>
````

**Comment by opoudjis** [comment]
This ticket should now be done, but would like @ronaldtse or @stuartgalt to confirm.

**Comment by ronaldtse** [comment]
Confirm fixed:

<img width="617" alt="Screenshot 2024-02-22 at 9 57 02 PM" src="https://github.com/metanorma/metanorma-iso/assets/11865/6268ebaa-c20d-4def-8d90-e0447d29328e">
<img width="546" alt="Screenshot 2024-02-22 at 9 57 13 PM" src="https://github.com/metanorma/metanorma-iso/assets/11865/d03422a1-505d-472d-b201-4ad36e30d59e">

Thank you for the amazing work!
