### ISSUE TITLE
Document attribute UDC (Universal Decimal Classification)

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1094]
Source issue: https://github.com/metanorma/metanorma-iso/issues/1089

Before 1992, ISO published the UDC (Universal Decimal Classification) instead of ICS (International Classification of Standards)
(found here https://docs.wto.org/dol2fe/Pages/SS/directdoc.aspx?filename=q:/G/TBT/GEN312.pdf&Open=True)

Example (https://cdn.standards.iteh.ai/samples/14/2c071d0698d64948a4b9f21a6314072b/ISO-R-1-1951.pdf):
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a12c6899-4eca-4c01-8f53-3fbcdaa73394)

Currently, Metanorma supports ICS via the attribute `:library-ics:` (https://www.metanorma.org/author/ref/document-attributes/#document-info):

![image](https://github.com/metanorma/metanorma-iso/assets/5559926/c39c7705-51a8-4335-953f-67c97975d93b)

Add the attribute `:library-udc:`.

**Comment by opoudjis** [comment]
I'm going to see if I can generalise this somehow, as library-* for any taxonomy classification.

**Comment by ronaldtse** [comment]
The Chinese also use their own taxonomy. A generalized solution would work great, for ICS and things we support we could do validation but for others we can at least accept them. It also gives us a chance to accept multiple taxonomy classification values.

**Comment by opoudjis** [comment]
We already have provision for multiple classification elements in bibdata/classification: `<classification type="UDC">600.1</classification>`. I had hard coded `ics` as an `bibdata/ext` element, but I think it would be fine to leave that as a legacy exception, and process all other classifications as `library-*`.

**Comment by Intelligent2013** [comment]
Also we need to support the localized strings for UDC:
- fr: CDU
- ru: УДК

**Comment by opoudjis** [comment]
`library-*` is too obscure, so I'm going to make it `classification-*`. The canonical value shall indeed be UDC.

**Comment by opoudjis** [comment]
Strike that: we already support `bibdata/classification`, as `:classification: UDC:563.5.081, UDC:537.71`. We only allow a single value per classification token. Documenting that, rather than playing silly buggers with multiple values in a key-value pair.

**Comment by opoudjis** [comment]
> Also we need to support the localized strings for UDC:
> 
> * fr: CDU
> * ru: УДК

This will be provided in the localization-string for `classification-UDC`.

**Comment by opoudjis** [comment]
````
:classification: UDC:563.5.081:537.71
````

results in the following in Presentation XML:


````
<bibdata type="standard">
...
<classification type="UDC">563.5.081:537.71</classification>
...
</bibdata><localized-strings>
...
<localized-string key="classification-UDC" language="en">UDC</localized-string>
...
````

**Comment by Intelligent2013** [comment]
@opoudjis thank you!
