### ISSUE TITLE
Support localized strings for 'Recommendation' document type (old ISO documents)

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1097]
Source issue: https://github.com/metanorma/metanorma-iso/issues/1089

- en: 
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/ee1bb60d-0f19-4406-a1b2-057aa787eec3)

- fr;
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/fb5da5eb-67df-406f-a09c-fc2e149cac55)

Currently, for adoc:
```
:doctype: recommendation
```
the Presentation XML looks so:
```xml
        <ext>
            <doctype>recommendation</doctype>
```

Expected results:
```xml
        <ext>
            <doctype language="">recommendation</doctype>
            <doctype language="en">ISO Recommendation</doctype>
```

```xml
        <ext>
            <doctype language="">recommendation</doctype>
            <doctype language="fr">Recommandation ISO</doctype>
```

Note: for 'ru' I can't find the old document.

**Comment by opoudjis** [comment]
I'm not going to replace "Recommendation" with "ISO Recommendation"; I will add a new localisation string, `iso-recommendation`. The current i18n term is a provision: it alternates with Requirement and Permission as a block label type.

**Comment by opoudjis** [comment]
Clearly the doctype label will be either Recommendation or ISO Recommendation depending on the rendering label. I'll switch it accordingly.

**Comment by opoudjis** [comment]
The `document-scheme` values are going to be:

* 1951
* 1972
* 1987
* 1989
* 2012
* 2013 = current

I will make the doctype be ISO Recommendation only in the 1951 scheme.

**Comment by opoudjis** [comment]
Actually, let me back up: Recommendation is an obsolete document type. So it's fine to associate "recommendation" as a document type with ISO Recommendation.

**Comment by opoudjis** [comment]
````
:doctype: recommendation
````

now consistently gives:

````
<doctype language="">recommendation</doctype><doctype language="en">ISO Recommendation</doctype>
````

**Comment by Intelligent2013** [comment]
@opoudjis thanks!
