### ISSUE TITLE
Copyright text for old documents

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1099]
Source issue: https://github.com/metanorma/metanorma-iso/issues/1089

@opoudjis I've tried to add old copyrights in the `boilerplate.adoc`, but I don't know how to retrieve the value from `:document-scheme:` to put values conditionally.

- en:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/11b12135-ed89-41e8-a094-901191955c9f)

```
COPYRIGHT RESERVED

The copyright of ISO Recommendations and 1SO Standards
belongs to ISO Member Bodies. Reproduction of these
documents, in any country, may be authorized therefore only
by the national standards organization of that country, being
a member of ISO.




For each individual country the only valid standard is the national standard of that country.


Printed in Switzerland


Also issued in French and Russian. Copies to be obtained through the national standards organizations.
```

- fr:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/acce88ff-cd7c-4e0c-8b84-e6796121e158)

```
REPRODUCTION INTERDITE

Le droit de reproduction des Recommandations ISO et des Normes
ISO est la propriété des Comitks Membres de ISO. En consé-
quence, dans chaque pays, la reproduction de ces documents ne
peut être autorisée que par l’organisation nationale de normalisation
sation de ce pays, membre de I’ISO.




Seules les normes nationales sont valables dans leurs pays respectifs.


Imprimé en Suisse


Ce document est également édité en anglais et en russe. Il peut être obtenu auprès des organisations
nationales de normalisation.
```

**Comment by opoudjis** [comment]
I need to extract it into the Metadata object, so it can be accessed. It will be `{{ document_scheme }}`.

**Comment by opoudjis** [comment]
It turns out that the metadata is already being extracted as an array to `{{presentation_metadata_document-scheme}}`, but `{{document_scheme}}` is more polite.

**Comment by Intelligent2013** [comment]
@opoudjis I've added the copyright text for 1951 in English and French in https://github.com/metanorma/metanorma-iso/pull/1102.
