### ISSUE TITLE
ISO Recommendation docidentifier with `/R`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1107]
Source issue: https://github.com/metanorma/metanorma-iso/issues/1089

ISO Recommendation identifier has a prefix `/R`:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a098aa81-7340-427a-a2c4-4fb86c44b742)

`pubid-iso` supports it:
```
pubid = Pubid::Iso::Identifier.create(publisher: "ISO", type: "R", number: 123)
print pubid.to_s
```
returns `ISO/R 123`.

Preliminary solution: add `"recommendation": :r` in `metanorma-iso\lib\metanorma\iso\front_id.rb`:
```
      DOCTYPE2HASHID =
        { directive: :dir, "technical-report": :tr, "guide": :guide,
          "technical-specification": :ts,
          "publicly-available-specification": :pas,
          "committee-document": :tc,
          "recommendation": :r }.freeze
```

**Comment by opoudjis** [comment]
Recommendation has not hitherto been recognised (it's legacy).
