### ISSUE TITLE
PDF: full-page-width and column-width tables and figures

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1111]
Source issues:
- https://github.com/metanorma/metanorma-iso/issues/1089
- https://github.com/metanorma/metanorma-iso/issues/1090
- https://github.com/metanorma/metanorma-iso/issues/1091
- https://github.com/metanorma/metanorma-iso/issues/1092

The documents contain tables and figures in full page width and column width:
- full page width figure
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/202302cd-6011-4511-b8c9-9a394d3d002b)

- column width figure
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/676444f0-00ce-4958-9331-2bcb40f57560)

- full-page table
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/d57dcb70-ee27-4726-8fdf-45102efb1fbc)

- column-width table
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/9fb58db5-a207-4f55-8d49-9d1aab253bd7)

Currently, BSI XSLT and metanorma-bsi support them already. Need extend to another XSLT.

**Comment by Intelligent2013** [comment]
@opoudjis metanorma-bsi allows to set `[width=text-width]` and presentation XML contains the attribute `width` for `figure`:
```xml
<figure id="fig1" width="text-width">
```
(https://github.com/metanorma/metanorma.org/blob/doc20230209/author/bsi/topics/markup.adoc#figures)

I've tried to set `[width=text-width]` for ISO document:
```
[[figureA-1]]
.Split-it-right sample divider
[width=text-width]
image::images/a1.png[Alt1]
```
and the tag `image` has `width="text-width"`, but not `figure`:
```xml
<figure id="figureA-1">
<name>Figure A.1 — Split-it-right sample divider</name>
<image src="data:image/png;base64,iVBOR..." mimetype="image/png" id="_4989f791-b93f-831b-5d40-402089695052" height="auto" width="text-width" alt="Alt1"/></figure>
```

Is there a way to move `text-width` to the `figure`?

**Comment by opoudjis** [comment]
I will make that a Metanorma-wide change.
