### ISSUE TITLE
Validate 2024 PDF layout using production standard

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1134]
We need to validate our implementation of the 2024 layout against a production standard:

* https://github.com/metanorma/mn-samples-iso-private/blob/main/reference-docs/19152-1_2024.pdf

This is a private copy.

**Comment by Intelligent2013** [comment]
Our implementation of the 2024 layout looks differently:
- page margins
  - rendered PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/dce2a8dc-553c-4e55-a42a-1e9b6d7b789a)

   - production standard
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/396425d0-199f-47bd-bcb9-e310972858de)

- header font-size
   - rendered PDF (0.5pt smaller font)
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/d565b90f-919f-45c8-a1e1-37242d6cd46e)

   - production standard
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/0b2aa7fc-9aa6-4a3c-9a23-4afd46f4ebcf)

- copyright font-size
   - rendered PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/c04c7a65-13a4-4d00-8022-64cc996f1738)
   
   - production standard
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/191159fc-6871-4995-8413-6c6e29b40c95)

- main text font-size
   - rendered PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/ea9d1ab6-a679-47bb-aeff-1cb34eafe9e5)

  - production standard
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/7db65e58-0ac8-46c2-8c7a-baa64299e924)


- last page footer
  - rendered PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/2b800b08-3e55-4e9c-9860-01281ee6e2b6)


  - production standard
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/02a657da-e124-4ea5-80d9-cfa5736f3f01)


Our PDF layout was updated in https://github.com/metanorma/metanorma-iso/issues/1079 based on the provided PDF example [2024-iso-new-pdf-layout.pdf](https://github.com/metanorma/metanorma-iso/files/13997474/2024-iso-new-pdf-layout.pdf) "Sample of layout for an International Standard (cover page, back page and internal centered layout)".

@ronaldtse to further actions I have to know exactly - what is the correct PDF - in this issue or in https://github.com/metanorma/metanorma-iso/issues/1079?

Note: the PDF from the initial posts opens in the Chrome browser only. Adobe Acrobat opens it and closes immediately, also Foxit Reader and PDF-XChange Viewer. So I have to repair it somehow.

**Comment by ronaldtse** [comment]
> Adobe Acrobat opens it and closes immediately

I'm seeing the same issue too. I can open it in macOS Preview however.

It is very likely that their "design spec" and implemented production PDF are slightly different.

**Comment by Intelligent2013** [comment]
To check the whole document I'll encode it in adoc.

**Comment by Intelligent2013** [comment]
- one numbered Note
  - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/bbb23f8d-4cac-49d8-8e73-9a4e014b9c8c)

  - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/3c4fc59d-d962-44b4-a368-c3e75539b66f)

The rendered PDF is correct. From https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor340:
> 24.3 Numbering and subdivision
> Within a given clause or subclause, notes shall be numbered sequentially. The numbering restarts at each new subdivision. A single note in a subdivision shall not be numbered.


- ordered list numbering - alphabetic vs. arabic:
  - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/fea6d014-3611-4900-a0e3-ae3d905e159e)

 - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/98dcc620-c509-450f-91f8-ef5a07c79d8f)

From https://www.metanorma.org/author/topics/blocks/lists/#general-2:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/05c4f83c-85ad-48d2-be5f-cd8d411690ea)


- different font size of Note:
   -  rendered PDF (a bit smaller):
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/62706f13-6b35-4934-8c85-b4708ca081a8)
   - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/e7fef39d-bf6d-471f-a18e-3de73405b6cf)


- wrong baseline when list text contains superscripted text
   - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/c70f6166-bedc-4e3b-b891-0ce06b0a7e6d)

- there isn't footnotes separator (51mm horizontal line) in the rendered PDF

- indents between footnotes:
   - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/3e895420-ec40-41a3-883e-77184db29f27)
   - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/f9308b94-3e90-478a-b14a-fe8a40f08786)

**Comment by Intelligent2013** [comment]
There is the identical entry in the `Normative references` and `Bibliography`:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/2b9d113b-2ec0-40d1-ac41-609973ecdc16)

![image](https://github.com/metanorma/metanorma-iso/assets/5559926/500460ea-d17d-4649-82bb-ed3ca7be58db)


therefore different identifiers should be used in the adoc:
```
[bibliography]
== Normative references

* [[[ISO19103,ISO 19103]]], _Geographic information -- Conceptual schema language_
...


[bibliography]
== Bibliography

* [[[ISO19103bib,ISO 19103]]], _Geographic information -- Conceptual schema language_
,..
```

**Comment by Intelligent2013** [comment]
- [ ] Source color link:
  -  rendered PDF:
  ![image](https://github.com/metanorma/metanorma-iso/assets/5559926/b0853d11-65c0-4fc7-86b5-0e4f76574691)

  - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/b3b37c14-404c-4384-99fe-f530c073d966)


- [ ] Example (numbered vs. unnumbered) alignment:
  - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/2774e022-d574-4e5d-b878-356b6a7d07b9)

  - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/54d57c44-5f36-4753-9102-d446cfa2a2e4)

**Comment by Intelligent2013** [comment]
- [ ] dash after `modified`:
  - rendered PDF `en dash` (U+2013):
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/e460d16a-2931-4b6d-9094-d2d26943e5f5)
  - production PDF `em dash` (U+2014):
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/31c3eac5-6e60-4ffc-bb49-6aaf25ad572f)

Presentation XML contains `en dash`:
```xml
</xref>, modified
 – Note 1 to entry removed.]</termsource>
```

**Comment by Intelligent2013** [comment]
- [ ] different vertical indents between the definition list items, need increase a bit

**Comment by Intelligent2013** [comment]
- [ ] text with indent
  - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/be69d659-1101-43de-aaf5-86c57a6eccbd)
  - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/134b740e-a789-4d93-86ce-18d9dc1f1977)

Note: I don't know how to achieve it.

- [ ] space before table name
   - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a181f0a6-0afd-4ef5-9e02-0ae265fa9335)

   - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/9d9aa046-c2fb-41eb-91ea-37433c6d2532)


- [ ] table footer top border
- [ ] space between footnotes
   - rendered PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/3234144d-dc01-4277-9209-b959311ed695)
   - production PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/4def60ed-a56f-442c-9651-e6ec5afa92ee)

- [ ] space after table
   - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/58e2cf0c-091f-4822-b556-f874a5cbc4f7)

   - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/dd66def9-3a7f-465a-ba7e-814dcafbf5b3)

**Comment by Intelligent2013** [comment]
- [ ] reference from Annex A sub-clause to another sub-clause
  - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/b82f3f71-4d18-4947-8219-b43273dcb215)
  - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/be4dd3bf-7a88-490d-bb9f-2fd5cca458c9)

- [ ] reference from Annex A sub-clause to main section sub-clause
  - rendered PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/750c2445-3e15-4929-9cf7-7f6eeab4ca08)
  - production PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/d675c9e8-98f8-4ac7-a245-b93271e1adab)

**Comment by Intelligent2013** [comment]
- [ ] table cell borders
  - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/f4f98f2e-26b8-49c9-a405-df31a8860b6a)
  - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/7899f8e1-28c8-43c6-8835-43573494baed)

  -

**Comment by ronaldtse** [comment]
@Intelligent2013 can you help file issues for @opoudjis for those he needs to fix? Thanks.

**Comment by Intelligent2013** [comment]
-  [ ] `smallcap` font-size
   - rendered PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/65ed5a25-0d03-4548-aa4e-fb6566cf1862)

   - production PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/eed8f468-5713-4607-a170-1d4dbbe44f63)

**Comment by Intelligent2013** [comment]
- [ ] references to the Bibliography items
  - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/66957b9f-8bdb-4abf-a3e5-54dc24bc082d)
  - production PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/a5da1066-573d-441d-a539-04754c2a4bca)

**Comment by Intelligent2013** [comment]
- [ ] comma between bibliography references
  - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/f76435a5-f5ac-4dc1-bbe9-77eebe9c369b)
  - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/73c743ba-50fe-4ee1-bb42-1bafeea8d175)

Adoc markup:
```
<<ref10>>,<<ref15>>
```

**Comment by Intelligent2013** [comment]
> - [ ] text with indent
>   - rendered PDF:
> ![image](https://github.com/metanorma/metanorma-iso/assets/5559926/be69d659-1101-43de-aaf5-86c57a6eccbd)
>   - production PDF:
> ![image](https://github.com/metanorma/metanorma-iso/assets/5559926/134b740e-a789-4d93-86ce-18d9dc1f1977)

This issue can be solved via css: `[css text-indent:7mm]#*1) CoreClassConformant*#`.
Rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/7e2c7c01-99f6-4440-9f58-84e89c8fcb42)

**Comment by Intelligent2013** [comment]
- [ ] reference to the standard 
  - rendered PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/02a04148-36ff-4dde-86e0-447b6ac13e3b)
  - production PDF
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/ab9f6536-8e1d-4c82-96d1-25e219ce0826)

**Comment by Intelligent2013** [comment]
ISO XSLT updated for PDF layout 2024.
Only one issue remains: https://github.com/metanorma/metanorma-iso/issues/1141
On hold.

**Comment by Intelligent2013** [comment]
Done.
