### ISSUE TITLE
Dash after 'modified'

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1140]
Source issue: https://github.com/metanorma/metanorma-iso/issues/1134#issuecomment-2007974100

> - dash after `modified`:
>   - rendered PDF `en dash` (U+2013):
> ![image](https://github.com/metanorma/metanorma-iso/assets/5559926/e460d16a-2931-4b6d-9094-d2d26943e5f5)
>   - production PDF `em dash` (U+2014):
> ![image](https://github.com/metanorma/metanorma-iso/assets/5559926/31c3eac5-6e60-4ffc-bb49-6aaf25ad572f)
> 
> Presentation XML contains `en dash`:
> ```xml
> </xref>, modified
>  – Note 1 to entry removed.]</termsource>
> ```

`em dash` should be used.

**Comment by opoudjis** [comment]
I agree, and I'm astonished that I used an en-dash.
