### ISSUE TITLE
Reference to Annex Clauses should be like "Clause A.2" and "A.2.3"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1145]
From @intelligent2013

According to ISO DIR 2, Annex clauses are "A.1", "B.1"... and they are considered "clause numbers":
<img width="749" alt="Screenshot 2024-03-24 at 10 47 29 PM" src="https://github.com/metanorma/metanorma-iso/assets/11865/d701b6a7-4e86-4f20-9e19-68423da326fd">

Therefore they should be rendered as:
* "Clause A.1"
* "Clause B.2"
* "A.1.2"
* "B.2.3.4"

reference from Annex A sub-clause to another sub-clause
  - rendered PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/b82f3f71-4d18-4947-8219-b43273dcb215)
  - production PDF:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/be4dd3bf-7a88-490d-bb9f-2fd5cca458c9)

_Originally posted by @Intelligent2013 in https://github.com/metanorma/metanorma-iso/issues/1134#issuecomment-2010589203_

**Comment by opoudjis** [comment]
This change expressly does not apply to BSI.

**Comment by ronaldtse** [comment]
> This change expressly does not apply to BSI.

How come?

**Comment by opoudjis** [comment]
But no clear reason to have the list reference container be any different to a clause crossreference: Clause 7 a), not 7 a).

**Comment by ronaldtse** [comment]
@opoudjis but look at Figure 1, it is the exact same figure as ISO’s, where A.1 is a “Clause number”. Accompanied by the paragraph you quote which are just examples, I’d say it’s a bit in their guide. The proper way is ISO here. I’ll report this bug.

**Comment by opoudjis** [comment]
Until I hear from them that it's in error, I'm going with the example. The figure doesn't take priority over it.

**Comment by ronaldtse** [comment]
@opoudjis just change it now. I’ll email them. Let’s not waste our time in waiting.

**Comment by opoudjis** [comment]
I am not introducing errors, so the answer is no. The documents do not reflect the figure chart, they reflect the examples, and BSI are clearly not authoring "Clause A.1." 

![Screenshot 2024-03-26 at 11 28 56](https://github.com/metanorma/metanorma-iso/assets/1911039/405d2108-de7d-4723-bc0e-47a224a0e33a)
![Screenshot 2024-03-26 at 11 23 00](https://github.com/metanorma/metanorma-iso/assets/1911039/5fdd200b-e74e-4545-bedf-b9f295b4dde8)

**Comment by ronaldtse** [comment]
Well then please keep track of Peter's reply. Please document the current behavior on the website since I can't keep track of this anymore.

**Comment by opoudjis** [comment]
Sure. If I get advice from BSI of a different default, that's what I'll implement.

**Comment by opoudjis** [comment]
BSI have replied, and they will stick with A.1, which is what they have been using to date.
