### ISSUE TITLE
Infer document layout to apply from copyright year

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#1148]
Currently if no document scheme is specified, the current default scheme is applied. If no document scheme is given, but an older copyright year is specified, we will use that to supply the document scheme instead. See https://github.com/metanorma/metanorma.org/issues/728 for the listing of schemes.

**Comment by opoudjis** [comment]
I'm not going to micro-parse the year, which is after all a year: 1979 is assumed effective by default as of 1 Jan 1979. If people want something else, they should declare the scheme explicitly.

**Comment by ronaldtse** [comment]
Okay for year based as long as we have it documented.
