### ISSUE TITLE
New document type: Addendum (historic, 1997 and prior)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1150]
An ISO "Addendum" document looks practically like an Amendment/Corr but has independent clause number like a normal international-standard.

This is used for encoding historic documents such as the [ISO 2533 collection](https://github.com/metanorma/iso-2533).

Metadata needed:
- Base document: edition number, publication date, document identifier, document type, document titles
- Addendum document: addendum title, publication date, addendum number, UDC or ICS (depending on document scheme), descriptors (predecessor of keywords)

These documents are structured like a normal document:
- Foreword
- Body with numbered clauses (Scope ...)
- Annexes (if any)
- Bibliography

ISO 2533:1975/Add 1:1985
<img width="714" alt="Screenshot 2024-03-29 at 9 49 52 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/b60647be-1031-46d0-a3a1-3090e38fcdbb">
<img width="731" alt="Screenshot 2024-03-29 at 9 50 03 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/b97d7a60-8b2a-4d85-8c75-8ebe068aad8a">
<img width="707" alt="Screenshot 2024-03-29 at 9 50 51 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/aae350c6-b905-474f-a5ec-c33dcc0b23c3">
<img width="697" alt="Screenshot 2024-03-29 at 9 51 12 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/fee48d46-d28a-4bd3-b1ce-82f9d09528de">

This seems to be the last Addendum published by ISO:

ISO 2533:1975/Add 2:1997
<img width="669" alt="Screenshot 2024-03-29 at 9 51 33 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/64908072-d5cd-4fd0-87ad-dbd7780ee4ca">
<img width="673" alt="Screenshot 2024-03-29 at 9 51 43 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/ac4a9235-2a37-4d52-a03f-3695de3c8d79">
<img width="669" alt="Screenshot 2024-03-29 at 9 51 55 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/1d220177-9f1e-47c0-bd9a-fcc9bf0fe43a">
<img width="670" alt="Screenshot 2024-03-29 at 9 52 16 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/e2311aa1-7e9a-434a-8791-c12da4a24d40">

<img width="670" alt="Screenshot 2024-03-29 at 9 52 09 AM" src="https://github.com/metanorma/metanorma-iso/assets/11865/265d3614-17aa-4b95-9266-cd9c5853541d">

**Comment by opoudjis** [comment]
Markup documented: you want:

````
= Document title
Author
:docnumber: 17301
:partnumber: 1
:doctype: addendum
:updates: ISO 17301-1:2030
:addendum-number: 3
:title-main-en: Main document
:title-main-fr: Document main
:title-addendum-en: Mass fraction of extraneous matter, milled rice (nonglutinous), sample dividers and recommendation
:title-addendum-fr: Fraction massique de matière étrangère, riz usiné (non gluant), diviseurs d’échantillon et recomma
:updates-document-type: international-standard
````
