### ISSUE TITLE
HTML: Table "units statement" should be part of the table header, now it's split off

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1152]
From metanorma/iso-2533#24

<img width="876" alt="image" src="https://github.com/metanorma/iso-2533/assets/11865/8c4a9c77-7940-4d65-b2ab-9dfc67524e7b">

Original for reference:
<img width="555" alt="Screenshot 2024-04-01 at 12 51 49" src="https://github.com/metanorma/iso-2533/assets/11865/d4889821-9e1d-4c75-858b-63e4872b8b53">

Is that empty row on top intended to be for the units statement?

The units statement should probably go in there, be right aligned, and also put in a smaller font.

**Comment by opoudjis** [comment]
> The units statement should probably go in there, be right aligned, and also put in a smaller font.

https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor441

I have implemented what ISO/IEC DIR 2 have. No smaller font, no inside of empty row. Just right aligned. Not replicating the empty row. As far as I can tell, this issue is now invalid.

**Comment by opoudjis** [comment]
Except that units statement should not be boldface.

**Comment by opoudjis** [comment]
That was put into the ISO styling as `<b>` explicitly, but it is not justified by ISO/IEC DIR 2. Removing.
