### ISSUE TITLE
Word: Table "units statement" outside of table and in funny paragraph alignment, header not repeating properly

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1153]
From metanorma/iso-2533#25

Now:
<img width="539" alt="Screenshot 2024-04-01 at 13 04 17" src="https://github.com/metanorma/iso-2533/assets/11865/fe92c68e-5acb-41e9-a936-f49cfdabb494">

Should probably look like this:
<img width="498" alt="Screenshot 2024-04-01 at 13 04 02" src="https://github.com/metanorma/iso-2533/assets/11865/59c40289-ae0f-4756-9c64-8d2979f2236a">

I put the units statement inside the table's first header row, and changed alignment to right. We probably need some "style" for this units statement because it's meant to be informational and therefore small in font size.

Which makes it look more reasonable as with the original:
<img width="536" alt="Screenshot 2024-04-01 at 13 05 03" src="https://github.com/metanorma/iso-2533/assets/11865/8c3ace0b-dc2d-4a09-9b57-80efd79803d3">

Word does support repeating headers but it seems that the full header is not being repeated, only the first header row:
<img width="503" alt="Screenshot 2024-04-01 at 13 06 18" src="https://github.com/metanorma/iso-2533/assets/11865/ca0b6c3e-a308-426e-88cb-5f3edfbf3684">

P.S. I'm actually impressed that Word loaded the file so fast, and smoothly scrollable, compared to Safari.

**Comment by opoudjis** [comment]
> P.S. I'm actually impressed that Word loaded the file so fast, and smoothly scrollable, compared to Safari.

It's hung my Word instance, so I don't share the sentiment...

**Comment by opoudjis** [comment]
Note currently looks like this:

![Screenshot 2024-06-24 at 01 21 49](https://github.com/metanorma/metanorma-iso/assets/1911039/6972436b-b444-4bd2-9880-bef4796a28b6)

Boldface has just been removed. Need to see if there is a built-in style for keeping right alignment and/or small font. Will not be moving note inside table, that's not how ISO define it.
