### ISSUE TITLE
Add boldfaced "Key" title in the table footer when `%key` is used

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#1162]
According to ISO's guidelines given in https://github.com/metanorma/mn-samples-iso/issues/96#issuecomment-2067627510 regarding the `key` element in the table footer, the `key` section should be preceded by a “Key” title in bold, as shown in the example below.

![IMG_4572](https://github.com/metanorma/mn-samples-iso/assets/11865/a271dd80-2472-4b76-831f-fdca453a1bfa)

Currently, Metanorma generates the `key` section as below
![image](https://github.com/metanorma/mn-samples-iso/assets/55683568/e9d7563b-4c56-4459-8615-1acfd3eac01b)
when the following markup is used.
````
NOTE: Ce tableau est basé sur l'<<ISO7301,table=1>>.

NOTE: Certains contrats commerciaux peuvent exiger des complémentaires à celles fournies dans le présent tableau.

NOTE: Seul le riz (cargo) rouge entièrement décortiqué est pris en considération dans le présent tableau.

[%key]
N/A:: N'est pas applicable.
````

**Comment by opoudjis** [comment]
To move table key around properly in Word postprocessing, which is not currently happening, need to wrap it in `div[@class = 'figdl']`, treating  it the same as figure keys are already being treated.

**Comment by opoudjis** [comment]
I'm marking up this key title as the title of a definition list, which is ListTitle; but ListTitle is centered, and this Key is not. Ugh. Will override in postprocessing.

**Comment by opoudjis** [comment]
Need to keep definition list, preceding title paragraph and following notes together in a div in rendering in HTML and DOC output, since they are going to be treated as a unit.

**Comment by opoudjis** [comment]
Will finish tomorrow
