### ISSUE TITLE
Inflect Russian date of printing

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#1200]
From https://github.com/metanorma/metanorma-iso/issues/1089:

While this is an edge case, the Russian ordinal needs inflection:

date_printing: Дата % печати

the % needs to be in the genitive. Also the French instance's ordinal needs to be in the feminine.

I've got that implemented somewhere, just need to look it up; hopefully twitter-cldr-rb knows about inflected ordinals.

**Comment by opoudjis** [comment]
So @Intelligent2013 I am going to use my i18n to inflect the Russian and French ordinals; that means that I will populate it instead of you. 

I see that this is driven by `<xsl:variable name="number_printing" select="normalize-space(/iso:iso-standard/iso:metanorma-extension/iso:presentation-metadata[iso:printing-date][1]/iso:printing-date)"/>` and 

````
:presentation-metadata-printing-date: second,1965-12-01
````

My change would allow the user to just specify a number: 

````
:presentation-metadata-printing-date: 2,1965-12-01
````

And in English, French, and Russian, that will generate _second_, _deuxième_ (feminine), and второво (fem.sg.gen). Without this, you will need to tell the user to type `:presentation-metadata-printing-date: второво,1965-12-01` for Russian.

I will give you a draft to test out before committing this.

**Comment by Intelligent2013** [comment]
@opoudjis ok, agree. But one comment. Instead of `второво`, should be `второй`.

**Comment by opoudjis** [comment]
Wait, it's a genitive, right? Дата второво печати?

The information will appear in /bibdata/ext/date-printing

**Comment by opoudjis** [comment]
Oh! That IS the feminine genitive!

**Comment by Intelligent2013** [comment]
> Wait, it's a genitive, right? Дата второво печати?

Yes, genitive. In Russian there isn't word 'второво'. There is 'второ*г*о' (numeral for masculine noun). For feminine noun - _второй_.

**Comment by opoudjis** [comment]
@Intelligent2013  It's late, so I was confused enough to spell второго phonetically lol, and I was further confused enough not to realise that on Wiktionary, the feminine was the third column, not the second in the declension table. :-)

Please try out with this file:

[a.presentation.xml.zip](https://github.com/user-attachments/files/16551068/a.presentation.xml.zip)


[a.presentation.xml.zip](https://github.com/user-attachments/files/16551058/a.presentation.xml.zip)

**Comment by Intelligent2013** [comment]
@opoudjis everything is ok:

![image](https://github.com/user-attachments/assets/1f6e8afe-11a0-41c5-8604-9a4eb2664370)
