### ISSUE TITLE
The version of the latest release seems not correct

### ISSUE THREAD

**Issue by kwkwan** [metanorma/metanorma-iso#1205]
The latest release `v2.3.8` seems not correct.  It is supposed to be `v.2.8.3`.

<img width="1617" alt="Screenshot 2024-08-19 at 4 45 28 PM" src="https://github.com/user-attachments/assets/51b411f5-6624-4883-948a-73fa0f75e388">

**Comment by opoudjis** [comment]
Typo, fixed.
