### ISSUE TITLE
Editorial check: all tables/figures/equations/annexes need to be referenced at least once

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1211]
From @stuartgalt 
* https://github.com/orgs/metanorma/discussions/10

ISO style checks should make sure that all tables, figures, equations are referenced somewhere in the document. 

@ronaldtse 

This is an ISO DIR or House Style requirement. All these items and the Annexes need to be referenced at least once.

**Comment by opoudjis** [comment]
That is not how I read  the ISO House Style at all, but I will implement this: all numbered tables, figures, formulae, annexes. Presumably not examples, notes, admonitions, lists.

**Comment by ronaldtse** [comment]
Providing references as requested by @opoudjis :

ISO DIR 2:

Annexes

<img width="378" alt="Screenshot 2024-09-08 at 4 29 22 PM" src="https://github.com/user-attachments/assets/88909f65-51ba-4462-aa03-4b15e6cd5b83">

Formulas

<img width="868" alt="Screenshot 2024-09-08 at 4 34 19 PM" src="https://github.com/user-attachments/assets/94516964-8ab5-4c86-94e3-7555d37da884">

Figures

<img width="516" alt="Screenshot 2024-09-08 at 4 00 13 PM" src="https://github.com/user-attachments/assets/0028fac2-6e00-4664-ade5-72fea5a460ae">

Tables

<img width="421" alt="Screenshot 2024-09-08 at 3 59 58 PM" src="https://github.com/user-attachments/assets/899b8200-a0e0-40f5-8d7b-2b3ec1df5d68">

-----


I am seeking clarification from ISO on whether:
* subfigures need references
* unnumbered formulas need references

**Comment by opoudjis** [comment]
I continue not to interpret ISO/IEC DIR 2 that way (the examples are more about making sure the examples are not *implicitly* referenced, e.g. as "see the following example") In any case, done.

**Comment by ronaldtse** [comment]
We received the following clarification from ISO:

> 1. the current wording that says “xxx shall be explicitly referred to within the text” means “xxx must be referred within the text at least once” (this is my understanding).

=> Yes. “shall” expresses a requirement.

> 2. a formula can unnumbered, and in this case it does not need to be referenced inside the text? According to Directives, Part 2, 27.4, a formula should be referenced if it is numbered.

=> “Should” expresses a recommendation, so it’s not required to reference a formula, but it’s good practice to do so.

> 3. a subfigure must have an internal reference from the text? The requirement to reference figures only applies to top-level figures.

=> Subfigures can be referenced in the text but this is not obligatory.

**Comment by opoudjis** [comment]
2 would mean that the warning about formulas not being referenced is downgraded, from 1 to 2.
