### ISSUE TITLE
documentation: clarification of :docnumber and :partnumber for multi-part iso deliverables

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-iso#1225]
on this page https://www.metanorma.org/author/iso/ref/document-attributes/
the following text describes` :docnumber `and `:partnumber`

![image](https://github.com/user-attachments/assets/9c090b3c-6a60-424c-8293-33d889d9c6d6)

what happens to `:docnumber` in a multi-part standard.

for example, considering ISO 19115-1

is it:

```
:docnumber: 19115-1
:partnumber: 1

```
or is it:

```
:docnumber: 19115
:partnumber: 1
```

**Comment by ronaldtse** [comment]
It is the latter.

**Comment by ReesePlews** [comment]
hi @ronaldtse thanks for the clarification.
