### ISSUE TITLE
Method to cite multiple clauses

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#180]
Original published PDF:

![screen shot 2018-06-27 at 1 29 05 am](https://user-images.githubusercontent.com/11865/41929055-a8842c1c-79a9-11e8-86e9-b2c3fe23d0cc.png)

Generated HTML:

![screen shot 2018-06-27 at 1 28 34 am](https://user-images.githubusercontent.com/11865/41929031-9e1b18e4-79a9-11e8-9c20-88700728df01.png)

Code:

```
==== Plan-Do-Check-Act cycle

The PDCA cycle can be applied to all processes and to the quality management
system as a whole. <<figure-2>> illustrates how Clauses <<context>> to
<<improvement>> can be grouped in relation to the PDCA cycle.
```

**Comment by opoudjis** [comment]
... OK, but this should only drop the first locality: Clause 3 Table 1 should still render as "3 Table 1".

**Comment by opoudjis** [comment]
This is an enhancement to functionality. It requires a new nolocality flag to be added to citations in ISOXML (not noclause, since this applies to any locality).

**Comment by opoudjis** [comment]
Calling it droploc:

````
Clauses <<context,droploc=true>> to
<<improvement,droploc=true>>
````
