### ISSUE TITLE
Support multiple TC identifiers for standards

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#235]
These are known as N numbers. I would appreciate any available documentation for them. Failing that, there will be a list of tc-docnumber1, tc-docnumber2... as document attributes.

**Comment by ronaldtse** [comment]
Thanks, not urgent for now.

**Comment by opoudjis** [comment]
Given that I have not received any documentation on these in the past 10 months, I am implementing these as a comma delimited array of numbers.

**Comment by ronaldtse** [comment]
Each TC or WG may assign N-numbers for the documents. We have to support multiple of these, eg. A document with WG N0001 can also have SC identifier N0501 and TC identifier N1001.
