### ISSUE TITLE
Genericise Quickstart document

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#238]
Make Quickstart document generic to all Metanorma classes, with appendixes specific to each Metanorma class. Include UNECE as a class.

**Comment by strogonoff** [comment]
There is now a generic quick start, with more coming, on https://www.metanorma.com/author/.

**Comment by opoudjis** [comment]
I *think* this is @strogonoff's issue for now. Once the structure is all in place and I need to review and update it, assign it back to me.
