### ISSUE TITLE
Support final Proof stage

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#254]
At the stage "50" we can have an FDIS or a PRF (final proof). i.e. After FDIS approval, there is a pre-publication "proof" (document stage code: PRF).

We should update the model and the implementation. I'm not exactly sure how the stage code differs from the FDIS stage code. Maybe it is "60.00" ("International Standard under publication")?

https://www.iso.org/stage-codes.html

**Comment by opoudjis** [comment]
@ronaldtse I'm happy to implement, but I need you to confirm that PRF is in fact 60.00; I don't have enough assurance from you to implement this yet. The stage codes page speaks of FDIS and proofs interchangeably, which is suspect: "50.99 FDIS or proof approved for publication".

**Comment by ronaldtse** [comment]
FDIS is 100% different from PRF.

Technically, a document is an FDIS = DIS + DIS-comments. This comment resolution process is done by the project leader/editor(s) (as with previous stages). Once this is done, FDIS goes into approval process.

If FDIS gets approved, PRF = FDIS + FDIS-comments. This comment resolution process is done by ISO/CS. Once this is done, PRF is approved by ISO/CS (with advice from project leader/editor(s)).

If you consider that DIS -> FDIS is 50.99 (i.e. pre-50.99), then FDIS -> PRF is 60.00 (i.e. pre-60.00).
