### ISSUE TITLE
Intelligent term references and formatting

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#255]
In ISO documents, terms used in definitions within the T&D section are required to be "italicized" and "referenced".

e.g. 
![screen shot 2019-02-13 at 2 24 01 pm](https://user-images.githubusercontent.com/11865/52691194-031a4380-2f9b-11e9-9d03-6035d403e9f8.png)

In this example, the term "duration", "seconds" and "leap second" are terms defined within this document's T&D, and therefore require the above formatting treatment. In the definition/notes, only the first occurrence of the term will receive this treatment -- the second and subsequent occurrences will be just treated normally.

Currently in Metanorma, we use this code to generate the output:

```adoc
[[term-minute]]
===== minute

_duration_ (<<term-duration>>) of 60 _seconds_ (<<term-second>>)

NOTE: See also <<ISO80000-3>>.

NOTE: The duration of a minute is 60 seconds except if modified by the insertion or deletion of a _leap second_ (<<term-leap-second>>)
```

However, this practice has proven mechanical, time-consuming and error prone for the human (and the editor). (painful for me)

This issue is to investigate the possibility of doing something like this:

```adoc
===== minute

term:[duration] of 60 term:[seconds,second]

NOTE: See also <<ISO80000-3>>.

NOTE: The duration of a minute is 60 seconds except if modified by the insertion or deletion of a term:[leap second]

```

Or even fully automatic like this:

```adoc
===== minute

duration of 60 seconds

NOTE: See also <<ISO80000-3>>.

NOTE: The duration of a minute is 60 seconds except if modified by the insertion or deletion of a leap second

```

Frankly it seems difficult to make it all automatic because with terms like "leap second" we could be matching "leap second" or just "second", there are also pluralities to consider "seconds" vs "second".

I'm happy enough to have some human-input, but the less of that the better.

**Comment by ronaldtse** [comment]
At least, we know that every term clause will need to be referenced (i.e. we don't need to manually write `[[term-xxx]]`), so it would be already a good step up to automatically create these `term-xxx` references.

**Comment by opoudjis** [comment]
As you correctly said, autodetecting terms is error-prone enough that it should not be done.

The semi-automated input is intriguing; it is feasible, but will probably require postprocessing.

**Comment by opoudjis** [comment]
The steps here are:

* In cleanup(), early on in the process: go through all //term instances, and if their ID is a GUID, replace it with "term-#{term.text}" If that anchor is already in use, keep suffixing numbers to the ID until it is unique in the document.
* Define a macro: "term:[X,Y]", with the second argument optional (defaults to identical to the first argument).
* Expand it to `<em>Y</em> (<termxref>X</termxref>)`
* In cleanup(), after we have made up all the IDs for terms, create a lookup table of terms to their anchors: 

````
docxml.xpath("//term").each do |x|
  p = x.at("./preferred")
  termlookup[p.text] = x["id"]
end
````

* And then globally replace all `<termxref>X</termxref>` with `<xref target="#{termlookup[X]}"/>`

Please discuss with me before starting. I will want to keep cleanup() tidy...

**Comment by ronaldtse** [comment]
Are we going to replace whitespaces and deal with capitalization changes in the anchors? i.e. term "X Y Z" => anchor "term-x-y-z"?

**Comment by opoudjis** [comment]
Merged, thank you! Please also add documentation to https://github.com/metanorma/metanorma.com/blob/master/author/iso/topics/markup.adoc , as a new clause under "Terms and Definitions": say that all terms have automatically assigned ID consisting of "term-" + term text, and what the macro does, with two or three examples.

**Comment by opoudjis** [comment]
Oh, you forgot to replace spaces and caps. Doing that now, include that in documentation.

**Comment by ronaldtse** [comment]
And this please: https://github.com/metanorma/metanorma-iso/issues/368

**Comment by ronaldtse** [comment]
This is to be done in https://github.com/metanorma/metanorma-iso/pull/369 now.

**Comment by w00lf** [comment]
@opoudjis @ronaldtse can i close it now?

**Comment by ronaldtse** [comment]
@w00lf let's close this. Thanks!
