### ISSUE TITLE
Refactor common components of isodoc/pdf_convert.rb, isodoc/html_convert.rb, isodoc/word-convert.rb

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#267]
Same refactoring as @CAMOBAP795 has just done with metanorma-ogc. To be applied to all metanorma-* gems but metanorma-standoc. 

metanorma-nist is under heavy active development, I will do the refactoring there.

**Comment by CAMOBAP795** [comment]
So list looks like:
 - [x] metanorma-nist
 - [ ] metanorma-acme
 - [ ] metanorma-csand
 - [ ] metanorma-csd
 - [ ] metanorma-gb
 - [ ] metanorma-iec
 - [ ] metanorma-ietf
 - [x] metanorma-iso
 - [ ] metanorma-itu
 - [ ] metanorma-m3d
 - [ ] metanorma-mpfd
 - [x] metanorma-ogc
 - [ ] metanorma-rsd
 - [x] metanorma-standoc
 - [ ] metanorma-unece

@opoudjis could you please confirm it

**Comment by opoudjis** [comment]
* Nothing to do in metanorma-standoc
* I will be doing NIST
* OGC is done
* ISO is to be done, unless you've already done it
* I have misnamed the files in m3d, you might as well rename them ;)
* Add metanorma-sample to the list. This has no associated gem, it is a skeleton for people to build new gems with.

**Comment by CAMOBAP795** [comment]
Done, PRs ready for review

**Comment by opoudjis** [comment]
With thanks.
