### ISSUE TITLE
Title with parts rendering funny

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#271]
Seems that part rendering has changed -- there's an empty line in between the main and part titles?

Now:
<img width="455" alt="Screen Shot 2019-05-31 at 1 19 25 PM" src="https://user-images.githubusercontent.com/11865/58683481-254b9c00-83a7-11e9-97b4-436604760178.png">

Old:
<img width="458" alt="Screen Shot 2019-05-31 at 1 21 24 PM" src="https://user-images.githubusercontent.com/11865/58683487-2aa8e680-83a7-11e9-9298-78ba0b179b95.png">

**Comment by opoudjis** [comment]
... There's an empty line in both of these. I do not know what you are talking about.

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-iso/issues/261: the line between the main and part titles was what you'd requested.

**Comment by ronaldtse** [comment]
@opoudjis we don't want an empty line, can it be a small vertical space break?

**Comment by opoudjis** [comment]
...

... Is there a specification for this?! This really looks like making things up.

I will remove the blank line, and introduce a top margin above part titles.

**Comment by opoudjis** [comment]
Given it 6pt on Word.
