### ISSUE TITLE
References now rendering without title-intro

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#272]
Look at this:

<img width="413" alt="Screen Shot 2019-06-25 at 4 50 02 PM" src="https://user-images.githubusercontent.com/11865/60083991-48305c80-9769-11e9-83db-5fe18d52ed03.png">

And this is also reproduced in other flavors like OGC:

<img width="431" alt="Screen Shot 2019-06-25 at 4 50 19 PM" src="https://user-images.githubusercontent.com/11865/60084015-52525b00-9769-11e9-887b-71a33c86aced.png">

I suspect this has to do with Relaton ISO. Needs to be fixed. Thanks!

ping @opoudjis @andrew2net

**Comment by ronaldtse** [comment]
P.S. These references are all auto-fetched.

**Comment by opoudjis** [comment]
I will hear NOTHING from you about new functionality in Metanorma, Ronald, and this is why.

This is likely an issue with the renaming of title types after the relation refactoring. @andrew2net, let me look at this first.

**Comment by andrew2net** [comment]
@ronaldtse in the last big updates the bib model was changed. Now we have an array of titles with different types such us title-main, title-intro, title-part. So to get full title we need to concatenate all titles in metanorma-iso.

**Comment by opoudjis** [comment]
No. We need to pick the right title in isodoc, not the first title it finds (which it used to). I'll take care of it.

The titles fetched are:

````
      <title type="title-main" format="text/plain" language="en" script="Latn">Sampling</title>
      <title type="title-intro" format="text/plain" language="en" script="Latn">Rubber latex</title>
      <title type="main" format="text/plain" language="en" script="Latn">Sampling - Rubber latex</title>
````

The correct title to use is "main", which is in fact already concatenated.
