### ISSUE TITLE
Word output: "Example" should use the "Example" style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#276]
Previously, the content of an Example will have an "Example" style (which is different from "Normal" text). (albeit this is from the period where Examples are rendered as Tables):

<img width="908" alt="Screen Shot 2019-08-13 at 2 40 05 PM" src="https://user-images.githubusercontent.com/11865/62920507-8eed1b00-bdd8-11e9-85d1-d7bb268ea7e2.png">

<img width="909" alt="Screen Shot 2019-08-13 at 2 40 17 PM" src="https://user-images.githubusercontent.com/11865/62920515-957b9280-bdd8-11e9-835f-71191906f164.png">

Now, the Example "label" has the "example_label" style, but the Example content has lost its style:

<img width="929" alt="Screen Shot 2019-08-13 at 2 40 21 PM" src="https://user-images.githubusercontent.com/11865/62920532-a2988180-bdd8-11e9-92e1-12cbf8f17cd0.png">

<img width="940" alt="Screen Shot 2019-08-13 at 2 40 30 PM" src="https://user-images.githubusercontent.com/11865/62920534-a4624500-bdd8-11e9-914d-e1a145d82ff6.png">

This is reported by an ISO author. I think there is some merit in this -- right now, we can't differentiate Normal text and Example text if the Example text contains multiple paragraphs (the first paragraph is discernible, the subsequent ones look just like normal text). (P.S. This is in WORD output)

**Comment by ronaldtse** [comment]
You can use the ISO 690 document to see the output.

**Comment by ronaldtse** [comment]
@opoudjis maybe the point is to check out ISO's current Word template to see how we should render the Example?

**Comment by opoudjis** [comment]
The Word template does not have a distinct Example style. ISO/IEC DIR 2 has examples in table format (despite contrary advice from ISO), and 10pt. We have an example style in the Word stylesheets; but we only apply example style to the div container of examples, not to the paragraphs within the paragraph.

The example style in the Word stylesheets has 10pt text. The div container does not apply its font size in Word. So we need to inherit example style from div to any Normal (unstyled) paragraphs within those div.
