### ISSUE TITLE
Reference to "EXAMPLE n" should be rendered as "EXAMPLE n", not "Example n"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#280]
This is from the Word output. The text should be shown as "EXAMPLE 1" and "EXAMPLE 2" instead of "Example 1" and "Example 2".

<img width="506" alt="Screen Shot 2019-09-26 at 11 38 05 PM" src="https://user-images.githubusercontent.com/11865/65703071-b2350680-e0b6-11e9-8d84-a5bd475a542f.png">

This issue might be better handled in Standoc?

**Comment by opoudjis** [comment]
No, this is ISO-specific practice.

**Comment by ronaldtse** [comment]
OK thanks for clarifying. So within metanorma-iso then.

**Comment by ronaldtse** [comment]
@opoudjis is this fixed or not?

**Comment by opoudjis** [comment]
Yes it is, don't know why I reopened.

**Comment by ronaldtse** [comment]
Thanks!
