### ISSUE TITLE
Links render badly

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iso#286]
Links are rendering with both address and label concatenated. For example, 

For this markup:
````
URL sample: link:http://www.tc184-sc4.org/titles/OTD_Titles.htm[URL label]
````
It renders like:
![capture](https://user-images.githubusercontent.com/33627611/67913597-feff7780-fb63-11e9-99de-74154baab236.JPG)

Please, refer to the sample:
[link-issues.zip](https://github.com/metanorma/mn-templates-iso/files/3791884/link-issues.zip)

This bug has been found in ISO and ITU flavours.

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-standoc/issues/35

Duplicate, and it's an elusive bug as well, it's been very difficult to replicate. Am merging into that ticket.
