### ISSUE TITLE
Line breaks should not cause Word to make text justified

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#289]
```adoc
==== Sample complaint letter

(Your Address) +
(Your City, State, Zip) +
(Date)
```

Gets rendered like this:
<img width="391" alt="Screen Shot 2019-11-07 at 10 37 44 PM" src="https://user-images.githubusercontent.com/11865/68398248-6abe9180-01af-11ea-94e7-91d0b935640f.png">

It's not supposed to be such.

**Comment by opoudjis** [comment]
That is the nature of line breaks in justified paragraphs.

There are two options:

* If I detect line break in a justified paragraph, automatically change it to be left aligned, in postprocessing. That... is presumptuous: it is possible that that rendering is intended.
* Require people to manually set `[align=left]` before any paragraph that they insert line breaks in, and even issue a warning if they don't.

**Comment by ronaldtse** [comment]
Maybe just allow the user to specify “align left”. I don’t see a good solution to this (personally I prefer left alignment of text instead of justified).

**Comment by opoudjis** [comment]
The user can, and so shall you. :-)

I'll note in documentation.
