### ISSUE TITLE
Elimination of post-editing Word: Requirement class "Table" headings.

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#295]
From @rggibb

> Sec 5, Requirements classes on p12 of .docx: remove the ‘Table 1’, and ‘Table 2’ headings, apply a mid-grey cell shading to the header row, and adjust the width. I’ve only used a table here as a way of laying out the text, so I don’t want it labelled as a ‘Table’.

<img width="576" alt="Screen Shot 2019-11-26 at 12 41 24 PM" src="https://user-images.githubusercontent.com/11865/69600084-53eeba80-104a-11ea-8840-ced1c7a73d23.png">

**Comment by opoudjis** [comment]
Requirements have been implemented throughout Metanorma, but rendering requirements as tables is specific to OGC, and extending that rendering to other flavours is unwarranted. I'm not convinced this needs to be actioned: the block rendering of requirements in ISO is legitimate. @ronaldtse?

**Comment by ronaldtse** [comment]
We need to render OGC requirements in ISO flavors, there are a few documents that need this. What's the easiest and cleanest way to do this?

**Comment by ronaldtse** [comment]
Superseded by metanorma/isodoc#200 .
