### ISSUE TITLE
Elimination of post-editing Word: Keep-together

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#296]
From @rggibb

> Lastly, there are a number of elements where I inserted page breaks into the .docx, but this isn’t allowed for DIS submission.
> I believe the preferred method is to use keep-together & keep with following etc to ensure page breaks don’t occur in the wrong places. 
> Examples I think were all around table constructs where I didn’t want the table to split across pages .. these include the Requirements class’s tables above, the Requirements and the Conformance Classes that I described in the previous email below.

I think this we can fix or at least enable keep-together?

**Comment by opoudjis** [comment]
This is not an ISO issue.

**Comment by ronaldtse** [comment]
I'm filing this here because it was reported on an ISO document. Feel free to move it to metanorma-standoc if preferred.

**Comment by ronaldtse** [comment]
We can probably generalize the Errata model we have for the other flavor.

We can inherit from the BasicDoc "ChangeSet" and "Change" models and make the "Modified node" to support a link and plain text.

![image](https://user-images.githubusercontent.com/11865/69638436-a903ee00-1095-11ea-9826-59a501f6cdf6.png)

(from: https://github.com/metanorma/basicdoc-models)
