### ISSUE TITLE
Missing full docidentifier of "ISO nnnn (L)" where L is language

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#298]
In the Rice document, the Word output contains the full identification number:

<img width="240" alt="Screen Shot 2019-12-01 at 4 19 08 PM" src="https://user-images.githubusercontent.com/11865/69911449-a0753400-1456-11ea-8fe8-b35a0a3ffd49.png">

But the XML doesn't:
<img width="759" alt="Screen Shot 2019-12-01 at 4 25 55 PM" src="https://user-images.githubusercontent.com/11865/69911515-93a51000-1457-11ea-8019-7e2f35e00b83.png">

This is an issue with PDF generation: 
https://github.com/metanorma/mn-native-pdf/pull/14

**Comment by opoudjis** [comment]
It is not clear to me at all that "ISO nnnn (L)" should appear to the exclusion of "ISO nnnn". In most instances (and certainly in citing the document), the language suffix is *inappropriate*.

The solution here is not to change the "iso" identifier, but to add a distinct "iso-with-lang" identifier.

**Comment by ronaldtse** [comment]
Good call, I agree.
