### ISSUE TITLE
ISO Rice Chinese marked up differently from English in XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#299]
The ISO Rice document is provided in https://github.com/metanorma/mn-samples-iso . Apparently, the DOC output differs as raised in https://github.com/metanorma/mn-native-pdf/issues/31 . 

Issue content quoted below:

> There are differences between xml and doc for ISO rice.
> 
> 1. In iso-rice-zh.xml there isn't section/preface/introduction, looks like it moved into sections/clause (first clause), i.e. second clause in iso-rice-zh.xml is first clause (Scope) in iso-rice-en.xml.
> 2. If compare docs iso-rice-en.doc  and iso-rice-zh.doc :
> 
>   * in iso-rice-zh.doc  section 'Normative references' (7 elements) moved at the end of document as Bibliography (7 elements)
>   * in iso-rice-zh.doc  there isn't last Bibliography section which contains 16 elements (in iso-rice-en.doc).
>   But xml there are such data.
> 
> 3. In iso-rice-en.xml  the section 'Terms and definitions' placed in terms/term tag, but iso-rice-zh.xml this section placed in clause/clause tag.
>    These texts 'paddy', 'husked rice', 'milled rice' display in Contents table (see image), because they are in clause/clause (we show 1st and 2nd level titles from clauses).
> 
> ![Untitled](https://user-images.githubusercontent.com/5559926/69905029-70c71d00-13bf-11ea-9b08-efbc3a543d2b.png)

**Comment by ronaldtse** [comment]
The Chinese XML T&D section is marked up incorrectly, see https://github.com/metanorma/mn-native-pdf/issues/31#issuecomment-566579269 .

**Comment by opoudjis** [comment]
I actually stumbled across some of these errors the other day, and fixed a couple already.

**Comment by opoudjis** [comment]
The issue is that the parser only recognises titles as distinct structural elements in English. If the title is in a different language, you need to use the `heading` attribute to indicate what kind of title it is.

**Comment by opoudjis** [comment]
... In fact yes, I did already fix them.
