### ISSUE TITLE
Non-English language issues with generated MN XML Table of Contents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#300]
This issue shows up here: https://github.com/metanorma/mn-native-pdf/pull/14

The source files are at https://github.com/metanorma/mn-samples-iso

English version:
<img width="591" alt="Screen Shot 2019-12-02 at 3 03 33 PM" src="https://user-images.githubusercontent.com/11865/69937313-674fc900-1515-11ea-92e7-1c69b078a19a.png">

Chinese version:
<img width="592" alt="Screen Shot 2019-12-02 at 3 03 27 PM" src="https://user-images.githubusercontent.com/11865/69937317-6cad1380-1515-11ea-9cce-ef06844c3536.png">
<img width="608" alt="Screen Shot 2019-12-02 at 3 06 25 PM" src="https://user-images.githubusercontent.com/11865/69937394-a716b080-1515-11ea-9201-918a001fae78.png">

Notice that in the Chinese version:

* "Contents" should have been in Chinese.
* "Introduction" “引言” is given as a numbered section, but should have been unnumbered.
* "Scope" “范围” is given as clause 3, but should have been clause 1.
* Clause 2 "Bibliography" should be in Chinese.
* Clause 3 should have been "Terms and definitions" “术语和定义” and the term clauses should not be listed in the TOC.
* "Annex A (normative)" should be in Chinese.
* "Bibliography" at the end should have been in Chinese.

**Comment by opoudjis** [comment]
In reality, the internationalisation model needs to be revisited. The assumption to date has been that titles are internationalised on isodoc, but the PDF stylesheets being unencumbered by i18n, the titles need to be internationalised in XML, and any decision making based on title content needs to be moved to a type attribute on the clause.

**Comment by opoudjis** [comment]
The needed refactor is:

1. Internationalisation needs to be defined as a class, with class inheritance, just as is now done with xrefs.
2. There is only one internationalisation file, in isodoc class, and asciidoc class uses the isodoc internationalisation class.

**Comment by opoudjis** [comment]
Refactor of 1, 2 is done. Now the fixes requested in December become dependent on metanorma/isodoc#171.

**Comment by opoudjis** [comment]
Only things remaining in PDF: "Contents" and "Page".

Have fixed "Contents" in HTML/DOC. @Intelligent2013, please use //localized-strings to look up:

`<localized-string key="table_of_contents" language="fr">SOMMAIRE</localized-string>`
`<localized-string key="locality.page" language="fr">Page</localized-string>`
