### ISSUE TITLE
Compliance with ISO Rice table output

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#302]
Originally from https://github.com/metanorma/mn-native-pdf/issues/34

Heading should be boldfaced in Table D.1.

> Definitive:
> <img alt="Screen Shot 2019-12-03 at 10 56 01 AM" width="555" src="https://user-images.githubusercontent.com/11865/70016643-d67ff880-15bb-11ea-8626-b971bb1ab70b.png">
> 
> DOC:
> <img alt="Screen Shot 2019-12-03 at 10 55 31 AM" width="529" src="https://user-images.githubusercontent.com/11865/70016628-cec05400-15bb-11ea-830c-84788392c889.png">
>

**Comment by ronaldtse** [comment]
In Table 1, first two rows should be boldfaced, i.e. terms such as "in husked rice" should be boldfaced

> Here's the definitive image from the original ISO Rice document:
> <img alt="Screen Shot 2019-12-03 at 10 52 53 AM" width="547" src="https://user-images.githubusercontent.com/11865/70016482-67a29f80-15bb-11ea-910a-de9e6d79674d.png">
>
> DOC:
> 
> > ![image](https://user-images.githubusercontent.com/55683568/69986795-5f584f00-153e-11ea-83b1-64490e10feb9.png)
> 
> The DOC version: should have the 2nd header row bolded, and the math unbolded. Missing "%" sign in the header row 1 column 2 as line 3. (ping @opoudjis )
> 

Entries are vertically centered in the Table 1 in the rendered document, while they are vertically aligned to the top in the original document (example above)

**Comment by opoudjis** [comment]
If 'headerrows` is used to designate multiple header rows, all those rows must contain `th` instead of `td`.
