### ISSUE TITLE
Compliance with ISO Rice: Equations

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#303]
1. Equations should not be vertically centered
2. The indent for the definition list after "where" is incorrect.

Definitive image from the original ISO Rice:

<img alt="Screen Shot 2019-12-03 at 10 54 33 AM" width="552" src="https://user-images.githubusercontent.com/11865/70016561-a173a600-15bb-11ea-96cb-e46ee85ec02b.png">

DOC:

![image](https://user-images.githubusercontent.com/55683568/69987071-f6250b80-153e-11ea-976d-4afd801f2e65.png)

**Comment by opoudjis** [comment]
> Equations should not be vertically centered

Already the case, this is cut and paste from https://github.com/metanorma/mn-native-pdf/issues/34#issuecomment-560977827

**Comment by opoudjis** [comment]
Will make classes dl.formula and dl.figure

**Comment by opoudjis** [comment]
Mark up output dl after formula as class "formula".
