### ISSUE TITLE
Compliance with ISO Rice document: Preface handling

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#304]
The ISO preface clause should only be numbered (with 0, 0.1, 0.2...) IFF it has subsections.

DOC:
<img width="641" alt="Screen Shot 2019-12-03 at 12 45 08 PM" src="https://user-images.githubusercontent.com/11865/70021268-14d0e400-15cb-11ea-8826-82913a3fbb7d.png">

Rice:
<img width="606" alt="Screen Shot 2019-12-03 at 12 44 53 PM" src="https://user-images.githubusercontent.com/11865/70021261-0b477c00-15cb-11ea-85f1-2b08df7fa7ec.png">

**Comment by opoudjis** [comment]
The Word output is consistent with the sectioning rule; the difference is in markup, and mn-samples-iso does not mark up the Patent Notice any more. (I had originally done so in pursuit of semantic markup.) So this is a non-issue.
