### ISSUE TITLE
Compliance with Rice document: Hyperlinks should be in BLUE and UNDERLINED

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#305]
URLs:
<img width="591" alt="Screen Shot 2019-12-03 at 12 46 03 PM" src="https://user-images.githubusercontent.com/11865/70021298-3500a300-15cb-11ea-990e-71db37eaeb69.png">

Clauses:
<img width="572" alt="Screen Shot 2019-12-03 at 12 46 11 PM" src="https://user-images.githubusercontent.com/11865/70021304-39c55700-15cb-11ea-83bc-fc93970eb51c.png">

Tables and Figures are not highlighted in Rice, but it's because they are not hyperlinks. We should retain them as hyperlinks and highlight them as well.

**Comment by opoudjis** [comment]
Confirmed in ISO template
