### ISSUE TITLE
Enhancement: Bibliographic references can be split into sub-clauses

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#306]
<img width="1337" alt="Screen Shot 2019-12-21 at 1 58 01 AM" src="https://user-images.githubusercontent.com/11865/71280113-53211e00-2395-11ea-88be-bdc648bfe895.png">

https://isotc.iso.org/livelink/livelink/fetch/2000/2122/4230767/Drafting_standards_-_Frequently_asked_questions_(FAQ).pdf?nodeid=18973477&vernum=-2

**Comment by opoudjis** [comment]
````
[bibliography]
== Bibliography

=== Biblio1

* [[[ISO_13399,ISO 13399 (all parts)]]], _Cutting tool data representation and exchange_.
````

renders as:

````
<bibliography><clause id="_bibliography" obligation="informative">
<title>Bibliography</title>
<references id="_biblio1" obligation="informative">
<title>Biblio1</title>
</references>
````

So this is doable, we just need to ensure that bibliography/clause/references is recognised correctly.

**Comment by ronaldtse** [comment]
@opoudjis the proposed solution looks good!

**Comment by opoudjis** [comment]
We've documented and tested this, in response to other tickets: https://www.metanorma.com/author/topics/document-format/bibliography/#general
