### ISSUE TITLE
Change namespace from "http://riboseinc.com/isoxml" to a proper one

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#307]
This namespace is not ideal for many reasons, it was temporary and doesn't resolve.

```xml
<iso-standard xmlns="http://riboseinc.com/isoxml">
```

I suggest we change the XML namespace to something proper, like "https://www.metanorma.org/ns/iso.org".

Thoughts @opoudjis ?

**Comment by opoudjis** [comment]
metanorma.org/ns/iso.org doesn't currently resolve either.

If they are to resolve, they should resolve to an online copy of the schema for each flavour.

Any implementation needs the refactoring in https://github.com/metanorma/metanorma-standoc/issues/155

**Comment by opoudjis** [comment]
Namespaces currently in Metanorma:

metanorma-acme:   "https://open.ribose.com/standards/acme"
metanorma-csand:      "https://open.ribose.com/standards/csa"
metanorma-csd:      "https://www.calconnect.org/standards/csd"
metanorma-gb:      "http://riboseinc.com/gbstandard".
metanorma-iec:      "http://riboseinc.com/isoxml"
metanorma-ietf:      "https://open.ribose.com/standards/ietf"
metanorma-iso:      "http://riboseinc.com/isoxml"
metanorma-itu:    "https://open.ribose.com/standards/itu"
metanorma-m3d:      "https://open.ribose.com/standards/m3d"
metanorma-mpfd:      "https://open.ribose.com/standards/mpfd"
metanorma-nist:      "http://www.nist.gov/metanorma".freeze
metanorma-ogc:    "https://standards.opengeospatial.org/document"
metanorma-rsd:    "https://open.ribose.com/standards/rsd"
metanorma-sample:    "https://open.ribose.com/standards/example"
metanorma-standoc:      "http://riboseinc.com/isoxml"
metanorma-unece:    "https://open.ribose.com/standards/unece"
metanorma-vsd:     'https://open.ribose.com/standards/vsd'

These should be replaced by a namespace that

* follows a consistent pattern (unless it is hosted externally, as in CSD, NIST, OGC)
* is resolvable to something meaningful

I suggest, in order of preference:

* The metanorma.com flavour landing page
* The GitHub UML repository
* The GitHub gem repository

**Comment by ronaldtse** [comment]
How about a base of https://www.metanorma.com/ns/{flavor} ?

**Comment by ronaldtse** [comment]
Discussed. We will use `https://www.metanorma.org/ns/{flavor}` and make that URL resolvable.
