### ISSUE TITLE
Discover gaps in non-English language support (in ISO)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#309]
There should not be any English in the TOC. It is likely that Metanorma-ISO needs to be fixed to provide Chinese clause labels in the XML.

From https://github.com/metanorma/mn-native-pdf/issues/59#issuecomment-577430232 , notice:

> Section 1 differs in DOC and PDF. Normative references are rendered as 2nd section in PDF and as 1st section in DOC. 

Here the DOC is clearly wrong. The word ”范围“ means "scope" so it should be Clause 1.

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-native-pdf/issues/59#issuecomment-577430232_

**Comment by opoudjis** [comment]
Recall that the Chinese Rice document was incorrectly marked up; it did not use the "heading" attribute to identify section headings. I fixed this last week, which means that the scope should have gone to the right place.

Do not assign me this issue until I am MUCH less overloaded. The PDF conversion is imposing a ton of work on me, and I am unlikely to get to this for a couple of months.

**Comment by opoudjis** [comment]
This issue will have gone away with the internationalisation refactoring just completed. Could someone please review it?

**Comment by ronaldtse** [comment]
@metanorma/editors can you help discover (and file issues) the gaps we have in non-English ISO documents? Thanks!

**Comment by ronaldtse** [comment]
Seems that this is done, thanks!
