### ISSUE TITLE
ISO Word DOC copyright style broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#310]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/11865/73506029-3bff3280-440f-11ea-9518-8fc5548beee1.png">

**Comment by ronaldtse** [comment]
Previously:
<img width="596" alt="Screen Shot 2020-01-31 at 10 35 12 AM" src="https://user-images.githubusercontent.com/11865/73507901-5d631d00-4415-11ea-866b-9dc76df6b3ed.png">

**Comment by opoudjis** [comment]
In fact, the top format was what was originally intended, judging from the CSS. But it also doesn't match the Word format, so I'll eliminate it.

Boilerplate in the XML is of course going to be the natural enemy of minute variation between text instances. This is going to be a lot more of my time wasted.

**Comment by ronaldtse** [comment]
The top format is clearly defective -- there did not used to be any color.

**Comment by ronaldtse** [comment]
Let me check on this variance between the text before we move forward here.

**Comment by ronaldtse** [comment]
Official:

<img width="516" alt="Screen Shot 2020-02-05 at 7 31 05 AM" src="https://user-images.githubusercontent.com/11865/73796890-79860600-47e9-11ea-8296-6b42269f38df.png">

**Comment by ronaldtse** [comment]
Let's call this the update to ISO 2020 copyright style.
