### ISSUE TITLE
"subcommittee-type" attribute is missing default

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#311]
Previously `:subcommittee-type:` was set to "SC" by default, but now it's not set:

e.g. 
<img width="595" alt="Screen Shot 2020-01-31 at 10 16 17 AM" src="https://user-images.githubusercontent.com/11865/73507080-b9787200-4412-11ea-973c-b157d88c3273.png">

**Comment by opoudjis** [comment]
User error.

The default value of `//bibdata/ext/editorialgroup/subcommittee/@type` is still "SC".

However, that type is extracted in metadata, prefixed to the subcommittee number, and made available to Liquid template as the variable `{{ sc }}`.

The "This document ... {subcommittee-type}" is nothing to do with Liquid. It is using asciidoctor's  document variables, and if subcommittee-type is not set as a document variable, nothing will show up there.

User confusion with Asciidoctor formatting should not be adding to my backlog.

**Comment by ronaldtse** [comment]
@opoudjis please indicate the correct markup for this. This is the boilerplate used for many ISO documents.

**Comment by opoudjis** [comment]
The correct markup is either to populate `subcommittee-type` as a document variable, or not to use the document variable. In fact, given the folly and fallibility of humans, avoid using subcommittee-type as a document variable. Just put SC in there.

**Comment by ronaldtse** [comment]
I wonder if there's a way to auto-populate this line, but maybe this is overengineering since it's only being done once per document.

**Comment by ronaldtse** [comment]
Fine leaving as is.
