### ISSUE TITLE
3.1 "Terms and definitions" broken formatting in Word DOC

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#313]
<img width="612" alt="Screen Shot 2020-01-31 at 12 31 32 PM" src="https://user-images.githubusercontent.com/11865/73512750-bc309280-4425-11ea-8d6e-e36db0e58245.png">

See http://gitlab.com/metanorma/iso-tc184-sc4 , under `sources/iso-8000/part100-2` .

**Comment by opoudjis** [comment]
Solution is to preempt treating a terminal node under a terms section as a term, and treat it as non-terminal, if it itself contains a reserved title (which "Terms and definitions" is.)

**Comment by opoudjis** [comment]
See if boilerplate needs  to move to empty 3.1.

**Comment by ronaldtse** [comment]
Seeking clarification from ISO EPM.

**Comment by opoudjis** [comment]
Remaining query on boilerplate now https://github.com/metanorma/metanorma-iso/issues/325

**Comment by ronaldtse** [comment]
Superseded by #325.
