### ISSUE TITLE
Visual differentiation of term references (ISO 704:2009)?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#318]
ISO 704:2009 "Terminology work — Principles and methods" is a core requirement for ISO documents, and it contains this paragraph:

> The notation used throughout this International Standard is as follows:
> ⎯ terms designating concepts defined in ISO 1087-1:2000 are in italics;
> ⎯ concepts are indicated by single quotes;
> ⎯ designations (terms, appellations or symbols) are in boldface;
> ⎯ characteristics are underlined;
> ⎯ examples are boxed.

This is not a requirement for other documents, but just an internal usage within this document.

For terminology references via `{{...}}`, perhaps there is benefit to enclose them with italics?

**Comment by opoudjis** [comment]
> This is not a requirement for other documents, but just an internal usage within this document.

Document-specific practices in large-scale formatting, such as boxing examples, are more than we can or should be doing. In HTML, it's simply a matter of dropping in CSS; in DOC, it's novel code. If people want ad hoc formatting, they should be using Word.

> For terminology references via {{...}}, perhaps there is benefit to enclose them with italics?

... Maybe. I'd prefer bold though; italics is used in normal text for emphasis, and is admittedly used in that function in Terms & Definitions; but italics would be too indistinct in main text.

**Comment by opoudjis** [comment]
Italics.

**Comment by ronaldtse** [comment]
Yeah let's do Italics so it's consistent with the reference style in Clause 3.

**Comment by opoudjis** [comment]
Internationalising rendering of concept, dealing with it in Presentation XML.
