### ISSUE TITLE
ISO HTML template using wrong numbered list bullets

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#319]
Numbered list bullets should be "a)" instead of "a." in documents. This was discovered at an ISO meeting today.

HTML is wrong:
<img width="858" alt="Screen Shot 2020-02-11 at 5 13 15 PM" src="https://user-images.githubusercontent.com/11865/74223494-cbe78b00-4cf1-11ea-847b-d52cce08f047.png">

(but HTML reference is correct):
<img width="844" alt="Screen Shot 2020-02-11 at 5 13 53 PM" src="https://user-images.githubusercontent.com/11865/74223535-e28de200-4cf1-11ea-9ae9-fd7803d399c1.png">

Word is correct:
<img width="645" alt="Screen Shot 2020-02-11 at 5 14 09 PM" src="https://user-images.githubusercontent.com/11865/74223554-ed487700-4cf1-11ea-8585-6eab6d3c8e52.png">

**Comment by opoudjis** [comment]
You can see from https://stackoverflow.com/questions/1632005/ordered-list-html-lower-alpha-with-right-parentheses how difficult this is to in HTML.
