### ISSUE TITLE
Wrong sorting order of bibliography (minor)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#320]
Notice that "ISO 8000-100" is sorted before "ISO/TS 8000-1". This was discovered at an ISO meeting today.

<img width="729" alt="Screen Shot 2020-02-11 at 5 15 20 PM" src="https://user-images.githubusercontent.com/11865/74223662-2b459b00-4cf2-11ea-8e54-e6501edd7ea7.png">

**Comment by opoudjis** [comment]
Adding part number as separate sort key.
