### ISSUE TITLE
Broken part title in bibliography with "ISO/IEC 8824-1"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#321]
The part title is missing in the bibliography. This was discovered at an ISO meeting today.

<img width="627" alt="Screen Shot 2020-02-11 at 4 52 55 PM" src="https://user-images.githubusercontent.com/11865/74223758-5a5c0c80-4cf2-11ea-929e-53cadaa99d28.png">

@andrew2net could you help check if this is a Relaton problem? Thanks.

**Comment by ronaldtse** [comment]
My question to ISO:
> The PDF version (screenshot attached) gives "Information technology -- Abstract Syntax Notation One (ASN.1): Specification of basic notation”, but is a part 1… What is the correct title?

![image002](https://user-images.githubusercontent.com/11865/74288493-7a79e300-4d67-11ea-82af-2c92370b02d3.png)

From ISO: 
>  It seems that the title entered in Projects (the application we use to enter standards metadata) is not the same as the one printed on the standard itself and this is replicated to the site.

ISO is checking and will get back to us.

**Comment by ronaldtse** [comment]
(i.e. it's not our bug!)

**Comment by opoudjis** [comment]
Is there something for me to do here?

**Comment by ronaldtse** [comment]
No, pending ISO Web Team investigation to fix this.

**Comment by ronaldtse** [comment]
Looks like the ISO Web team fixed this one:
<img width="765" alt="Screenshot 2022-06-14 at 1 21 02 AM" src="https://user-images.githubusercontent.com/11865/173399427-35b88d5a-dd9f-4a2d-96d1-9b98bdb672b2.png">

@andrew2net can you help verify that this works properly now? Thanks.

**Comment by ronaldtse** [comment]
Verified working now in https://github.com/metanorma/iso-8000-118:

<img width="565" alt="Screenshot 2022-06-14 at 1 24 03 AM" src="https://user-images.githubusercontent.com/11865/173400009-ca9528af-5435-418b-9dda-438e544f1629.png">
