### ISSUE TITLE
Consolidated "Terms, definitions, ..." location of T&D boilerplate should be in 3.1

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#325]
A document may not have specifically defined terms but can import terms from another document. In this case, the boilerplate still needs to exist inside a consolidated "Terms, definitions, ..." clause under 3.1.

> We’ve been recently working on the ISO 8000-100 Ed 2 draft, and came into an issue on "Terms and definitions”.

> The document contains “Terms and definitions”, “Symbols” and “Abbreviated terms”.

> According to ISO DP 2, we can combine them into "Terms, definitions, symbols and abbreviated terms”.

> But since the document inherits the terms from ISO 8000-2, and does not contain any actual terms, which of the following rendering is correct?

ISO/CS has confirmed that the solution is the latter rendering. We should fix this.

Right now it does this (boilerplate under 3, empty 3.1):
```
3 Terms, definitions, symbols and abbreviated terms
For the purposes of this document, the terms and definitions given in ISO 8000-2 apply.
ISO and IEC maintain terminological databases for use in standardization at the following addresses:
•   ISO Online browsing platform: available at https://www.iso.org/obp
•   IEC Electropedia: available at http://www.electropedia.org/

3.1 Terms and definitions
3.2 Symbols
…
3.3 Abbreviated terms
…
```

Correct rendering (boilerplate under 3.1):

```
3 Terms, definitions, symbols and abbreviated terms

3.1 Terms and definitions
For the purposes of this document, the terms and definitions given in ISO 8000-2 apply.
ISO and IEC maintain terminological databases for use in standardization at the following addresses:
•   ISO Online browsing platform: available at https://www.iso.org/obp
•   IEC Electropedia: available at http://www.electropedia.org/

3.2 Symbols
…
3.3 Abbreviated terms
…
```

**Comment by opoudjis** [comment]
The rule I'm deriving here is that the term boilerplate goes to the deepest `<terms>` element, not the topmost.

**Comment by opoudjis** [comment]
And allow multiple instances thereof
