### ISSUE TITLE
Questions on values in ISO when document header is parsed as Hash

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#327]
In https://github.com/metanorma/metanorma.com/pull/219 we can see some values need work.

```ruby
{
  :agency => "ISO",
  :authors => [],
  :authors_affiliations => {},
  :docnumber => "ISO/NWIP 33032",
  :docnumeric => "33032",
  :docsubtitle => "",
  :docsubtitlemain => "",
  :docsubtitlepartlabel => "Partie&nbsp;",
  :doctitle => "Cybernetics&#x2009;&#x2014;&#x2009;Neuro-information interchange interface",
  :doctitlemain => "Neuro-information interchange interface",
  :doctitlepartlabel => "Part&nbsp;",
  :doctype => "Article",
  :docyear => "2020",
  :draft => nil,
  :draftinfo => "",
  :edition => "2",
  :editorialgroup => ["TC 399"],
  :ics => "XXX",
  :obsoletes => nil,
  :obsoletes_part => nil,
  :revdate => nil,
  :sc => "XXXX",
  :secretariat => "XXXX",
  :stage => "10",
  :stage_int => 10,
  :statusabbr => "NWIP",
  :tc => "TC 399",
  :tc_docnumber => [],
  :unpublished => true,
  :wg => "XXXX"
}
```

These values not set should be `nil` to indicate it is not supplied:
* `docsubtitle` is `""` => change to `nil`
* `docsubtitlemain` is `""` => change to `nil`
* `draftinfo` is `""` => change to `nil`
* `ics` is `XXX` => change to `nil`
* `sc` is `XXXX` => change to `nil`
* `secretariat` is `XXXX` => change to `nil`
* `wg` is `XXXX` => change to `nil`

This is strange:
* `unpublished` is `true` => change to `published` = `false`

These default values are wrong:
* `doctype` is `Article` => change to the default of the flavor, i.e. `standard` for ISO
* `docsubtitlepartlabel` is `"Partie&nbsp;"`, but this is French?

These values should be fixed?
* `:doctitle => "Cybernetics&#x2009;&#x2014;&#x2009;Neuro-information interchange interface",` Why isn't `&#x2009;` just space, and `&#x2014;` just the long dash?
* `:doctitlepartlabel => "Part&nbsp;",` This is a bit strange with a trailing whitespace?

What does this mean? `  :tc_docnumber => [],` The `tc_docnumber` can have multiple values?

**Comment by opoudjis** [comment]
This is a request for massive refactoring of things that are not truly broken, and will accordingly be aggressively demoted in priority.

`&#x2009;&#x2014;&#x2009;` is built in Asciidoctor behaviour as an expansion of " -- ", putting thin spaces around em-dash. It is a legitimate way of dealing with em-dahes: I see no reason to overrrule it, and Asciidoctor would not make it easy.

Subtitle is the "other" language to the Title in ISO; if the document were in French, the subtitle would be in English.

The XXX were there to signal to the user that a mandatory value has not been supplied.

You explicitly requested multiple TC numbers in https://github.com/metanorma/metanorma-iso/issues/230: you had a document with two of them.

**Comment by opoudjis** [comment]
Empty strings have already been replaced with nils.

Not strongly motivated to flip unpublished to published; unpublished is just a more generic word for draft, and draft is the exceptional state in formatting.

Setting default doctype to be "standard" in standoc.

`:doctitlepartlabel=>"Part&#xa0;1",` properly; the number was absent because of missing data in the sample.
