### ISSUE TITLE
Word: Possibility to support table width specification, or make all table 100% by default

### ISSUE THREAD

**Issue by ribose-jeffreylau** [metanorma/metanorma-iso#330]
It has been requested to make table width consistent in the generated Word documents.

While the table widths are all set to 100% in the HTML output, it is not so in the Word version -- the width expands to the content's width.

I'm wondering if it is a good idea to add `width: 100%;` to the css class `table.MsoISOTable`, if we have no particular need to specify tables of other widths.

Related issue in GitLab: https://gitlab.com/calconnect/tc-localization/csd-transcription-systems/issues/61

**Comment by opoudjis** [comment]
Can do it, although if the aim is to look as close as possible to existing standards documents, this is a bad idea, since of course few people do set tables to 100% in Word to begin with. @ronaldtse ?

**Comment by ronaldtse** [comment]
@opoudjis I don't think we want to apply this to all tables. Just to allow this option.

The request was to set every data table in https://gitlab.com/calconnect/tc-localization/csd-transcription-systems/ to be of the same width. 

If we can set "some" table width or allow specifying 100%, it would be good.

**Comment by opoudjis** [comment]
Added attribute width, which corresponds to the HTML attribute on tables; so

````
[width=100%]
|===
|A |B

|C |D
|===
````
