### ISSUE TITLE
Issue with sorting and missing characters inside Symbols list

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#338]
```adoc
=== Symbols and abbreviated terms

[ stem:[x] ]:: Square brackets are used to enclose IPA phonetic symbols.

{ stem:[x] }:: Curved brackets are used to enclose phoneme symbols and tones of the Jyutping system.

< stem:[x] >:: Angle brackets are used to enclose graphemes as the orthography writes them.

IPA:: International Phonetic Alphabet

LSHK:: The Linguistic Society of Hong Kong

CTL:: Chao Tone Letter
```

Output (HTML + Word):
<img width="695" alt="Screen Shot 2020-04-04 at 3 15 45 AM" src="https://user-images.githubusercontent.com/11865/78396819-96d92400-7622-11ea-8414-71e9b762ec19.png">

There are 2 bugs here:
* The `stem:[x]` has disappeared from 2 of the 3 bracket types.
* The symbol list becomes randomly sorted

If I do:
```
<stem:[x]>:: Angle brackets are used to enclose graphemes as the orthography writes them.
```

The first `<` will not be rendered.

**Comment by opoudjis** [comment]
Replaced xpath with traverse for generating sortable snippets of symbols, the xpath was clearly generating strange side-effects.

Sortable key needs to exclude brackets.

**Comment by opoudjis** [comment]
Greek letters also need to appear in correct sort order: they are not being converted correctly.
