### ISSUE TITLE
Non-English characters rendered using multiple fonts

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#339]
In this markup:

```adoc
\{ping3jam1} (<拼音> "`phonetic transcription`").
```

* The first character "拼" is assigned the "PingFang TC" font.
* The second character "音" is assigned the "Batang" font.

The usage of different fonts cause characters to not align.

I have no idea why it consistently acts this way.

The following photos illustrate the problem:

<img width="420" alt="Screen Shot 2020-04-04 at 3 47 57 AM" src="https://user-images.githubusercontent.com/11865/78399353-5203bc00-7627-11ea-9b87-ff40e52e22bd.png">

<img width="416" alt="Screen Shot 2020-04-04 at 3 47 50 AM" src="https://user-images.githubusercontent.com/11865/78399366-562fd980-7627-11ea-8ee4-0c26ab454319.png">

Notice that the term "粵拼" are both using "PingFang TC".

Perhaps there's a Word CSS thing to set non-`Latn` fonts?

**Comment by opoudjis** [comment]
Word has no idea that these are Chinese characters and is attempting to render them in Cambria, or whatever the default Latin font is. That fails, and random fonts get applied instead to Chinese, varying by character. The fact that these are Cantonese and not Mandarin probably doesn't help.

Even if CSS could work out allocating different fonts to different character ranges, there is of course no way on earth Microsoft Word would know how to do it.

Now, there is something in the CSS which *might* patch this temporarily. Word styles have a mso-fareast-font-family which can be set; and if that property is set to a CJK compatible font, Chinese in a Roman context will render in that font.

Except that is a very narrow fix: it imposes the one CJK font for all of Traditional Chinese, Simplified Chinese, Korean, and Japanese. That is not the real solution.

The real solution is to allow users to specify fonts for each script, automatically detect runs of characters in those scripts outside of the default script, and automatically mark them up with that font. Failing that, allow manual markup of such runs.

To be blunt, for standards documents that do not routinely deal with multilingual texts, this is drastic overkill. I'm going to plunk SimSun in the Word stylesheets as a short term solution.

**Comment by opoudjis** [comment]
I am not implementing this any further than ISO btw. This really is an edge case.
