### ISSUE TITLE
Addressing post-processing steps for Word document submission to ISO

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#340]
From @rggibb

> Also just for the record, the other post compile processing that I did was:
>  1) renaming the file and the usual conversion to .docx in word, by a series of save as. And then, after I'd finished all other edits, updating the ToC field after I'd finished all other edits

This is unavoidable under our current system, but we should improve documentation on how to deal with this. Let's do a blog post.

>  2) increasing the size of the images in figures to a greater proportion of the width of the page,

I think we should allow specifying width and height of images using `%`?

>  3) removing single spaces after forward slashes in URIs that the compiler had inserted. They weren’t random, neither were they after every '/' it was as if after a certain length of URI string a space was inserted. For instance '/spec/ DGGS/' was a common example. While removing these extra instances of a space, I also changed the paragraph alignment to justified left for the 'Requirement' row in the Conformance test tables, and inserted a new-line before 'http' to avoid wraps in the middle of URIs.

This was implemented as a feature in response to https://github.com/metanorma/metanorma-standoc/issues/219 , but perhaps this needs a re-think. We need to allow long URLs without them breaking (since people who print out ISO documents do not see that the hyperlink is "correct").

**Comment by opoudjis** [comment]
3. Feature not bug. But we can make the behaviour optional by setting a document attribute.

2. That option is already in place:

````
image::spec/examples/rice_img/rice_image1.png[Sunset,200%,200%]
image::spec/examples/rice_img/rice_image1.png[Sunset,100%,100%]
````

1. I do not know what this needs to be, and would encourage someone else to write any blog posts.

**Comment by opoudjis** [comment]
It's a oneliner, I'll do it before IHO.
