### ISSUE TITLE
How to determine document stage (CD, WD, AWI, DIS, FDIS,...)

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#342]
What is a best way to determine a document stage (CD, WD, AWI, DIS, FDIS,...) ?
In xml I see two places to store stages:
1. `<docidentifier type="iso">ISO/CD 17301-1</docidentifier>`
2. 
```
<status>
<stage>30</stage>
<substage>00</substage>
</status>
```

In PDF I need to put a full name of stage, for example 'COMMITTEE DRAFT' for CD. Can I cut substring after 'ISO/' or would be better to use 'status' and 'substage' elements? Then, where can I find a mapping table between 'stage' / 'substage' values and document's name stage?
Thanks.

**Comment by opoudjis** [comment]
The mapping code, like so much else that you seem to need, is in the isodoc/*/metadata.rb file of the flavour. In particular for ISO:

https://github.com/metanorma/metanorma-iso/blob/master/lib/isodoc/iso/metadata.rb

````
 STAGE_ABBRS = {
        "00": "PWI",
        "10": "NWIP",
        "20": "WD",
        "30": "CD",
        "40": "DIS",
        "50": "FDIS",
        "60": "IS",
        "90": "(Review)",
        "95": "(Withdrawal)",
      }.freeze

def status_abbrev(stage, substage, iter, draft)
        return "" unless stage
        stage = self.class::STAGE_ABBRS[stage.to_sym] || "??"
        stage = "PRF" if stage == "IS" && substage == "00"
        stage += iter if iter
        stage = "Pre" + stage if draft =~ /^0\./
        stage
      end

def docstatus(isoxml, _out)
        docstatus = isoxml.at(ns("//bibdata/status/stage"))
        set(:unpublished, false)
        if docstatus
          set(:stage, docstatus.text)
          set(:stage_int, docstatus.text.to_i)
          set(:unpublished, unpublished(docstatus.text))
          set(:statusabbr, status_abbrev(docstatus.text,
                                         isoxml&.at(ns("//bibdata/status/substage"))&.text,
                                         isoxml&.at(ns("//bibdata/status/iteration"))&.text,
                                         isoxml&.at(ns("//version/draft"))&.text))
          unpublished(docstatus.text) and
            set(:stageabbr, stage_abbr(docstatus.text))
        end
        revdate = isoxml.at(ns("//version/revision-date"))
        set(:revdate, revdate&.text)
      end

 def unpublished(status)
        status.to_i > 0 && status.to_i < 60
      end
````

All those `set` variables are the metadata variables that I use to populate the title pages from via Liquid (e.g. stage, stageabbr). Either you replicate what those commands are doing, or I pass them as variables into the XSLT.

**Comment by opoudjis** [comment]
> In PDF I need to put a full name of stage, for example 'COMMITTEE DRAFT' for CD.

... Huh. That's a new requirement to me. But yes, you must read it from the stage, and map 30 to CD to Committee Draft. As you can see, the stage is only reflected in the identifier for pre-publication stages. (And if https://github.com/metanorma/metanorma-iso/issues/343 is correct, that excludes PRF.)

**Comment by ronaldtse** [comment]
@opoudjis do you think it's fair to put the "Committee Draft" part inside the XML?

**Comment by opoudjis** [comment]
Clearly I'm going to have to anyway.

**Comment by opoudjis** [comment]
Ideally the markup would be:

`<stage number="30" abbreviation="CD">Committee Draft</stage>`

But we cannot do that: we have too much legacy XML of `<stage>30</stage>`.

So I will globally add an optional abbreviation attribute to `stage`. I will *not* proactively populate it, because I have far better things to do with my life; but the mechanism is available.

I will give the full name of the stage in ISO as `//bibdata/ext/stagename`. So:

````
<bibdata>
<status>
<stage abbreviation="CD">30</stage>
...
</status>
....
<ext>
...
<stagename>Committee Draft</stagename>
</ext>
</bibdata>
````

**Comment by opoudjis** [comment]
@andrew2net FYI: stage and substage can now have an optional "abbreviation" attribute, containing the abbreviation (e.g. "CD" for a stage of 30 in ISO); you are not currently expected to populate it.

I am also adding  //bibdata/ext/stagename as an optional element in ISO, for the full name of the stage.

**Comment by opoudjis** [comment]
This of course also applies to GB and IEC, which inherit from ISO
