### ISSUE TITLE
XML: docidentifier contains /PRF for PROOF document

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#343]
The xml source for PROOF document (https://github.com/metanorma/mn-samples-iso/blob/gh-pages/documents/iso-rice-en.covers.prf.xml) shouldn't contain '/PRF' suffix:

```
<docidentifier type="iso">ISO/PRF 17301-1</docidentifier>
<docidentifier type="iso-with-lang">ISO/PRF 17301-1 (E)</docidentifier>

```
 (see https://github.com/metanorma/mn-native-pdf/issues/98#issuecomment-611844712)

**Comment by opoudjis** [comment]
In https://github.com/metanorma/metanorma-iso/issues/254, @ronaldtse, you expressly requested a PRF stage to be implemented, and you haven't said anything in the intervening year. Have you confirmed this with ISO?

**Comment by ronaldtse** [comment]
The ISO/PRF stage exists, but the doc identifier there is "ISO XXXX" since it is "proof of final". I only received confirmation recently on this. This raises another question -- how can we differentiate a PRF document from real one in document identifier.

**Comment by ronaldtse** [comment]
I wonder if the best solution is to keep the docidentifier with ISO/PRF, then strip it from the PDF.

**Comment by opoudjis** [comment]
No it is not. Clearly there is no such thing as an ISO/PRF document identifier; we shouldn't be artificially creating one; and we are record PRF in the stage abbreviation.
