### ISSUE TITLE
Support ISO doctypes: `technical-corrigendum` and `amendment`

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#345]
Currently, ISO doctype technical corrigendum is not available for ISO documents. This doctype was needed for ISO 10303-50, for which we had 2 TCs. 

What was noticed while converting these TCs to .adoc format was that by default, text of TC is in italic. Normal text is used for changes which should be implemented.

**Comment by ronaldtse** [comment]
The sample ISO Amendment has been uploaded here:
https://github.com/metanorma/mn-samples-iso/issues/25

Screenshots:

<img width="611" alt="Screen Shot 2020-04-13 at 12 44 50 AM" src="https://user-images.githubusercontent.com/11865/79074612-fc629a00-7d1f-11ea-9260-5f8fbab04b8c.png">
<img width="610" alt="Screen Shot 2020-04-13 at 12 44 58 AM" src="https://user-images.githubusercontent.com/11865/79074614-01274e00-7d20-11ea-97d8-3ce2dc6b1f22.png">
<img width="612" alt="Screen Shot 2020-04-13 at 12 45 09 AM" src="https://user-images.githubusercontent.com/11865/79074620-084e5c00-7d20-11ea-8d0f-1f042efb42e7.png">
<img width="610" alt="Screen Shot 2020-04-13 at 12 45 19 AM" src="https://user-images.githubusercontent.com/11865/79074624-0daba680-7d20-11ea-92e7-1386811679f9.png">
<img width="613" alt="Screen Shot 2020-04-13 at 12 45 28 AM" src="https://user-images.githubusercontent.com/11865/79074629-1308f100-7d20-11ea-9cb2-5a38f6496ce0.png">
<img width="612" alt="Screen Shot 2020-04-13 at 12 45 37 AM" src="https://user-images.githubusercontent.com/11865/79074635-18663b80-7d20-11ea-986f-664bf4faeb29.png">
<img width="614" alt="Screen Shot 2020-04-13 at 12 45 47 AM" src="https://user-images.githubusercontent.com/11865/79074637-1e5c1c80-7d20-11ea-90fd-1e57c6e33383.png">
<img width="612" alt="Screen Shot 2020-04-13 at 12 45 56 AM" src="https://user-images.githubusercontent.com/11865/79074642-2320d080-7d20-11ea-87f7-dc021bb260c1.png">

**Comment by ronaldtse** [comment]
ISO Technical corrigendum:
http://www.mszt.hu/documents/10157/bb117640-ccf8-4d32-885d-b2006954fe22

<img width="641" alt="Screen Shot 2020-04-13 at 8 39 40 PM" src="https://user-images.githubusercontent.com/11865/79121026-e6f47b00-7dc6-11ea-808a-e04ae27828ec.png">
<img width="643" alt="Screen Shot 2020-04-13 at 8 39 51 PM" src="https://user-images.githubusercontent.com/11865/79121039-ed82f280-7dc6-11ea-83d5-32a12d9efbe2.png">
<img width="641" alt="Screen Shot 2020-04-13 at 8 40 01 PM" src="https://user-images.githubusercontent.com/11865/79121048-f378d380-7dc6-11ea-9d7e-d32153dfd7f0.png">
<img width="643" alt="Screen Shot 2020-04-13 at 8 40 11 PM" src="https://user-images.githubusercontent.com/11865/79121067-0390b300-7dc7-11ea-91e2-b35add99906c.png">

**Comment by ronaldtse** [comment]
https://infostore.saiglobal.com/preview/258645433280.pdf?sku=880419_SAIG_NSAI_NSAI_2091657

An older Technical Corrigendum document but demonstrates the textual requirements (we will not adopt the styling but only text requirements).

Technical Corrigendum 2:

<img width="624" alt="Screen Shot 2020-04-14 at 8 36 28 PM" src="https://user-images.githubusercontent.com/11865/79225637-9f85f180-7e8f-11ea-8467-7ae38db5ca66.png">

<img width="621" alt="Screen Shot 2020-04-14 at 8 36 44 PM" src="https://user-images.githubusercontent.com/11865/79225665-a876c300-7e8f-11ea-899e-82a86da33fd8.png">

Technical Corrigendum 1:

<img width="624" alt="Screen Shot 2020-04-14 at 8 36 54 PM" src="https://user-images.githubusercontent.com/11865/79225682-add40d80-7e8f-11ea-9399-665cf94e7bac.png">

<img width="620" alt="Screen Shot 2020-04-14 at 8 37 03 PM" src="https://user-images.githubusercontent.com/11865/79225699-b3315800-7e8f-11ea-86f9-85ec0fbd1b15.png">

DCOR (Draft Technical Corrigendum)
<img width="621" alt="Screen Shot 2020-04-14 at 8 37 26 PM" src="https://user-images.githubusercontent.com/11865/79225739-c2b0a100-7e8f-11ea-9c43-249cf0e6d576.png">
<img width="622" alt="Screen Shot 2020-04-14 at 8 37 40 PM" src="https://user-images.githubusercontent.com/11865/79225761-ca704580-7e8f-11ea-9ba8-2fdc33da6ef7.png">

**Comment by ronaldtse** [comment]
Another older (2012) COR: https://www.ift-rosenheim.de/documents/10180/114265/DIN_EN_ISO_10077-2_2012_Technical_Corrigendum_1.pdf/f8601abd-e983-4e39-9bc5-20b67d350d24

**Comment by ronaldtse** [comment]
ISO Model Draft Amendment (DAM): https://www.iso.org/files/live/sites/isoorg/files/archive/pdf/en/moddam.pdf

**Comment by ronaldtse** [comment]
Latest official ISO Technical Corrigendum style:
https://www.iec.ch/dyn/www/f?p=103:391:0::::P391_PUB_ID%2CP391_LANG:63838

Front page:
<img width="543" alt="Screen Shot 2020-04-15 at 1 28 34 PM" src="https://user-images.githubusercontent.com/11865/79301777-02719a00-7f1d-11ea-8600-7389d81d7e7c.png">

As for content, this screenshot reflects the proper document identifier on the top right corner. The content itself is from ITU.
<img width="539" alt="Screen Shot 2020-04-15 at 1 29 11 PM" src="https://user-images.githubusercontent.com/11865/79301806-1917f100-7f1d-11ea-92e3-9bc5e24d4957.png">

**Comment by opoudjis** [comment]
Each clause is a locality. Grammars restricted to only clauses (not forbidding subclauses at the moment, but it will come).

* Identifier and Amendment-specific metadata will need to be handled
* Heading 1 must be in italics
* No special recognition of clause heading types
* NO assets are numbered, and neither are headings
* Material to be changed, added, deleted is quoted
* Heading numbers will need to be faked in quoted material
* requested patch hints, for now as "change" and "locality" attributes on the clause; change limited to delete, add, modify; locality follows locality input syntax (e.g. `clause=introduction,paragraph=4-7`), and may eventually encoded like it

**Comment by opoudjis** [comment]
Remaining:

* Amendment-specific metadata will need to be handled in rendering (title pages)
* Heading 1 must be in italics
* NO assets are numbered, and neither are headings
* Heading numbers will need to be faked in quoted material

**Comment by opoudjis** [comment]
Done as much as I care to. @ronaldtse Please test with editors.
