### ISSUE TITLE
Missing equations and list dashes (with example doc)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#350]
From @anermina 

Stem expressions are not generated in the attached document, although the same expressions render properly in other documents using ISO flavor.

Example (ISO 10303-52):
![image](https://user-images.githubusercontent.com/55683568/80151103-c93ec700-85b9-11ea-8e99-42c6956dea2e.png)

Example (attached document):
![image](https://user-images.githubusercontent.com/55683568/80151176-e70c2c00-85b9-11ea-9af3-df4e4210d511.png)

Moreover, note block which contains a list of items is not rendered properly in this document (dashes are missing). The same AsciiDoc expression renders properly in other documents using ISO flavor.

Example (ISO 10303-52):
![image](https://user-images.githubusercontent.com/55683568/80151245-02773700-85ba-11ea-9876-9af9aef68bf4.png)

Example (attached document):
![image](https://user-images.githubusercontent.com/55683568/80151332-25095000-85ba-11ea-86ad-57609c8d3835.png)

Example document which shows some AsciiDoc expressions for which the aforementioned issues appear is attached.

[test.zip](https://github.com/metanorma/iso-10303/files/4525378/test.zip)

**Comment by opoudjis** [comment]
Cannot replicate. In both places, I'm getting the expected behaviour when I generate the documents; see attached.

[document.doc.zip](https://github.com/metanorma/metanorma-iso/files/4552035/document.doc.zip)

At this stage, can only ask again that you and @manuel489 generate again and check.

**Comment by anermina** [comment]
I can confirm I don't have issues with the example document anymore. However, these differences are still present in ISO 10303-52. @manuel489 , please try generating this document as well.

Attached are the outputs I get for ISO 10303-52.
[iso-10303-52.zip](https://github.com/metanorma/metanorma-iso/files/4552229/iso-10303-52.zip)

**Comment by opoudjis** [comment]
Ok, on the one hand the missing list bullets are also missing my side.

The maths expressions your side are systematically missing the `<math>` wrappers already in the XML, so they are untranslated AsciiMath.

Just in case this is related to https://github.com/metanorma/metanorma-standoc/issues/265 yesterday: could you please include `gem "isodoc", git: "https://github.com/metanorma/isodoc"` in your Gemfile.

**Comment by manuel489** [comment]
@opoudjis , apparently this issue seems to related with this https://github.com/metanorma/metanorma-standoc/issues/243

When I change the sub-clause title `Abbreviated terms` to another text. The problem of the missing equations gets solved. @anermina , could you confirm this please?

**Comment by manuel489** [comment]
In these outputs, I put `Abbreviated termss` instead `Abbreviated terms`

[iso-10303-52.zip](https://github.com/metanorma/metanorma-iso/files/4552492/iso-10303-52.zip)

**Comment by anermina** [comment]
> When I change the sub-clause title `Abbreviated terms` to another text, the problem of missing equations gets solved. @anermina , could you confirm this please?

Yes, you're right. Thank you @manuel489 .

**Comment by opoudjis** [comment]
And Nermina's document suffers from a similar issue: "The presence of Abbreviations is resulting in the MathML markup being stripped..."

So this indicates that the fix from standoc (which is not yet released) needs to be applied here too.

The notes are a different issue: the Html2Doc  code, which is processing rendering of lists, is assuming that all nested lists are ul/li/ul/li... In fact, Metanorma allows Notes to be inserted inside of lists; and those notes can contain lists; so those note lists are not being navigated to, to insert the styling needed for bullets.

Metanorma has its own reasons to want to inject non-list material inside of lists.

**Comment by opoudjis** [comment]
The notes fix requires an html2doc update.
