### ISSUE TITLE
Reference footnotes wrongly repeating, wrong order

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#352]
1. There are two separate references with different footnotes. However the rendered version only referred to the first one.

2. The order of references is wrong. (ISO 646 < 8601 < 80000-1 < 80000-3)

Original:
<img width="553" alt="Screen Shot 2020-04-25 at 9 29 26 PM" src="https://user-images.githubusercontent.com/11865/80281165-d84d8280-873b-11ea-999a-12af06d2db29.png">

Footnotes:
```
1) Under preparation. Stage at the time of publication: ISO/DIS 80000-1:2019.
2) Under preparation. Stage at the time of publication: ISO/FDIS 80000-3:2019.
```

Encoding:
```adoc

[bibliography]
== Bibliography

* [[[ISOIEC646,ISO/IEC 646]]], _Information technology -- ISO 7-bit coded character set for information interchange_

* [[[ISO8601-2,ISO 8601-2:2019]]], _Date and time -- Representations for information interchange -- Part 2:
Extensions_

* [[[ISO80000-1,ISO 80000-1:--]]] footnote:[Under preparation. Stage at the time of publication: ISO/DIS 80000-1:2019.], _Quantities and units -- Part 1: General_

* [[[ISO80000-3,ISO 80000-3:--]]] footnote:[Under preparation. Stage at the time of publication: ISO/FDIS 80000-3:2019.], _Quantities and units -- Part 3: Space and time_

* [[[ITURTF460-6,ITU-R TF.460-6]]], _Standard-frequency and time-signal emissions_

* [[[BIPMRCCTF3,BIPM Recommendation CCTF 3 (2017)]]], Bureau International des Poids et Mesures / The International Bureau of Weights and Measures: Consultative Committee for Time and Frequency (CCTF),
_Report of the 21st meeting to the International Committee for Weights and Measures_, 2017

* [[[IAUR24,International Astronomical Union Resolution B1.9 (2000)]]], International Astronomical Union, _IAU Resolutions adopted at the 24th General Assembly_, 2000

* [[[IEV,IEV]]], _IEV: Electropedia_
// This line is automatically removed by Metanorma
```

Result:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/11865/80281156-ca97fd00-873b-11ea-8172-f56ca4afe279.png">

This comes from https://github.com/metanorma/iso-8601-1

**Comment by opoudjis** [comment]
Footnotes are registered against the `fn/@ref` attribute. But the bibliographic date not is not tagged as a footnote, though it is rendered as one. So because it does not have a `fn/@ref` attribute, both instances are indexed against the value nil, which means they end up conflated. Will assign against GUID if `fn/@ref` is missing.

**Comment by opoudjis** [comment]
Sorting of ISO references is done by docnumber, the numeric portion of the identifier. For ISO 80000-1, that numeric portion is not extracted in relaton-iso; hence incorrect sorting. Will request this be fixed.

**Comment by opoudjis** [comment]
Pending https://github.com/relaton/relaton-iso/issues/87

**Comment by opoudjis** [comment]
No, issue is my side.

**Comment by opoudjis** [comment]
Adding docnumber to all instances where I generate the reference instead of looking it up.
