### ISSUE TITLE
Hyperlink behavior in cross-references isn't working

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iso#354]
In the sample below, notice that there is no hyperlink indicator.

*Code sample:*
````
== Section title

Cross-reference: <<table-3>>

[[table-3]]
.External namespace URIs and namespace abbreviation conventions used in this document
[cols="a,a,a",options="header"]
|===
| Namespace abbreviation convention
| Name
| Namespace URI

| dqc
| Data quality common
| http://standards.iso.org/iso/19157/-2/dqc/1.0

|===
````

*Output:*
![capture](https://user-images.githubusercontent.com/33627611/80315829-1b553780-87c8-11ea-98dd-5ffaf00cd274.PNG)

**Comment by opoudjis** [comment]
I was explicitly asked to disable crossreference hyperlinks for tables in https://github.com/metanorma/metanorma-iso/issues/301:

> All links to clauses (not figures or tables) should be hyperlinked in BLUE.

I see that there is contradictory advice in https://github.com/metanorma/metanorma-iso/issues/305, which @ronaldtse issued on the same day. 

As you can see from their model PDF, https://www.iso.org/files/live/sites/isoorg/files/developing_standards/docs/en/model_document-rice_model.pdf, ISO hyperlink clauses and not figures or tables.

This ticket is therefore invalid.

**Comment by ronaldtse** [comment]
@opoudjis I'm going to revisit this again:

<img width="611" alt="Screen Shot 2020-05-02 at 3 17 54 AM" src="https://user-images.githubusercontent.com/11865/80834549-85843700-8c23-11ea-85d7-faa7255286dd.png">

This is the actual published document. So ISO does do them.

The Rice document hasn't been updated in a while, so it's possible it is no longer following latest practice.

**Comment by opoudjis** [comment]
I am not actioning this until you get explicit confirmation from ISO. I have been burned too many times by guessing editorial policy.

**Comment by ronaldtse** [comment]
Question sent to ISO/CS, pending reply.

**Comment by opoudjis** [comment]
Confirmed

**Comment by ronaldtse** [comment]
From ISO/CS 
> All the cross-references within the document (including those to "Table X" and "Figure X”) should become hyperlinks in the PDF. So the style you see in ISO 8601-1/2 is correct.
