### ISSUE TITLE
Bug when filling in errata table

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#357]
Originally from https://github.com/metanorma/metanorma-iso/issues/296 @rggibb

> Also the Revision history table was problematic, I removed the Table D.1 header, and made the header row repeat at the top of each page .. I think that was only possible once it was reformatted as .docx, and I recall there was a deeper problem that required me to start the table again as a empty table and progressively copy the rows across, but I’m afraid I’ve forgotten the details. 
> If you don’t know exactly what that might have been, I’ll recreate it and find out. I seem to recall all the tables that may have had double cell boundaries or something that I couldn’t convert back to single cell boundaries ...

Right now we don't support "revision history" natively, maybe we can port something from NIST to OGC?

<img width="570" alt="Screen Shot 2019-11-26 at 12 44 24 PM" src="https://user-images.githubusercontent.com/11865/69600201-c069b980-104a-11ea-8859-1b2b58daccd4.png">

**Comment by ronaldtse** [comment]
Originally from: https://github.com/metanorma/metanorma-iso/issues/296

We can probably generalize the Errata model we have for the other flavor.

We can inherit from the BasicDoc "ChangeSet" and "Change" models and make the "Modified node" to support a link and plain text.

![image](https://user-images.githubusercontent.com/11865/69638436-a903ee00-1095-11ea-9826-59a501f6cdf6.png)

(from: https://github.com/metanorma/basicdoc-models)

**Comment by opoudjis** [comment]
Am reluctant to implement without evidence of a fixed structure for errata from OGC; and since this seems to have been a joint ISO structure originally, the warrant for this cannot extend to ISO anyway. @ronaldtse?

**Comment by opoudjis** [comment]
This presupposes serious engagement with SDOs, to establish their requirements for errata.

**Comment by ronaldtse** [comment]
@opoudjis pending feedback from OGC now.

**Comment by opoudjis** [comment]
Ticker superseded by https://github.com/metanorma/metanorma-ogc/issues/152

**Comment by ronaldtse** [comment]
> Am reluctant to implement without evidence of a fixed structure for errata from OGC; and since this seems to have been a joint ISO structure originally, the warrant for this cannot extend to ISO anyway.

ISO doesn't have Errata, they issue Errata using a new TC or a new revision.
