### ISSUE TITLE
XSLT update for ISO flavors

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#361]
@opoudjis FYI, to import updated artefacts into metanorma:
- updated xslt for ISO flavors in mn-native-pdf repository.
- download path for updated mn2pdf.jar: https://github.com/metanorma/mn2pdf/releases/download/v1.10/mn2pdf-1.10.jar
- in command to run mn2pdf.jar add JVM options `-Xss5m -Xmx1024m` after `java`:
`java -Xss5m -Xmx1024m -jar mn2pdf.jar --xml-file ...`

I'll post here any further updates when xslt or mn2pdf will be changed.

**Comment by opoudjis** [comment]
With a backlog of 90 tickets, I really would rather you communicate with me about changes in invocation through new tickets. I am checking out new XSLTs before every release (fortnightly), and I will now remember to check for mn2pdf as well; so there is no need to inform me directly.
