### ISSUE TITLE
Duplicated year in page header document identifier

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#362]
https://github.com/metanorma/iso-10303/blob/master/sources/iso-10303-104/document.adoc

Using git gems:
```ruby
gem "metanorma-cli", git: "https://github.com/metanorma/metanorma-cli"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso"
gem "isodoc", git: "https://github.com/metanorma/isodoc"
gem "metanorma", git: "https://github.com/metanorma/metanorma"
```

Generates this erroneous document identifier in the page header (the cover is correct).

Source:
```adoc
= Product data representation and exchange: Integrated application resource: Finite element analysis
:docnumber: 10303
:partnumber: 104
:copyright-year: 2000
:language: en
:publish-date: 2000-12-15
:edition: 1
...
```

Page header:
<img width="725" alt="Screen Shot 2020-05-01 at 12 21 04 PM" src="https://user-images.githubusercontent.com/11865/80781774-3ba93b80-8ba6-11ea-98bb-cec3b00c04e8.png">

Page cover:
<img width="603" alt="Screen Shot 2020-05-01 at 12 21 10 PM" src="https://user-images.githubusercontent.com/11865/80781780-3fd55900-8ba6-11ea-9ac4-a016108d6a0c.png">

**Comment by opoudjis** [comment]
The docidentifier includes the year in ISO, so any specification of them as separate in the templates is incorrect.

**Comment by opoudjis** [comment]
Introduced docnumber_lang as the full "ISO number:year(X)" identifier in metadata.
