### ISSUE TITLE
Term referencing improvements (`term:[]`)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#368]
1. We should also have `term:[X]` as shorthand as `term:[X,X]` because often we don't need to change the term used (only need to change for plurals, etc).

2. Can we use the `term:[]` syntax inside the document (outside of the Terms and definitions section)?

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-iso/pull/366#issuecomment-624978759_

**Comment by ronaldtse** [comment]
Also need to ensure this works in IEC. Thanks.

**Comment by opoudjis** [comment]
> We should also have term:[X] as shorthand as term:[X,X] because often we don't need to change the term used (only need to change for plurals, etc).

Already done.

**Comment by opoudjis** [comment]
> Can we use the term:[] syntax inside the document (outside of the Terms and definitions section)?

Yes, it just gets globally replaces with `<em>X</em> (<xref>Y</xref>)` wherever in the document it is.
