### ISSUE TITLE
URGENT: term referencing showing `<termref>` tags in HTML and PDF when term not defined

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#370]
Most are fine, but:

HTML:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/11865/81364338-0063bb00-9118-11ea-89e1-48e82f5ad5ee.png">

PDF:
<img width="1069" alt="Screen Shot 2020-05-08 at 10 38 21 AM" src="https://user-images.githubusercontent.com/11865/81364364-0a85b980-9118-11ea-843b-fc8ebba2150f.png">

**Comment by ronaldtse** [comment]
I found out that these terms are the ones that have not been defined.

Clearly there needs to be a detection mechanism of warning the user just like how it is done with missing references.

**Comment by w00lf** [comment]
Fixed in #371
