### ISSUE TITLE
Word: missing table identifiers when table is located inside EXAMPLE

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#374]
The cross-references still work, but the table identifiers are missing.

```adoc
[[annexE]]
[appendix,obligation=informative]
== Examples

The following examples are provided to clarify concepts that are presented within this part of ISO 10303.

[EXAMPLE]
====
For a relationship with a parent to child *serial_action_method* within the context of the gear settings of an automobile automatic transmission, there are four possible gear settings that represent methods for the car to operate: drive, reverse, neutral, and park. Each gear setting is an *action_method* and is given in <<tableE1>>.

[[tableE1]]
.Automobile gear setting as an action_method
|===
^.^h| action_method
^.^| "park"
^.^| "reverse"
^.^| "neutral"
^.^| "drive"
|===

The context *action_method* would be the context of the capability of the automatic transmission: four possible methods for gear operation. The *serial_action_methods* are given in <<tableE2>>. The car is only in one of four gear operations at any point in time. The *action_method* of "gear operation" defines the context of the automatic transmission capabilities.

[[tableE2]]
.Automobile gear operation as a serial_action_method
|===
2+^.^h| serial_action_method
^.^h| relating_action_method ^.^h| related_action_method
^.^| "gear operation" ^.^| "drive"
^.^| "gear operation" ^.^| "reverse"
^.^| "gear operation" ^.^| "neutral"
^.^| "gear operation" ^.^| "park"
|===
====

```

<img width="628" alt="image" src="https://user-images.githubusercontent.com/11865/81759573-a7b96700-94f7-11ea-8752-d2fffe259f41.png">

**Comment by anermina** [comment]
This also applies to figures included in Example blocks.

**Comment by opoudjis** [comment]
That was deliberately done: `lbl = nil if labelled_ancestor(node)` is in the code of isodoc. 

That change was brought in in https://github.com/metanorma/isodoc/issues/165:

> Sourcecode and pseudocode within examples are not labelled. This should be extended to tables; and in general, any labelled asset should not include another labelled asset:

> * Requirements/Permissions/Recommendations
> * Tables
> * Figures
> * Sourcecode

> All these should be checked for ancestors that are likely already labelled.

I regard that decision as sensible: for a captioned example to contain a captioned table seems to me bizarre. Since you disagree, do you want me to relax all the other constraints? Do I at least retain the constraint of not labelling sourcecode and pseudocode within examples?

**Comment by ronaldtse** [comment]
From ISO/CS' Chief Editor: 

1. Tables and Figures are first-class document elements -- they belong to the main document and NOT inside EXAMPLEs or NOTEs. 

2. As @opoudjis mentioned, all Tables and Figures must have an independent numbering. 

3. ISO/CS says that EXAMPLEs and NOTEs should point to Tables and Figures in the document (i.e. outside of the EXAMPLEs and NOTEs).

**Comment by ronaldtse** [comment]
Technically, the encoding should be changed to separate the EXAMPLE and the Tables:

```adoc
[[annexE]]
[appendix,obligation=informative]
== Examples

The following examples are provided to clarify concepts that are presented within this part of ISO 10303.

[EXAMPLE]
====
For a relationship with a parent to child *serial_action_method* within the context of the gear settings of an automobile automatic transmission, there are four possible gear settings that represent methods for the car to operate: drive, reverse, neutral, and park. Each gear setting is an *action_method* and is given in <<tableE1>>.

The context *action_method* would be the context of the capability of the automatic transmission: four possible methods for gear operation. The *serial_action_methods* are given in <<tableE2>>. The car is only in one of four gear operations at any point in time. The *action_method* of "gear operation" defines the context of the automatic transmission capabilities.

====

[[tableE1]]
.Automobile gear setting as an action_method
|===
^.^h| action_method
^.^| "park"
^.^| "reverse"
^.^| "neutral"
^.^| "drive"
|===
[[tableE2]]
.Automobile gear operation as a serial_action_method
|===
2+^.^h| serial_action_method
^.^h| relating_action_method ^.^h| related_action_method
^.^| "gear operation" ^.^| "drive"
^.^| "gear operation" ^.^| "reverse"
^.^| "gear operation" ^.^| "neutral"
^.^| "gear operation" ^.^| "park"
|===
```

ISO/CS Chief Editor says the "informative/normative" of a Table or Figure purely depends on how it is referred, e.g:

1. A Table/Figure that is only referred by a NOTE or EXAMPLE is purely informative.
2. A Table/Figure that referred by main text as a requirement ("should") is normative.
3. A Table/Figure that referred by main text as informative example ("see Table/Figure X") is informative.
4. A Table/Figure that is referred by normative AND informative elements are both informative and normative depending where the question is asked from.

**Comment by anermina** [comment]
Change is applied in https://github.com/metanorma/iso-10303/pull/62.

**Comment by ronaldtse** [comment]
Thanks, closing.
