### ISSUE TITLE
Add Keywords/Descriptors to Metanorma-ISO

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#377]
ISO flavor doesn't include `:keywords:` as document attribute. However, ISO 10303-49 includes "Descriptors", which are listed at the end of the paper. This is a single case I encountered while converting ISO 10303 documents, so I was wondering whether keywords should be removed from the source .adoc in this case, or ISO documents can regularly include keywords, making them a needed document attribute.

![image](https://user-images.githubusercontent.com/55683568/82128944-75da2600-97bf-11ea-81d5-9fc75bc16a6b.png)

**Comment by ronaldtse** [comment]
A number of ISO 10303 documents include them, so we should enhance Metanorma-ISO to accept them.

**Comment by opoudjis** [comment]
In HTML, they should not placed in a final colophon, and ICS already isn't. These two are being put at the bottom of the title section instead.

**Comment by opoudjis** [comment]
Moving keywords to isodoc from individual flavours
