### ISSUE TITLE
Issues with pseudocode

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#378]
In pseudocode blocks, indentation is not preserved and line breaks are not added if source .adoc doesn't include `+` indicators.

This issue was noticed while converting ISO 10303-55 document, so it is opened here. However, I believe it is a general issue, since pseudocode blocks don't render well in ITU flavor, either.

Attached is an example which illustrates the issue.
[pseudocode.zip](https://github.com/metanorma/metanorma-iso/files/4639145/pseudocode.zip)

![image](https://user-images.githubusercontent.com/55683568/82129130-d74ec480-97c0-11ea-80d7-0dc14c1e55a7.png)

**Comment by opoudjis** [comment]
OK, we have a problem @manuel489 @anermina 

https://github.com/metanorma/metanorma-standoc/issues/275 is incorrect

`[pseudocode]` is not just a style attribute: it invokes the macro which guarantees that initial indents and line breaks are applied. The advice to use `[.pseudocode]` instead is incorrect, and rescinded, and I am reopening https://github.com/metanorma/metanorma-standoc/issues/275

**Comment by opoudjis** [comment]
I have now resolved the original issue that provoked this erroneous suggestion.
