### ISSUE TITLE
ISO 10303-55: definition list is not generated inside of the NOTE block

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#379]
In this specific example, definition of the term "process" should be a part of the (first) multi-paragraph note. However, it is generated below the second note:

![image](https://user-images.githubusercontent.com/55683568/82129460-4b8a6780-97c3-11ea-8bae-91482edf1fb2.png)

This happens when generating the whole ISO 10303-55 document, while both notes generate well when rendering them in separate document:

![image](https://user-images.githubusercontent.com/55683568/82129518-d1a6ae00-97c3-11ea-8073-49d9cd89da1a.png)

Source .adoc:
![image](https://user-images.githubusercontent.com/55683568/82129584-424dca80-97c4-11ea-9732-eebb52958418.png)

**Comment by opoudjis** [comment]
There is a long standing policy in Metanorma that by default notes are included in the block that immediately precedes them --- in this instance, the preceding definition list.  Clearly this can't always be the case, even though I think it is a proper default. I will address this by adding a "keep-separate" attribute. So:

`[NOTE,keep-separate=true]`
