### ISSUE TITLE
Placing Admonition at the beginning of the main content

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iso#381]
ISO-13584-42 includes an admonition placed at the beginning of the main content, just before the first section (Scope):

![Capture](https://user-images.githubusercontent.com/33627611/82463986-81fa0800-9a8b-11ea-90af-fae77c071c58.PNG)

However, in generated version, such admonition gets placed at the end of the preface area. Is there a way to get it in the right position?

**Comment by opoudjis** [comment]
There is not: the content after the preface is explicitly defined in terms of clauses, and crafting an exception is not going to be straightforward. I certainly can't see how this is conformant with ISO/IEC DIR 2. @ronaldtse Do I attempt to, or should Manuel move this somewhere else? If so, where?

**Comment by ronaldtse** [comment]
Requested clarification from ISO/CS regarding:

1. Is this “IMPORTANT” message a best practice for software specification standards?

2. ISO DP 2 18.4 only shows the “WARNING" admonition — is “IMPORTANT” also one of the types allowed? Are there other message types, e.g. CAUTION?

3. Is IMPORTANT only allowed to be placed before the Scope? Or is it allowed in all places, like NOTEs? Is WARNING only allowed in “test methods” (as per DP 2 18.4), or allowed everywhere like NOTEs?

4. Is the formatting of “IMPORTANT” always in bold? Or does the bold style apply for all admonitions before the Scope (if they are allowed)?

5. Can there be multiple “IMPORTANT” messages?

Will update when we have a reply.

**Comment by opoudjis** [comment]
There is of course a perfectly compliant solution, which I'd prefer: place the admonition inside the Scope. I could even sneak in a move to flip the admonition at the start of Scope before the scope in postprocessing. But the clarification is important anyway, because I do not believe this usage is compliant after all: ISO is very invested in every letter of a document being refererncable inside of a well-defined clause.

**Comment by ronaldtse** [comment]
From ISO/CS:

> It is possible to use "WARNING", "CAUTION", "DANGER" and "IMPORTANT"

> These are allowed to be placed before the Scope, and can also be placed within the standard to highlight a potential issue for a particular clause.

> The formatting will always be in bold.

> In theory, there is no limit to the number of such statements, but it would be unusual, and it would not make sense to have one statement immediately after another.

> the words IMPORTANT, DANGER, CAUTION and WARNING do need to be in block capitals

**Comment by ronaldtse** [comment]
The best way to deal with an admonition before the Scope is to have it apply directly to the document itself.

**Comment by opoudjis** [comment]
Going to have to do this with an option flagging the admonition(s) as `[%beforeclauses]`

**Comment by opoudjis** [comment]
For now, only licensing in grammar of ISO
