### ISSUE TITLE
Document identifiers for technical corrigendum

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#384]
FDCor
<img width="603" alt="Screen Shot 2020-05-29 at 2 46 47 PM" src="https://user-images.githubusercontent.com/11865/83230108-c720e700-a1bb-11ea-9644-1fddfd2f95f3.png">

DIS Cor
<img width="603" alt="Screen Shot 2020-05-29 at 2 48 21 PM" src="https://user-images.githubusercontent.com/11865/83230093-c25c3300-a1bb-11ea-9778-1e8173a725b0.png">

WD Cor
<img width="627" alt="Screen Shot 2020-05-29 at 2 48 00 PM" src="https://user-images.githubusercontent.com/11865/83230102-c5572380-a1bb-11ea-9ccc-e994472d9b6e.png">

CD Cor
<img width="595" alt="Screen Shot 2020-05-29 at 2 47 49 PM" src="https://user-images.githubusercontent.com/11865/83230107-c6885080-a1bb-11ea-92c4-8230775a6ad4.png">

AWI Cor

NP Cor

PWI Cor

**Comment by opoudjis** [comment]
DAmd, FDAmd
*DIS Cor*, FDCor

Because Reasons.

**Comment by ronaldtse** [comment]
> *DIS Cor*, FDCor

I'm with you. Just the way it is...
