### ISSUE TITLE
Add format: NISO STS via `mn2sts` gem

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#386]
The JAR https://github.com/metanorma/mn2sts is packed in the `mn2sts` gem at https://github.com/metanorma/mn2sts-ruby.

mn2sts produces an NISO STS XML compliant with ISOSTS (the ISO internal STS format) from a Metanorma XML.

The current version of `mn2sts` is 1.1.0.

**Comment by opoudjis** [comment]
Add to IEC as well
