### ISSUE TITLE
ISO amendment: Numbering figures/tables/code blocks/examples

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#388]
Figures are titled/numbered differently in generated DOC/PDF comparing to the original.

Generated DOC doesn't include "Figure x" before the caption. Generated PDF numbers figures with 1, 2, etc., while the original document can include a section indicator, such as "Figure A.1".

It might be helpful if we could manually add figure/table/code/example number in amendments and other document types which are referring to some specific parts of the other documents.

In this particular amendment (ISO Rice), we include the text "(...) shown in Figure A.1 (...)" and then we add Figure 1 (in PDF), or unnumbered figure (in DOC), instead of Figure A.1. Text shouldn't be changed (or replaced by some cross-reference) because it refers to the real figure in some other ISO document.

PDF:
![image](https://user-images.githubusercontent.com/55683568/83757105-46a52f00-a670-11ea-91c7-dad1b1610166.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/83757136-515fc400-a670-11ea-9a74-e714b9cbd2ee.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83757078-3bea9a00-a670-11ea-8076-ef0eb9f58871.png)

**Comment by opoudjis** [comment]
Autonumbering is very clearly completely inapplicable to quoted material in amendments. https://github.com/metanorma/metanorma-standoc/issues/287 is for overriding autonumbering, and *might* be the solution here. But suppressing numbering was a deliberate choice on my part.
