### ISSUE TITLE
ISO amendment: Font size for the "Key" after the figures

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#389]
Font size  for the "Key" after the figures is smaller in the original document than in generated DOC.

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/83760444-3d6a9100-a675-11ea-8b1d-9a61956851c9.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83760507-52472480-a675-11ea-9ecd-31a1a90e3f1c.png)

**Comment by opoudjis** [comment]
This applies to all figure keys, not just amendments.
