### ISSUE TITLE
Error using shortcut syntax for terms referencing

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#392]
When shortcut for term is used, the rest of the text doesn't render at all. 

For example, following text in .adoc:
`term:[husked rice] from which almost all of the bran and embryo have been removed by milling`

produces only:
`husked rice`

[example.zip](https://github.com/metanorma/metanorma-iso/files/4732476/example.zip)

**Comment by opoudjis** [comment]
Two problems, one @anermina, and one @w00lf  

@anermina: the content of the `term:[]` macro is not the text that will appear there, but the anchor of the term: not `term:[husked rice]`, but `term:[husked-rice]`. Metanorma looks up the text of the term, and inserts it at that location. If the text is different from the lookup term, you insert it as the second argument of the macro; e.g. `term:[husked-rice,rice that is husked]`.

@w00lf When the `term:[]` destination anchor is not found, the text following the macro instance is being deleted. I will fix.

**Comment by opoudjis** [comment]
Code intended to strip just the surrounding parentheses around "missing" when there was no corresponding target. Instead, they are stripping all surrounding text.

Moreover, I'm changing "missing" to MISSING, the error needs to be more obvious.

**Comment by anermina** [comment]
> @anermina: the content of the `term:[]` macro is not the text that will appear there, but the anchor of the term: not `term:[husked rice]`, but `term:[husked-rice]`. Metanorma looks up the text of the term, and inserts it at that location. If the text is different from the lookup term, you insert it as the second argument of the macro; e.g. `term:[husked-rice,rice that is husked]`.

Thanks for explanation, @opoudjis. Someone else converted document which had this issue and I referred to https://www.metanorma.com/author/iso/topics/markup/ when I noticed the problem. It is of course logical that anchors should be used, but can you please also change the following example on the aforementioned link, so that it says `term:[terminological-data]` instead of `term:[terminological data]`:

```
part of a terminological data collection which contains the term:[terminological data] related to one term:[concept]
```  

And also here `term:[time-axis]` instead of `term:[time axis]`:

```
system of ordered marks which can be attributed to term:[instants, instant] on the term:[time axis], one instant being chosen as the origin
```

In ISO Rice IS, `alt:[]` was also used, but this option is not documented in https://www.metanorma.com/author/iso/topics/markup/. Please let me know if this option is still valid. If it is, I will apply the same changes as for `term:[]` in this document, and I think we should add a few words about it on metanorma.com.

**Comment by ronaldtse** [comment]
@opoudjis @anermina the intent is: `term:[husked rice]`, not `term:[husked-rice]`.

And `term:[husked rice,rice that is husked]`, not `term:[husked-rice,rice that is husked]`.

**Comment by ronaldtse** [comment]
Proof that this worked properly before.

<img width="434" alt="Screen Shot 2020-06-09 at 1 25 19 PM" src="https://user-images.githubusercontent.com/11865/84109444-3ec10280-aa55-11ea-88d7-88581e3d1fd7.png">

<img width="555" alt="Screen Shot 2020-06-09 at 1 25 23 PM" src="https://user-images.githubusercontent.com/11865/84109439-3c5ea880-aa55-11ea-8f2d-0f39affa760b.png">

This is either a bug or a regression.

Also, when you define a term, there is NO NEED to create an anchor for it anymore. It is now auto-generated as `term-{your term with spaces replaced with hyphens}`

**Comment by opoudjis** [comment]
Try now.

Bug was only impacting cases when an anchor had been assigned; that's been fixed. The text should indeed be `term:[husked rice]`.

**Comment by ronaldtse** [comment]
Thank you @opoudjis ! You're the best.

**Comment by anermina** [comment]
> Thank you @opoudjis ! You're the best.

I couldn't agree more. Thanks @opoudjis , it works perfectly now.
