### ISSUE TITLE
ISO IS document review

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#393]
Generated DOC and PDF versions of ISO Rice International Standard were compared against the ISO IS model. Following differences were noticed:

*Difference 1*. In footnote description, number of the footnote is not subscripted in PDF, unlike in DOC. PDF matches the original.

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/83807316-2cd90b80-a6b3-11ea-9cb0-b70d8b307cde.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83807345-39f5fa80-a6b3-11ea-9bc4-31a7cf0727b3.png)

*Difference 2*.  Footnotes in tables are marked differently. PDF uses style: a, b, c, etc., while DOC uses style a), b), c), etc. PDF matches the original.

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/83807404-51cd7e80-a6b3-11ea-8cee-e819c493029b.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83807432-5db94080-a6b3-11ea-8cbf-d7ae81ea40c9.png)

*Difference 3*.  Caution is rendered differently.

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/83807470-6f024d00-a6b3-11ea-9c82-3c01901eb162.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83807492-79244b80-a6b3-11ea-8702-6f90ab71bb6d.png)

*Difference 4*.  Warning is rendered differently.

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/83807685-c6a0b880-a6b3-11ea-865c-ef24138e155a.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83807661-b983c980-a6b3-11ea-909b-da2e466d0482.png)

*Difference 5*.  Different cross-referencing of Formula B.1 from subsection B.6:

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/83807823-f6e85700-a6b3-11ea-9676-ec020f57a0c4.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83807763-df10d300-a6b3-11ea-9e3f-655ade827aa7.png)

*Difference 6*.  Subfigures have different titles. They are marked with: a), b), etc. in PDF, while they are marked in the format "Figure x.y-1", "Figure x.y-2", etc. in DOC. PDF matches the original.

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/83807947-24cd9b80-a6b4-11ea-8406-a9322b184b33.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83807979-37e06b80-a6b4-11ea-9e18-733fd8925ac1.png)

*Difference 7*.  At the end of the document, DOC doesn't add an information about ICS number and on how much pages was the price based.

Original/generated PDF:
![image](https://user-images.githubusercontent.com/55683568/83808026-4b8bd200-a6b4-11ea-9d2b-819b4c9b0733.png)

**Comment by opoudjis** [comment]
Difference 1, footnote rendering, is NOT supported in the Word template provided by ISO, which does not even use the parenthesis (let along sizing the footnote reference differently from the footnote anchor). Will not action unless confirmed by ISO, they may want the Word document to keep default footnote rendering. (So may need to revert https://github.com/metanorma/metanorma-iso/issues/301). @ronaldtse Please escalate to ISO.

Difference 2, footnote rendering of table footnotes. This was overgeneralisation of footnote rendering in https://github.com/metanorma/metanorma-iso/issues/301. 

Difference 3 and Difference 4, admonition rendering. Have already fixed rendering in IEC, moving that code up to ISO.

Difference 5. The Rice model document is violating ISO policy on this point:

https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor372

> Use, for example, the following forms for references to mathematical formulae:
> *  “see 10.1, Formula (3)”;
> *  “see A.2, Formula (A.5)”.

I therefore will not action this.

Difference 6. Confirmed in ISO/IEC DIR 2.

Difference 7. In fact that is already implemented, but only for documents with Published status:

<img width="1603" alt="Στιγμιότυπο 2020-06-19, 00 04 23" src="https://user-images.githubusercontent.com/1911039/85030255-903d6000-b1c0-11ea-9de7-848041a027e8.png">

**Comment by opoudjis** [comment]
Of the points gone through, 

* Difference 1 to be escalated.
* Difference 5 rejected.

**Comment by ronaldtse** [comment]
Difference 1. Let’s not forget that the Word output and PDF output are for different purposes. Word is for review (track changes) and submission to ISO/CS. PDF is only for review and reading. This discrepancy is acceptable. There is no need to escalate this to ISO because they will provide the same sort of answer. 

Difference 5. The ISO Rice document was authored a couple years ago and contains a number of errors, and is likely to deviate from current Directives. So we have to be aware of that.

**Comment by opoudjis** [comment]
In that case, ticket closed.
