### ISSUE TITLE
Error using gems "asciimath" and "isodoc"

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#395]
In order to properly generate some math expressions, gem "asciimath" needs to be used (https://github.com/metanorma/metanorma-standoc/issues/257#issuecomment-621159820).
In order to avoid issues with Windows failing to run rspec, gem "isodoc" needs to be used (https://github.com/metanorma/metanorma-itu/issues/213).

However, these two gems cannot be used at the same time, producing the following error:

PS D:\Metanorma\mn-samples-iso> bundle install
Fetching https://github.com/asciidoctor/asciimath
Fetching gem metadata from https://rubygems.org/..............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "asciimath":
  In Gemfile:
    isodoc x64-mingw32 was resolved to 1.0.27, which depends on
      html2doc (~> 1.0.0) x64-mingw32 was resolved to 1.0.1, which depends on
        asciimath (~> 1.0.9) x64-mingw32
    isodoc x64-mingw32 was resolved to 1.0.27, which depends on
      asciimath x64-mingw32
Could not find gem 'asciimath (~> 1.0.9)', which is required by gem 'isodoc', in
any of the relevant sources:
  https://github.com/asciidoctor/asciimath (at master@1f74439)

Could you please let me know how to avoid this error and manage to get the proper output?

**Comment by CAMOBAP** [comment]
@anermina could you please share Gemfile or repository which you used

**Comment by anermina** [comment]
Gemfile content is as follows:

```
source "https://rubygems.org"

gem "metanorma-cli"
gem "asciimath", git: "https://github.com/asciidoctor/asciimath"
gem "metanorma-itu", git: "https://github.com/metanorma/metanorma-itu"
gem "isodoc", git: "https://github.com/metanorma/isodoc"
```

**Comment by opoudjis** [comment]
Btw asciimath is now updated to 2.0.0, which means @anermina you should no longer need to pull the asciimath gem from github. I'm going a major release tomorrow, but I'm bumping up the asciimath dependency with html2doc tonight.

@CAMOBAP @anermina That means this issue may go away after tomorrow.

**Comment by CAMOBAP** [comment]
looks fixed, @anermina  could you please confirm?

**Comment by ronaldtse** [comment]
Ping @anermina this is supposed to be fixed. Any further issues?

**Comment by anermina** [comment]
All good now. Closing.
