### ISSUE TITLE
XML: ISO Rice IS review

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#397]
Two minor changes are required in ISO Rice IS:

- Remove "ISO DATE:" text from the footnote 1.

> Source XML (https://github.com/metanorma/mn-samples-iso/blob/gh-pages/documents/international-standard/rice-en.final.xml) contains "ISO DATE:" text:
> 
> ```
> <bibitem id="ISO712" type="standard">...
> <note format="text/plain">ISO DATE: Under preparation. (Stage at the time of publication ISO/DIS 16634)</note>
> </bibitem>
> ```

- "Normative References" title should be changed to "Normative references", i.e. capital R should be replaced with small r.

> References has capital R in XML:
> 
> ```
> <bibliography><references id="_normative_references" normative="true" obligation="informative"><
> ```

(Original comments copied from https://github.com/metanorma/mn-native-pdf/issues/59#issuecomment-642134861)

**Comment by opoudjis** [comment]
Normative References: will defer addressing this to https://github.com/metanorma/metanorma-standoc/issues/285, the title contents of fixed sections is an internationalisation issue.

**Comment by opoudjis** [comment]
ISO DATE prefix to biblio note swapped out for biblio type:

````
<note>ISO DATE: ...</note>
````

to 


````
<note type="ISO DATE">...</note>
````

**Comment by ronaldtse** [comment]
Is there something more semantically sane than `<note type="ISO DATE">...</note>`?

**Comment by opoudjis** [comment]
sigh... Will address in https://github.com/metanorma/metanorma-iso/issues/402
