### ISSUE TITLE
When there is no detected T&D section (e.g. wrong title), document rendering is completely broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#408]
The XML will contain a `<terms>` section like this:

```xml
<terms id="_terms_definitions_symbols_and_abbreviated_terms" obligation="normative"><title>Terms, definitions, symbols and abbreviated terms</title><p id="_622ba80d-47e7-4bc5-bf2b-99c9bc9fcd99">No terms and definitions are listed in this document.</p>
<p id="_e7a5d7e7-6535-4c4a-9258-18655fa14cee">ISO and IEC maintain terminological databases for use in
standardization at the following addresses:</p>

<ul id="_3befae21-12b7-4f4d-9d3f-bae12d18c392">
<li> <p id="_fb149544-2d80-4ce4-b936-36ab0e813cc0">ISO Online browsing platform: available at
  <link target="http://www.iso.org/obp"/></p> </li>
<li> <p id="_1bc191bc-9f31-4492-8afd-789c1aec5927">IEC Electropedia: available at
<link target="http://www.electropedia.org"/>
</p> </li> </ul>
```

But this rendering does not even show in the HTML output.

The eventual document will be all broken: (see clause 3 and 4 swapped, despite that the include order is 3 then 4).

![image](https://user-images.githubusercontent.com/11865/88084426-01ed3d00-cbb7-11ea-95f1-46ed1391ee38.png)

The Annex will also be broken if there are no terms defined in the document:

![image](https://user-images.githubusercontent.com/11865/88084527-221cfc00-cbb7-11ea-9f67-2bf2675caae8.png)

Regardless whether the user remembers to provide a T&D, or provides zero or more terms, the layout should not break.

**Comment by opoudjis** [comment]
@ronaldtse Point me to what document this is in. Not actioning this without that.

**Comment by ronaldtse** [comment]
https://github.com/metanorma/iso-10303/commit/fc88f31aae83d713bfd8bb7269f163528dc0c1d5#diff-f2ab5fb218da8b84623f45579aa4ba11

**Comment by ronaldtse** [comment]
i.e. if you change the T&D section to an unrecognized title, your document will break.

If there is no recognized T&D title, then there should be a T&D section with no entries, and the document rendering shouldn't break.

**Comment by opoudjis** [comment]
Introducing a new terms empty terms section is a new and unwelcome change.

**Comment by opoudjis** [comment]
There was a rogue `@definitions` status variable: a definitions clause was detected, under `[.nonterm]`, but the status variable was never being turned off. As a result, everything was being treated as a Symbols & Abbreviations clause.

Fixing this in https://github.com/metanorma/metanorma-iso/issues/411 is fixing most of these issues. The clauses are now being parsed in the right order, since there is no putative out of sequence definitions clause. The annexes do not have spurious definition subclauses, which were why there were top level headings.

The remaining task here is to introduce an empty terms section.

**Comment by opoudjis** [comment]
Generalising task: inserting missing scope, normative references, and terms & definitions.

**Comment by ronaldtse** [comment]
We need to determine whether the insertion of default clauses is necessary -- how do we deal with legacy? Or is there a document attribute that "forces compliance" vs "relaxed"?

**Comment by opoudjis** [comment]
No insertion for now; will make warnings on absent sections more explicit
