### ISSUE TITLE
non-Eng review: Some predefined section titles aren't in Chinese. Should they be so?

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iso#412]
*As requested in https://github.com/metanorma/metanorma-iso/issues/309#issuecomment-666342904*

Predefined sections like "Foreword", "Introduction", "Scope", "Normative references" and "Terms and Definitions" are not rendering in Chinese language (nor their boilerplates).
I have noticed that the markup is slightly different in these cases:  

````
[heading=Introduction]
== 引言
...

[heading=Scope]
== 范围
...

[bibliography,heading=Normative references]
== 规范性引用文件
...

[source="ISO712,ISO24333",heading=Terms and definitions]
== 术语和定义
...

````

Which is as stated in the documentation. So I wonder if this is the expected result:

![intro-zh](https://user-images.githubusercontent.com/33627611/89088338-b6c8ec00-d365-11ea-9ce9-f2a5fc684ae2.PNG)

![scope-zh](https://user-images.githubusercontent.com/33627611/89088361-d233f700-d365-11ea-8336-4a565729debc.PNG)

**Comment by anermina** [comment]
According to https://github.com/metanorma/metanorma-iso/issues/299, specifically https://github.com/metanorma/metanorma-iso/issues/299#issuecomment-575090670, I believe that markup is correct, but the titles should be in Chinese.
