### ISSUE TITLE
Non-English (Chinese) document review: ISO Rice ZH

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#413]
_As requested in [#309 (comment)](https://github.com/metanorma/metanorma-iso/issues/309#issuecomment-666342904) and in addition to https://github.com/metanorma/metanorma-iso/issues/412_

1. Cross-references to annexes/appendices, figures and tables are in English.

![image](https://user-images.githubusercontent.com/55683568/89129274-63d56d00-d4fc-11ea-9c17-e474b648381c.png)

2. Introduction to Normative references section is in English. It can also be seen from the screenshot that auto-fetched references do not contain details written in Chinese (added in .adoc). Should we turn auto-fetching off in .adoc, or this should be solved in the code?
[Update]: I opened a ticket https://github.com/metanorma/metanorma-iso/issues/417 for auto-fetching references in Chinese/French.

![image](https://user-images.githubusercontent.com/55683568/89129355-0988dc00-d4fd-11ea-8de1-b1dc286b1c7b.png)

Source .adoc:
````
[bibliography,heading=Normative references]
== 规范性引用文件

下列文件对于本文件的应用是必不可少的。凡是注日期的引用文件，仅注日期的版本适用于本文件。凡是不注日期的引用文件，其最新版本（包括所有的修改单）适用于本文件。

* [[[ISO712,ISO 712]]], _谷物和谷类产品水分含量的测定参考方法，Cereals and cereal products -- Determination of moisture content -- Reference method_
````

3. Introduction to Terms and definitions section is also in English.

![image](https://user-images.githubusercontent.com/55683568/89129368-4228b580-d4fd-11ea-95d1-6af547183b1d.png)

4. Keywords such as "note"/"note -x- to entry", "caution", "warning", "source", "deprecated", etc., which are produced as a result of using some markup element (such as `[.source]` and `[deprecated]`) should probably be generated in Chinese. 
[Update]: Ticket https://github.com/metanorma/metanorma-iso/issues/418 refers to the same issue when it comes to the French version of the document.

![image](https://user-images.githubusercontent.com/55683568/89129493-10fcb500-d4fe-11ea-8e7c-9caf1b941690.png)
![image](https://user-images.githubusercontent.com/55683568/89129535-58834100-d4fe-11ea-9218-c198cc0eb697.png)
![image](https://user-images.githubusercontent.com/55683568/89129631-0393fa80-d4ff-11ea-9a21-3c5faeab10ec.png)
![image](https://user-images.githubusercontent.com/55683568/89129696-7c935200-d4ff-11ea-8f8d-af6de014aa9b.png)
![image](https://user-images.githubusercontent.com/55683568/89129726-d431bd80-d4ff-11ea-8a70-bd6f01272643.png)

5. In the following screenshot, it can be seen that the word "modified" is written in English, which is probably different type of error than the above mentioned, since it doesn't appear in the French version of the document.

![image](https://user-images.githubusercontent.com/55683568/89129493-10fcb500-d4fe-11ea-8e7c-9caf1b941690.png)

6. Tables and figures should probably have a caption (keyword "Table"/"Figure") in Chinese.

![image](https://user-images.githubusercontent.com/55683568/89129598-c6c80380-d4fe-11ea-882a-51ed5c12e9e8.png)
![image](https://user-images.githubusercontent.com/55683568/89129673-5ff71a00-d4ff-11ea-8abe-c515c15383b4.png)

7. Annexes and appendices should probably have a title and a subtype in Chinese.

![image](https://user-images.githubusercontent.com/55683568/89129647-2d4d2180-d4ff-11ea-9438-927b6cc40728.png)

**Comment by opoudjis** [comment]
You will be assigning this to me eventually?

**Comment by anermina** [comment]
Yes @opoudjis, please let me know if I can assign the ticket now. Otherwise, I'll let it like this until you have some more time.

**Comment by opoudjis** [comment]
@anermina: I'm sorry it's taken me so long to even glance at this (though it's not my fault I have so much of a backlog.)

Chinese localisation requires currently not just the language, but the script to be set in document attributes: `:script: Hans` as opposed to :script: Hant` for Simplified Chinese. (We never felt comfortable making Simplified Chinese the default.)

With that done, the document is substantially improved. Could I ask you to check the attached, and tell me if there is anything left to do? The title and boilerplate are in English, because we have hardcoded English and French as the two languages of the ISO; unless we define a Chinese title page and boilerplate, that will remain the case. (@ronaldtse ?)

[rice-zh.zip](https://github.com/metanorma/metanorma-iso/files/5471163/rice-zh.zip)

**Comment by anermina** [comment]
Issues are mostly solved.

1. What I can see is that "All rights reserved" is written in English on odd and in Chinese on even pages. This should be adjusted.

![image](https://user-images.githubusercontent.com/55683568/97916983-14e5e080-1d54-11eb-8560-cc686485ae35.png)
![image](https://user-images.githubusercontent.com/55683568/97916736-b02a8600-1d53-11eb-834c-b64bd0892d28.png)

2.
> The title and boilerplate are in English, because we have hardcoded English and French as the two languages of the ISO; unless we define a Chinese title page and boilerplate, that will remain the case.

In case Chinese is not defined, we won't be able to auto-fetch references in Chinese (#417), right?

Additionally for adoc:

3. Sentence "The results of an interlaboratory test are given in 附件 D for information" remained written in English. Do we have an original Chinese document, so that I can change this?

![image](https://user-images.githubusercontent.com/55683568/97916434-41e5c380-1d53-11eb-9f02-8cbac8617bca.png)

There are some minor non-language-related issues in generated Word DOC comparing to the original English version. I'll address them in a new ticket.

**Comment by opoudjis** [comment]
> What I can see is that "All rights reserved" is written in English on odd and in Chinese on even pages. This should be adjusted.

Fixed

> In case Chinese is not defined, we won't be able to auto-fetch references in Chinese (#417), right?

if there is no language match, we should be degrading gracefully. In our benighted age that means, Andrej is returning all languages (English and French), and since I am filtering the title language, the references will show up in English as the default language. Amusingly, in a Chinese document, the bibliographic entry is in English, but the footnote now added to indicate that the document is a draft (#402) is Chinese:

````
<bibitem id="x" type="standard">  
<fetched>2020-11-04</fetched>  
<title type="title-intro" format="text/plain" language="en" script="Latn">Processing of health care products</title>  
<title type="title-main" format="text/plain" language="en" script="Latn">Information to be provided by the medical device manufacturer for the processing of medical devices</title>  
<title type="title-part" format="text/plain" language="en" script="Latn">Part 1: Critical and semi-critical medical devices</title>  
<title type="main" format="text/plain" language="en" script="Latn">Processing of health care products — Information to be provided by the medical device manufacturer for the processing of medical devices — Part 1: Critical and semi-critical medical devices</title>  
<uri type="src">https://www.iso.org/standard/81720.html</uri>  
<uri type="rss">https://www.iso.org/contents/data/standard/08/17/81720.detail.rss</uri>  
<docidentifier type="ISO">ISO/FDIS 17664-1</docidentifier>  
<docidentifier type="URN">urn:iso:std:iso-fdis:17664:-1:stage-50.00:ed-1:en</docidentifier>  
<docnumber>17664</docnumber>  
<contributor>    <role type="publisher"/>    <organization>      <name>International Organization for Standardization</name>      <abbreviation>ISO</abbreviation>      <uri>www.iso.org</uri>    </organization>  </contributor>  
<edition>1</edition>  
<note type="Unpublished-Status">
  <p id="_0e5f13c7-aefd-4cff-a76d-c74b3c40fbaf">制定中（出版时最新状态为ISO/FDIS 17664-1）</p></note>
<language>en</language>  
<script>Latn</script>  
<status>    <stage>50</stage>    <substage>00</substage>  </status>  
<copyright>    <from>unknown</from>    <owner>      <organization>        <name>ISO/FDIS</name>      </organization>    </owner>  </copyright>  
</bibitem>
````

**Comment by opoudjis** [comment]
> Sentence "The results of an interlaboratory test are given in 附件 D for information" remained written in English. Do we have an original Chinese document, so that I can change this?

In fact the Chinese for it appears immediately below; deleting the English.
