### ISSUE TITLE
Enable ISOSTS extension output

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#415]
mn2sts now supports ISOSTS output in addition to NISO STS.

Add command line parameter `--output-format iso`:
```sh
java -jar mn2sts.jar --xml-file-in input.mn.xml --xml-file-out output.sts.xml --output-format iso
```
_Originally posted by @Intelligent2013 in https://github.com/metanorma/mn2sts/issues/13#issuecomment-675457435_

**Comment by opoudjis** [comment]
Implemented as -t isosts.
