### ISSUE TITLE
Missing ISO document identifier and revdate at stage 60/60

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#416]
Generated document:
<img width="608" alt="Screen Shot 2020-08-29 at 5 29 08 PM" src="https://user-images.githubusercontent.com/11865/91633711-255ca080-ea1d-11ea-8dc0-62a06c2b96d1.png">

Encoding:
```adoc
:docnumber: 10303
:partnumber: 11
:edition: 2
:copyright-year: 2004
:revdate: 2004-11-01
```

Previously:
<img width="608" alt="Screen Shot 2020-08-29 at 5 29 23 PM" src="https://user-images.githubusercontent.com/11865/91633715-2f7e9f00-ea1d-11ea-944d-08a908ea6e86.png">

**Comment by Intelligent2013** [comment]
Fixed.
![изображение](https://user-images.githubusercontent.com/5559926/91634782-b4f15780-e9fb-11ea-8e54-26c4d645ee62.png)

Changes:
- in the previous version I've put published date for IS, now - if there is published date, then put it, else revision date.
- docidentifier attribute 'type' was changed from 'iso' to 'ISO':
`<docidentifier type="iso">ISO 10303-11:2004</docidentifier>` ->  `<docidentifier type="ISO">ISO 10303-11:2004</docidentifier>`
