### ISSUE TITLE
Rendering syntax `[en]#t-en# [fr]#t-fr#`

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#419]
If document attribute `language` is set to `fr`, I'm not sure whether syntax `=== [en]#husked rice# [fr]#riz décortiqué#` should produce the title only in French or in both languages, as it does now. The same applies for using `:language: zh`.

Since this syntax was used in Chinese version of the document which was converted earlier, the same principle was followed for French version as well. In case changes in .adoc are needed, please let me know.

Original:
![image](https://user-images.githubusercontent.com/55683568/92161588-1ddc3380-ee31-11ea-9de3-e21d7e342d4f.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/92161501-069d4600-ee31-11ea-995b-96906c30dbda.png)

**Comment by opoudjis** [comment]
This is indeed a bug.

**Comment by opoudjis** [comment]
@anermina In order to generalise this, I want to stop using `[en]#text#`, which relies on the role attribute of Asciidoctor (which we may want to use for other functions), and instead use the macros `lang:en[text]`, and `lang:en-Latn[text]`.
