### ISSUE TITLE
Update ISO Amendment PDF layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#422]
I think we need to find a DAmd layout to check. We're not showing the "Amendment name" (see below cover)

[Archive.zip](https://github.com/metanorma/metanorma-iso/files/5230685/Archive.zip)

<img width="631" alt="Screen Shot 2020-09-16 at 3 48 52 PM" src="https://user-images.githubusercontent.com/11865/93307897-20c52400-f834-11ea-8f3a-ef46f3c4c7c2.png">

**Comment by Intelligent2013** [comment]
Fixed.
![изображение](https://user-images.githubusercontent.com/5559926/93323385-37ac4c00-f81d-11ea-8e06-daf5126e4c3a.png)

**Comment by ronaldtse** [comment]
Ping @opoudjis on schedule a PR.

**Comment by opoudjis** [comment]
PDF XSLT updates are pulled just before gem release, as a matter of course. There is nothing for me to do for this ticket that I do not do every fortnight, there is no PR process to be initiated manually for XSLT updates. Alex Bobrokovich still has the task of initiating them automatically from commits in mn-native-pdf and mn-native-pdf-nist: https://github.com/metanorma/mn-native-pdf/issues/230

I am therefore unassigning myself this ticket.

**Comment by ronaldtse** [comment]
And I found one DAmd:
<img width="539" alt="Screen Shot 2020-09-23 at 6 07 24 PM" src="https://user-images.githubusercontent.com/11865/93998837-b11cdf00-fdc7-11ea-8adb-75c918855f9f.png">
<img width="524" alt="Screen Shot 2020-09-23 at 6 08 00 PM" src="https://user-images.githubusercontent.com/11865/93998858-b843ed00-fdc7-11ea-830d-b8a2ce3545c5.png">
<img width="531" alt="Screen Shot 2020-09-23 at 6 08 12 PM" src="https://user-images.githubusercontent.com/11865/93998887-bf6afb00-fdc7-11ea-965b-4155a99786d6.png">
<img width="533" alt="Screen Shot 2020-09-23 at 6 08 20 PM" src="https://user-images.githubusercontent.com/11865/93998897-c42faf00-fdc7-11ea-8e9e-42cb36e5b0e5.png">

**Comment by ronaldtse** [comment]
This is reopened for PDF, ping @Intelligent2013 .

**Comment by Intelligent2013** [comment]
Fixed.

Example of resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/94993666-517abc80-059b-11eb-956c-a95f93b5990e.png)
