### ISSUE TITLE
Missing translations to French

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#428]
Follow-on from https://github.com/metanorma/metanorma-iso/issues/418:

Please use /local_bibdata/i18nyaml/i18n_reference_number for string value for "Reference Number" in ISO cover.

Please use /local_bibdata/i18nyaml/i18n_all_rights_reserved for string value for "All rights reserved" in ISO (back?) cover.

Please use /local_bibdata/i18nyaml/i18n_price_based_on for string value for "Price based on % pages" in ISO back cover. Note convention of % for placeholder. (Ronald would prefer Liquid conventions, but Liquid conventions are useless for XSLT.)

Please use /local_bibdata/i18nyaml/i18n_deprecated for string value for "DEPRECATED"

Please use  /local_bibdata/i18nyaml/i18n_admonition for the titles for admonitions:

````
<i18n_admonition><i18n_danger>Danger</i18n_danger><i18n_warning>Avertissement</i18n_warning><i18n_caution>Attention</i18n_caution><i18n_important>Important</i18n_important><i18n_safety_precautions>Précautions de Sécurité</i18n_safety_precautions></i18n_admonition>
````

I've created a French language boilerplate. Note that COPYRIGHT PROTECTED DOCUMENT is now a clause title, and not to be supplied by you: I've had to refactor boilerplate/copyright-statement. 

For Presentation XML, see https://github.com/metanorma/metanorma-iso/issues/418

**Comment by Intelligent2013** [comment]
Done. PDF example for rice-fr.presentation.xml from #418 (with manually moved `i18nyaml` tags to `localized-strings` structure):
[rice-fr.presentation.pdf](https://github.com/metanorma/metanorma-iso/files/5487481/rice-fr.presentation.pdf)
