### ISSUE TITLE
Word: ISO Rice (Chinese) review

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#433]
Word:

1. I'm not sure whether the angle brackets should look like this in Chinese version. Probably usual ones `[ ]` should be used.

![image](https://user-images.githubusercontent.com/55683568/97915032-14981600-1d51-11eb-9718-de2bcb8f5a6e.png)

2. Equations are not centered (but only indented) in PDF and in the original document, unlike in Word (except from the Appendix part in Word, where they are also indented).

Word:
![image](https://user-images.githubusercontent.com/55683568/97916560-722d6200-1d53-11eb-8bf4-6484605ab532.png)

PDF:
![image](https://user-images.githubusercontent.com/55683568/97916585-79ed0680-1d53-11eb-8704-49fd572aacd7.png)

Word or/and PDF:

3. Cross-references to bibliography are blue and underlined in Word, unlike in PDF. Original document (in English) doesn't even have the cross-references here, so I'm not able to tell what is correct.

PDF:
![image](https://user-images.githubusercontent.com/55683568/97915907-8886ee00-1d52-11eb-865b-aba1e668cde6.png)

Word:
![image](https://user-images.githubusercontent.com/55683568/97915932-92a8ec80-1d52-11eb-8205-7eb4b8bd876c.png)

4. Footnote, note, key elements and figure caption are ordered differently after the corresponding figure. 

The order in Word: caption, footnote, key elements, note.
![image](https://user-images.githubusercontent.com/55683568/97917848-6a6ebd00-1d55-11eb-841f-43208a8d995e.png)

The order in PDF:  footnote, caption, key elements, note.
![image](https://user-images.githubusercontent.com/55683568/97917799-56c35680-1d55-11eb-897a-1a14b32a5165.png)

The order in original document (English version): key elements, footnote, note, caption.
![image](https://user-images.githubusercontent.com/55683568/97917864-73f82500-1d55-11eb-8193-46f054dcb9c9.png)

**Comment by ronaldtse** [comment]
> I'm not sure whether the angle brackets should look like this in Chinese version. Probably usual ones [ ] should be used.

Those are the Simplified Chinese square brackets, so they are correct.

Cross references like "附件A" or "表1" should not have any space in between.

**Comment by opoudjis** [comment]
2. The issue in Word is that the main body formulas are unnumbered, but the formulas only render correctly if a tab appears after them. Inserting dummy tab just for Word.

**Comment by opoudjis** [comment]
3. Blue is correct for Word: https://github.com/metanorma/metanorma-iso/issues/305

**Comment by opoudjis** [comment]
4. English rendering correctly in Word.

The gotcha here is the "key" word in the source: this is currently actually expected to be in English, as it detected during parsing. This behaviour will be eliminated in https://github.com/metanorma/metanorma-standoc/issues/202, if Ronald ever lets me get to it.

**Comment by opoudjis** [comment]
Space in cross-references: have not been applying (spacing) localisation to the generation of cross-reference labels. Fixing; this is a Presentation XML-level fix, so it will be inherited by PDF.
