### ISSUE TITLE
PDF: ISO Rice (Chinese) review

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#434]
PDF:

1. Word "Cereals" is in different font.

![image](https://user-images.githubusercontent.com/55683568/97914531-51afd880-1d50-11eb-80da-271d3c9431ad.png)

2. Baseline is not the same for the text in Chinese and the text in English (though we shouldn't have text in English, but word "ISO" should remain).

![image](https://user-images.githubusercontent.com/55683568/97914654-84f26780-1d50-11eb-9a7e-20a732288b5c.png)

3. Highlighted keywords should be in Chinese.

![image](https://user-images.githubusercontent.com/55683568/97914881-db5fa600-1d50-11eb-8195-3f80d02ca201.png)
![image](https://user-images.githubusercontent.com/55683568/97916109-ce43b680-1d52-11eb-8140-8bf8c8f6c85a.png)
![image](https://user-images.githubusercontent.com/55683568/97917209-71490000-1d54-11eb-8363-ec9114e3cff3.png)

4. "All rights reserved" is written in English, unlike in Word (currently we have this in English on odd and in Chinese on even pages in Word, as mentioned in https://github.com/metanorma/metanorma-iso/issues/413).

![image](https://user-images.githubusercontent.com/55683568/97916906-f1bb3100-1d53-11eb-9b29-f57c49f0efba.png)

Word or/and PDF:

1. Cross-references to bibliography are blue and underlined in Word, unlike in PDF. Original document (in English) doesn't even have the cross-references here, so I'm not able to tell what is correct.

PDF:
![image](https://user-images.githubusercontent.com/55683568/97915907-8886ee00-1d52-11eb-865b-aba1e668cde6.png)

Word:
![image](https://user-images.githubusercontent.com/55683568/97915932-92a8ec80-1d52-11eb-8205-7eb4b8bd876c.png)

2. Footnote, note, key elements and figure caption are ordered differently after the corresponding figure. 

The order in Word: caption, footnote, key elements, note.
![image](https://user-images.githubusercontent.com/55683568/97917848-6a6ebd00-1d55-11eb-841f-43208a8d995e.png)

The order in PDF:  footnote, caption, key elements, note.
![image](https://user-images.githubusercontent.com/55683568/97917799-56c35680-1d55-11eb-897a-1a14b32a5165.png)

The order in original document (English version): key elements, footnote, note, caption.
![image](https://user-images.githubusercontent.com/55683568/97917864-73f82500-1d55-11eb-8193-46f054dcb9c9.png)

**Comment by opoudjis** [comment]
@Intelligent2013 note that I have made edits to doc in related ticket #433; 

* Word or/and PDF issues: Blue is ok, and the figure rendering should be fixed in markup. 

Use this PresentationXML:

[rice-zh.zip](https://github.com/metanorma/metanorma-iso/files/5487291/rice-zh.zip)

**Comment by Intelligent2013** [comment]
> ### 1. Word "Cereals" is in different font.

Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/98266130-fcb3d280-1f9a-11eb-845d-405b45b3ac6e.png)

> ### 2. Baseline is not the same for the text in Chinese and the text in English (though we shouldn't have text in English, but word "ISO" should remain).

Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/98266272-279e2680-1f9b-11eb-8fc6-9df8308b8170.png)
![изображение](https://user-images.githubusercontent.com/5559926/98266301-2e2c9e00-1f9b-11eb-8aa8-bc335477c13b.png)

> ### 3. Highlighted keywords should be in Chinese.

Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/98266401-50beb700-1f9b-11eb-8ba2-056f1c68c7ef.png)
![изображение](https://user-images.githubusercontent.com/5559926/98266437-5ae0b580-1f9b-11eb-8fec-6f62e55b42d0.png)
![изображение](https://user-images.githubusercontent.com/5559926/98266496-70ee7600-1f9b-11eb-9669-800358155239.png)
![изображение](https://user-images.githubusercontent.com/5559926/98266549-82d01900-1f9b-11eb-937f-03094ee0bd28.png)

> ### 4. "All rights reserved" is written in English,

Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/98266704-ac894000-1f9b-11eb-90f3-fe9123319f99.png)


> ### 1. Cross-references to bibliography are blue and underlined in Word, unlike in PDF. Original document (in English) doesn't even have the cross-references here, so I'm not able to tell what is correct.

ISO xslt was updated earlier to align original PDF (https://github.com/metanorma/mn-native-pdf/issues/35) which hasn't blue/underline style.
Example of original English PDF (https://github.com/metanorma/mn-samples-iso/blob/master/reference-docs/iso-rice-sample.pdf):
![изображение](https://user-images.githubusercontent.com/5559926/98267731-c11a0800-1f9c-11eb-97e0-6cc70f43f425.png)

Example of resulted English PDF:
![изображение](https://user-images.githubusercontent.com/5559926/98267467-79937c00-1f9c-11eb-88a4-4f1c19cdf60e.png)
![изображение](https://user-images.githubusercontent.com/5559926/98267823-dc851300-1f9c-11eb-9360-2142dd448353.png)

(I don't recall why Table reference blue/underlined...)

Example of resulted Chinese PDF:
![изображение](https://user-images.githubusercontent.com/5559926/98268891-1d315c00-1f9e-11eb-85b2-46a56cd8927a.png)


@ronaldtse Would you like to set blue/underline for cross-references to bibliography for Chinese PDF only, or for English also?


> ###  2. Footnote, note, key elements and figure caption are ordered differently after the corresponding figure.

Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/98271925-85ce0800-1fa1-11eb-9e57-226d7487f5ca.png)

Resulted PDF in Chinese:
[rice-zh.presentation.pdf](https://github.com/metanorma/metanorma-iso/files/5495817/rice-zh.presentation.pdf)

**Comment by Intelligent2013** [comment]
Before closing this 3 years ago fixed issue I've tested it again for Issue 1 'Word "Cereals" is in different font.' and it occurred again:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/c9d4bf30-68b7-459a-aa90-1f6b4b809b7c)

Currently used fonts in `fo:root`: `font-family="Noto Serif, Noto Serif SC, Cambria, Times New Roman,...`
The font `Noto Serif` and `Noto Serif SC` have different baselines (yes, it's very strange). Current font selection strategy is `auto` (https://xmlgraphics.apache.org/fop/2.9/fonts.html#selection). Apache FOP 2.9 supports `character-by-character` strategy and upgrade to FOP 2.9 should solve this issue.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/54c675a3-3fd0-4e0a-8c15-72ac576a6957)

Done in https://github.com/metanorma/mn2pdf/releases/tag/v1.86 and will be available in the latest ISO XSLT.
