### ISSUE TITLE
Issue with Appendices inside of Annex

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iso#444]
Something goes wrong with section numbering in appendices inside annexes. The section numbering takes the value of the cross-reference anchor of the section if provided, if not, it takes the title of the section in the form: `[_{section-title}]`.

Example taken from https://github.com/metanorma/mn-samples-iso/pull/66:

````

[%appendix]
=== Justification criteria questions

[[_idTextAnchor562]]
==== General

The list of questions to be addressed in the justification study are in line with the principles
listed in <<_idTextAnchor541>>. This list is not exhaustive. Additional information not covered
by the questions should be provided if it is relevant to the case.

...
````

Renders:

![Capture](https://user-images.githubusercontent.com/33627611/100253056-06d04d80-2f17-11eb-9e84-37e877c3f730.PNG)

Also, the any cross-reference inside the appendix stops working.

**Comment by opoudjis** [comment]
Looks like I'd forgotten to recurse inside appendices and assign anchors to subclauses.
