### ISSUE TITLE
Smart single quotes sometimes not working?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#453]
This is from ISO 8601-1/Amd 1 (https://github.com/CalConnect/iso-8601-1-amd1/pull/3):

```adoc
[change=modify,locality="clause=5.3.2]
== 5.3.2

[quote]
____
...
When a system receives for processing the natural language
expression '`24:00:00`' to express time of day for a given day, it
shall convert '`24:00:00`' to the proper representation of the last
second of the day; it shall not convert the specified time to
'`00:00:00`' or modify the calendar date to that of the following
day.
____
```

Gives out the opening single quote in the wrong direction. This seems to only happen when the first character is a number (e.g. ``'`24:00:00`'``), not with alphabets (e.g. ``'`abc`'``).

DOC:
<img width="650" alt="Screen Shot 2020-12-18 at 1 28 54 AM" src="https://user-images.githubusercontent.com/11865/102523404-77abf500-40d2-11eb-980a-2343ec302c38.png">

HTML:
<img width="409" alt="Screen Shot 2020-12-18 at 1 41 24 AM" src="https://user-images.githubusercontent.com/11865/102523410-7975b880-40d2-11eb-8bdf-c5b05fb20de6.png">

**Comment by opoudjis** [comment]
The smart quotes processor from sterile is clearly not smart enough. We had raised a bug about ’99’ in https://github.com/pbhogan/sterile/pull/1, but the pattern needs to be more restrictive still. Will do another PR, hopefully gem is still being maintained.

**Comment by ronaldtse** [comment]
* ``"`24`"`` works
<img width="47" alt="Screen Shot 2020-12-19 at 7 43 14 PM" src="https://user-images.githubusercontent.com/11865/102688561-71cd2580-4232-11eb-8803-43608e2ae905.png">

* ``"24:00:00`"`` gives the wrong first single quote

<img width="117" alt="Screen Shot 2020-12-19 at 7 43 36 PM" src="https://user-images.githubusercontent.com/11865/102688569-7e517e00-4232-11eb-8928-ca31b76ed9a6.png">

**Comment by opoudjis** [comment]
Yes, I know that's the behaviour, and it didn't do `'24'` correctly either until I PR'd it.

**Comment by opoudjis** [comment]
Also duplicating that functionality locally, in case sterile no longer maintained.

**Comment by ronaldtse** [comment]
Thanks @opoudjis!
