### ISSUE TITLE
Document elements inside quotations not showing properly in PDF output

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#454]
This is from ISO 8601-1/Amd 1 (https://github.com/CalConnect/iso-8601-1-amd1/pull/3):

```
[change=modify,locality="clause=5.3.2]
== 5.3.2

Replace the clause with the following content.

[quote]
____
...
The complete representations in basic and extended format for the
beginning of the day and the ending of the day, in accordance with
5.3.1, are as follows:

. Beginning of the day

Basic format::: T000000	(in the format of 5.3.1.2 a))

Extended format::: 00:00:00 (or T00:00:00) 	(in the format of 5.3.1.2 b))

. Ending of the day

Basic format::: the last second of the day (in the format of 5.3.1.2 a)):

**** With no leap second: T235959
**** With a negative leap second: T235958
**** With a positive leap second: T235960

Extended format::: the last second of the day (in the format of 5.3.1.2 b)):

**** With no leap second: 23:59:59 (or T23:59:59)
**** With a negative leap second: 23:59:58 (or T23:59:58)
**** With a positive leap second: 23:59:60 (or T23:59:60)

NOTE: '`T`' is always present in basic format. For extended format,
'`T`' can be omitted for a time-only expression but is included for a
date-and-time expression.

...
____
```

This works in Word:

<img width="541" alt="Screen Shot 2020-12-18 at 1 46 14 AM" src="https://user-images.githubusercontent.com/11865/102523653-d1142400-40d2-11eb-94ce-6d32460becbc.png">

Also in HTML:
<img width="674" alt="Screen Shot 2020-12-18 at 1 46 30 AM" src="https://user-images.githubusercontent.com/11865/102523695-dd987c80-40d2-11eb-9a78-557155ccde62.png">

But broken in PDF:

<img width="544" alt="Screen Shot 2020-12-18 at 1 47 17 AM" src="https://user-images.githubusercontent.com/11865/102523772-f739c400-40d2-11eb-8d51-9db9b51e39a4.png">

The Lists and NOTE formatting are all missing.

**Comment by Intelligent2013** [comment]
After fixing issue https://github.com/metanorma/mn-native-pdf/issues/295 it displays as:

![изображение](https://user-images.githubusercontent.com/5559926/102532175-a024f680-40b4-11eb-8940-6cbbef491165.png)

Resulted PDF: [iso-8601-1-amd.presentation.pdf](https://github.com/metanorma/metanorma-iso/files/5711628/iso-8601-1-amd.presentation.pdf)

But there is a difference between list item numbering rules - in doc and html  default numbering for `ol` is `a)` `b)`... but in PDF is `1.` `2.`.
Should I fix it?

**Comment by Intelligent2013** [comment]
And I don't like a right indent in definition list. Will fix it.

**Comment by Intelligent2013** [comment]
Issue with right indent fixed:
![изображение](https://user-images.githubusercontent.com/5559926/102542767-54c61480-40c3-11eb-809f-47cf249a433f.png)

Resulted PDF:
[iso-8601-1-amd.presentation.pdf](https://github.com/metanorma/metanorma-iso/files/5712084/iso-8601-1-amd.presentation.pdf)

**Comment by ronaldtse** [comment]
Thanks for the fixes!

> But there is a difference between list item numbering rules - in doc and html default numbering for ol is a) b)... but in PDF is 1. 2..
> Should I fix it?

Yes please! This is important indeed.

**Comment by Intelligent2013** [comment]
Done.
Resulted PDF: [iso-8601-1-amd.presentation.pdf](https://github.com/metanorma/metanorma-iso/files/5714187/iso-8601-1-amd.presentation.pdf)

**Comment by ronaldtse** [comment]
@opoudjis could you help incorporate the latest PDF styling? Thanks!
