### ISSUE TITLE
DAmd cover warning showing up as "D stage"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#455]
<img width="588" alt="Screen Shot 2020-12-19 at 7 40 44 PM" src="https://user-images.githubusercontent.com/11865/102688521-27e43f80-4232-11eb-99bb-7e621fcac255.png">

Document: https://github.com/CalConnect/iso-8601-1-amd1

**Comment by ronaldtse** [comment]
Manually fixing this right now.

**Comment by opoudjis** [comment]
Yet again, absolute failure to provide me with proper specs. https://github.com/metanorma/metanorma-iso/issues/383 provided only doc identifiers, it gave no information about status.

**Comment by ronaldtse** [comment]
Part of the implementation process includes discovering gaps. Nothing can be done perfectly in the first go. No point in bickering.

**Comment by opoudjis** [comment]
So, I need a real and explicit spec, PREFERABLY FROM ISO and not reconstructed via Wikipedia, of what the stage names and id names are. In particular, I have assumed that the ID names are stage + doctype, e.g. D + Amd. Is it always the case that the thing after the slash is the full stage name, and e.g. there is no separate D stage?

**Comment by ronaldtse** [comment]
No. There are defined stage names that have nothing to do with doc type. Only some stages have special stage names. I will provide a list, which I’m sure has been provided before.

**Comment by opoudjis** [comment]
The stage name "DAmd" is related to doc type, even if DIS is putatively not, and we no longer are certain whether the stage banner for DIS Cor should be DIS or DIS Cor. Issue on hold pending formal advice.

**Comment by ronaldtse** [comment]
This is being clarified at #456
