### ISSUE TITLE
Clarification of ISO document identifier stage code and draft stage codes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#456]
Sought clarification from ISO regarding the said title. The following information will be clarified.

ISO document identifiers per stage:

Stage code | IS | TR | TS | Amd | Cor
-- | -- | -- | -- | -- | --
00.00-00.99 | PWI | PWI TR | PWI TS | {base}/PWI Amd | {base}/PWI Cor
10.00-10.98 | NP | NP TR | NP TS | {base}/NP Amd | {base}/NP Cor
10.99-10.98 | AWI | AWI TR | AWI TS | {base}/AWI Amd | {base}/AWI Cor
20.00-20.99 | WD | WD TR | WD TS | {base}/WD Amd | {base}/WD Cor
30.00-30.99 | CD | CD TR | CD TS | {base}/CD Amd | {base}/CD Cor
40.00-40.99 | DIS | DTR | DTS | {base}/DAmd | {base}/DIS Cor
50.00-50.99 | FDIS | N/A | N/A | {base}/FDAmd | {base}/FDCor
60.00 | PRF | PRF TR | PRF TS | {base}/PRF Amd | {base}/PRF Cor
60.60 | none | TR | TS | {base}/Amd | {base}/Cor

ISO stage name on draft:

Stage code | IS | TR | TS | Amd | Cor
-- | -- | -- | -- | -- | --
00.00-00.99 | PWI | PWI | PWI | PWI Amd | PWI Cor
10.00-10.98 | NP | NP | NP | NP Amd | NP Cor
10.99-10.98 | AWI | AWI | AWI | AWI Amd | AWI Cor
20.00-20.99 | WD | WD | WD | WD Amd | WD Cor
30.00-30.99 | CD | CD | CD | CD Amd | CD Cor
40.00-40.99 | DIS | DIS | DIS | DAmd | DCor
50.00-50.99 | (pdf) | N/A | N/A | (pdf) | (pdf)
60.00 | (pdf) | (pdf) | (pdf) | (pdf) | (pdf)
60.60 | (pdf) | (pdf) | (pdf) | (pdf) | (pdf)

**Comment by ronaldtse** [comment]
Response from ISO/CS:

From ISO EPM:
> Both sets of names should refer to the same stages.

i.e. Both stage names should be identical.

From ISO TPM:
> TR, TS and PAS don’t have stage 40 and 50. They go through a committee ballot before publication, whereas an IS goes through at least one vote to all members.
> PRF refers to a document that only needs to be proofed, rather than an FDIS (i.e. when it passed DIS with no technical changes).
> Remember that the “reference copy” is always the PDF. That is the document that should be correctly formatted with proper cover pages when it goes for ballot.

So we should standardize on using the PDF stage names for Word + PDF.

Specifically:

Stage code | IS | TR | TS | Amd | Cor
-- | -- | -- | -- | -- | --
00.00-00.99 | PWI | PWI TR | PWI TS | {base}/PWI Amd | {base}/PWI Cor
10.00-10.98 | NP | NP TR | NP TS | {base}/NP Amd | {base}/NP Cor
10.99-10.98 | AWI | AWI TR | AWI TS | {base}/AWI Amd | {base}/AWI Cor
20.00-20.99 | WD | WD TR | WD TS | {base}/WD Amd | {base}/WD Cor
30.00-30.99 | CD | CD TR | CD TS | {base}/CD Amd | {base}/CD Cor
40.00-40.99 | DIS | N/A | N/A | {base}/DAmd | {base}/DIS Cor
50.00-50.99 | FDIS | N/A | N/A | {base}/FDAmd | {base}/FDCor
60.00 (only used if previous stage is DIS) | DIS | PRF (from DIS) | PRF TR | PRF TS | {base}/PRF Amd | N/A
60.60 | no prefix | TR | TS | {base}/Amd | {base}/Cor

Where: N/A => not possible according to ISO Directives Part 1.

**Comment by ronaldtse** [comment]
We need to update the internal map and also metanorma.com documentation.

**Comment by opoudjis** [comment]
Nothing in the foregoing indicates that PRF is not to be used in International Standards.
