### ISSUE TITLE
Table of Contents i18n

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#462]
Follow-on to https://github.com/metanorma/metanorma-iso/issues/300:

For the heading of tables of contents:

@Intelligent2013, please use //localized-strings to look up the localised versions of "CONTENTS" and "Page":

`<localized-string key="table_of_contents" language="fr">SOMMAIRE</localized-string>`
`<localized-string key="locality.page" language="fr">Page</localized-string>`

**Comment by Intelligent2013** [comment]
Done.
@opoudjis  original ISO PDFs contain 'Contents', 'Sommaire', but not 'CONTENTS' 'SOMMAIRE'.

**Comment by opoudjis** [comment]
The Word template also has lowercase. Not sure what happened, but fixing.
