### ISSUE TITLE
When a term SOURCE refers to an ISO/IEC document “clause”, it is not actually a clause and should not have the “Clause” prefix

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iso#471]
*Found while working in https://github.com/metanorma/iso-690/issues/12*

Currently, if a source reference points to a certain clause, the word "Clause" is omitted
and only the clause number is shown.
However, it seems like if the specified clause doesn't contain any dots, the word "Clause" is added.

*Example:*
````
...

=== program

syntactic unit that conforms to the rules of a particular programming
language and that is composed of declarations and statements or
instructions needed to solve a certain function, task, or problem

[.source]
<<ISO2382,clause 2121372>>, Notes to entry and accepted term "`computer program`" have been omitted.

...
````

Renders:
![issue1-doc](https://user-images.githubusercontent.com/33627611/107262895-7f738000-6a17-11eb-9530-7bad1c769a3f.PNG)

*Original source*:
![issue1-pdf](https://user-images.githubusercontent.com/33627611/107262942-8b5f4200-6a17-11eb-91f1-b85112cf4425.PNG)

Is it possible to remove the word "Clause" for cases like this?

**Comment by opoudjis** [comment]
Right, it is inferring that this is a top level clause, and it is applying the syntax correctly; the citation itself is sadly malformed.

And yes: `<<xref,droploc%>>` will give just the number of the locality, without the prefix "Clause": https://www.metanorma.com/author/topics/document-format/text/#general-5

**Comment by ronaldtse** [comment]
> it is applying the syntax correctly; the citation itself is sadly malformed.

What does this mean? 

I wonder if the correct behavior is to have it with “Clause”...

**Comment by ronaldtse** [comment]
I have sought clarification from ISO. Will update.

**Comment by ronaldtse** [comment]
Clarification from ISO/CS:

> For the reference you see in the SOURCE, this is slightly different, as terminological entries are not strictly speaking clauses/subclauses (this is mentioned in DP2, 16.5.3, NOTE); so it is ok to give just the terminological entry number.

i.e. the reference in a SOURCE is a reference to a terminology identifier, not to a clause.

**Comment by opoudjis** [comment]
I mean, I get it, but there is no way in principle for Metanorma to know that this is not a clause, unless we introduce the (rather artificial) `<<ISO2382,location:term 2121372>>`, and tell metanorma-iso not to render "term" in term references. I can do that, but I don't see why I can't just use `<< ISO2382,droploc%clause 2121372>>`.

**Comment by ronaldtse** [comment]
Let's just use `<<ISO2382,droploc%clause 2121372>>` for now, but @manuel489 can you also add this to metanorma.com? Thanks.

**Comment by manuel489** [comment]
Seems like there is an issue with Nick's solution:

This:
````
[.source]
<<ISO2382,droploc%clause 2121372>>, Notes to entry and accepted term "`computer program`" have been omitted.
````

renders

![capture1](https://user-images.githubusercontent.com/33627611/112230560-67dd0900-8c0b-11eb-889f-35c36a186e20.PNG)

**Comment by opoudjis** [comment]
To my embarrassment, the droploc% flags and other flags on xrefs are not being parsed as prefixes on localities. Fixing.

**Comment by opoudjis** [comment]
And need to extent the attributes of `xref` (including droploc) to `origin`. Also need to process those attributes in `origin` and `eref` in isodoc.

**Comment by opoudjis** [comment]
It is working now, but it has required updates in all of metanorma-standoc, isodoc, and metanorma-iso. I'd wait until next release (in a week) before using it.

**Comment by manuel489** [comment]
> Let's just use `<<ISO2382,droploc%clause 2121372>>` for now, but @manuel489 can you also add this to metanorma.com? Thanks.

I have confirmed that is working. So I'll procede to add it to metanorma.com.

**Comment by ronaldtse** [comment]
Thanks @manuel489 !
