### ISSUE TITLE
Investigate compliance with "ISO house style"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#472]
As title.

https://www.iso.org/ISO-house-style.html

Perhaps we need some pointers from Metanorma documentation to the "ISO house style"

cc: @metanorma/editors for thoughts too.

**Comment by opoudjis** [comment]
There are a few additional warnings we could issue on content, e.g. the positioning of "e.g." (Use “e.g.” when giving an example in brackets or at the end of a sentence), but (a) the ISO/IEC DIR 2 complaints on content are noisy enough already, and I don't have much evidence they are being found useful; (b) the style guide ITSELF does not observe those rules, and (c) I've seen little evidence of compliance in past ISO documents. I don't think even more content warnings is a useful thing for us to be doing.

**Comment by ronaldtse** [comment]
I have also received new information with the ISO House Style from ISO/CS:

> The preferred structure of a vocabulary document is to have a parent clause which heading is “Terms and definitions” with subclauses.
> ```
> 3             Terms and definitions
>                3.1         General
>                3.2         Refinery products
> ```
> It is also possible to have separate/distinct clauses provided that the heading starts with “Terms …” with subclauses.
> ``` 
> 3             Terms related to raw pigments
>                3.1         Organic pigments
>                3.2         Mineral pigments
> 4             Terms related to coated pigments
> …
> ```

**Comment by opoudjis** [comment]
> Use “one billion” for “1 000 million”.

Style guide contradicts ISO/IEC DIR 2: 

> Ambiguous terms such as “billion” shall not be used.

**Comment by opoudjis** [comment]
> “…in accordance with IETF RFC 2046.”

@ronaldtse You might want to advise IETF that their rejection of the prefix is news to them.

**Comment by opoudjis** [comment]
List casing check: an all caps acronym (like ISO) is ambiguous as to whether it is lowercase or uppercase.
