### ISSUE TITLE
Support "vocabulary documents" as per ISO house style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#473]
From https://www.iso.org/ISO-house-style.html:

<img width="672" alt="Screenshot 2021-02-13 at 12 47 51 PM" src="https://user-images.githubusercontent.com/11865/107841849-b40d8000-6df9-11eb-8da9-91fcbc8b0869.png">

For example, ISO 34000 (https://github.com/calconnect/iso-34000) is a vocabulary document.

There are the following specific rules for a "vocabulary":

* It can have terminological entries in clauses other than Clause 3. If terminological entries are given in other clauses, use a clause title starting “Terms related to”. Terminological entries are never included in annexes.
* Do not include the first line of the fixed text for Clause 3, i.e. “For the purposes of this document, the following terms and definitions apply.” This is not needed in a vocabulary document because the terminological entries apply to all the documents of the committee.

We need to implement these specifics.

I wonder how one can specify a document being a "vocabulary" via attributes. This is clearly not a "doctype" because a vocabulary could be an IS or a TS, etc. Is a new attribute warranted? Or is this like a subtype?

In ISO DIR 2 there are type "subtypes" specified:

> 11.5.2 Wording
> 
> The terminology used in the titles of documents shall be consistent.
> 
> For documents dealing exclusively with terminology, the following expressions shall be used:
> • “Vocabulary” if both terms and definitions are included, or
> • “List of equivalent terms” if only equivalent terms in different languages are given.
> 
> For documents dealing with test methods, use the form
> “Test method” or “Determination of …”
> instead of expressions such as
> “Method of testing”, “Method for the determination of …”, “Test code for the measurement of …” and “Test on …”.

Maybe there's only "vocabulary" or "test"?

**Comment by opoudjis** [comment]
Doc subtype seems reasonable to me

**Comment by ronaldtse** [comment]
Agree, we should implement the "vocabulary" and "test" types as ISO "doc-subtypes", which are types defined separately from the ISO deliverables (IS, TS, TR etc).

**Comment by ronaldtse** [comment]
This functionality has been also requested by David Leal, convenor of the ISO/TC 184/SC 4's Ad Hoc Group on Ontology.

**Comment by ronaldtse** [comment]
Done, closing.
