### ISSUE TITLE
"ISO Directives Part 1" reference showing as "ISO 1"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#474]
```
The scope of this activity is subject to the governing principles
stated in <<ISODIR1>>.

[bibliography]
== Bibliography

* [[[ISODIR1,ISO Directives Part 1]]]
```

This is rendering as:
<img width="569" alt="Screenshot 2021-02-15 at 6 33 01 PM" src="https://user-images.githubusercontent.com/11865/107935356-4198cd80-6fbc-11eb-8d80-c63386898c5b.png">

**Comment by andrew2net** [comment]
@ronaldtse I think the reference should be `ISO/IEC DIR 1`

**Comment by ronaldtse** [comment]
Thanks @andrew2net . Where can I find that documented?

Also, how do I cite the ISO Consolidated Supplement and the IEC Supplement? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse
These documents are in the `relaton`'s static cache. Possible references:
`ISO/IEC DIR 1 IEC SUP`, `ISO/IEC DIR 1 ISO SUP`, `ISO/IEC DIR 1`, `ISO/IEC DIR 2 IEC`, `ISO/IEC DIR 2 ISO`, `ISO/IEC DIR IEC SUP`, `ISO/IEC DIR JTC 1 SUP`
It isn't documented yet. It seems a good place to document is in the relaton-iso but this gem doesn't support these references. Maybe we can put the documentation into the relaton gem and refer it relaton-iso. What do you think?

**Comment by andrew2net** [comment]
its documented here https://github.com/relaton/relaton-iso#search-for-isoiec-directives
