### ISSUE TITLE
When English and French main title provided but not the other portions, French validation fails

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#475]
In a document with only the main title in English and French, these messages appears:

```adoc
:title-main-en: Letter of Intent: ISO/TC 211 and Ribose
:title-main-fr: Lettre d'intention: ISO/TC 211 et Ribose
```

French validation fails here with these two errors:
```
Style: (XML Line 000001): No French Title Intro!
Style: (XML Line 000001): No French Title Part!
```

But this should not be raised because it's okay to not have those parts, since it's okay for the English too.

**Comment by opoudjis** [comment]
Specified that the title being checked for existence is the title of bibdata, not of a random reference.
