### ISSUE TITLE
Index support needed for ISO, PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#481]
Follow-on from https://github.com/metanorma/metanorma-iso/issues/480

Index support needs to be added to ISO. Same arrangement as for BIPM.

**Comment by Intelligent2013** [comment]
Done.
![изображение](https://user-images.githubusercontent.com/5559926/110162775-3c32e400-7e00-11eb-9596-c7c2d01d44f5.png)

**Comment by Intelligent2013** [comment]
To do: fix issue - instead of section's numbers should be displayed page numbers.
