### ISSUE TITLE
expressir causing GitHub Actions problems for metanorma-iso

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#483]
https://github.com/metanorma/metanorma-iso/pull/482/checks?check_run_id=2039811738

````
LoadError:
828
#   127: The specified procedure could not be found.   - D:/a/metanorma-iso/metanorma-iso/vendor/bundle/ruby/2.6.0/gems/expressir-0.2.15-x64-mingw32/lib/expressir/express_exp/2.6/express_parser.so
829
#   ./vendor/bundle/ruby/2.6.0/gems/expressir-0.2.15-x64-mingw32/lib/expressir/express_exp/parser.rb:3:in `require_relative'
830
````

**Comment by CAMOBAP** [comment]
- https://github.com/lutaml/expressir/issues/63 - root issue

**Comment by ronaldtse** [comment]
lutaml/expressir#63 is fixed and this repo looks like it's running fine now. Closing.

<img width="1214" alt="Screenshot 2021-04-19 at 3 52 35 PM" src="https://user-images.githubusercontent.com/11865/115200862-421e2380-a127-11eb-9095-c74531ef0981.png">
