### ISSUE TITLE
Support Annexes beyond "Z", and support ISO DIR Annex numbering

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#495]
In the ISO DIR Part 1 Annexes extend beyond "Z".
<img width="955" alt="Screenshot 2021-04-19 at 3 28 26 PM" src="https://user-images.githubusercontent.com/11865/115197716-e2724900-a123-11eb-9665-5a343e6ab3ef.png">

"Tables and annexes beginning with “S” in this Consolidated ISO Supplement are all unique to ISO and do not follow the order in the ISO/IEC Directives. Where a reference in an ISO annex (i.e. beginning with “S”) is made to an annex in the ISO/IEC Directives, Part 1, this is explicitly indicated."

Right now after "Z" it will use "]" and "/" symbols to  name the annexes...

This issue probably should be applied to metanorma-standoc; @opoudjis please feel free to move this there if appropriate.

**Comment by ronaldtse** [comment]
From https://github.com/metanorma/mn-samples-iso/pull/70

**Comment by ronaldtse** [comment]
I suppose after "Z" we have "AA" to "ZZ", etc.

**Comment by ronaldtse** [comment]
As suggested by @opoudjis this syntax works:

```adoc
[appendix,number="SA"]
== ISO Code of Conduct
```

All subsequent annexes are followed by "SB", "SC", etc.

**Comment by opoudjis** [comment]
So this issue is only about incrementing Z to AA, not about the specific issue of SA.
