### ISSUE TITLE
Support ISO Directives identifiers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#496]
In https://github.com/metanorma/mn-samples-iso/issues/73 the identifier is showing as "ISO -2".

relaton-iso supports the "ISO/IEC DIR X" identifiers:
https://github.com/relaton/relaton-iso#search-for-isoiec-directives

**Comment by opoudjis** [comment]
The solution is clearly to make this a separate document type, because after all... it is.
