### ISSUE TITLE
ISO Vocabulary document error: Clause 3 and 4 have locations swapped

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#503]
From: https://github.com/metanorma/iso-10303-2/issues/37

This is an ISO Vocabulary document so it allows terms in multiple first level clauses. However the clauses 3 and 4 are swapped.

Clause 3:
```
== Terms, definitions, abbreviated terms and symbols

=== Terms and definitions

==== General

include::030-general.adoc[leveloffset=+2]

==== From STEPmod

// from STEPmod
include::031-stepmod-general.adoc[leveloffset=+2]
```

Clause 4:
```
[heading=terms and definitions]
== STEPmod resource entities

=== General

include::041-stepmod-entities-resources.adoc[leveloffset=+2]
```

Clause 5:
```
[heading=terms and definitions]
== STEPmod module entities

include::05x-stepmod-entities-modules-403.adoc[leveloffset=+1]
```

Main doc:
```
include::sections/01-scope.adoc[]

include::sections/02-normrefs.adoc[]

include::sections/03-terms.adoc[]

include::sections/04-stepmod-resources.adoc[]

include::sections/05-stepmod-modules.adoc[]
```

Result:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/11865/118344570-6a9c1080-b561-11eb-8e8b-c157906e7d45.png">

**Comment by opoudjis** [comment]
Suspect this is a consequence of https://github.com/metanorma/metanorma-iso/issues/504 : Clause 3 was not being recognised as a terms clause, so ISO was publishing the first terms clause it found (4), before any other clauses (including, as it thought, clause 3).

**Comment by opoudjis** [comment]
Confirmed fixed
