### ISSUE TITLE
ISO Vocabulary document: Clause 3 missing 3.1 in TOC

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#504]
<img width="1026" alt="Screenshot 2021-05-15 at 2 39 05 PM" src="https://user-images.githubusercontent.com/11865/118350820-4ead6480-b58b-11eb-87c8-5dc8c7dded6e.png">

**Comment by opoudjis** [comment]
Section 3 was being named as "Terms, definitions, abbreviated terms and symbols" instead of the correct "Terms, definitions, symbols and abbreviated terms": it was not being recognised as a terms section, and that has had a flow-on effect in the tagging of child headings. Fixing that fixes this.
