### ISSUE TITLE
Quote unable to enter reference

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#507]
From David Leal.

In Clause 3:

```adoc
[NOTE]
====
<<IEC81346-1>> defines the term *component* as follows:

[quote, ISO/IEC, "IEC81346-1,clause=3.7"]
____
product used as a component in an assembled product, system or plant.
____
====
```

In references:

```adoc
[bibliography]
== Bibliography

* [[[IEC81346-1,IEC 81346-1]]]
```

This works!

=>
<img width="547" alt="Screenshot 2021-06-10 at 6 21 22 PM" src="https://user-images.githubusercontent.com/11865/121508874-acad5a80-ca18-11eb-8e48-3b524ded881f.png">

I've also tried:

```adoc
[NOTE]
====
<<IEC81346-1>> defines the term *component* as follows:

[quote, ISO/IEC, <<IEC81346-1,clause=3.7>>]
____
product used as a component in an assembled product, system or plant.
____
====
```

Error:
```
Metanorma XML Syntax: (XML Line 000748:65): IDREF "<<IEC81346-1" without matching ID
```

=>
<img width="539" alt="Screenshot 2021-06-10 at 6 22 48 PM" src="https://user-images.githubusercontent.com/11865/121509088-e0888000-ca18-11eb-8cf9-0c54c3a5a8e6.png">

Also:

```adoc
[NOTE]
====
<<IEC81346-1>> defines the term *component* as follows:

[quote, <<IEC81346-1,clause=3.7>>]
____
product used as a component in an assembled product, system or plant.
____
====
```

=> 
<img width="805" alt="Screenshot 2021-06-10 at 6 18 37 PM" src="https://user-images.githubusercontent.com/11865/121508548-4cb6b400-ca18-11eb-942c-ce3b6a8bbcd1.png">

**Comment by ronaldtse** [comment]
I was confused about the question -- it wasn't about this, David had it correct.

However this is really confusing for me, that we have to double quote the anchor+clause.

This should really be documented on metanorma.org for people who wish to use quotes.

cc @metanorma/writers

**Comment by opoudjis** [comment]
You only have to double quote it as an attribute because it contains a comma, and that's a general asciidoc thing...
