### ISSUE TITLE
Fix font style for ISO copyright section

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#510]
<img width="668" alt="Screenshot 2021-06-11 at 11 11 55 PM" src="https://user-images.githubusercontent.com/11865/121708711-6df7cd00-cb0a-11eb-8b44-4abae7504fe8.png">

The highlighted portion is in Times New Roman. ISO uses Cambria.

**Comment by ronaldtse** [comment]
This can be fixed using with #511 .

**Comment by opoudjis** [comment]
Has indeed been so fixed.

<img width="797" alt="Στιγμιότυπο 2021-06-15, 17 02 41" src="https://user-images.githubusercontent.com/1911039/122007783-a98ce280-cdfb-11eb-8c58-9031d484c9de.png">
