### ISSUE TITLE
PDF: SVG and PNG inclusions look awkward

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#522]
https://github.com/metanorma/annotated-express-report

See report-part-2.

Original images:
[images.zip](https://github.com/metanorma/metanorma-iso/files/6839445/images.zip)

When I use SVG, the PDF renders like this:

<img width="556" alt="Screenshot 2021-07-19 at 4 52 22 PM" src="https://user-images.githubusercontent.com/11865/126133711-feaab6e0-0727-4022-a05a-f1ba05b72399.png">

When I use PNG, the PDF rendered image exceeds boundaries, see the overlap with caption.

<img width="632" alt="Screenshot 2021-07-19 at 4 54 33 PM" src="https://user-images.githubusercontent.com/11865/126133752-44dcfa8a-6ecc-4679-a230-bdd8fce0cac6.png">

**Comment by Intelligent2013** [comment]
SVG image - there aren't the attribute `width` and `height` in `svg` element:
```xml
<svg xmlns:lucid="lucid" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 720 1049.8" style="enable-background:new 0 0 720 1049.8;" xml:space="preserve">
```
To do: in xslt on-fly add them from `viewBox`:
```xml
<svg xmlns:lucid="lucid" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" height="1050" width="720" viewBox="0 0 720 1049.8" style="enable-background:new 0 0 720 1049.8;" xml:space="preserve">
```
Resulted PDF will be rendered so:
![image](https://user-images.githubusercontent.com/5559926/126143895-0878bfbc-0cce-4b49-81de-691e7dd54f14.png)

**Comment by ronaldtse** [comment]
For the record, this SVG is generated from LucidChart. Safari seems to handle it properly with text shown.

**Comment by Intelligent2013** [comment]
PNG image - Apache FOP doesn't calculate correct height for image with following keep-with-next title. 
To do: calculate scale factor by image's width, height and dpi via xslt on-fly.

**Comment by Intelligent2013** [comment]
> 
> 
> For the record, this SVG is generated from LucidChart. Safari seems to handle it properly with text shown.

@ronaldtse in Firefox and IE it shows without text:
![image](https://user-images.githubusercontent.com/5559926/126201934-dd25eab4-aa03-482c-9c0d-5ce599315f38.png)

And in .svg file there isn't no one element `text`.

**Comment by ronaldtse** [comment]
I must have sent you the wrong file. Let me re-do this.

**Comment by ronaldtse** [comment]
The fixed images. [images.zip](https://github.com/metanorma/metanorma-iso/files/6842894/images.zip)

**Comment by Intelligent2013** [comment]
Issue fixed (mn2pdf and common xslt updated):
PNG:
![image](https://user-images.githubusercontent.com/5559926/126211456-d6bedcca-ac2d-4f86-8a14-5246b20d9d6f.png)

SVG:
![image](https://user-images.githubusercontent.com/5559926/126211522-94dab2c9-2c06-420e-9676-40f0f3b8b8fa.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
