### ISSUE TITLE
Support hierarchical numbering of terminology entries according to ISO 10241-1

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#525]
The relevant section from ISO 10241-1:

<img width="798" alt="Screenshot 2021-08-09 at 9 41 17 PM" src="https://user-images.githubusercontent.com/11865/128715755-31cbbd8f-bc05-467e-9a23-8e2231a04561.png">

The hierarchical numbering scheme is shown in EXAMPLE 1, where a "lower-level" concept can be numbered under a "higher-level" concept.

ISO 56000 provides an example of such in 3.1.1 vs 3.1.1.1 and 3.1.1.2:
https://www.iso.org/obp/ui#iso:std:iso:56000:ed-1:v1:en

We will need to come up with a syntax that supports this encoding and also a mechanism to render this.

And a friendly reminder from ISO DIR 2:
> "the Terms and definitions clause consists of a list of terminological entries and not subclauses."

That's why IEV documents contain terms that are identified with IEV IDs, not clause numbers. And eventually that's why arbitrary IDs of terms should be supported.

_Originally posted by @ronaldtse in https://github.com/metanorma/mnconvert/issues/50#issuecomment-895234091_

**Comment by opoudjis** [comment]
@Intelligent2013 FYI: `term` can now contain nested `term` in XML.
