### ISSUE TITLE
PDF: Legacy ISO documents with "Terms and definitions" not at clause 3 break layouts

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#531]
ISO TC 211 documents traditionally had "Terms and definitions" at Clause 4, where Clause 3 is "Conformance". (This is similar to old OGC practice.

In https://github.com/metanorma/iso-19135 (see `sources/iso-19135-1-2015`) we see the following problems.

## PDF

1. (PDF) The TOC has 3 and 4 reversed in order
<img width="567" alt="Screenshot 2021-09-24 at 9 21 43 AM" src="https://user-images.githubusercontent.com/11865/134604082-535b8350-2b52-49ce-8c30-e646f9a3ebe5.png">

2. (PDF) The content has 3 and 4 reversed in order
<img width="578" alt="Screenshot 2021-09-24 at 9 22 13 AM" src="https://user-images.githubusercontent.com/11865/134604106-f154aad1-f22a-4ddc-8352-0ccc29080a90.png">

...

<img width="568" alt="Screenshot 2021-09-24 at 9 22 33 AM" src="https://user-images.githubusercontent.com/11865/134604136-6d4bb4a5-eaf6-4e56-8727-31c9f2d309c6.png">

## HTML

In HTML the TOC order and content order are both correct.

<img width="276" alt="Screenshot 2021-09-24 at 9 27 38 AM" src="https://user-images.githubusercontent.com/11865/134604556-29df47e1-3c21-4b92-ad12-310630ad3655.png">
 
<img width="862" alt="image" src="https://user-images.githubusercontent.com/11865/134604626-2495852f-b230-465a-9ec0-797db5fb8bb4.png">

**Comment by Intelligent2013** [comment]
Currently xslt displays sections in this order:
- `clause[@type='scope']`
- `references[@normative='true']`
- `terms or clause[terms] or definitions or clause[definitions]`
- another `clause`s

But in metanorma xml there is the attribute `displayorder` and it seems I have to use it:
```xml
<sections>

<clause id="cls-2" type="scope" inline-header="false" obligation="normative" displayorder="3">
			<title depth="1">1<tab/>Scope</title>
<clause id="_conformance" inline-header="false" obligation="normative" displayorder="5">
			<title depth="1">3<tab/>Conformance</title>
<clause id="cls-4" obligation="normative" displayorder="6">
			<title depth="1">4<tab/>Terms and definitions</title>
...
</sections>
<bibliography>
		<references id="cls-3" normative="true" obligation="informative" displayorder="4">
			<title depth="1">2<tab/>Normative references</title>
...

**Comment by Intelligent2013** [comment]
Issue fixed:
![image](https://user-images.githubusercontent.com/5559926/134678947-dee308d5-fa7f-4c45-9734-cd75093b2d3b.png)
...
![image](https://user-images.githubusercontent.com/5559926/134678992-dfc699d9-89b4-4ddf-853d-7931e530717d.png)
...
![image](https://user-images.githubusercontent.com/5559926/134679023-07243da6-a460-47f7-aff1-0083ea9ce942.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
