### ISSUE TITLE
Inconsistent syntax for replacing boilerplate with `[.boilerplate]` vs `[NOTE,type=boilerplate]`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#532]
The syntax for replacing boilerplate differs in different places:
* `[NOTE,type=boilerplate]` in Normative references
* `[.boilerplate]` in Terms and definitions

From @manuel489:
> maybe there is a reason for this. I think it's better to consult @opoudjis 😃

_Originally posted by @manuel489 in https://github.com/metanorma/mn-samples-bsi/issues/64#issuecomment-937939440_

**Comment by ronaldtse** [comment]
I finally understood your proposal after a year. Why do we need to make it a Note? The boilerplate isn't really a note.

I think what you mean is that Asciidoctor cannot accept a paragraph tagged with `[.boilerplate]`?

**Comment by opoudjis** [comment]
> I think what you mean is that Asciidoctor cannot accept a paragraph tagged with [.boilerplate]?

We cannot do a clause tagged `[boilerplate]`, because of how bibliography nesting works. We can do paragraphs tagged boilerplate, but you would need to do that to multiple paragraphs in a row. A note, or at least open block tagged [.boilerplate] is far simpler.

**Comment by opoudjis** [comment]
open block
