### ISSUE TITLE
Support `obsoletes` attribute in ISO flavor (ISOSTS compatibility) 

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iso#534]
*In relation to https://github.com/metanorma/mn-samples-bsi/pull/65*

We are in the need of extending the support of `:obsoletes:` attribute to ISO flavor.

**Comment by ronaldtse** [comment]
Because ISOSTS supports this:

```xml
<std-xref type="revises"> 
   <std-ref>ISO/TR 8888:2222</std-ref> 
 </std-xref> 
 <std-xref type="revises"> 
   <std-ref>ISO 9999:1111</std-ref> 
 </std-xref> 
```

Possibly there is a dictionary for these `<std-xref>` relationship values.

**Comment by opoudjis** [comment]
That's... huge.

**Comment by opoudjis** [comment]
So... you want me to support ALL of these for ISO?

**Comment by opoudjis** [comment]
From https://github.com/metanorma/mn-samples-bsi/issues/8:

* `revises`: `relation/@type` = `relation/@type` = `updates`, `relation/description` = `revises`
* `replaces`: `relation/@type` = `relation/@type` = `obsoletes`, `relation/description` = `replaces`
* `amends:` `relation/@type` = `relation/@type` = `updates`, `relation/description` = `amends`
* `corrects:` `relation/@type` = `relation/@type` = `updates`, `relation/description` = `corrects`
* `informativelyReferencedBy`: `relation/@type` = `isCitedIn`, `relation/description` = `is informatively cited in`
* `informativelyReferences`: `relation/@type` = `cites`, `relation/description` = `informatively cites`
* `normativelyReferencedBy`: `relation/@type` = `isCitedIn`, `relation/description` = `is normatively cited in`
* `normativelyReferences`: `relation/@type` = `cites`, `relation/description` = `normatively cites`
* `isIdenticalNationalStandardOf`: `relation/@type` = `adoptedForm`, `relation/description` = `identical`
* `isModifiedNationalStandardOf`: `relation/@type` =  `adoptedForm`, `relation/description` = `modified`
* `isProgressionOf`: `relation/@type` = `successorOf`
* `isPublishedFormatOf`: `relation/@type` = `manifestationOf`
* `relatedDirective`: `relation/@type` = `related`, `relation/bibitem/ext/doctype` = `directive`, `relation/description` = `related directive` (for round-tripping)
* `relatedMandate`: `relation/@type` = `related`, `relation/bibitem/ext/doctype` = `mandate`, `relation/description` = `related mandate` (for round-tripping)
* `supersedes`: `relation/@type` = `obsoletes`, `relation/description` = `supersedes`
* `""` (empty value): `relation/@type` = `related`

These also need to be carried across to asciidoc. Will document.

**Comment by opoudjis** [comment]
Descriptions of relations, if entered in asciidoc, need to be normalised not like types (`informatively-cited-in` => `informatively-citedIn`), but as prose (`informatively-cited-in` => `informatively cited in`)

**Comment by opoudjis** [comment]
* `revises`: STS `revises`: `relation/@type` = `relation/@type` = `updates`, `relation/description` = `revises`
* `replaces`: STS `replaces`: `relation/@type` = `relation/@type` = `obsoletes`, `relation/description` = `replaces`
* `amends`: STS `amends:` `relation/@type` = `relation/@type` = `updates`, `relation/description` = `amends`
* `corrects`: STS `corrects:` `relation/@type` = `relation/@type` = `updates`, `relation/description` = `corrects`
* `informatively-cited-in` : STS `informativelyReferencedBy`: `relation/@type` = `isCitedIn`, `relation/description` = `informatively cited in`
* `informatively-cites`: STS `informativelyReferences`: `relation/@type` = `cites`, `relation/description` = `informatively cites`
* `normatively-cited-in`: STS `normativelyReferencedBy`: `relation/@type` = `isCitedIn`, `relation/description` = `normatively cited in`
* `normatively-cites`: STS `normativelyReferences`: `relation/@type` = `cites`, `relation/description` = `normatively cites`
* `identical-adopted-from`: STS `isIdenticalNationalStandardOf`: `relation/@type` = `adoptedFrom`, `relation/description` = `identical adopted from`
* `modified-adopted-from`: STS `isModifiedNationalStandardOf`: `relation/@type` =  `adoptedFrom`, `relation/description` = `modified adopted from`
* `successor-of`: STS `isProgressionOf`: `relation/@type` = `successorOf`
* `manifestation-of`: STS `isPublishedFormatOf`: `relation/@type` = `manifestationOf`
* `related-directive`: STS `relatedDirective`: `relation/@type` = `related`, `relation/bibitem/ext/doctype` = `directive`, `relation/description` = `related directive` (for round-tripping)
* `related-mandate`: STS `relatedMandate`: `relation/@type` = `related`, `relation/bibitem/ext/doctype` = `mandate`, `relation/description` = `related mandate` (for round-tripping)
* `supersedes`: STS  `supersedes`: `relation/@type` = `obsoletes`, `relation/description` = `supersedes`
* `related` (empty value):  STS  `""` (empty value): `relation/@type` = `related`

**Comment by ronaldtse** [comment]
@opoudjis using `relation/description` will cause a challenge for round tripping. Things like `related-mandate` and `related-directive` express not only the notion of `related` but also the type of the cited item. Can we have a second thought here?
