### ISSUE TITLE
Very slow processing of ISO 10303-2 to HTML and Word

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#545]
Takes crazy long time to compile.

Document at https://github.com/metanorma/iso-10303-2

XML files available at https://github.com/metanorma/iso-10303-2/issues/65

**Comment by opoudjis** [comment]
Profiling of combined XML and ISO processing of this file:

145 mins total, 2h25

* 80 min was spent on Asciidoc processing, 65 min was spent on XML processing
* 39 min, was fetching bibliographic references. This is meant to go away with local caching, but the local caches need a lot of updating as the processing changes.
  * Of that, 26 min was RelatoinIso::IsoBibliography::isobib_results_filter (screen scraping), and 12 min was RelatoinIso::IsoBibliography::isobib_search_filter
* 38 min was spent on Asciidoc XML post processing. 37 min of that was spent on smartquotes cleanup, and almost all of that on `uninterrupted_quotes_around_xml` (which moves commas inside tags, to prevent bad rendering later); that was a recent addition. All the time is spent on the searching and not the manipulation: it is a complex search expression.

The main thing to do then is to change the XML Path in `uninterrupted_quotes_around_xml`, to make it based on Nokogiri `traverse` instead. (This is already done for smart quotes, and is much more efficient than text search in XPath.)

Any optimisation of Relaton is welcome.

**Comment by opoudjis** [comment]
Profiling of combined XML and ISO processing of this file:

105 mins, 1h45

* 80 > 36 min was spent on Asciidoc processing, 65 > 33 min was spent on XML processing
* Of the 33 min, 18 min was spent on PDF, 27 > 10 min on Word, 16 > 2 min on HTML, 1.5 min on STS

**Comment by opoudjis** [comment]
Have reduced Word (in ISO) down to 4.5 min.

**Comment by opoudjis** [comment]
Add processing to run Word, HTML, PDF, STS etc simultaneously through threading

**Comment by opoudjis** [comment]
Will do that in https://github.com/metanorma/metanorma/issues/220
