### ISSUE TITLE
PDF: rendering of grammatical properties incorrect

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#550]
Source:

```adoc
==== register

[%metadata]
grammar::
isNoun::: true

set of files containing {{identifier,identifiers}} assigned to items with
descriptions of the associated items

NOTE: The use of the verb form "register" is discouraged when used in
conjunction with the noun form "register" to prevent confusion.
```

Rendered:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/11865/142370088-6f26230b-e1ce-4da8-98e2-169a0524a193.png">

Correct rendering from ISO 10241-1:
<img width="549" alt="Screenshot 2021-11-18 at 3 20 39 PM" src="https://user-images.githubusercontent.com/11865/142370211-8e05a61b-0776-482e-885d-11c68c54be35.png">

**Comment by Intelligent2013** [comment]
Issue in the presentation xml:
```xml
<term id="term-register">
	<name>3.1.10</name>
	<preferred>register n</preferred>
	<definition>
```

Semantic xml looks ok:
```xml
<term id="term-register">
	<preferred>
		<expression>
			<name>register</name>
			<grammar>
				<isNoun>true</isNoun>
			</grammar>
		</expression>
	</preferred>
	<definition>
```

I'll raise a ticket in metanorma-iso.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/143873909-4de1345b-6b67-40b0-88b5-4833050910e6.png)
