### ISSUE TITLE
PDF: rendering of domain not always correct

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#551]
## Example 1

```adoc
==== invalidation
alt:[deprecation]
domain:[register]

action taken to mark as invalid or remove a substantive error in a
{{register item}}
```

Missing an empty line before domain/definition:

<img width="820" alt="Screenshot 2021-11-18 at 3 21 33 PM" src="https://user-images.githubusercontent.com/11865/142370346-1e8a5ec7-4730-4d37-983d-39aa63650dba.png">

## Example 2

```adoc
==== identifier
domain:[register]

linguistically independent sequence of characters capable of uniquely and
permanently identifying a {{register item}}
```

Domain is not rendered right in front of the definition.

<img width="838" alt="Screenshot 2021-11-18 at 3 23 14 PM" src="https://user-images.githubusercontent.com/11865/142370545-b31266c7-1b25-4d4b-8264-0ee24cade528.png">

## Correct rendering from ISO 10241-1
<img width="553" alt="Screenshot 2021-11-18 at 3 23 37 PM" src="https://user-images.githubusercontent.com/11865/142370584-e61ddd0d-834a-4db6-9817-6d6779533e63.png">

**Comment by Intelligent2013** [comment]
> 
> ## Example 1
> . . .
> Missing an empty line before domain/definition:
> 
> <img alt="Screenshot 2021-11-18 at 3 21 33 PM" width="820" src="https://user-images.githubusercontent.com/11865/142370346-1e8a5ec7-4730-4d37-983d-39aa63650dba.png">


@ronaldtse sorry, I don't see a difference between 3.1.7 rendering and 
![image](https://user-images.githubusercontent.com/5559926/142400501-fc835416-ebd7-4786-a1de-e215623fe6c7.png)


> ## Example 2
> 
> ```
> ==== identifier
> domain:[register]
> 
> linguistically independent sequence of characters capable of uniquely and
> permanently identifying a {{register item}}
> ```
> 
> Domain is not rendered right in front of the definition.
> 
> <img alt="Screenshot 2021-11-18 at 3 23 14 PM" width="838" src="https://user-images.githubusercontent.com/11865/142370545-b31266c7-1b25-4d4b-8264-0ee24cade528.png">

The reason of issue in an empty `p`:
```xml
<term id="term-identifier"><name>3.1.6</name><preferred>identifier</preferred><domain>register</domain><definition><p id="_60af303e-6bdf-53ba-37d2-e0888cdf5614">

</p><p id="_9fc8de8b-4b01-c191-d0c1-23f0e53a5ea7">linguistically independent sequence of characters capable of uniquely and
permanently identifying a register item</p></definition>
</term>
```

I'll add the ticket.

**Comment by ronaldtse** [comment]
The document is:
https://github.com/metanorma/iso-19135/blob/master/sources/iso-19135-2021/document.adoc

**Comment by ronaldtse** [comment]
Not fixed.

**Comment by ronaldtse** [comment]
Confirm fixed: <img width="576" alt="Screenshot 2021-11-29 at 9 56 11 AM" src="https://user-images.githubusercontent.com/11865/143797187-00a2a216-0bd6-4ff8-a261-fcc91fe8e569.png">
