### ISSUE TITLE
Grammatical properties in presentation xml

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#554]
Source: https://github.com/metanorma/metanorma-iso/issues/550

The document: https://github.com/metanorma/iso-19135/tree/master/sources/iso-19135-1-2021

03-terms.adoc:
```adoc
==== register

[%metadata]
grammar::
isNoun::: true

set of files containing {{identifier,identifiers}} assigned to items with
descriptions of the associated items
```

The presentation xml contains `n` at the end of preferred:
```xml
<term id="term-register">
	<name>3.1.10</name>
	<preferred>register n</preferred>
	<definition>
```

Should I process `n` as indication for `noun` or is it a bug?

Semantic xml is ok:
```xml
<term id="term-register">
	<preferred>
		<expression>
			<name>register</name>
			<grammar>
				<isNoun>true</isNoun>
			</grammar>
		</expression>
	</preferred>
	<definition>
```

**Comment by ronaldtse** [comment]
Bug indeed. Thanks for investigating.

**Comment by Intelligent2013** [comment]
Additional issues:

- terms in languages 'eng' and 'fra':
adoc:
```adoc
=== jetty

[%metadata]
language:: eng

preferred:[pier]

[%metadata]
language:: fra

deck structure supported by vertical and possibly inclined piles extending into the sea, frequently in a
direction normal to the coastline
```

Presentation xml contains only 'eng' (due two terms in the one element?):
```xml
<term id="term-jetty">
	<name>4.9</name>
	<preferred language="eng">jetty; pier</preferred>
	<definition>
		<p id="_">deck structure supported by vertical and possibly inclined piles extending into the sea, frequently in a
direction normal to the coastline</p>
	</definition>
</term>
```

- pronunciation
```adoc
=== disturbance

[%metadata]
pronunciation:: dıˈstɜ:bəns

any event or series of events that disrupt ecosystem, community, or population structure and alters the
physical environment
```

no info for pronunciation  in the metanorma xml:
```xml
<term id="term-disturbance">
	<name>4.10</name>
	<preferred>disturbance</preferred>
	<definition>
		<p id="_">any event or series of events that disrupt ecosystem, community, or population structure and alters the
physical environment</p>
	</definition>
</term>
```

**Comment by opoudjis** [comment]
> Should I process n as indication for noun or is it a bug?

Let's not call it a bug, let's call it a different convention to what ISO 10241-1 A.1.3.2.4 recommends. Fixing.

**Comment by opoudjis** [comment]
Oversight in model: we will also need to add sg/pl to model. (And dual: we need number as a category.)

**Comment by opoudjis** [comment]
There is another issue: the grammatical information in presentation XML needs to be not boldfaced. @Intelligent2013 I will explicitly introduce boldfaced rendering of terms, so that it excludes grammatical information; you will likewise need to ensure that preferred, admitted, deprecated are not by default boldface.

**Comment by opoudjis** [comment]
And grammatical information is delimited from designation by comma.

**Comment by opoudjis** [comment]
> Presentation xml contains only 'eng' (due two terms in the one element?):

The Presentation XML is conflating preferred terms for rendering; it must not if they are in different languages.

**Comment by opoudjis** [comment]
Adding language, script, country code, pronunciation to designation rendering in Presentation XML.

**Comment by opoudjis** [comment]
And only merging preferred terms if they don't have grammar information, have identical geographic info or language, and don't have pronunciations.
