### ISSUE TITLE
Empty paragraph in definition causing broken "domain" rendering in Metanorma-ISO 

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#555]
Source: https://github.com/metanorma/metanorma-iso/issues/551

Both presentation and semantic xml contains empty `p` _sometimes_ and there is `domain` term:
```xml
<term id="term-identifier"><name>3.1.6</name><preferred>identifier</preferred><domain>register</domain><definition><p id="_60af303e-6bdf-53ba-37d2-e0888cdf5614">

</p><p id="_9fc8de8b-4b01-c191-d0c1-23f0e53a5ea7">linguistically independent sequence of characters capable of uniquely and
permanently identifying a register item</p></definition>
</term>
```
```xml
<term id="term-identifier"><preferred><expression><name>identifier</name></expression></preferred><domain>register</domain><definition><verbaldefinition><p id="_60af303e-6bdf-53ba-37d2-e0888cdf5614">

</p><p id="_9fc8de8b-4b01-c191-d0c1-23f0e53a5ea7">linguistically independent sequence of characters capable of uniquely and
permanently identifying a <concept><refterm>register item</refterm><renderterm>register item</renderterm><xref target="term-register-item"/></concept></p></verbaldefinition></definition>
</term>
```

If there are both 'domain' and  'admitted' term, then there isn't empty `p`:
```xml
<term id="term-invalidation"><name>3.1.7</name><preferred>invalidation</preferred><admitted>deprecation</admitted>

<domain>register</domain><definition><p id="_ed6b680d-e267-000c-f725-d49410882216">action taken to mark as invalid or remove a substantive error in a
register item</p></definition></term>
```

**Comment by ronaldtse** [comment]
I'm not sure if this is "really done".

It seems that all the definitions are gone?
<img width="736" alt="Screenshot 2021-11-29 at 2 10 00 AM" src="https://user-images.githubusercontent.com/11865/143780409-dedbe399-0d45-4b33-bd77-98bee309fd94.png">

**Comment by ronaldtse** [comment]
PDF is also completely broken. This is clearly a bug.

<img width="540" alt="Screenshot 2021-11-29 at 2 11 36 AM" src="https://user-images.githubusercontent.com/11865/143780464-155d64c8-bf85-4a07-9a3c-ad57d7335c6d.png">

**Comment by ronaldtse** [comment]
@opoudjis the document is:
https://github.com/metanorma/iso-19135/blob/master/sources/iso-19135-2021/document.adoc

**Comment by opoudjis** [comment]
Works fine for me
<img width="780" alt="Στιγμιότυπο 2021-11-29, 12 21 56" src="https://user-images.githubusercontent.com/1911039/143795074-581dfb5f-d092-4ac2-b042-9637fadf77ef.png">

**Comment by ronaldtse** [comment]
Confirm fixed with using git gems from isodoc, metanorma-standoc and metanorma-iso.

**Comment by ronaldtse** [comment]
PDF confirm fixed:
<img width="580" alt="Screenshot 2021-11-29 at 9 55 44 AM" src="https://user-images.githubusercontent.com/11865/143797128-74917ebe-fdac-44e7-a1dc-1b56460049ae.png">
