### ISSUE TITLE
Explicit boldface in preferred

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#559]
Because of https://github.com/metanorma/metanorma-iso/issues/554, `preferred` is no longer to be rendered as boldface by default: the designation within the preferred term in the Presentation XML is indicated to be boldface explicitly:

`<preferred><strong>человек</strong>, ед.</preferred>`

If the PDF XSLT does assume that the contents of preferred are all boldface, please remove that assumption.

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/143680012-f7f6e570-c29c-4ca9-bb29-5fd08776f89e.png)
