### ISSUE TITLE
HTML: make TOC second-level collapsable

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#561]
From https://github.com/metanorma/iso-10303-2/issues/79

> Right now the TOC second level is not collapsable. In Clause 4 and 5, the numerous entries make navigation difficult.
> 
> WG 12 has requested to make the TOC second-level collapsable before this can be circulated for CD.
> 
> This task is to implement this functionality.
> 
> <img alt="Screenshot 2021-11-29 at 11 23 55 AM" width="283" src="https://user-images.githubusercontent.com/11865/143803875-6e85b630-c73e-48ff-922f-b27ea9b88931.png">

This has been done as an example in https://github.com/metanorma/temp-iso-10303-2-toc

@s4birli can you please help explain the necessary snippets to update?
* JS
* HTML / structure

**Comment by ronaldtse** [comment]
@opoudjis you might have to separate the HTML / Word HTML if they are using the same TOC layout. Hopefully they aren't (because that would be weird anyway).

**Comment by s4birli** [comment]
First I changed the li element with h1 class into the elements with original content and collapse button.
        <li class="h1">
              <div class="collapse-group">
                 <a href="#toc8"> 4&#xA0; ISO 10303 resource entities</a>  //original content
                 <div class="collapse-button"></div>   //collapse button
               </div> 
         </li>
And then grouped the li elements with h2 under the ul to collapse/expand when clicking the collapse button.
         <ul class="content collapse">
                                                        <li class="h2"><a href="#toc9"> 4.1&#xA0;
                                                                        annotation_occurrence_associativity</a></li>
                                                        <li class="h2"><a href="#toc10"> 4.2&#xA0;
                                                                        dimension_text_associativity</a></li>
                                                        <li class="h2"><a href="#toc11"> 4.3&#xA0;
                                                                        shape_aspect_associativity</a></li>
            </ul>
  And finally I added the javascript function regarding the collapse-button action.
            $(".collapse-button").click(function () {
                        $(this).toggleClass('expand'); // expand: the class to change the collapse button shape
                        $(this).closest('li').children(".content").toggleClass('collapse'); // collapse: the class to collapse/expand the li 
                                                                                                                                             elements with the h2 class
             })

**Comment by opoudjis** [comment]
Arrows are as on https://github.com/metanorma/temp-iso-10303-2-toc . Confirmed, sent to Ronald.
