### ISSUE TITLE
Investigate styling differences between ISO draft and DIS in Word

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#568]

**Comment by opoudjis** [comment]
This will take at least 3 weeks.

Attaching massaged stylesheets before and after, to show the magnitude of what needs to be done. There are dozens of new styles absent in the default template (at inline as well as block level), and lots of discrepancies in spacing, and all these would need to be addressed manually. Having to rename styles depending on the document stage is going to be very difficult to craft and maintain.

[Αρχειοθήκη.zip](https://github.com/metanorma/metanorma-iso/files/7773933/default.zip)

**Comment by ronaldtse** [comment]
## Cover page content

zzCover
<img width="1074" alt="Screenshot 2022-05-02 at 1 20 18 PM" src="https://user-images.githubusercontent.com/11865/166187768-d1cc08db-5c48-4748-ab48-f2a479d4b4df.png">

## Copyright statement

"ISO"
<img width="1075" alt="Screenshot 2022-05-02 at 1 20 38 PM" src="https://user-images.githubusercontent.com/11865/166187786-190aea64-7190-4ec9-983b-c70743ec4250.png">

"2022"
<img width="1076" alt="Screenshot 2022-05-02 at 1 20 57 PM" src="https://user-images.githubusercontent.com/11865/166187803-b2776db4-5d41-44c9-b778-583a4669553f.png">

Content shifted to left:
<img width="1069" alt="Screenshot 2022-05-02 at 1 21 26 PM" src="https://user-images.githubusercontent.com/11865/166187839-222ebcfc-0f6f-452e-ad0f-02ab224fbbce.png">

Content without shift (Address):
<img width="1072" alt="Screenshot 2022-05-02 at 1 21 51 PM" src="https://user-images.githubusercontent.com/11865/166187863-9611e376-5cb5-4ea6-838a-6e32e66ff0c7.png">

## TOC

Heading
<img width="1077" alt="Screenshot 2022-05-02 at 1 22 06 PM" src="https://user-images.githubusercontent.com/11865/166187879-48d0b94a-c134-418d-a645-9abae54c2558.png">

TOC 1
<img width="1076" alt="Screenshot 2022-05-02 at 1 22 25 PM" src="https://user-images.githubusercontent.com/11865/166187900-0ee3c9ca-16ed-4bc1-bbaa-9a73955e6bd9.png">

TOC 2
<img width="1073" alt="Screenshot 2022-05-02 at 1 22 49 PM" src="https://user-images.githubusercontent.com/11865/166187940-ffd07c68-5dda-4212-811b-76f5801a72c8.png">

TOC 3
<img width="1072" alt="Screenshot 2022-05-02 at 1 23 01 PM" src="https://user-images.githubusercontent.com/11865/166187956-d94490e1-e6d3-41a3-b86c-e50822d5fd35.png">

## Foreword

Foreword title
<img width="1071" alt="Screenshot 2022-05-02 at 1 23 19 PM" src="https://user-images.githubusercontent.com/11865/166187979-dac1f723-dfcc-43cd-869b-bcb23c4df25b.png">

Foreword text
<img width="1074" alt="Screenshot 2022-05-02 at 1 23 44 PM" src="https://user-images.githubusercontent.com/11865/166188026-2e37d9de-8163-47c9-9239-48585429aff8.png">

Hyperlink
<img width="1073" alt="Screenshot 2022-05-02 at 1 23 59 PM" src="https://user-images.githubusercontent.com/11865/166188052-07df7dea-6959-40c4-83dd-d0cd18b2417d.png">

List continue 1
<img width="1076" alt="Screenshot 2022-05-02 at 1 24 14 PM" src="https://user-images.githubusercontent.com/11865/166188068-9ba6a25b-a22b-45a9-abe8-6821331000b1.png">

Italics
<img width="1075" alt="Screenshot 2022-05-02 at 1 24 33 PM" src="https://user-images.githubusercontent.com/11865/166188092-920e1e3b-325e-44ea-a8fe-08bca00c69f7.png">

## Introduction

Introduction Title
<img width="1074" alt="Screenshot 2022-05-02 at 1 24 51 PM" src="https://user-images.githubusercontent.com/11865/166188122-090e599c-5b93-46c4-96ed-96549996bc8f.png">

Body text
<img width="1072" alt="Screenshot 2022-05-02 at 1 25 08 PM" src="https://user-images.githubusercontent.com/11865/166188146-5d01ac35-83a1-4a02-a88f-cea8535b479f.png">

## Body

zzSTDTitle
<img width="1074" alt="Screenshot 2022-05-02 at 1 25 27 PM" src="https://user-images.githubusercontent.com/11865/166188170-0c5c2826-04d3-428d-a620-2ade88f19b05.png">

Heading 1
<img width="1076" alt="Screenshot 2022-05-02 at 1 25 57 PM" src="https://user-images.githubusercontent.com/11865/166188195-5c5cf45d-db63-4cd2-94c9-444940531fc5.png">

## Normative references

RefNorm (std_publisher)
<img width="1074" alt="Screenshot 2022-05-02 at 1 26 31 PM" src="https://user-images.githubusercontent.com/11865/166188245-1f829d0b-0f14-41a3-be64-d901cc2ebe1e.png">

(std_docnumber)
<img width="1072" alt="Screenshot 2022-05-02 at 1 26 56 PM" src="https://user-images.githubusercontent.com/11865/166188281-dd0ba167-85e7-4a7f-b917-8b82e613b64d.png">

(std_docPartNumber)
<img width="1075" alt="Screenshot 2022-05-02 at 1 27 16 PM" src="https://user-images.githubusercontent.com/11865/166188321-4c56edb9-12ad-4c47-86f0-c6f4e8fb1ae2.png">

(std_docTitle)
<img width="1069" alt="Screenshot 2022-05-02 at 1 27 32 PM" src="https://user-images.githubusercontent.com/11865/166188344-f625b389-4cc2-45b9-bfd3-15ef1cdb22f0.png">

(std_year)
<img width="1074" alt="Screenshot 2022-05-02 at 1 27 55 PM" src="https://user-images.githubusercontent.com/11865/166188376-cd2719a5-2acd-4fa8-b50f-84f6067fa2b7.png">

## Terms and definitions

<img width="1072" alt="Screenshot 2022-05-02 at 1 28 15 PM" src="https://user-images.githubusercontent.com/11865/166188395-6094d033-b9ec-4e96-90c6-8a55b379ac0f.png">

TermNum
<img width="1073" alt="Screenshot 2022-05-02 at 1 28 51 PM" src="https://user-images.githubusercontent.com/11865/166188455-6a18ae98-716e-495a-ad85-97c983d6cf5e.png">

Term(s)
<img width="1073" alt="Screenshot 2022-05-02 at 1 29 17 PM" src="https://user-images.githubusercontent.com/11865/166188484-35986a3c-f44b-4bc1-b817-d2c67a6a8585.png">

Definition
<img width="1076" alt="Screenshot 2022-05-02 at 1 29 30 PM" src="https://user-images.githubusercontent.com/11865/166188501-b7f10b70-afc2-443b-a0fb-5af35e8f86ad.png">

Source
<img width="1071" alt="Screenshot 2022-05-02 at 1 29 43 PM" src="https://user-images.githubusercontent.com/11865/166188517-e0b62413-51d6-4a33-aee4-bb3f9444b34c.png">

Standard numbers follow rules above
<img width="1072" alt="Screenshot 2022-05-02 at 1 29 51 PM" src="https://user-images.githubusercontent.com/11865/166188528-dba0f564-6772-44da-984e-bf587a8dc94c.png">

(std_section)
<img width="1069" alt="Screenshot 2022-05-02 at 1 30 12 PM" src="https://user-images.githubusercontent.com/11865/166188550-f9405ce3-be04-42d9-9cf3-07bdb4f376cf.png">

Note
<img width="1075" alt="Screenshot 2022-05-02 at 1 30 34 PM" src="https://user-images.githubusercontent.com/11865/166188581-e1908e8c-9127-46c3-991b-20d6acdf15af.png">

Admitted term in "Term(s) not bold"
<img width="1075" alt="Screenshot 2022-05-02 at 1 30 55 PM" src="https://user-images.githubusercontent.com/11865/166188616-998fde4a-af97-4c54-92f8-4bb4e7df2ad4.png">

Symbol in "Term(s) not bold, italics"
<img width="1074" alt="Screenshot 2022-05-02 at 1 31 19 PM" src="https://user-images.githubusercontent.com/11865/166188652-406fefd2-f1af-46ce-8c5c-affcc9f3a160.png">

Example
<img width="1072" alt="Screenshot 2022-05-02 at 1 31 45 PM" src="https://user-images.githubusercontent.com/11865/166188682-84d1e145-d676-4e87-ace0-2fe1c1002eef.png">

Heading 2
<img width="1073" alt="Screenshot 2022-05-02 at 1 32 07 PM" src="https://user-images.githubusercontent.com/11865/166188717-174034b9-1f0f-48d4-ae0a-821b56a0bc26.png">

## Elements

### Standards identifiers

References "std_publisher"
<img width="1071" alt="Screenshot 2022-05-02 at 1 32 44 PM" src="https://user-images.githubusercontent.com/11865/166188770-15fda57a-77d1-4f71-b717-7471cef7fe2f.png">

std_docNumber
<img width="1071" alt="Screenshot 2022-05-02 at 1 33 07 PM" src="https://user-images.githubusercontent.com/11865/166188798-ddac591f-63b3-4289-8b5f-31a19c304e7f.png">

std_year
<img width="1075" alt="Screenshot 2022-05-02 at 1 34 14 PM" src="https://user-images.githubusercontent.com/11865/166188876-83e65ef2-1e55-4aeb-8792-d557ecb0b946.png">

Standards identifier in NOTE
<img width="1073" alt="Screenshot 2022-05-02 at 1 57 47 PM" src="https://user-images.githubusercontent.com/11865/166190882-6ec30a7c-aff9-4b45-8fa5-5542f9130267.png">


### Citation

Citation (cite_app)
<img width="1070" alt="Screenshot 2022-05-02 at 1 33 21 PM" src="https://user-images.githubusercontent.com/11865/166188814-c8ded647-d022-4e37-86d4-41bf0c84a175.png">

Citation (cite_tbl)
<img width="1073" alt="Screenshot 2022-05-02 at 1 33 44 PM" src="https://user-images.githubusercontent.com/11865/166188841-cd44579c-a64e-4cbd-bf5d-d9092baf8344.png">

Citation (cite_sec)
<img width="1073" alt="Screenshot 2022-05-02 at 1 34 35 PM" src="https://user-images.githubusercontent.com/11865/166188898-f13007e6-2378-4a9a-affa-71906bddf3e9.png">

Citation (to a list item, no style)
<img width="1073" alt="Screenshot 2022-05-02 at 1 34 54 PM" src="https://user-images.githubusercontent.com/11865/166188914-434120de-f4b3-4955-a322-6ed8f0397222.png">

Citation (cite_sec)
<img width="1075" alt="Screenshot 2022-05-02 at 1 55 19 PM" src="https://user-images.githubusercontent.com/11865/166190665-0ba23a54-fef0-4676-ad32-1bc01f8e10aa.png">

Citation (cite_app)
<img width="1075" alt="Screenshot 2022-05-02 at 1 55 36 PM" src="https://user-images.githubusercontent.com/11865/166190682-c424dfa2-c8ea-49a9-af9c-69af2ec136bc.png">

Citation (cite_tbl)
<img width="1074" alt="Screenshot 2022-05-02 at 1 55 48 PM" src="https://user-images.githubusercontent.com/11865/166190697-4a7935e7-9e37-43dc-971d-b49be1f3843c.png">

Citation (cite_fig)
<img width="995" alt="Screenshot 2022-05-02 at 2 08 41 PM" src="https://user-images.githubusercontent.com/11865/166191761-5d36797b-3419-407e-b27d-f03b475b83cb.png">

### Code

Code (inline):
<img width="1071" alt="Screenshot 2022-05-02 at 1 37 03 PM" src="https://user-images.githubusercontent.com/11865/166189073-65118c0b-413b-4fcf-ac01-2ae2c6e3f4d8.png">

Code (bold):
<img width="1072" alt="Screenshot 2022-05-02 at 1 46 51 PM" src="https://user-images.githubusercontent.com/11865/166190017-0f558774-76f3-483d-bbc7-fbdd6dba6a66.png">

Code:
<img width="1069" alt="Screenshot 2022-05-02 at 1 47 11 PM" src="https://user-images.githubusercontent.com/11865/166190032-03b048fc-4d9e-4948-87fc-df336505baff.png">

Code:
<img width="1075" alt="Screenshot 2022-05-02 at 1 51 37 PM" src="https://user-images.githubusercontent.com/11865/166190412-58bbd412-35e2-42a4-96af-7a645e1dfaf0.png">

Code with Hyperlink:
<img width="1074" alt="Screenshot 2022-05-02 at 1 52 12 PM" src="https://user-images.githubusercontent.com/11865/166190456-c0555239-e28b-4873-b494-b8df01803c6d.png">

Code (italics):
<img width="1073" alt="Screenshot 2022-05-02 at 1 50 26 PM" src="https://user-images.githubusercontent.com/11865/166190302-1e586dfd-6e13-4e4d-8c2f-8578bde31ac9.png">


### Lists

Definition list in "Body Text"
<img width="989" alt="Screenshot 2022-05-02 at 1 32 24 PM" src="https://user-images.githubusercontent.com/11865/166188739-869b8522-7745-46c8-908f-71ae473fa8be.png">

Numbered list item
<img width="1072" alt="Screenshot 2022-05-02 at 1 36 21 PM" src="https://user-images.githubusercontent.com/11865/166189021-f72345f8-7c2d-465b-b34c-5423e7a95eba.png">

List Number 2
<img width="1069" alt="Screenshot 2022-05-02 at 1 50 57 PM" src="https://user-images.githubusercontent.com/11865/166190359-197762e1-51b1-4b37-a5f6-5ef7cc675267.png">

List Number 3:
List Continue 4:
<img width="1073" alt="Screenshot 2022-05-02 at 1 52 49 PM" src="https://user-images.githubusercontent.com/11865/166190493-bd10c12d-5307-4f94-a513-be6af8e0fb66.png">

List unnumbered:
<img width="1075" alt="Screenshot 2022-05-02 at 1 58 21 PM" src="https://user-images.githubusercontent.com/11865/166190931-89f3377a-9d96-486a-8ef1-e3e46dd49a54.png">



### Table

Table title
<img width="1075" alt="Screenshot 2022-05-02 at 1 56 02 PM" src="https://user-images.githubusercontent.com/11865/166190718-e2367cc3-adce-4a97-85dc-e6962256448b.png">

Table header (centered)
<img width="1074" alt="Screenshot 2022-05-02 at 1 56 25 PM" src="https://user-images.githubusercontent.com/11865/166190751-775effec-8680-49de-9ed6-8688304d25c2.png">

Table header
<img width="1075" alt="Screenshot 2022-05-02 at 1 56 44 PM" src="https://user-images.githubusercontent.com/11865/166190804-f66acfad-8f48-40ac-9e9e-bb24fd68d856.png">

Table body
<img width="1073" alt="Screenshot 2022-05-02 at 2 00 21 PM" src="https://user-images.githubusercontent.com/11865/166191110-9647253b-ed16-4778-a8b8-609d685179a5.png">

### Figure

Figure graphic:
<img width="1070" alt="Screenshot 2022-05-02 at 1 58 53 PM" src="https://user-images.githubusercontent.com/11865/166190987-8bd1b5f6-e385-43da-baf6-d59ac87340fd.png">

Figure note:
<img width="1074" alt="Screenshot 2022-05-02 at 1 59 11 PM" src="https://user-images.githubusercontent.com/11865/166191008-b03ad189-90d1-4173-b460-c45b1c0bc879.png">

Figure title:
<img width="1073" alt="Screenshot 2022-05-02 at 1 59 21 PM" src="https://user-images.githubusercontent.com/11865/166191024-7328a311-207d-4772-a462-7c4bafb897cf.png">




## Body text

Content NOTE
<img width="1070" alt="Screenshot 2022-05-02 at 1 35 44 PM" src="https://user-images.githubusercontent.com/11865/166188977-143f9ca3-c259-4c03-b519-296f414e0f73.png">

Content EXAMPLE
<img width="1079" alt="Screenshot 2022-05-02 at 1 36 04 PM" src="https://user-images.githubusercontent.com/11865/166189003-93f5ad0d-66f3-4ccd-9d80-7afff31fe3c2.png">

Hyperlink:
<img width="1072" alt="Screenshot 2022-05-02 at 1 48 12 PM" src="https://user-images.githubusercontent.com/11865/166190155-b5f22d18-7173-402d-b40e-0a7ca1b23f0e.png">

Text that looks like a link:
<img width="1070" alt="Screenshot 2022-05-02 at 1 48 52 PM" src="https://user-images.githubusercontent.com/11865/166190178-dae97297-074a-4fda-bf82-bcc824140bae.png">

Example (continued):
<img width="1069" alt="Screenshot 2022-05-02 at 1 47 40 PM" src="https://user-images.githubusercontent.com/11865/166190064-051c5277-5380-4dac-83ba-cdc898b678cb.png">

EXAMPLE block
<img width="1069" alt="Screenshot 2022-05-02 at 1 49 41 PM" src="https://user-images.githubusercontent.com/11865/166190254-b6ee48b7-0cb3-41dd-ac52-9f874f5922a9.png">

Body Text Indent
<img width="1072" alt="Screenshot 2022-05-02 at 1 51 16 PM" src="https://user-images.githubusercontent.com/11865/166190384-565b72a1-c572-4c0b-89b9-0ebc197c668b.png">


## Annex

ANNEX
<img width="1075" alt="Screenshot 2022-05-02 at 1 53 48 PM" src="https://user-images.githubusercontent.com/11865/166190567-8d6ff148-91d2-4fd8-a487-5a9277f87d64.png">

ANNEX (not bold)
<img width="1075" alt="Screenshot 2022-05-02 at 1 54 06 PM" src="https://user-images.githubusercontent.com/11865/166190590-4b3a3270-0ac3-4da1-8ae1-9909184a9947.png">

Empty line between title
<img width="1076" alt="Screenshot 2022-05-02 at 1 54 30 PM" src="https://user-images.githubusercontent.com/11865/166190614-b2dc78b5-192d-4b7a-828e-06ab7e295ddf.png">

Annex title
<img width="1074" alt="Screenshot 2022-05-02 at 1 54 40 PM" src="https://user-images.githubusercontent.com/11865/166190625-62df5ce8-d6fb-45ed-8ece-2114b7fa1e62.png">

a2: Annex clause heading
<img width="1074" alt="Screenshot 2022-05-02 at 1 54 50 PM" src="https://user-images.githubusercontent.com/11865/166190640-a369ae10-2742-4985-8ffd-16c2c378e5b8.png">

a3: Annex clause 2nd level
<img width="1075" alt="Screenshot 2022-05-02 at 1 57 06 PM" src="https://user-images.githubusercontent.com/11865/166190826-f61d96a4-d59e-4908-b549-d1f3ad307435.png">


## Bibliography

Biblio Title
<img width="1075" alt="Screenshot 2022-05-02 at 2 01 18 PM" src="https://user-images.githubusercontent.com/11865/166191186-741fdd77-dce0-4f6d-b14a-3c153ace961f.png">

Biblio Entry
<img width="1074" alt="Screenshot 2022-05-02 at 2 01 37 PM" src="https://user-images.githubusercontent.com/11865/166191205-91436463-223d-4d82-9f1a-320917805411.png">

std_publisher
<img width="1076" alt="Screenshot 2022-05-02 at 2 02 21 PM" src="https://user-images.githubusercontent.com/11865/166191255-3bafa7bb-ea1b-43e0-aa34-fb2b5abf3d42.png">

std_docNumber
<img width="1076" alt="Screenshot 2022-05-02 at 2 02 42 PM" src="https://user-images.githubusercontent.com/11865/166191270-d39a0946-ddb6-445b-a1a9-4bca7ce2a9cb.png">

std_docTitle
<img width="1077" alt="Screenshot 2022-05-02 at 2 01 58 PM" src="https://user-images.githubusercontent.com/11865/166191228-db57eb92-baf4-489b-a90c-1d2254aed725.png">

std_year
<img width="1075" alt="Screenshot 2022-05-02 at 2 02 59 PM" src="https://user-images.githubusercontent.com/11865/166191286-36748f5b-2fbb-4dd6-9007-68c9d04ca736.png">

bib_url
<img width="1074" alt="Screenshot 2022-05-02 at 2 03 29 PM" src="https://user-images.githubusercontent.com/11865/166191331-a8500dfd-2c7f-42dd-a92d-bd081e087713.png">

bib_surname
<img width="965" alt="Screenshot 2022-05-02 at 2 06 31 PM" src="https://user-images.githubusercontent.com/11865/166191571-975fdcba-2b98-492c-a7a0-31294b1ebb29.png">


## Header

<img width="1028" alt="Screenshot 2022-05-02 at 2 06 14 PM" src="https://user-images.githubusercontent.com/11865/166191535-63505032-fc1c-4c98-9e4f-745dcf6197b9.png">

## Footer
<img width="1035" alt="Screenshot 2022-05-02 at 2 06 01 PM" src="https://user-images.githubusercontent.com/11865/166191519-04c7bc99-3eeb-453f-806d-29b335c74fef.png">

**Comment by ronaldtse** [comment]
It is also noted that auto-numbering of clauses does not work in MN generated output.

**Comment by ronaldtse** [comment]
> Having to rename styles depending on the document stage is going to be very difficult to craft and maintain.

This would be easier if we are simply targeting "two types of templates". However, I am inclined to only support the Edited DIS template -- ISO/TC 184/SC 4/WG 12 will complain about it, but if we can get confirmation from ISO/CS then it will work.

**Comment by opoudjis** [comment]
This is not a distinct issue from https://github.com/metanorma/metanorma-iso/issues/595. Closing.
