### ISSUE TITLE
PDF: table with numbers going outside of box

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#580]
From: https://github.com/metanorma/iso-5843-6/issues/7

![](https://user-images.githubusercontent.com/11865/154108947-ee8ee1e4-e53a-4144-b79c-422bafd7c494.png)

**Comment by Intelligent2013** [comment]
Automatically setup width based on longest word in the table cell:
```xml
proportional-column-width(3)
proportional-column-width(15)
proportional-column-width(15)
proportional-column-width(20)
proportional-column-width(25)
```

**Comment by Intelligent2013** [comment]
I've updated common.xsl to support soft-hyphen char in the column auto-width calculation algorithm.
Now, soft-hyphen char (&#xAD; &#173;) can be used in the long words to 'split' them in the table cells.

Using soft-hyphen in ![image](https://user-images.githubusercontent.com/5559926/154118699-44735f8c-ce58-4e60-b954-041e9b46cc14.png) together with setting of less accurate column's width `[cols="1a,4a,4a,4a,4a",options="header"]` give such result:

![image](https://user-images.githubusercontent.com/5559926/154240648-f6023ba1-e106-4a07-b744-bb8fa83a84ed.png)

But there are another long words in German:
![image](https://user-images.githubusercontent.com/5559926/154241490-35c78a10-c351-4051-8b54-bac8aa748c46.png)
![image](https://user-images.githubusercontent.com/5559926/154241665-2af3fede-25e5-4427-b42c-21338419806a.png)
which should be split by soft-hyphen also.

I.e. there are two options to solve this issue:
- set accurate table column's width (as done in https://github.com/metanorma/metanorma-iso/issues/580#issuecomment-1040563662), or
- split all long words by soft-hyphen also.

Apache FOP supports hyphenation feature (https://xmlgraphics.apache.org/fop/2.7/hyphenation.html), but there are limitation with licenses and   the language property should be set for each word (`de`) that different from document's language (`ru` in our case).
