### ISSUE TITLE
URGENT: Citation of standards that have a withdrawn past incorrectly marked as "withdrawn"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#591]
It seems that citing an undated standard that has a withdrawn edition will mark the whole standard as "withdrawn". Remember that the undated standard reference obtains metadata from the "newest active edition".

For example, ISO 9000 is current https://www.iso.org/standard/45481.html
<img width="646" alt="Screenshot 2022-03-09 at 9 51 12 AM" src="https://user-images.githubusercontent.com/11865/157356673-89b6226e-f21a-4e11-912c-676d9af4f654.png">

However, this code gives a withdrawn result:
```adoc
<<ISO_9000>> explains that quality is not an abstract concept of absolute
perfection. Quality is actually the conformance of characteristics to
requirements. This actuality means that any item of data can be of high quality
for one purpose but not for a different purpose. The quality is different
because the requirements are different between the two purposes.

...
[bibliography]
== Bibliography

* [[[ISO_9000,ISO 9000]]]]
```

Rendered as:
<img width="525" alt="Screenshot 2022-03-09 at 9 52 16 AM" src="https://user-images.githubusercontent.com/11865/157356773-3a4115b7-7e6d-4bb5-9e90-086dca39ef34.png">

Metanorma is now treating so many documents as withdrawn, incorrectly.

<img width="527" alt="Screenshot 2022-03-09 at 9 53 19 AM" src="https://user-images.githubusercontent.com/11865/157356893-b17cd4cc-5e11-4ebc-8880-28fd9d11bd9d.png">
<img width="140" alt="Screenshot 2022-03-09 at 9 53 43 AM" src="https://user-images.githubusercontent.com/11865/157356942-299bba81-417e-4b67-a00f-db457c951bb7.png">

**Comment by ronaldtse** [comment]
@opoudjis @andrew2net is this a Relaton problem or a Metanorma problem? If a Relaton problem please create a ticket in Relaton-ISO. Thanks!

**Comment by opoudjis** [comment]
Metanorma

**Comment by opoudjis** [comment]
https://github.com/relaton/relaton-iso/issues/106

**Comment by andrew2net** [comment]
the status of the returned by relaton document is `90.93` "confirmed"
```
<status>
    <stage>90</stage>
    <substage>93</substage>
</status>
```
as it is on the document's page

<img width="334" alt="image" src="https://user-images.githubusercontent.com/5623890/157424092-b5d01e78-d095-415e-8a50-be182c422496.png">

I don't understand what we need to fix.

**Comment by ronaldtse** [comment]
90.93 is correct as in “confirmed”. Maybe Metanorma is mistaking that code for withdrawn?

**Comment by opoudjis** [comment]
It is.
