### ISSUE TITLE
Word: investigate special ISO "Edited DIS" template

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#595]
This is a cleaned "Edited DIS" Word template from ISO. This document shows encoding of an Amendment, demonstrating usage of modifiers.

There are two tasks here:
1. Usage of Amendment modifiers have changed according to latest ISO EPM guidance. We need to update the generation of the locality identifiers. (and document them, perhaps on metanorma.org)
2. This is the "Edited DIS" template which is used at the DIS stage onwards and managed by ISO/CS. This differs from the "ISO Simple Template" which only has a few styles. Maybe we should use this template for DIS onwards so that we can directly generate the output needed by ISO (and stay with the Simple Template for NP to CD).

[iso-damd-fdis-sample.docx](https://github.com/metanorma/metanorma-iso/files/8221100/iso-damd-fdis-sample.docx)

**Comment by opoudjis** [comment]
There is a profusion of added styles in the new Word Template, and I do not believe it is feasible for us to directly generate them without a lot more overt collaboration with ISO Editorial than I think likely, especially as the distinctions made are often likely human discretion. The utility of this exercise is unclear to me.

The following is not an exhaustive list of the added styles, and some associated issues:

p.figure, p.BiblioEntry, p.Notice, BiblioDescription, BiblioText
span.addition, deletion, stem, notelabel, examplelabel, partlabel, part, zzcopyrighthdr
span.partlabel, part, aubase, aucollab, audeg, aufname, aurole, ausuffix, ausurname
span.bibbase, biarticle, bibcomment, bibdeg, bibdoi, bibetal, bibfname, bibfpage, bibissue, bibjournal, biblpage, biborganization, bibsuffix, bibsuppl, bibsurname, bibunpubl, biburl, bibvolume, bibyear
span.citebase, citebib, citebox, citeen, citefig, citefn, citetbl, stdbase, bibextlink, citeeq, bibmedline, citefn, auprefix, citeapp, citesec
span.stddocNumber, stddocPartNumber, stddocTitle, aumember, stdfootnote, stdpublisher, stdsection, stdyear, stddocumentType
span.bibalt-year, bibbook, bibchapterno, bibchaptertitle, bibed-etal, bibed-fname, bibedtionno, bibed-organization, bibed-suffix, bibed-surname, bibinstitution, bibisbn, biblocation, bibpagecount, bibpatent, bibpublisher, bibreportnum, bibschool, bibseries, bibseriesno, bibtrans, stdsuppl, citesection
Code-, Code--, Example0, Examplecontinued, Exampleindent, Exampleindentcontinued
p.dl NOT table.dl
Figureexample, FigureGraphic, Note0, Figurenote, Figuresubtitle, Figuretitle0
KeyText, KeyTitle, ListContinue1, ListContinue1-, ListContinue2, ListContinue3-, ListContinue4-, ListNumber1, ListNumber1-, ListNumber2-, ListNumber3-, ListNumber4-
Tabletitle0, Tablebody-, Tablebody--, Tablebody0, Tablefooter, Tableheader, Tableheader-, Tableheader--, Tableheader0
RefNorm, Notecontinued, Noteindent, Noteindentcontinued, TableGraphic
ListNumber5-, ListContinue5-
FigureImage, Figuredescription
Formuladescription, Tabledescription
Box-begin, Box-end, Box-title
FrontHead, IndexHeadA
BodyTextIndent22, BodyTextIndent32, Exampleindent2, Exampleindent2continued, Noteindent2continued, Noteindent2
span.Chinese
AMENDTermsHeading, AMENDHeading1Unnumbered
AdmittedTerm as well as AltTerm
dlnoindent
Not clear if ISO DIS allows Roman numeral foreword

**Comment by ronaldtse** [comment]
> The utility of this exercise is unclear to me.

All ISO DIS/FDIS documents are required to use this template. Therefore it is important we support it properly to allow Metanorma authors to directly submit their documents to ISO/CS.

We will have to investigate these styles to find out when and where they are used. I have a couple documents in this "EDITED DIS" format that we can check to see where the styles are used.

**Comment by opoudjis** [comment]
I'm using this as a trigger to initiate refactoring of citation rendering into Presentation XML, so that the semantic markup required by ISO DIS can be injected into Word output for ISO.

**Comment by opoudjis** [comment]
Factor IsoDoc::I18n into a separate gem, so both IsoDoc and Iso690Render can use it for their i18n files.

**Comment by opoudjis** [comment]
Putting on hold pending https://github.com/metanorma/metanorma-standoc/issues/479

**Comment by ronaldtse** [comment]
Update: https://github.com/metanorma/metanorma-standoc/issues/479 is now done.

**Comment by ronaldtse** [comment]
Thanks to @reeseplews for providing the styles list at the PRF stage!
[prf_styles_list.pdf](https://github.com/metanorma/metanorma-iso/files/8600882/prf_styles_list.pdf)

**Comment by opoudjis** [comment]
> It is also noted that auto-numbering of clauses does not work in MN generated output.

And I cannot guarantee that we will use Word's heading numbering: there is a lot of clause numbering overriding in Metanorma.

**Comment by opoudjis** [comment]
> This would be easier if we are simply targeting "two types of templates". However, I am inclined to only support the Edited DIS template -- ISO/TC 184/SC 4/WG 12 will complain about it, but if we can get confirmation from ISO/CS then it will work.

The default template Word styles are in fact the default across Metanorma (because ISO was implemented first), so they will not be dropped.

**Comment by opoudjis** [comment]
I will be documenting in this ticket the styles that I am mapping to the DIS styles this week, the DIS styles that I have not found a match for or a rule for, and the DIS styles that will have to be lower priority for mapping. This is a big task, and I am not yet convinced it can be fully automated; a lot of the DIS style choices may well be manual.

**Comment by opoudjis** [comment]
Through fault of people other than me, the document sample I was handed to realise DIS styles from contained  the Metanorma styles as well as the DIS styles. Therefore, up to 118 styles will need to be removed from the new DIS template. I'm not even going to bother: I'm only going to remove styles that are eliminated through mapping.

The Metanorma stylesheet for ISO Word, derived from the default ISO template with some Metanorma-specific additions, contains 155 styles.

The DIS style template for ISO 6709 in English contains 467 styles.

The French 6709 document renames its styles in French, and no, I am not going to manually rename 467 styles.

Some of the styles in the default ISO template are in uppercase, with lowercase equivalents in the DIS template. In the previous iteration, I had allowed both style names in the template; I am now going to have to differentiate them.

59 style names are shared between the default ISO template and the DIS template.
96 names are unique to the default ISO template.
408 names are unique to DIS.

It is simply not going to be the case I generate these 408 distinct style names. 

I am going to essay a mapping of the 96 names to equivalents in DIS, and then work out what other additional style names can be recovered.

**Comment by opoudjis** [comment]
Mere mapping is simply not going to cut it for DIS, because the granularity of styles is utterly different (e.g. in cross-references). This is going to have to be a new class of WordConvert, inheriting from ISO WordConvert.

**Comment by opoudjis** [comment]
Introducing `<span>` into Presentation XML in order to mark up inline elements semantically for DIS styles. These spans will be ignored in HTML, non-DIS word, and PDF.

**Comment by opoudjis** [comment]
With no great happiness, I'm introducing `span` into the Semantic XML as well: the semantic markup does pertain to ISO 2022 in the example, and that is included in the boilerplate.

**Comment by opoudjis** [comment]
Introducing \_ in processing of templates for relaton-render, so that style names containing underscore can be preserved.

**Comment by opoudjis** [comment]
List processing in Word in DIS is different than the default under Html2Doc. To specialise Html2Doc behaviour, need to change it from a module to a class.

**Comment by opoudjis** [comment]
Restore "Annex A" heading to Word ToC
