### ISSUE TITLE
Machine-readable changes/amendments: changing clause title

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#597]
We used to have this:
```adoc
[change=modify,locality="clause=5.3.2"]
== 5.3.2, title

Rename the title of "`Beginning of day`" to
"`Beginning of the day, ending of the day`".
```

But ISO/CS says we need to do this:

```adoc
[change=modify,locality="clause=5.3.2"]
== 5.3.2

Replace the subclause title of "`Beginning of day`" to
"`Beginning of the day, ending of the day`".
```

i.e. the locality of "title" has to be removed from the `== ...`.

Do we need an additional parameter in the `[change]` command to indicate that we are replacing the title?

**Comment by opoudjis** [comment]
You can just do:

````
[change=modify,locality="clause=5.3.2,title"]
== 5.3.2
````

just as we currently provide for

````
[change=modify,locality="clause=5.3.2,paragraph=4-7"]
````

But in order for that to be permissible, I will need to add "title" as a permitted locality.

**Comment by opoudjis** [comment]
Adding title and line to localities.
