### ISSUE TITLE
HTML: add spacing after subclause titles in Clause 3 ("terms and definitions" sections in general)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#601]
PDF (better):
<img width="762" alt="Screenshot 2022-03-16 at 7 40 12 PM" src="https://user-images.githubusercontent.com/11865/158582108-b8fcbf3f-a0c4-493e-a340-b184df29449a.png">

HTML (missing vertical whitespace):
<img width="776" alt="Screenshot 2022-03-16 at 7 41 43 PM" src="https://user-images.githubusercontent.com/11865/158582305-903cfdbc-807e-43ad-9a65-6bde15f7a83e.png">

**Comment by opoudjis** [comment]
This is simply because in HTML, h2 has a bottom margin of 1em, but h3 (which the 3.1.26 heading is) has no bottom margin. Making 1em bottom margin consistent for all HTML headings in ISO.
