### ISSUE TITLE
(URGENT) ISO 10303-52: Figure within EXAMPLE is missing "Figure nn" caption

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#603]
This is from ISO 10303-52:

```
[example]
====
<<fig21>> illustrates a 1-to-1 abutting interface, also referred to as matching or C0 continuous. The interface is a plane of vertices that are physically coincident (i.e., they have identical coordinate values) between the adjacent meshes; mesh-coordinate lines perpendicular to the interface are continuous from one mesh to the next. In 3-D, a 1-to-1 abutting interface is always a logically rectangular region.

[[fig21]]
.A 1-to-1 abutting interface
image::fig21.png[]
====
```

This is counted as "Figure 21" internally -- Figure 20 is present, and the next numbered figure is Figure 22.

<img width="535" alt="Screenshot 2022-04-02 at 11 57 00 AM" src="https://user-images.githubusercontent.com/11865/161365327-e7d4ae91-3f69-4655-b9ae-a7c7dfb906af.png">

However, it is not rendered as such.

This is the original:
<img width="509" alt="Screenshot 2022-04-02 at 11 57 59 AM" src="https://user-images.githubusercontent.com/11865/161365350-e1a4aea5-a720-46e5-b4ce-fb17fd086357.png">

Compare:
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/11865/161366550-04b71c22-a887-49a4-bec7-fd47eb786442.png">

**Comment by opoudjis** [comment]
I have a good reason for not captioning figures embedded inside of other things—if you're referencing this from outside, you're actually referencing the example and not the figure. We did originally allow captioning of figures within tables, and it was a horror film (and did not correspond to desired markup).

I could make a rule that figures can be captioned numbered within tables and not figures, but frankly I'd rather use a %numbered vs %unnumbered option, and a rule: figures embedded within other assets are by default unnumbered, unembedded figures by default are numbered, and you override that with %unnumbered (already implemented) or numbered.

@ronaldtse?

**Comment by ronaldtse** [comment]
The real problem here is logical inconsistency with the missing number of "Figure 21". This is the same issue we encountered at OGC. If the system "numbers" every figure but hides it in the caption titles, a reader has no way of referring to the Figure.

Logically, if we take the typical behavior of NOTEs in a clause, the NOTE is numbered according to the clause itself, not taking into the location hierarchy of the NOTE itself (e.g. NOTE in the clause or a NOTE within a list item in the clause).

Similarly, a Figure is numbered in an ISO document with a scope of the document itself, i.e. the location of the Figure in the content hierarchy (e.g. in a Table or in an Example) is not relevant to its title captioning.

If we wanted to hide the Figure caption, `%unnumbered` should then be used, but by default the Figure reference in the caption should be shown.

**Comment by opoudjis** [comment]
> If we wanted to hide the Figure caption, %unnumbered should then be used, but by default the Figure reference in the caption should be shown.

I think this is going to be disastrous, but I'll be very happy to point the finger when it does. OK then, numbering embedded figures unless they are explicitly unnumbered, and including the numbering in captions.

**Comment by ronaldtse** [comment]
HTML: <img width="900" alt="Screenshot 2022-04-14 at 12 58 16 AM" src="https://user-images.githubusercontent.com/11865/163231977-287eb2df-04b0-440f-bb8f-f81e47fc1b7b.png">

PDF:
<img width="565" alt="Screenshot 2022-04-14 at 12 58 30 AM" src="https://user-images.githubusercontent.com/11865/163232013-7bf79857-de22-43e0-bec6-dfe5540d2cb4.png">

The caption "Figure 21" is still missing from the figure...

**Comment by opoudjis** [comment]
Needed to remove inherited instances in metanorma-iso and metanorma-bipm

**Comment by ronaldtse** [comment]
Confirm fixed. Thanks!

<img width="543" alt="image" src="https://user-images.githubusercontent.com/11865/163306365-84c3f4be-972d-4d36-943d-866d98ff20f5.png">
