### ISSUE TITLE
Proposal provide 3 types of `docid`s for an ISO document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#608]
The proposal here is to provide 3 types of `docid`s for a document.

* ISO "Reference number" (reference PubID): `ISO 10303-52:2011(E)`
* ISO dated reference (dated PubID): `ISO 10303-52:2011`
* ISO undated reference (undated PubID): `ISO 10303`
* ISO machine readable reference (RFC 5141 "ISO URN"): `urn...`

This will solve issues such as #607 and also consolidate all identifiers under the `docid` attribute in a Bibitem.

Ping @andrew2net @mico

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-iso/issues/607#issuecomment-1088238682_

**Comment by opoudjis** [comment]
From the rspec of metanorma-iso:

````
            <docidentifier type="ISO">ISO/PreWD3 1000-1</docidentifier>
            <docidentifier type="iso-with-lang">ISO/PreWD3 1000-1(E)</docidentifier>
            <docidentifier type="iso-reference">ISO/PreWD3 1000-1:2000(E)</docidentifier>
```

`docidentifier[@type = 'iso-reference']` is the ISO Reference Number, and is already provided.

I will have to investigate the claim that undated PubID is not provided.

**Comment by opoudjis** [comment]
````
<docidentifier type="ISO">ISO 10303-52:2011</docidentifier><docidentifier type="iso-with-lang">ISO 10303-52:2011(E)</docidentifier><docidentifier type="iso-reference">ISO 10303-52:2011(E)</docidentifier>
````

is what is currently generated in ISO 10303-52. So I'll add `type=iso-undated`.

**Comment by ronaldtse** [comment]
> ```
>             <docidentifier type="ISO">ISO/PreWD3 1000-1</docidentifier>
>             <docidentifier type="iso-with-lang">ISO/PreWD3 1000-1(E)</docidentifier>
>             <docidentifier type="iso-reference">ISO/PreWD3 1000-1:2000(E)</docidentifier>
> ```

What's PreWD3? I don't think I've seen that acronym of "PreWD"...

**Comment by ronaldtse** [comment]
> <docidentifier type="ISO">ISO 10303-52:2011</docidentifier>

And `type="ISO"` should have `ISO` in lowercase.

**Comment by opoudjis** [comment]
> > ```
> >             <docidentifier type="ISO">ISO/PreWD3 1000-1</docidentifier>
> >             <docidentifier type="iso-with-lang">ISO/PreWD3 1000-1(E)</docidentifier>
> >             <docidentifier type="iso-reference">ISO/PreWD3 1000-1:2000(E)</docidentifier>
> > ```
> 
> 
> What's PreWD3? I don't think I've seen that acronym of "PreWD"...

Pre for Draft, 3 for third iteration. It is a possible identifier, if you put a draft in to a stage.

**Comment by opoudjis** [comment]
> > ISO 10303-52:2011
> 
> And `type="ISO"` should have `ISO` in lowercase.

Unwelcome micromanagement of internals that do not see users. The default prefix of the identifier is used as the default identifier type.

**Comment by ronaldtse** [comment]
> Unwelcome micromanagement of internals that do not face users.

This is also used in the BibXML Service and in the generation of Relaton data. It is not an internal detail.
