### ISSUE TITLE
How to encode term definitions with source definition reference?

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iso#611]
Taking the following definition (from ISO 1030-519) as example:
![issue_1](https://user-images.githubusercontent.com/33627611/162504458-06c8049e-a8d8-4aeb-8e46-03a31935a22a.PNG)

I encode it like: 
````
==== application interpreted construct

a logical grouping of interpreted constructs that supports a specific
function for the usage of product data across multiple application contexts

[.source]
<<iso_10303-202,definition 3.7.1>>
````

And get:

![issue_1-2](https://user-images.githubusercontent.com/33627611/162506527-d2b55f4a-d36c-4a8d-b51e-a9afcea776c9.PNG)

Which is not exactly the same format as original source.
Am I using the correct approach?

The documentation reflects the use of the word *clause* instead of *definition*:

````
...
[.source]
<<iso_10303-202,clause3.7.1>>
````

From which I get:
![issue_1-3](https://user-images.githubusercontent.com/33627611/162508617-c8191b4b-5c35-4e51-9366-4314653d2fdc.PNG)

Would this be the correct approach?

Thanks!

**Comment by Intelligent2013** [comment]
@manuel489 this is 'custom locality' (https://www.metanorma.org/author/topics/document-format/bibliography/#custom-locality):
[.source]
<<iso_10303-202,locality:definition=3.7.1>>

**Comment by manuel489** [comment]
Ohh I see! Thank you @Intelligent2013 !

**Comment by ronaldtse** [comment]
@manuel489 actually I think this could just have been this:
![image](https://user-images.githubusercontent.com/11865/162553914-2df1deb2-04df-4f67-98c1-91c813b3176c.png)

@Intelligent2013 is correct on the syntax for custom locality.
