### ISSUE TITLE
Numbered bibliography missing ISO standards document identifiers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#612]
<img alt="Screenshot 2022-04-07 at 10 55 34 AM" width="849" src="https://user-images.githubusercontent.com/11865/162111771-1943e9d7-1164-4415-a645-99a9c5bb45e0.png">

This is clearly a bug.

_Originally posted by @ronaldtse in https://github.com/metanorma/iso-10303-detached-docs/issues/91#issuecomment-1091039791_

**Comment by opoudjis** [comment]
No, it is incorrect markup. cc @manuel489 

These references have been marked up as:

`* [[[iso10303-49, (1)ISO 10303-49]]], _Industrial automation systems and integration — Product data representation and exchange — Part 49: Integrated generic resource: Process structure and properties._`

The `(1)ISO 10303-49` is requesting Metanorma to replace the identifier "ISO 10303-49" with a numeric identifier, and SUPPRESS the "ISO 10303-49" display. In the case of Bibliographies under ISO, this markup is unnecessary: the reference tag `ISO 10303-49` will give the correct output of a numbered bibliography entry, and will not suppress the SDO identifier.

(In fact, the HTML is rendering them correctly regardless.)

````
* [[[iso10303-49, ISO 10303-49]]], _Industrial automation systems and integration — Product data representation and exchange — Part 49: Integrated generic resource: Process structure and properties._

* [[[iso10303-21, ISO 10303-21]]], _Industrial automation systems and integration — Product data representation and exchange — Part 21: Implementation methods: Clear text encoding of the exchange structure._

* [[[iso10303-109, ISO 10303-109]]], _Industrial automation systems and integration — Product data representation and exchange — Part 109: Integrated application resource: Kinematic and geometric constraints for assembly models._

* [[[iso10303-203, ISO 10303-203]]], _Industrial automation systems and integration — Product data representation and exchange — Part 203: Application protocol: Configuration controlled design._

* [[[iso13584-20, ISO 13584-20]]], _Industrial automation systems and integration — Parts library — Part 20: Logical resource: Logical model of expressions._

* [[[hoffmann,6]]], HOFFMANN, C.M., _Geometric and Solid Modeling,_ San Mateo, CA: Morgan Kaufmann, 1989.

* [[[hoschek,7]]], HOSCHEK, J.; DANKWORT, W. (editors). _Parametric and Variational Design,_ Stuttgart: Teubner- Verlag, 1994.

* [[[rappaport,8]]], RAPPAPORT, A. _Breps as Displayable-Selectable Models in Interactive Design of Families of Geometric Objects_, in _Geometric Modeling: Theory and Practice_ (edited by W. Strasser, R. Klein and R. Rau); Berlin: Springer-Verlag, 1997.

* [[[shah,9]]], SHAH, J. J.; MÄNTYLÄ, M. _Parametric and Feature-based CAD/CAM,_ New York: Wiley, 1995.
````

<img width="916" alt="Στιγμιότυπο 2022-04-14, 00 32 25" src="https://user-images.githubusercontent.com/1911039/163204203-d5b59316-c2ed-475a-9758-aea581cce98d.png">

**Comment by ronaldtse** [comment]
Thanks @opoudjis . @manuel489 can we update our documentation on metanorma.org to reflect this? Thanks.

**Comment by manuel489** [comment]
Update performed.
New output:
![reference_pdf](https://user-images.githubusercontent.com/33627611/163216923-3a4ad33d-ec03-43f7-bb96-5dab896a1760.PNG)

**Comment by ronaldtse** [comment]
Thank you @opoudjis !

**Comment by ronaldtse** [comment]
@opoudjis I note with interest that the HTML and PDF rendering had different behaviors. They should really be aligned. Will this behavior change with relaton-render?

**Comment by opoudjis** [comment]
I intend for it to, yes: I want to reduce the amount of decision-making Alex D has to make. I will admit, I thought I'd taken care of document IDs already in refactoring, but until the references are really just pure BasicDoc in Presentation XML, this kind of thing will still happen. (And pure BasicDoc references is the intent behind relaton-render; reference tags though do have to be dealt with on top of relaton-render in isodoc.)

**Comment by ronaldtse** [comment]
> (And pure BasicDoc references is the intent behind relaton-render; reference tags though do have to be dealt with on top of relaton-render in isodoc.)

Isn't BasicDoc also handling reference tags?

**Comment by opoudjis** [comment]
The decision on which reference tag to *prefix* a citation with (as seen here) needs context, not just the content of the bibitem. It will be done within isodoc.
