### ISSUE TITLE
Omission of closing parenthesis in rendered index term

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-iso#614]
When a rendered index term includes a closing parenthesis at the end,
this one doesn't appear in output.

For example:

````
* ((application protocol (AP)))
````

Renders:
![issue_1](https://user-images.githubusercontent.com/33627611/163082331-aba7b764-9fb1-4ec3-9e8f-b8fcdf7c0f21.PNG)

Changing the syntax to hidden index term approach solves the problem:

````
* application protocol (AP)(((application protocol (AP))))
````

**Comment by ronaldtse** [comment]
The inability to handle this syntax will have some implications in generation of Annotated EXPRESS documents, because the index terms will be automatically created according to a template.

**Comment by opoudjis** [comment]
We have a problem. This behaviour is deliberate in Asciidoctor:

https://github.com/asciidoctor/asciidoctor/blob/25931b4e11eb3fc2100bcb09c1fae879c5ff1d81/lib/asciidoctor/substitutors.rb#L492

          if visible
            # ((Tigers))
            if (term = normalize_text encl_text, true).include? ';&'
              if term.include? ' &gt;&gt; '
                term, _, see = term.partition ' &gt;&gt; '
                attrs = { 'see' => see }
              elsif term.include? ' &amp;&gt; '
                term, *see_also = term.split ' &amp;&gt; '
                attrs = { 'see-also' => see_also }
              end
            end

Asciidoctor actually thinks that an index term ending with `)` and not starting with `(` is an error, and removes the final `).

This behaviour does not occur in hidden index terms, as @manuelfuenmayor found.

The recommendation from Asciidoctor is to switch to `indexterm2:[application protocol (AP)]`, which is processed correctly: see https://github.com/asciidoctor/asciidoctor/issues/1581
