### ISSUE TITLE
STS validation fails for ISO 10303-2

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#615]
https://github.com/metanorma/iso-10303-2/runs/5764826572?check_suite_focus=true

You can find the document generated here as an artifact:
https://github.com/metanorma/iso-10303-2/actions/runs/2068693001

<img width="953" alt="Screenshot 2022-04-13 at 11 24 37 PM" src="https://user-images.githubusercontent.com/11865/163215185-8895d471-30aa-4e16-9e6c-7060dc23afe9.png">

etc.

Seems that the MathML is failing validation?

**Comment by Intelligent2013** [comment]
@ronaldtse the error occurs due a new element `index` in `term/preferred/expression/name`:
```
<term id="term-iso-10303-application-module">
	<preferred>
		<expression>
			<name>ISO 10303 application module<index>
					<primary>ISO 10303 application module</primary>
				</index>
			</name>
		</expression>
	</preferred>
```
mnconvert doesn't know about it.
I'll fix it.

**Comment by Intelligent2013** [comment]
`<sec id="ind">` structure added for semantic metanorma xml, but total time processing degraded from ~200sec to ~1000sec. I'll try to improve it.

**Comment by Intelligent2013** [comment]
Performance restored and improved a bit (the converting process takes ~180sec).

I'll add `index/index-entry` support.

**Comment by Intelligent2013** [comment]
All done in https://github.com/metanorma/mnconvert/releases/tag/v1.16.0
