### ISSUE TITLE
PDF: In ISO/IEC joint document "Note 1 to entry" too close to text?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#616]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/11865/163360395-45445aa5-e04b-4110-a4ed-0dd1c0fbffce.png">

**Comment by Intelligent2013** [comment]
Strange behavior in FOP.
1. If in the source xml `p` placed in the next line after `name`, then FOP added space between two `fo:inline`, i.e. new line treats as space:
```xml
<termnote id="_"><name>Note 1 to entry</name>
<p id="_">Machine...
```

```xml
<fo:inline>Note 1 to entry:</fo:inline>
<fo:inline>Machine...
```

2. If note's text placed immediately after `name`, then FOP renders text without space (this issue):
```xml
<termnote id="_"><name>Note 1 to entry</name><p id="_">Machine...
```

```xml
<fo:inline>Note 1 to entry:</fo:inline><fo:inline>Machine...
```

XSLT updated - space added for 2nd case.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 ! Confirmed fixed.
<img width="1038" alt="Screenshot 2022-04-14 at 11 35 08 PM" src="https://user-images.githubusercontent.com/11865/163424235-0f8bbfa8-6ef7-482a-8e1f-85960f2a1f4c.png">
