### ISSUE TITLE
Column breaks should not insert additional blank space within an inline code element

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#620]
This is from ISO 10303-110. It seems that whenever an in-column word wrap occurs, a blank space will be inserted after `_`, but this practice breaks the actual EXPRESS reference.

In the last meeting, TF 1 requested that:
1. The EXPRESS reference in PDF should not contain the ` ` blank space2. 
2. Try our best to keep the EXPRESS reference in the same column.

<img width="870" alt="Screenshot 2022-04-19 at 10 54 19 AM" src="https://user-images.githubusercontent.com/11865/163910942-70eb346e-3ed6-44c0-94d2-275184d53699.png">
<img width="891" alt="Screenshot 2022-04-19 at 11 05 02 AM" src="https://user-images.githubusercontent.com/11865/163912066-bfe265f1-3be2-4900-b55d-fcb490ee6f40.png">

From ISO 10303-108:
<img width="899" alt="Screenshot 2022-04-19 at 11 08 52 AM" src="https://user-images.githubusercontent.com/11865/163912474-47963c73-9488-4f84-92a0-35216067b1cb.png">

Please find source files here:
https://github.com/metanorma/iso-10303-detached-docs/issues/104

**Comment by Intelligent2013** [comment]
Fixed in https://github.com/metanorma/iso-10303-detached-docs/issues/104#issuecomment-1103074000

**Comment by ronaldtse** [comment]
Is it really fixed? I'm still seeing this with the Git version of metanorma-iso, this is a new document compare:

<img width="980" alt="Screenshot 2022-04-20 at 10 34 20 AM" src="https://user-images.githubusercontent.com/11865/164135546-4d643701-3e9a-47a1-b8f1-f73caf841a84.png">

**Comment by Intelligent2013** [comment]
@ronaldtse I've double checked (ISO 10303-52) with latest commit on metanorma-iso (branch main):

![image](https://user-images.githubusercontent.com/5559926/164169864-f19ab832-ae79-4936-a84b-b6b6e28283f4.png)
