### ISSUE TITLE
PDF: Math not showing up at all in content text

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#621]
This is causing issues like this:
<img width="925" alt="Screenshot 2022-04-19 at 10 45 59 AM" src="https://user-images.githubusercontent.com/11865/163910045-2b6c38af-2d64-4481-b93c-f8c91ea82961.png">

In Metanorma-BIPM, the math is shown in AsciiMath format. This seems like a bug in Metanorma-ISO.

From https://github.com/metanorma/iso-10303-detached-docs/issues/103

**Comment by Intelligent2013** [comment]
Fixed in https://github.com/metanorma/iso-10303-detached-docs/issues/103#issuecomment-1102675828.

**Comment by Intelligent2013** [comment]
Done.
