### ISSUE TITLE
PDF: table layout anomalies

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#624]
This is from ISO 10303-108:

The "NOTE" column was invaded by the second column:
<img width="582" alt="Screenshot 2022-04-21 at 11 11 45 AM" src="https://user-images.githubusercontent.com/11865/164527963-4ad1b2c6-9f3e-432c-bc1f-bb1a5417c1c6.png">

Why does "WR1" and "NOTE 2" align in the same way? The NOTE 2 does not belong to the table of WR1.
<img width="581" alt="Screenshot 2022-04-21 at 11 07 30 AM" src="https://user-images.githubusercontent.com/11865/164528038-1a14736a-8643-4c2b-9166-0b2d0f627f51.png">

Don't know why it is pushed all the way to the right?
<img width="550" alt="Screenshot 2022-04-21 at 11 06 51 AM" src="https://user-images.githubusercontent.com/11865/164528238-244d1021-130c-4f4b-b6cc-be03314705c1.png">

The slash character is always being pushed down due to a whitespace inserted.
In particular, the diff looks like this, where the generated version split off "m/s" into "m/ s":
```
[change (285)]  OLD: "m/s"
[change (285)]  NEW: "velocity m/ s s"
[change (285)] DIFF: "{+"velocity "}m/{+" "}s{+" s"}"
```

<img width="546" alt="Screenshot 2022-04-21 at 10 58 40 AM" src="https://user-images.githubusercontent.com/11865/164528373-8cce6a9d-d3ed-44de-adce-09bcc8257dd1.png">

"area" is clearly should be on a separate line/paragraph than "two-dimensional curve".
<img width="921" alt="Screenshot 2022-04-21 at 11 15 30 AM" src="https://user-images.githubusercontent.com/11865/164528469-dd7019c3-e582-4e66-878f-8a7cbd1e51d3.png">

**Comment by ronaldtse** [comment]
> Why does "WR1" and "NOTE 2" align in the same way? The NOTE 2 does not belong to the table of WR1.

I think this is due to the NOTEs not having `keep-separate`:
https://www.metanorma.org/author/topics/document-format/text/

@opoudjis do we need `keep-separate` for all NOTEs like this?

**Comment by Intelligent2013** [comment]
> The "NOTE" column was invaded by the second column:

It seems I don't process correct this case when `note` in `dl`:
```xml
<dl id="_">
  <dt>
    <strong>WR1</strong>
  </dt>
  <dd>
    <p id="_">The <strong>SELF\free_form_constraint.constraining_expression</strong> attribute shall be of type <strong>boolean_expression</strong> as defined in <eref type="inline" bibitemid="iso13584-20" citeas="ISO 13584-20">ISO 13584-20</eref>.</p>
  </dd>
  <dt>
    <strong>WR2</strong>
  </dt>
  <dd>
    <p id="_">All <strong>model_parameter</strong> instances belonging to the sets <strong>SELF\explicit_constraint.constrained_elements</strong> and <strong>SELF\explicit_constraint.reference_elements</strong> shall participate in <strong>SELF\free_form_constraint.constraining_expression</strong>.</p>
  </dd>
  <note id="_">
    <name>NOTE  2</name>
    <p id="_">A <strong>boolean_expression</strong> is defined in <eref type="inline" bibitemid="iso13584-20" citeas="ISO 13584-20">ISO 13584-20</eref> to be an expression whose range is the <tt>BOOLEAN</tt> data type defined in <eref type="inline" bibitemid="iso10303-11" citeas="ISO 10303-11">ISO 10303-11</eref> (i.e., the expression evaluates to <tt>TRUE</tt> or <tt>FALSE</tt>).</p>
  </note>
  <note id="_">
    <name>NOTE  3</name>
    <p id="_">A single <strong>free_form_relation</strong> instance can capture both aspects of a reciprocal dimensional relationship. Assume that two <strong>bound_model_parameter</strong> instances have been defined and associated with the radius attributes of two different <strong>circle</strong> instances, whose values will be denoted here by <stem type="MathML">
        <math xmlns="http://www.w3.org/1998/Math/MathML">
```


> Why does "WR1" and "NOTE 2" align in the same way? The NOTE 2 does not belong to the table of WR1

Similar to the previous - `dl/note`:
```
<dl id="_346fdc1a-bded-b5fc-c8fd-9eff05fa8865">
  <dt>
    <strong>WR1</strong>
  </dt>
  <dd>
    <p id="_1374157b-38a4-1642-2aca-4f6e450d117d">Every instance of <strong>unbound_model_parameter</strong> shall be referenced by an instance of <strong>unbound_parameter_environment</strong>.</p>
  </dd>
  <note id="_5738d69d-139d-9770-b56b-3cccfa470ed4">
    <name>NOTE  2</name>
```

> Don't know why it is pushed all the way to the right?

In the presentation xml second `dl` relates to the note:
```xml
<dl id="_346fdc1a-bded-b5fc-c8fd-9eff05fa8865">
  <dt>
    <strong>WR1</strong>
  </dt>
  <dd>
    <p id="_1374157b-38a4-1642-2aca-4f6e450d117d">Every instance of <strong>unbound_model_parameter</strong> shall be referenced by an instance of <strong>unbound_parameter_environment</strong>.</p>
  </dd>
  <note id="_5738d69d-139d-9770-b56b-3cccfa470ed4">
    <name>NOTE  2</name>
    <p id="_f9de918d-9c18-503e-fb98-a500961d8719">The <eref type="inline" bibitemid="iso13584-20" citeas="ISO 13584-20">ISO 13584-20</eref> entity data type <strong>environment</strong> has two attributes, <strong>semantics</strong> and <strong>syntactic_representation</strong>. As a subtype of <strong>environment</strong>, <strong>unbound_parameter_environment</strong> also possesses these attributes, which are treated as follows:</p>
    <dl id="_3ab5f469-9c50-31a7-b90a-a990745c5a14">
      <dt>
        <strong>semantics</strong>
      </dt>
      <dd>
        <p id="_c83f90d3-65dd-9f30-4e9b-b8358b39b7a1">The value of this attribute is required to be of type <strong>unbound_model_parameter_semantics</strong> (see clause <xref target="unbound_model_parameter_semantics">4.4.7</xref>).</p>
      </dd>
      <dt>
        <strong>syntactic representation</strong>
      </dt>
      <dd>
        <p id="_055bd962-1ce1-62d0-ed9e-15aedfcbe011">A WHERE rule applying to <strong>unbound_parameter_environment</strong> requires that the value of this attribute shall be of type <strong>unbound_model_parameter</strong>.</p>
      </dd>
    </dl>
  </note>
</dl>
```

> The slash character is always being pushed down due to a whitespace inserted.

I'll add a rule to keep within line the sequence `one char/one char`.

> "area" is clearly should be on a separate line/paragraph than "two-dimensional curve".

I don't understand the issue. Could you clarify, please?
.

**Comment by Intelligent2013** [comment]
@ronaldtse first 3 issues fixed:

> The "NOTE" column was invaded by the second column:

![image](https://user-images.githubusercontent.com/5559926/164756444-a251ce59-dd55-4129-8a2d-bc985c96d40b.png)

> Why does "WR1" and "NOTE 2" align in the same way? The NOTE 2 does not belong to the table of WR1.

![image](https://user-images.githubusercontent.com/5559926/164756682-2fd57bd6-929d-4524-9067-6f96d72b58b3.png)

> Don't know why it is pushed all the way to the right?

![image](https://user-images.githubusercontent.com/5559926/164756997-7a59ddf2-4519-4ac1-9a15-3b5843bc587a.png)

Also I've found some issues like this:
![image](https://user-images.githubusercontent.com/5559926/164757970-cb537643-b233-45f7-a9c6-9ec0f19fb14c.png)

due wrong adoc markup (double `:`: after `NOTE`):
```
NOTE:: If it is desired to constrain
```
See iso-10303-108\sections\07\04-entity_definitions.adoc (there are two entries)

**Comment by Intelligent2013** [comment]
> The slash character is always being pushed down due to a whitespace inserted.
> In particular, the diff looks like this, where the generated version split off "m/s" into "m/ s":

Fixed:
![image](https://user-images.githubusercontent.com/5559926/164895864-f4c0e3f2-9ecc-4fca-8b8c-aba64aceb98b.png)

But table's column width isn't enough to fit text:
![image](https://user-images.githubusercontent.com/5559926/164895879-5bc8144c-fb56-46cd-ac53-72354df86a6b.png)

![image](https://user-images.githubusercontent.com/5559926/164895927-c6d80a2c-f82a-4b12-8b6a-d46fbd4b940c.png)

```adoc
[cols="5,40,5,5,40,5",options="unnumbered"]
```
should be replace by:
```adoc
[cols="5,33,12,5,33,12",options="unnumbered"]
```
![image](https://user-images.githubusercontent.com/5559926/164896008-3ecef103-219f-45d5-82de-d9e9b7db38f7.png)
![image](https://user-images.githubusercontent.com/5559926/164896028-a65fc743-bffd-4796-8746-deb7b2ae3fdf.png)

![image](https://user-images.githubusercontent.com/5559926/164895990-615fb28b-3de5-4b4f-b13d-6aeae49a6a09.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 . Is this task now complete? If so let's close it.

**Comment by Intelligent2013** [comment]
All done.
