### ISSUE TITLE
Hierarchical locality with Annex not working

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#626]
Metanorma supports hierarchical locality (https://www.metanorma.org/author/topics/document-format/bibliography/).

<img width="801" alt="Screenshot 2022-04-25 at 12 49 38 AM" src="https://user-images.githubusercontent.com/11865/164987749-b13bb546-b065-499b-be57-7b379be86aab.png">

But the following is not rendering properly.

```adoc
=== interested party
alt:[stakeholder]

person or organization that can affect, be affected by, or perceive itself to be
affected by a decision or activity

[.source]
<<ISO-IEC_DIR_1_ISO_SUP,annex=SL,appendix=2,clause=3.2>>

...

[bibliography]
== Bibliography
* [[[ISO-IEC_DIR_1_ISO_SUP,ISO/IEC DIR 1 ISO SUP]]]
```
<img width="558" alt="Screenshot 2022-04-24 at 11 34 42 PM" src="https://user-images.githubusercontent.com/11865/164987763-d48a76e5-c59c-4f8c-aa38-0ca5eca658cb.png">

When I only use `<<ISO-IEC_DIR_1_ISO_SUP,annex=SL>>`, it shows properly:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/11865/164987880-066da21b-df8e-4db0-b45f-7d59c757dde2.png">

**Comment by opoudjis** [comment]
Only the following localities are currently recognised:

`section|clause|part|paragraph|chapter|page|line|table|annex|figure|example|note|formula|list|time|anchor`

I guess it is acceptable to add appendix to that list within ISO; I'm wary of introducing it in general. The alternative is to manually enter it as a non-default locality, with `locality:appendix=2`. The latter is my preferred course of action.

**Comment by ronaldtse** [comment]
> I guess it is acceptable to add appendix to that list within ISO; I'm wary of introducing it in general.

I'm sure you recall that ISO Directives have Annexes that contain Appendixes. The problem with the localities is that it is a controlled vocabulary but this list is not exhaustive?

**Comment by opoudjis** [comment]
> I'm sure you recall that ISO Directives have Annexes that contain Appendixes

Of course I do. I also recall that they are idiosyncratic to ISO. That's why they don't appear in that controlled list.

> The problem with the localities is that it is a controlled vocabulary but this list is not exhaustive?

It's a problem, and it's begotten of me trying to be clever in Asciidoctor parsing, by restricting the interpretation of `<<a,x=y,...>>` . `locality:appendix=2` will work fine. 

What likely would also work fine is arbitrary x and y in the `,x=y,`, and escaping x=y when it is intended as literal text instead. But `locality:appendix=2` is the current solution to this issue.

**Comment by ronaldtse** [comment]
@opoudjis then I would be happy if that description is available on metanorma.org, that locality references to ISO Annex Appendices are to use `locality:appendix=2`. We can use the ISO DIR 1 Annexes as examples. Thanks!

**Comment by opoudjis** [comment]
OK, I'll put in examples of extraneous localities that need to be prefixed that way.

**Comment by ronaldtse** [comment]
@opoudjis you can use the real example provided here for realism.
