### ISSUE TITLE
(URGENT) PDF: Incorrect layout of Annex A?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#627]
Correct:

<img width="732" alt="Screenshot 2022-04-25 at 1 25 08 AM" src="https://user-images.githubusercontent.com/11865/164988671-3b5d573d-c2a1-4a89-865b-ac1cbe183353.png">

Incorrect:
<img width="680" alt="Screenshot 2022-04-25 at 1 24 15 AM" src="https://user-images.githubusercontent.com/11865/164988644-64525326-9923-4e95-8761-96862c1cc912.png">

Encoding:
```adoc

[appendix,obligation=informative]
== Abbreviated terms

ISO:: International Organization for Standardization

IEC:: International Electrotechnical Commission

IEEE:: Institute of Electrical and Electronics Engineers

PDF:: Portable Document Format

XML:: eXtensible Markup Language
```

**Comment by Intelligent2013** [comment]
@ronaldtse this case occurs due the special title `Abbreviated terms`.
Presentation xml doesn't contain title in element `annex` and it moved into `definitions `:
```xml
<annex id="_" obligation="" language="" script="" displayorder="5">
	<title>
		<strong>Annex A</strong>
		<br/>(informative)</title>
	<definitions id="_abbreviated_terms" type="abbreviated_terms" obligation="normative">
		<title depth="1">A<tab/>Abbreviated terms</title>
```

If we change title to something else like this:
```adoc
[appendix,obligation=informative]
== Another title Abbreviated terms

ISO:: International Organization for Standardization
```

then presentation xml is correct:
```xml
<annex id="_another_title_for_abbreviated_terms" inline-header="false" obligation="informative" displayorder="5">
	<title>
		<strong>Annex A</strong>
		<br/>(informative)<br/>
		<br/>
		<strong>Another title for Abbreviated terms</strong>
	</title>
	<dl id="_">
```
and PDF renders ok:
![image](https://user-images.githubusercontent.com/5559926/164990466-334951e2-fe3d-4e7d-b63d-0de79f5a73c9.png)

ping @opoudjis

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 for the investigation. 

This document is a “vocabulary document”, which allows “Abbreviated terms” as an Annex.

**Comment by opoudjis** [comment]
What is happening here, and I'm not passing that information on to Presentation XML clearly enough, is that the "Abbreviated terms" title is not meant to appear here AT ALL, so any numbering of it is means to be suppressed.

The difficulty here is that this is both an appendix and a definitions section. The proper way to mark it up is as

````
[appendix,obligation=informative]
== Example date and time expressions and representations

=== Abbreviated terms
````

i.e. as a definition section within an appendix. There then needs to be a special rule, to suppress title generation for a single terms or definitions section appearing within the annex. That is already the case with NIST, but I need to generalise it, by outright deleting the title in Presentation XML.

I was going to ask @Intelligent2013 to copy whatever has been done in NIST across, but I'll do this in Presentation XML.

**Comment by ronaldtse** [comment]
@opoudjis I'm not sure I understand. The specific guidance given by the ISO Chief Editor is:

> Vocabulary documents usually do not contain a clause for Symbols and Abbreviated terms. Preferably, those are included in term entries as preferred or admitted terms.
> Alternatively they can be listed in an annex.

In this case I would prefer having an Annex that is just called "Abbreviated terms".

**Comment by opoudjis** [comment]
They ARE being listed in the annex. This is how listing them in the annex is going to work. Having them in an annex that is just called Abbreviated terms is NOT going to work, because neither Asciidoctor nor Metanorma allow a clause to be simultaneously an annex and a symbols clause, and that is not going to change.

**Comment by opoudjis** [comment]
This has been done sporadically per flavour in the past: it will now be systematic.

If an annex contains a single terms, symbol, or references subclause, the title of that section will be skipped, as will the level itself for any subclauses.

**Comment by opoudjis** [comment]
Actually there wasn't that much for me to do...
