### ISSUE TITLE
Word: set the Index into a 2-column layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#630]
PDF index is in a two column layout:
<img width="699" alt="Screenshot 2022-04-25 at 12 06 48 PM" src="https://user-images.githubusercontent.com/11865/165019214-cfe22359-a23c-4fe0-949d-7391345cbd3d.png">

Word is in a single column now:
<img width="441" alt="Screenshot 2022-04-25 at 12 07 05 PM" src="https://user-images.githubusercontent.com/11865/165019236-2db4af42-3427-4b30-8f10-0087a30e6574.png">

Changing it to a 2-column layout is just a click away in Word (highlight the list items without the title "Index", then click Layout > 2 columns):
<img width="766" alt="Screenshot 2022-04-25 at 12 07 59 PM" src="https://user-images.githubusercontent.com/11865/165019390-c4fc636a-35ee-4a6b-878c-ea062f60c873.png">

<img width="626" alt="Screenshot 2022-04-25 at 12 08 44 PM" src="https://user-images.githubusercontent.com/11865/165019348-dba7cac1-b639-4e33-8f6f-c404ce992d37.png">

This is dependent on #629 .

**Comment by opoudjis** [comment]
> Changing it to a 2-column layout is just a click away in Word (highlight the list items without the title "Index", then click Layout > 2 columns):

I am not clicking things in Metanorma, it is more involved than that.

Implemented the basics, but getting rid of the bullets is more invovled.

**Comment by opoudjis** [comment]
Ending up removing bullets in div.index, i.e. only in Indexes (and only because ISO already overrides HTML2DOC handling of lists in DIS mede).
