### ISSUE TITLE
HTML: smaller images are not showing in table cells

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#631]
HTML: <img width="1229" alt="Screenshot 2022-04-25 at 12 17 56 PM" src="https://user-images.githubusercontent.com/11865/165020106-6ab5383b-e638-42e5-a553-7c092d579258.png">

PDF:
<img width="700" alt="Screenshot 2022-04-25 at 12 19 00 PM" src="https://user-images.githubusercontent.com/11865/165020228-8d9e2206-b8dc-4c14-bfab-73985dc13e11.png">

The document is https://github.com/metanorma/iso-9

**Comment by opoudjis** [comment]
In HTML CSS, div.figure > img is set to "max-width: 100%", so that images are not shrunk. This needs to be rescinded within tables, since they can shrink image sizes; right now, the images are being cut off by the cell widths that fit in the table.
