### ISSUE TITLE
(URGENT) PDF: Missing title in TOC if entry contains locality link under List of Tables

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#632]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/11865/165024935-5e39f158-6f59-4f1a-87f6-22caec78fb31.png">

e.g.
```adoc
[[tableA1]]
[cols="^,^,^,^",options=header]
.Diacritical signs used in <<table_1>> and <<table_2>>
|===
h| No. h| Position in the code table h| No. h| Position in the code table
```

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/165047244-b61c0386-6fae-47eb-b35b-4a766c3b3e10.png)

**Comment by ronaldtse** [comment]
Confirmed fixed. Thanks @Intelligent2013 !
