### ISSUE TITLE
ISO/CS request: add "IEC/ISO" style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#633]
Some documents published jointly by ISO and IEC are to be taken as "IEC/ISO" in styling. It should use the same template as "ISO/IEC", but the document identifier, the logo order, should have IEC first and then ISO second.

**Comment by Intelligent2013** [comment]
ISO xslt renders logos and document identifier based on order in `bibdata/docidentifier`.
Copyright owners order based on order of `bibdata/copyright` elements.
Rendered PDF example (for manually edited presentation xml):
![image](https://user-images.githubusercontent.com/5559926/165143902-7ba56e5a-c053-4fa4-a54a-cd0e63178046.png)

**Comment by ronaldtse** [comment]
I tried using this in the document but it is not working, it still shows ISO/IEC both in the document identifier and the same logo order.

```adoc
:publisher: IEC;ISO
```

This is related to https://github.com/metanorma/metanorma-iso/issues/633

**Comment by opoudjis** [comment]
````
:publisher: IEC;ISO
:copyright-holder: IEC;ISO
````
