### ISSUE TITLE
PDF feature request: for drafts, provide additional metadata on top right corner like published/DIS document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#635]
For (docstage != 60) documents, we should provide additional metadata.

Published deliverables have "edition info" and "published date".
<img width="438" alt="Screenshot 2022-04-25 at 5 45 51 PM" src="https://user-images.githubusercontent.com/11865/165064494-ce396112-0e66-4c91-bcdf-55eaa4b6ae6f.png">

Taking hint from the ISO DIS PDF layout:

<img width="580" alt="Screenshot 2022-04-25 at 6 13 19 PM" src="https://user-images.githubusercontent.com/11865/165069401-6f019e04-20ab-4ba1-b456-709feeb62846.png">

Let's add the following metadata:
1. Revdate
2. Secretariat
3. TC/WG info
4. ICS if it exists

5. Preferably, a special line of comment to be placed at the bottom. Do we have a Metanorma XML place for this sentence?
<img width="503" alt="Screenshot 2022-04-25 at 6 17 39 PM" src="https://user-images.githubusercontent.com/11865/165070216-894d0723-7f22-426e-8f4e-1f9ecaaed3bd.png">

**Comment by Intelligent2013** [comment]
@ronaldtse ISO xslt supports DIS layout already.

https://github.com/metanorma/mn-samples-iso/blob/gh-pages/documents/international-standard/rice-en.dis.pdf
![image](https://user-images.githubusercontent.com/5559926/165121457-93529f74-5596-43f3-83d2-87fd63b9aacc.png)



> 1. Revdate

do you mean 'Voting begins on:' and 'Voting terminates on:'?
adoc:
```adoc
:vote-started-date: 2020-02-19
:vote-ended-date: 2020-05-13
```

> 2. Secretariat

I'll fix double `Secretariat: Secretariat:`.

> 3. TC/WG info

Currently, only `ISO/TC 46` rendered, but I'll add SC.

> 4. ICS if it exists

It renders already, but:
```adoc
:ics: 01.140.10
```
should be changed to:
```adoc
:library-ics: 01.140.10
```

> 5. Preferably, a special line of comment to be placed at the bottom. Do we have a Metanorma XML place for this sentence?

No, this sentence is hard-coded in ISO xslt and display for DIS documents only.

**Comment by Intelligent2013** [comment]
@ronaldtse ISO updated. Here is rendered PDF example for data:

```
:docstage: 40
...
:workgroup-number: 3 
...
:library-ics: 01.140.10
...
:vote-started-date: 2020-02-19
:vote-ended-date: 2020-05-13
```

![image](https://user-images.githubusercontent.com/5559926/165140620-f8aa22ed-13a6-43e3-89b2-7c474e48e062.png)

Note: `DRAFT` rendered instead of `DRAFT INTERNATIONAL STANDARD` due the value in presentation xml:
```xml
<stage abbreviation="DIS" language="en">Draft</stage>
```

**Comment by ronaldtse** [comment]
@Intelligent2013 for DIS layout, we have to show the document type "DRAFT INTERNATIONAL STANDARD" on top.

The point of this ticket is to allow showing metadata information for other draft stages (PWI, AWI, WD, CD) as well, like this:
<img width="823" alt="Screenshot 2022-04-26 at 7 12 28 AM" src="https://user-images.githubusercontent.com/11865/165189423-a5d582ad-75f0-43b0-8ce9-bcd92543f35b.png">

And I also want to display an additional comment at the bottom (if exists), this will need to be a new attribute that Metanorma provides.

**Comment by ronaldtse** [comment]
>> TC/WG info
> Currently, only ISO/TC 46 rendered, but I'll add SC.

Does MN XML provide the full name of the drafting committee? We need to have the full identifier. In DIS and FDIS, only the TC/SC (if SC exists), no WG.

**Comment by Intelligent2013** [comment]
> Does MN XML provide the full name of the drafting committee? We need to have the full identifier. In DIS and FDIS, only the TC/SC (if SC exists), no WG.

@ronaldtse MN XML provides textual name for each sub-component:
```
<editorialgroup>
	<technical-committee number="46">Information and documentation</technical-committee>
	<subcommittee number="2" type="SC">Conversion of written languages</subcommittee>
	<workgroup number="3" type=""/>
	<secretariat>AFNOR</secretariat>
</editorialgroup>
```
But there isn't predefined value `ISO/TC 46/SC 2/WG 3`. Xslt renders it on-fly.
I'll create a ticket.

**Comment by Intelligent2013** [comment]
ISO xslt updated for PWI, AWI, WD, CD cover page, added:
- revision date
- TC/WG information
- secretariat
- ICS code

> And I also want to display an additional comment at the bottom (if exists), this will need to be a new attribute that Metanorma provides.

![image](https://user-images.githubusercontent.com/5559926/165271066-4f56450f-b967-4c78-b966-2a1a51e0b997.png)

@ronaldtse I'm going to create ticket for metanorma-iso gem, so:
- how would you like to set this additional comment - via parameter in document.adoc or hard-coded in gem?
- what is condition to render this comment - DIS only or something else?

**Comment by ronaldtse** [comment]
> TC/WG information

The current rendering isn't most correct. Is that identifier provided by Metanorma XML (it should) or is it generated from XSLT?

> how would you like to set this additional comment - via parameter in document.adoc or hard-coded in gem?

Parameter in `document.adoc` please.

> what is condition to render this comment - DIS only or something else?

Whenever such comment exists.

**Comment by ronaldtse** [comment]
@Intelligent2013 the TC/WG information shown is incorrect.

This is the data encoded:

```adoc
:technical-committee-type: SG
:technical-committee-number: SMART
:technical-committee: SMART
:subcommittee-type: SG
:subcommittee-number: TS
:subcommittee: Technical solutions sub-group
:workgroup-type: AG
:workgroup-number: 1
:workgroup: Terminology
```

<img width="533" alt="Screenshot 2022-05-03 at 10 06 40 AM" src="https://user-images.githubusercontent.com/11865/166394844-928c44dc-8886-4716-baa0-5ee59bc9a760.png">

It should show as "ISO/SG SMART/SG TS/AG 1". Does the XML not provide you with the full identifier? It should be encoded in the Semantic XML.

**Comment by Intelligent2013** [comment]
>  Does the XML not provide you with the full identifier?

Not yet, https://github.com/metanorma/metanorma-iso/issues/638

**Comment by Intelligent2013** [comment]
@ronaldtse I've updated ISO xslt for rendering
![image](https://user-images.githubusercontent.com/5559926/165271066-4f56450f-b967-4c78-b966-2a1a51e0b997.png)

only if adoc contains note:

```
...
:local-cache-only:
:toc-figures: true
:toc-tables: true

[NOTE,notag=true,coverpage=true]
====
This document is circulated as received from the committee secretariat.
====

include::sections-en/00-foreword.adoc[]
...
```

(https://github.com/metanorma/metanorma-iso/issues/642#issuecomment-1127408991)

**Comment by ronaldtse** [comment]
@Intelligent2013 I'm only seeing the cover page note only appear for DIS layout. It should appear at all stages except for a published document. Can you update?

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !

**Comment by ronaldtse** [comment]
Confirm fixed. Closing. <img width="1031" alt="Screenshot 2022-05-26 at 3 09 55 AM" src="https://user-images.githubusercontent.com/11865/170349235-2d109bec-120e-42b7-af99-9d10e3b8bc55.png">

Moving the approval committee to a separate ticket.
