### ISSUE TITLE
Document type "Draft international standard"

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#637]
Source: https://github.com/metanorma/metanorma-iso/issues/635#issuecomment-1109128707

For DIS layout, we have to encode the document type "Draft international standard" in the presentation xml.
Current value - `Draft`:
```xml
<stage abbreviation="DIS" language="en">Draft</stage>
```

**Comment by ronaldtse** [comment]
Confirm fixed. Thanks.<img width="579" alt="Screenshot 2022-05-21 at 7 17 02 PM" src="https://user-images.githubusercontent.com/11865/169649269-32e5d388-7ccd-436b-b1f8-9588635cd8b7.png">
