### ISSUE TITLE
Use Presentation XML for i18n of editions

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#641]
Follow-on from https://github.com/metanorma/metanorma-iso/issues/640

The text for the localised ordinal of an edition shall henceforth reside in

`<edition language="{{lang}}">`

e.g.

`<edition language="">2</edition><edition language="fr">deuxième édition</edition>`

Do not generate it in PDF.

**Comment by Intelligent2013** [comment]
This task relates to all documents, not ISO only.

**Comment by Intelligent2013** [comment]
@opoudjis for **Ribose** documents - the word 'Version' is using on the cover page:
![image](https://user-images.githubusercontent.com/5559926/166119932-270f2524-1430-4312-a560-3d8c7b63e1a7.png)

Xslt renders the word 'Version' from own resource + value from the xml element:
```xml
<edition>1.0</edition>
```

Should I switch to `<edition language="{{lang}}">`?

**Comment by Intelligent2013** [comment]
@opoudjis same for OGC documents:

![image](https://user-images.githubusercontent.com/5559926/166121021-5e302ee4-f04e-41e7-97f7-65438fab5fe4.png)

May be we need the localized string for 'Version'?

**Comment by Intelligent2013** [comment]
@opoudjis for MPFD document, xslt displays value from 
```xml
<edition>2</edition>
```
(currently generated xml)

and word 'Edition' from own resource:
![image](https://user-images.githubusercontent.com/5559926/166121210-1e0d5d8d-d4a3-42a8-bb30-df5ce7f3bdd5.png)

**Comment by Intelligent2013** [comment]
@opoudjis Ah, I see, this issue relates to the _ordinal_ number. So I'll move my investigations to the another issue.

**Comment by Intelligent2013** [comment]
Xslt should support `edition` without i18n:
For adoc:
```adoc
:edition: 1.3
```
presentation xml:
```xml
<edition>1.3</edition>
```

**Comment by Intelligent2013** [comment]
In some xslt (for instance, BIPM) the short form is using:
![image](https://user-images.githubusercontent.com/5559926/166139809-9c1a1e76-d244-44fb-955e-973a96937294.png)

```xml
<xsl:choose>
	<xsl:when test="$curr_lang = 'fr'">
		<xsl:choose>
			<xsl:when test="$number = '1'">re</xsl:when>
			<xsl:otherwise>e</xsl:otherwise>
		</xsl:choose>
	</xsl:when>
	<xsl:otherwise>
		<xsl:choose>
			<xsl:when test="$number = 1">st</xsl:when>
			<xsl:when test="$number = 2">nd</xsl:when>
			<xsl:when test="$number = 3">rd</xsl:when>
			<xsl:otherwise>th</xsl:otherwise>
		</xsl:choose>
	</xsl:otherwise>
</xsl:choose>
```
Currently PDF renders:
![image](https://user-images.githubusercontent.com/5559926/166139872-e49ff41f-504f-4a91-b4c4-b2a3ccc0fc47.png)

Need to fix.

**Comment by opoudjis** [comment]
I can add these numeric ordinals to the presentation xml replacing the spelled out versions, just tell me which flavors they apply to

**Comment by Intelligent2013** [comment]
Done.
