### ISSUE TITLE
Add draft comment attribute that can show on PDF cover page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#642]
We want to display an additional comment at the bottom (if exists), this will need to be a new attribute that Metanorma provides.

![image](https://user-images.githubusercontent.com/5559926/165271066-4f56450f-b967-4c78-b966-2a1a51e0b997.png)

Ideally that we can do this for other flavors as well. The Ribose flavor can use it as well.

_Originally posted by @Intelligent2013 in https://github.com/metanorma/metanorma-iso/issues/635#issuecomment-1109579156_

**Comment by opoudjis** [comment]
We already have conditional text that appears in draft, and appears in the boilerplate section of the Semantic XML, so this is nothing new at all.

**Comment by ronaldtse** [comment]
Can we have a way to change that text using document attributes or a special block?

**Comment by ronaldtse** [comment]
e.g. a "WARNING" or "NOTE" before the content body starts?

**Comment by opoudjis** [comment]
We can do all sorts of stuff, but you're not telling me what you need. There is a ticket on making the boilerplate XML easier to configure, which I think is a waste of time. There is provision for admonitions at the start of a document, and the warning can be injected there in Presentation XML generation. 

But I am not interested in a fishing expedition. You want a comment at the bottom of the title page, that's what you're getting.

**Comment by opoudjis** [comment]
What you want is custom text that can be added to include on e.g. a cover page.

That will need an extension to the code used to manipulate the boilerplate contents onto the cover page, will try to make it generalisable.

**Comment by opoudjis** [comment]
We are going to reuse the solution for putting admonitions before all clauses, at the top of a document: instead of `beforeclauses=true`, it will be `coverpage=true`.

We have an added requirement that such admonitions may need to appear without their default title. I will do so in markup by setting their caption to empty: `. {blank}`

**Comment by opoudjis** [comment]
notag notes and admonitions are unnumbered

**Comment by opoudjis** [comment]
coverpage notes and annotations will be moved to `div[@id = 'coverpage-note-destination']` in HTML and Word in postprocessing.

**Comment by Intelligent2013** [comment]
@opoudjis could you clarify how to encode ?

![image](https://user-images.githubusercontent.com/5559926/165271066-4f56450f-b967-4c78-b966-2a1a51e0b997.png)

**Comment by opoudjis** [comment]
As a result of this ticket, you can populate that by adding the following to the document preface:

````
[NOTE,notag=true,coverpage=true]
====
This document is circulated as received from the committee secretariat.
====
````

https://www.metanorma.org/author/topics/document-format/text/#cover-page-admonitions

**Comment by Intelligent2013** [comment]
@opoudjis thanks!
