### ISSUE TITLE
ignore <span> in PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#646]
https://github.com/metanorma/metanorma-iso/issues/595 is forcing the introduction of `<span>` markup into Presentation XML, to enable the addition of character span markup with semantic styling for DIS Word output. This markup is to be ignored in all other destinations of the ISO Presentation XML: `<span>` is to be parsed as a parse of its children.

**Comment by Intelligent2013** [comment]
Done.
