### ISSUE TITLE
Metanorma XML: encode drafting committee identifier as "author" 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#647]
In the `<bibdata>` element the drafting committee is not listed as the "author".

**Comment by opoudjis** [comment]
The descriptions of the drafting committee under `contributor/type[@role  = 'author']` will be: "Technical Committee", "Subcomittee", "Working Group". I'm not putting in "Drafting", because those terms should not be modified, and the approval groups are authorisers if relevant.

**Comment by opoudjis** [comment]
Is carrying to all flavours inheriting from ISO.
