### ISSUE TITLE
(ISO 6709) Reference to a "locality range" drops actual locality

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#650]
When I change to use a "locality range", I get this output:

```adoc
Using the character string delimiters specified in
<<item_6-4-a;to!item_6-4-i>> the following structures are defined:
```

<img width="654" alt="Screenshot 2022-05-04 at 4 24 39 PM" src="https://user-images.githubusercontent.com/11865/166646170-edaaec6b-1316-42c7-ab2f-7752d2f2f81d.png">

However, this text is in 6.6, and therefore should actually be "6.4 List 1 a) to List 2 e)"

_Originally posted by @ronaldtse in https://github.com/metanorma/iso-6709/issues/10#issuecomment-1117050052_

**Comment by opoudjis** [comment]
The common shared container was not being added to combined xrefs.

**Comment by ronaldtse** [comment]
Confirm fixed. Thanks. <img width="569" alt="Screenshot 2022-05-20 at 6 23 23 PM" src="https://user-images.githubusercontent.com/11865/169508496-a201df7e-aa77-487c-946e-6f631d37529e.png">

**Comment by ronaldtse** [comment]
Confirm fixed. Thanks! <img width="493" alt="Screenshot 2022-05-22 at 6 43 33 PM" src="https://user-images.githubusercontent.com/11865/169691408-4f6bebd7-398e-458c-82e7-0fbee4d61a6c.png">
