### ISSUE TITLE
(ISO 6709) Word: Locality range in Word gets rendered with an XML element

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#651]
Encoding:
```adoc
. CRS identifiers shall be listed at the end of the string, beginning
after the last coordinate and separated by a space. Formatting of
CRS identifiers shall follow rules <<item_7-2-c-1;to!item_7-2-c-4>>:
```

PDF (good): <img width="685" alt="Screenshot 2022-05-04 at 5 04 08 PM" src="https://user-images.githubusercontent.com/11865/166652142-8a4e7e2f-f23e-43f9-bb8c-03dcc1d98b2d.png">

Word (broken):
<img width="725" alt="Screenshot 2022-05-04 at 5 04 40 PM" src="https://user-images.githubusercontent.com/11865/166652215-4bc5c4ed-a9e3-48a3-b156-50360da73010.png">

From: https://github.com/metanorma/iso-6709/issues/11

**Comment by opoudjis** [comment]
Has been fixed in https://github.com/metanorma/metanorma-iso/issues/650
