### ISSUE TITLE
(ISO 6709) PDF: missing copyright warning symbol

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#653]
As per @manuel489 : https://github.com/metanorma/iso-6709/issues/13

Original:
![issue1_original](https://user-images.githubusercontent.com/33627611/166718731-1bd1d6bf-bbbe-4efa-8846-ab1951f40337.PNG)

Generated:
![issue1_generated](https://user-images.githubusercontent.com/33627611/166718942-cf497c02-1d93-481c-bccc-01e1d64d8e04.PNG)

**Comment by Intelligent2013** [comment]
Xslt renders copyright warning symbol (static image in xslt) before the text 'COPYRIGHT PROTECTED DOCUMENT' from `boilerplate/copyright-statement/clause/title`. Here is example from mn-samples-iso repository:
![image](https://user-images.githubusercontent.com/5559926/166766584-ff40717a-dad1-4ce1-a5a9-d818e75042a1.png)
(see two month ago generated xml and pdf:
https://github.com/metanorma/mn-samples-iso/blob/gh-pages/documents/international-standard/rice-en.fdis.presentation.xml
https://github.com/metanorma/mn-samples-iso/blob/gh-pages/documents/international-standard/rice-en.fdis.pdf)

But in ISO 6709 presentation xml the element `boilerplate/copyright-statement/clause/title` is missing:
![image](https://user-images.githubusercontent.com/5559926/166774599-625faadb-cdc5-4ade-a4d4-e64e20faccb5.png)

ping @opoudjis

**Comment by opoudjis** [comment]
In https://github.com/metanorma/metanorma-iso/issues/587, the update to the 2022 Simple ISO template meant the removal of the COPYRIGHT PROTECTED DOCUMENT heading. I had no reason at the time to think that would not apply to all stages, and to be blunt, I still don't.

I am not going to put it back in until I have an explicit statement, from ISO, overriding the 2022 Simple ISO template, and an indication of where it is to be ridden. My assumption until then is that you are working off a Word document generated following 2021 rules, which is invalid. 

And this is why I keep insisting on official statements from ISO editors, and not random documents they generated last year.

**Comment by ronaldtse** [comment]
> In https://github.com/metanorma/metanorma-iso/issues/587, the update to the 2022 Simple ISO template meant the removal of the COPYRIGHT PROTECTED DOCUMENT heading. I had no reason at the time to think that would not apply to all stages, and to be blunt, I still don't.

1. The "ISO Simple Template" is different from the Edited DIS template.
2. Published PDF documents do not use the "ISO Simple Template", at all.

The contents of the ISO Simple Template have no bearing to the Edited DIS or the resulting PDF.

**Comment by opoudjis** [comment]
This is no way to run a project.

Reinserting the title into the copyright boilerplate if Stage < 40. (ref https://github.com/metanorma/metanorma-iso/commit/7c596d57041164baa46882cb15ab945ef47cba7a)

**Comment by ronaldtse** [comment]
I think we just want to separate the generation of templates. The ISO Simple Template does not have the copyright statement.

The Edited DIS has a copyright statement. I believe the XML should be identical. It’s only the rendering of the Simple Template does not render it.

**Comment by opoudjis** [comment]
Since I did not change the copyright template other than the title of the copyright statement, I don't see what else I need to do here:

````
<boilerplate>
  <copyright-statement>
      {% if stage_int >= 40 %}
      <title>COPYRIGHT PROTECTED DOCUMENT</title>
      {% endif %}
    <clause>
      <p id="boilerplate-year">&#xa9; <span class="std_publisher">{{ agency }}</span> <span class="std_docNumber">{{ docyear }}</span></p>

  <p id="boilerplate-message">
    All rights
    reserved. Unless otherwise specified, or required in the context of its implementation,
    no part of this publication may be
reproduced or utilized otherwise in any form or by any means, electronic or
mechanical, including photocopying, or posting on the internet or an intranet,
without prior written permission. Permission can be requested from either ISO
at the address below or ISO's member body in the country of the requester.
  </p>
    
  <p id="boilerplate-address" align="left">
    ISO copyright office<br/>
    CP 401 &#x2022; Ch. de Blandonnet 8<br/>
    CH-1214 Vernier, Geneva<br/>
    Phone:&#xa0;&#xa0;+ 41 22 749 01 11<br/>
    Email: copyright@iso.org<br/>
    Website: www.iso.org
  </p>
    <p id="boilerplate-place">
    Published in Switzerland
  </p>
</clause>
  </copyright-statement>
    
  {% if unpublished %}
  <license-statement>
    <clause>
<title>Warning for WDs and CDs</title> 

<p>This
document is not an ISO International Standard. It is distributed for review and
comment. It is subject to change without notice and may not be referred to as
an International Standard.</p>

<p>Recipients
of this draft are invited to submit, with their comments, notification of any
relevant patent rights of which they are aware and to provide supporting
documentation.</p>
</clause>
  </license-statement>
{% endif %}
</boilerplate>
````


<img width="486" alt="Screen Shot 2022-05-21 at 16 10 29" src="https://user-images.githubusercontent.com/1911039/169638470-51e92dc0-ed7d-4248-a3dc-96b9ac5aa2d4.png">

**Comment by opoudjis** [comment]
I will note that the published samples you sent me DO NOT include the COPYRIGHT PROTECTED DOCUMENT title, as you can see, but I am at this stage so sick of the ongoing clusterfuck lack of clarity around DIS rendering, that I'm just doing what you told me.
