### ISSUE TITLE
Document identifier pattern for "copublished" documents is "IEC/ISO {stage}" not "IEC/ISO/{stage}"

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#657]
From source issue: https://github.com/metanorma/metanorma-iso/issues/648

> In ISO, the document identifier pattern for "copublished" documents is "IEC/ISO {stage}" not "IEC/ISO/{stage}", e.g. https://www.iso.org/standard/56572.html. 

Current presentation xml:
```xml
<docidentifier type="ISO">IEC/ISO/PWI 83000</docidentifier>
<docidentifier type="iso-undated">IEC/ISO/PWI 83000</docidentifier>
<docidentifier type="iso-with-lang">IEC/ISO/PWI 83000(E)</docidentifier>
<docidentifier type="iso-reference">IEC/ISO/PWI 83000:2022(E)</docidentifier>
```

Source adoc: https://github.com/metanorma/iso-iec-smart-terms

**Comment by ronaldtse** [comment]
Relaton ISO and PubID-ISO generates the correct PubIDs.

I think we need to now clarify this properly. The types of these identifiers are not properly distinguished. In addition, we are also missing the dated form "IEC/ISO PWI 83000:2022".

Maybe we should do something like this:
```xml
<docidentifier type="urn:pubid:iso:dated">IEC/ISO PWI 83000:2022</docidentifier>
<docidentifier type="urn:pubid:iso:dated:lang">IEC/ISO PWI 83000:2022(E)</docidentifier>
<docidentifier type="urn:pubid:iso:undated">IEC/ISO PWI 83000</docidentifier>
<docidentifier type="urn:pubid:iso:undated:lang">IEC/ISO PWI 83000(E)</docidentifier>
```

**Comment by ronaldtse** [comment]
> When the Publisher element contains a “slash” (“/”), the separation in front of the document stage will be converted into an empty space.

Yes. See ISO DIR 2. You never knew this!?

> I am not seeing documentation of how to do so in the readme or the rspec. @mico I will need exemplars of how to use this gem to generate an identifier given publishers, stages, numbers, etc.

Posted to https://github.com/metanorma/pubid-iso/issues/54 . @mico can you please provide documentation and examples?

> This is not ready for actioning.

I'm trying to encourage a discussion. If you are happy with what is proposed, we will implement that in pubid-iso (and across pubid gems as a whole.)

**Comment by opoudjis** [comment]
Proceed. Issue on hold until https://github.com/metanorma/pubid-iso/issues/54 is done.

**Comment by opoudjis** [comment]
With pubid-iso in place and documented (to the degree needed), I am replacing ID generation code in metanorma-iso with pubid-iso.

**Comment by opoudjis** [comment]
https://github.com/metanorma/pubid-iso/issues/70

The pubid-iso generator remains unfit for purpose. This ticket is put back on hold.

**Comment by opoudjis** [comment]
Remaining blocker is https://github.com/metanorma/pubid-iso/issues/125, everything else appears to be done.

**Comment by opoudjis** [comment]
Blocker now becomes https://github.com/metanorma/pubid-iso/issues/130

**Comment by opoudjis** [comment]
Test again.

**Comment by opoudjis** [comment]
Cannot test again, current branch is buggy. Will not action anything until there is a working branch

**Comment by opoudjis** [comment]
Now pending:

https://github.com/metanorma/pubid-iso/issues/189
https://github.com/metanorma/pubid-iso/issues/192
https://github.com/metanorma/pubid-iso/issues/193

With FYI on:

https://github.com/metanorma/pubid-iso/issues/191

**Comment by opoudjis** [comment]
Work on this is now concluded. @mico please contact @andrew2net to arrange release of pubid-iso, and notify me when done, so I can merge the metanorma-iso PR. This will again need to be a major version release (0.4.0), and I note that the removal of the `with_date` option is now crashing relaton-iso.
