### ISSUE TITLE
Word: Amendment layout not indenting properly (compared to PDF)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#660]
PDF:
<img width="488" alt="Screenshot 2022-05-11 at 1 51 19 AM" src="https://user-images.githubusercontent.com/11865/167691353-03ce6052-c3ce-4339-8efd-99d8c186f100.png">

Word:
<img width="593" alt="Screenshot 2022-05-11 at 1 51 44 AM" src="https://user-images.githubusercontent.com/11865/167691423-240dfc8a-dd74-4103-978c-70578b8dda6f.png">

The lists indents seem to be incorrect.

The document is: https://github.com/CalConnect/iso-8601-1-amd1

**Comment by opoudjis** [comment]
See attached. 
[iso-8601-1-amd.doc.zip](https://github.com/metanorma/metanorma-iso/files/8695240/iso-8601-1-amd.doc.zip)

I cannot replicate this issue, and regard this ticket as invalid.

**Comment by ronaldtse** [comment]
Confirmed fixed.
