### ISSUE TITLE
(ISO 10303-2) CD ballot GB-007: HTML output should show ISO branding

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#662]
From ISO/CD 10303-2 GB-007:

> The html should have ISO branding and formatting.
> The standard number, title and ISO copyright should remain visible at all times.	
>
> Proposal: Update the html to have ISO style, and always visible standard number, title and ISO copyright.

**Comment by opoudjis** [comment]
The parent ticket has been closed by TR Thurman as invalid; no specifics have been provided (in typical ISO review style); and the ISO HTML does have ISO branding and formatting—it was patterned after the Word document! 

Unactionable ticket, closing.
