### ISSUE TITLE
(ISO 10303-2) Abbreviated terms clause: support multiple definition lists and show captions (HTML, PDF)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#663]
From ISO/CD 10303-2 ballot US-035:

> inconsistency in the symbols.  V, 𝜇 have two entries.  

These symbols actually originate from ISO 10303-110.

They are encoded as:

```adoc
// From 10303-110

.Symbols for dimensions
stem:[M]:: mass dimension
stem:[L]:: length dimension
stem:[T]:: time dimension
stem:[Theta]:: temperature
stem:[A]:: angle dimension

.Symbols for coordinate systems
stem:[x], stem:[y], stem:[z]:: coordinates in a Cartesian system
stem:[r], stem:[theta], stem:[z]:: coordinates in a Cylindrical system
stem:[r], stem:[theta], stem:[phi]:: coordinates in a Spherical system
stem:[xi], stem:[eta], stem:[zeta]:: coordinates in an auxiliary system

.Symbols for unit vectors
stem:[hat e_x]:: stem:[x]-direction
stem:[hat e_r]:: stem:[r]-direction
stem:[hat e_xi]:: stem:[xi]-direction
stem:[hat e_y]:: stem:[y]-direction
stem:[hat e_theta]:: stem:[theta]-direction
stem:[hat e_eta]:: stem:[eta]-direction
stem:[hat e_z]:: stem:[z]-direction
stem:[hat e_phi]:: stem:[phi]-direction
stem:[hat e_zeta]:: stem:[zeta]-direction
...
```

However, the output does not show these symbols belonging to different definition lists and the list captions are missing. We need to allow multiple definition lists to exist in the "Abbreviated terms" clause and that list captions are shown

HTML:
<img width="436" alt="Screenshot 2022-05-12 at 12 36 00 PM" src="https://user-images.githubusercontent.com/11865/167992884-3e9e4635-057e-483b-b818-ebb77fb159f0.png">

PDF:
<img width="319" alt="Screenshot 2022-05-12 at 12 33 59 PM" src="https://user-images.githubusercontent.com/11865/167992697-e8a9f564-1254-4945-91c6-299cd4309eb0.png">
<img width="319" alt="Screenshot 2022-05-12 at 12 34 13 PM" src="https://user-images.githubusercontent.com/11865/167992707-414646cc-a0b0-41a2-a160-b8c14a53396e.png">

**Comment by Intelligent2013** [comment]
The lists captions are missing in the presentation xml:
```xml
					<dd>
						<p id="_e720352b-5871-96bc-4c7e-533b4f8641d3">associative Cartesian product of spaces</p>
					</dd>
				</dl>
				<dl id="_d623c139-ad19-ecd7-6f81-017d393dd398">
					<dt id="symbol-__x22c5_">
						<stem type="MathML">
							<math xmlns="http://www.w3.org/1998/Math/MathML">
								<mo>⋅</mo>
							</math>
							<!-- * -->
						</stem>
						<bookmark id="_476d0127-ee7b-4368-aa16-68cad6a766d9"/>
					</dt>
					<dd>
						<p id="_2bd36570-2c96-dd81-316b-d19565c37976">Scalar product</p>
					</dd>
```
There aren't any data between the closing `</dl>` and next opening `<dl...`.

**Comment by opoudjis** [comment]
Captions of definition lists have never been implemented, and I'll want to confirm that that is even legal Asciidoctor.

**Comment by opoudjis** [comment]
Not only is it legal Asciidoctor, but it forces lists not to nest within other lists if they are captioned. Who knew.

Implementing ol/name, ul/name, dl/name

**Comment by opoudjis** [comment]
Distinct ListTitle style for list captions (need to keep it separate from other captions, as they can be used for tables of contents.)
