### ISSUE TITLE
(ISO 19115-3) Failure in re-using W3C references from Relaton

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#665]
This issue blocks publication of [ISO 19115-3](https://github.com/metanorma/iso-19115-3/).

In Metanorma, when I run Relaton for the first time, it works:
```
[relaton-w3c] ("W3C xlink11") fetching...
[relaton-w3c] ("W3C xml") fetching...
[relaton-w3c] ("W3C xpath") fetching...
[relaton-w3c] ("W3C xmlschema-0") fetching...
[relaton-w3c] ("W3C xmlschema-1") fetching...
[relaton-w3c] ("W3C xmlschema-2") fetching...
[relaton-w3c] ("W3C xslt") fetching...
[relaton-w3c] ("W3C xml-names") fetching...
[relaton-w3c] ("W3C xmlschema-0") found xmlschema-0
[relaton-w3c] ("W3C xmlschema-1") found xmlschema-1
[relaton-w3c] ("W3C xpath") found xpath
[relaton-w3c] ("W3C xlink11") found xlink11
[relaton-w3c] ("W3C xmlschema-2") found xmlschema-2
[relaton-w3c] ("W3C xml-names") found xml-names
[relaton-w3c] ("W3C xslt") found xslt
[relaton-w3c] ("W3C xml") found xml
```

But when I re-run with the cache present, it becomes this. I wonder if this is because Metanorma has problems reading W3C references, or the Relaton cache is corrupted for W3C entries?

```
Bibliography: ERROR: No document identifier retrieved for W3C xlink11
Bibliography: ERROR: No title retrieved for W3C xlink11
Bibliography: ERROR: No document identifier retrieved for W3C xml
Bibliography: ERROR: No title retrieved for W3C xml
Bibliography: ERROR: No document identifier retrieved for W3C xpath
Bibliography: ERROR: No title retrieved for W3C xpath
Bibliography: ERROR: No document identifier retrieved for W3C xmlschema-0
Bibliography: ERROR: No title retrieved for W3C xmlschema-0
Bibliography: ERROR: No document identifier retrieved for W3C xmlschema-1
Bibliography: ERROR: No title retrieved for W3C xmlschema-1
Bibliography: ERROR: No document identifier retrieved for W3C xmlschema-2
Bibliography: ERROR: No title retrieved for W3C xmlschema-2
Bibliography: ERROR: No document identifier retrieved for W3C xslt
Bibliography: ERROR: No title retrieved for W3C xslt
Bibliography: ERROR: No document identifier retrieved for W3C xml-names
Bibliography: ERROR: No title retrieved for W3C xml-names
```

The document is: https://github.com/metanorma/iso-19115-3

**Comment by ronaldtse** [comment]
This problem is exemplified in Word:
<img width="477" alt="Screenshot 2022-05-16 at 2 40 44 PM" src="https://user-images.githubusercontent.com/11865/168533778-fbf45c93-233c-4b86-8a0b-930052c9e4a2.png">

And PDF (notice that the "W3C xxx" text after the entry):
<img width="651" alt="Screenshot 2022-05-16 at 2 41 33 PM" src="https://user-images.githubusercontent.com/11865/168533894-72c82a30-ca0e-4fdd-8d47-4e6e2bf26f51.png">

**Comment by opoudjis** [comment]
https://github.com/relaton/relaton-w3c/issues/27 to be fixed to address this.

**Comment by opoudjis** [comment]
Will revisit once formattedref removed, to ensure correct rendering in both Word and PDF.

**Comment by opoudjis** [comment]
Yes, confirmed after clearing relaton cache and rerunning site generation twice.

**Comment by ronaldtse** [comment]
Confirm fixed:

Word:
<img width="735" alt="Screenshot 2022-07-04 at 1 36 48 PM" src="https://user-images.githubusercontent.com/11865/177082381-e24ecf0c-d0fa-4e7b-9a0e-c34f03c099dd.png">

PDF:
<img width="493" alt="Screenshot 2022-07-04 at 1 37 07 PM" src="https://user-images.githubusercontent.com/11865/177082409-1eed5bca-1fc9-42f1-bb90-c88ea124bd96.png">

Thanks @opoudjis and @andrew2net for https://github.com/relaton/relaton-w3c/issues/27!
