### ISSUE TITLE
Empty conversion for `&times;`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#666]
Source document: https://github.com/metanorma/mn-samples-iso/blob/main/sources/international-standard/rice-en.final.adoc

Adoc (https://raw.githubusercontent.com/metanorma/mn-samples-iso/main/sources/international-standard/body/body-en.adoc):
```adoc
with long rounded apertures of (1 mm stem:[{:(+0.02),(0):}] mm) &times; (20 mm stem:[{:(+2),(-1):}] mm).
```

Presentation xml (version="2.1.0") - there isn't character `×` after `mm)`:
```xml
<p id="_">with long rounded apertures of (1 mm <stem .... </stem> mm)  (20 mm <stem ... /stem> mm).</p>
```

Presentation xml (version="2.0.8.1") - correct:
```xml
<p id="_">with long rounded apertures of (1 mm <stem ... </stem> mm) × (20 mm <stem ... </stem> mm).</p>
```

**Comment by opoudjis** [comment]
Nokogiri 1.13 no longer tolerates HTML escapes in its input for generating XML, so we will have to do preprocessing or postprocessing for any HTML escapes in Asciidoctor input.
