### ISSUE TITLE
(ISO 8601-1/Amd 1) EXAMPLE contents not being indented

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#667]
This task blocks submission of [ISO 8601-1/Amd 1](https://github.com/CalConnect/iso-8601-1-amd1).

Lists inside EXAMPLEs (and presumably NOTEs) are not being indented within.

Encoding:
```adoc
[example]
====
The following are valid reduced precision expressions of the beginning of
the day:

* '`T00`' (time of day expression with omission of minutes and seconds)
* '`00`' (time of day expression, omission of minutes, seconds and time designator)
* '`T00:00`' (time of day expression with omission of minutes and seconds)
* '`00:00`' (time of day expression with omission of minutes, seconds and time designator)
====
```

<img width="498" alt="Screenshot 2022-05-16 at 8 52 56 AM" src="https://user-images.githubusercontent.com/11865/168502667-086a4de0-984f-4936-a58b-dc872814967a.png">

**Comment by opoudjis** [comment]
Unnumbered lists within a note or example container need to have their style incremented, from List Continue 1, to List Continue 2.

Numbered lists within a note or example container need to have their style incremented, from ListNumber1 to ListNumber2.

There is a complication in ordered lists: they do not in fact appear to be autonumbered at all in DIS. Hence, arbitrary levels of nested ol are indented without numbering actually being impacted. This is... to be postponed as an issue.

**Comment by ronaldtse** [comment]
Confirm fixed.
<img width="604" alt="Screenshot 2022-05-21 at 7 21 24 PM" src="https://user-images.githubusercontent.com/11865/169649420-ad29db77-722a-4e87-9573-4c282ded0606.png">
