### ISSUE TITLE
(ISO 8601-1/Amd 1) "Note" style is still lowercase "note" which doesn't exist

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#668]
This task blocks submission of [ISO 8601-1/Amd 1](https://github.com/CalConnect/iso-8601-1-amd1).

From @opoudjis:
> The style Note was being applied correctly. It is still showing as "note" because I was permitting "note" as a variant name of Note in the CSS, to license both names, and Word is reading the style name from the CSS, not the document instance. Removing.

Can we find a way to do this? Having the wrong style name will not work for ISO. In addition, the "note_label" is also not an ISO style.

Metanorma generated doc:
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/11865/168503113-94e5325f-9ae1-43d2-9e13-1f38a5ea0f88.png">

ISO encoded doc:
<img width="1270" alt="Screenshot 2022-05-16 at 9 01 01 AM" src="https://user-images.githubusercontent.com/11865/168503133-b1422de9-4059-4334-acdb-cc698bef2569.png">

<img width="1272" alt="Screenshot 2022-05-16 at 9 00 51 AM" src="https://user-images.githubusercontent.com/11865/168503126-9a131693-a1c6-4139-9db9-8a02d4f34160.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-iso/issues/656#issuecomment-1127110083_

**Comment by ronaldtse** [comment]
I believe this is being addressed in #661.

**Comment by opoudjis** [comment]
<img width="598" alt="Screen Shot 2022-05-16 at 22 01 05" src="https://user-images.githubusercontent.com/1911039/168588219-5ec9b0e4-d831-43c4-b639-af02adc06373.png">

With just-released metanorma-iso 2.1.1

**Comment by opoudjis** [comment]
Stripping note_label, example_label from DIS output; they are semantically useful in building up the documents in Metanorma in general, but they can be stripped in the final DIS artefact.

**Comment by ronaldtse** [comment]
Confirm fixed. Thanks! <img width="603" alt="Screenshot 2022-05-21 at 7 20 52 PM" src="https://user-images.githubusercontent.com/11865/169649402-73804c6e-f120-439f-9ae8-5853eda9446b.png">
