### ISSUE TITLE
(ISO 8601-1/Amd 1) regression: auto-number command of NOTEs/EXAMPLEs in Amendment documents stopped working

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#669]
This task blocks submission of [ISO 8601-1/Amd 1](https://github.com/CalConnect/iso-8601-1-amd1).

Auto-numbering of NOTEs in the Amendment used to work:

```adoc
[change=modify,locality="clause=5.3.2]
== 5.3.2

autonumber:note[1]
autonumber:example[1]

Replace the text with the following:

[quote]
____
The beginning of the day is defined as the first instant of the day,
and the ending of the day is defined as the last instant of the day, where
the last instant of the day is identical to the first instant of the next day.

NOTE: An instant does not have any duration.
...
```

Auto-numbering used to work before the latest release:

## NOTEs
<img width="634" alt="Screenshot 2022-05-16 at 9 24 38 AM" src="https://user-images.githubusercontent.com/11865/168504545-49a87006-a6db-4953-92bb-c9f4c90f9c0c.png">

Now it doesn't:
PDF:
<img width="762" alt="Screenshot 2022-05-16 at 9 25 56 AM" src="https://user-images.githubusercontent.com/11865/168504645-94091e56-792e-4f4b-ba2f-5be8fa73f3c8.png">

Word:
<img width="1301" alt="Screenshot 2022-05-16 at 9 26 16 AM" src="https://user-images.githubusercontent.com/11865/168504658-392a89af-1340-4841-a605-eda56665164f.png">

## EXAMPLEs

Before:
<img width="598" alt="Screenshot 2022-05-16 at 9 26 51 AM" src="https://user-images.githubusercontent.com/11865/168504696-bd02063d-86f1-4c00-a376-d2e5848379a9.png">

Now (PDF):
<img width="778" alt="Screenshot 2022-05-16 at 9 28 01 AM" src="https://user-images.githubusercontent.com/11865/168504761-92ffcfc5-9d3b-4ba4-bb0e-ae5f2c7cd793.png">

**Comment by opoudjis** [comment]
Cannot replicate, autonumbering is working fine. Will leave for you to confirm after the release actually goes through.

**Comment by ronaldtse** [comment]
Confirmed working. Thank you @opoudjis !
