### ISSUE TITLE
Em dash is missing in Figure's titles

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#671]
Latest presentation xml:
```xml
... type="presentation" version="2.1.0"
....
<figure id="figureA-1">
	<name>Figure A.1 Split-it-right sample divider</name>
```

Previous presentation xml:
```xml
... type="presentation" version="2.0.8.1">
...
<figure id="figureA-1">
	<name>Figure A.1 — Split-it-right sample divider</name>
```

**Comment by opoudjis** [comment]
This is a consequence of the move to Nokogiri 1.13, which no longer accepts named HTML escapes in input. Such named escapes have been removed from Presentation XML in https://github.com/metanorma/isodoc/issues/402, so this is already addressed.

**Comment by Intelligent2013** [comment]
Confirm. Fixed.
