### ISSUE TITLE
(ISO 8601-1/Amd 1) Amendment first page title should be put on the same line

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#675]
Left: ISO/CS. Right: Metanorma.
<img width="1920" alt="Screenshot 2022-05-17 at 11 32 28 AM" src="https://user-images.githubusercontent.com/11865/168723108-76006713-3c87-4b78-9ea6-5b05a026ea63.png">

**Comment by opoudjis** [comment]
zzSTDTitle is bold, so need to set font-weight:normal to turn off boldface
