### ISSUE TITLE
(ISO 6709) PDF layout: EXAMPLE numbering flows to next line if content splits into new line 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#678]
Examples:
<img width="666" alt="Screenshot 2022-05-17 at 12 06 05 PM" src="https://user-images.githubusercontent.com/11865/168726583-ca2ffadb-8159-4790-b517-2a2ba48024c3.png">
<img width="682" alt="Screenshot 2022-05-17 at 12 06 13 PM" src="https://user-images.githubusercontent.com/11865/168726594-fa1aff32-0939-4cce-b001-2a7f36d18af3.png">

**Comment by Intelligent2013** [comment]
The issue fixed ~2 week ago in https://github.com/metanorma/mn-native-pdf/commit/4fac756995727fb20dff66937cb486c52f270e9f (https://github.com/metanorma/iso-6709/issues/4)


![image](https://user-images.githubusercontent.com/5559926/168745748-62a1dc74-625d-4e68-a23d-9420bcf78a0d.png)

![image](https://user-images.githubusercontent.com/5559926/168745836-0965c0b2-8486-46c5-9cc7-e7a5184730ae.png)

**Comment by ronaldtse** [comment]
Confirm fixed. Thanks!
<img width="503" alt="Screenshot 2022-05-23 at 11 44 53 AM" src="https://user-images.githubusercontent.com/11865/169739272-fb3aafa4-0152-4efd-9e0d-691c9ef31105.png">
<img width="504" alt="Screenshot 2022-05-23 at 11 44 59 AM" src="https://user-images.githubusercontent.com/11865/169739281-a1b44235-1459-437f-a6c5-db107b4ec899.png">
