### ISSUE TITLE
(ISO 6709) PDF layout: source code lines do not respect indents and introduces a tall line margin at the first line

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#679]
This example shows both problems.

<img width="670" alt="Screenshot 2022-05-17 at 12 07 25 PM" src="https://user-images.githubusercontent.com/11865/168726693-fa7b68e8-bca7-40df-ba96-643ee646a0d7.png"><img width="670" alt="Screenshot 2022-05-17 at 12 07 25 PM" src="https://user-images.githubusercontent.com/11865/168726693-fa7b68e8-bca7-40df-ba96-643ee646a0d7.png">

1. The source code lines are not indented properly.2. 
2. The second source code line has a huge gap with the first line, but the rest of the lines do not have this gap. It should not have this gap.

**Comment by Intelligent2013** [comment]
The issue fixed in https://github.com/metanorma/iso-6709/issues/4 already:

![image](https://user-images.githubusercontent.com/5559926/168746486-eae2b97a-d8ce-43ec-a71c-31c1d075d454.png)

**Comment by ronaldtse** [comment]
Confirm fixed. Thanks!
<img width="727" alt="Screenshot 2022-05-23 at 11 47 49 AM" src="https://user-images.githubusercontent.com/11865/169739512-0fff80c2-8f7c-4858-a0cf-55160a3fa5fb.png">
