### ISSUE TITLE
(ISO 6709) ISO Edited DIS template: encode "editor comments" as "zzHelp" style using "EDITOR: ..." admonition

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#682]
The "zzHelp" style is used to encode editor comments to be deleted at publication.

<img width="1144" alt="Screenshot 2022-05-18 at 3 05 13 PM" src="https://user-images.githubusercontent.com/11865/168978076-da51b97a-1136-4cec-80ed-a6781ad28cb0.png">

In Metanorma ISO, we can support encoding the zzHelp style through some syntax like this:
https://www.metanorma.org/author/topics/document-format/reviewer-notes/

```adoc
EDITOR: This is an editors comment.

[EDITOR]
--
Propose to deprecate the term "submitting organization".
--
```

(Updated: syntax changed to "EDITOR" from "TODO")

**Comment by opoudjis** [comment]
Currently, TODO notes are rendered as Word comments. Are you now saying that in DIS documents, they should not be rendered as Word comments, but as zzHelp?

This seems made up on the spot and ad hoc, but so is everything about DIS. Kindly confirm this is desired behaviour.

**Comment by ronaldtse** [comment]
> Are you now saying that in DIS documents, they should not be rendered as Word comments, but as zzHelp?

Actually not. I made a mistake with the `TODO:` syntax.

I have discussed with @rplews that we should distinguish Editor inline notes vs Comments. We can call these "Editor comments" and use the syntax `EDITOR:`?

**Comment by opoudjis** [comment]
This is going to be an admonition in Metanorma, and I think we can just mark it up as an admonition. So:

````
[IMPORTANT,type=editorial]
````

We can make `EDITOR:` an alias for it, but I don't see the point.

**Comment by ronaldtse** [comment]
> We can make `EDITOR:` an alias for it, but I don't see the point.

It's easier to use for authors. It is indeed an admonition.

**Comment by ronaldtse** [comment]
@opoudjis perhaps it's not implemented yet?

```adoc
[IMPORTANT,type=editorial]
These are zzHelp notes.
```

<img width="409" alt="Screenshot 2022-05-25 at 9 32 09 AM" src="https://user-images.githubusercontent.com/11865/170159699-eeaa3685-20e3-445e-89f2-45f580a75226.png">

**Comment by opoudjis** [comment]
From PR:

I can confirm that Word is using the zzHelp style for the editors notes:

<img width="1144" alt="Screenshot 2022-05-25 at 12 33 13 PM" src="https://user-images.githubusercontent.com/11865/170180383-a3a96720-acb5-4054-b79c-cb912f863816.png">

However:
1. There is "+6pt" afterwards
2. The colour shown in the styles pane is black

If I re-apply the clean zzHelp style, the proper "green" colour shows up in the styles pane and the +6pt goes away. 
<img width="1157" alt="Screenshot 2022-05-25 at 12 33 27 PM" src="https://user-images.githubusercontent.com/11865/170180392-42c74e0d-7506-45e8-b9dc-47aad0412f0e.png">

**Comment by opoudjis** [comment]
Need to propagate zzHelp from div to paragraphs contained in them.
