### ISSUE TITLE
(ISO 6709) Styles: "normref" => "RefNorm"; "note" => "Note"; "Normal" => "Body Text", and "List Paragraph" => "List Continue 1"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#685]
"normref" => "RefNorm"
<img width="1558" alt="Screenshot 2022-05-20 at 6 30 21 PM" src="https://user-images.githubusercontent.com/11865/169509705-5bdd616d-aa02-4339-9c07-2a3c74c370cd.png">

"note" => "Note"
<img width="1481" alt="Screenshot 2022-05-20 at 6 31 15 PM" src="https://user-images.githubusercontent.com/11865/169509913-5cb93c5a-7d32-4589-9aec-b3ad3cf842b8.png">
<img width="1425" alt="Screenshot 2022-05-20 at 6 33 06 PM" src="https://user-images.githubusercontent.com/11865/169510190-84f9ace9-464f-4b09-bac5-f2b942eabe89.png">

"Normal" => "Body Text", and "List Paragraph" => "List Continue 1"
<img width="1501" alt="Screenshot 2022-05-20 at 6 31 45 PM" src="https://user-images.githubusercontent.com/11865/169510000-173a4570-4dad-453b-9b59-05310a3a5654.png">

**Comment by opoudjis** [comment]
All of these issues have already been resolved.

<img width="852" alt="Screen Shot 2022-05-20 at 22 04 09" src="https://user-images.githubusercontent.com/1911039/169524777-11a55b52-b34b-44bb-9db3-b5fa2ee01a9e.png">
<img width="852" alt="Screen Shot 2022-05-20 at 22 04 23" src="https://user-images.githubusercontent.com/1911039/169524793-ef3dcd41-f46b-487e-a6d1-22e789d1a0fa.png">
<img width="852" alt="Screen Shot 2022-05-20 at 22 04 37" src="https://user-images.githubusercontent.com/1911039/169524808-cda3abc0-440a-4906-b9fc-d979d4edcf26.png">
<img width="852" alt="Screen Shot 2022-05-20 at 22 05 20" src="https://user-images.githubusercontent.com/1911039/169524816-6ee28c61-d598-4120-883e-361c87428adc.png">

**Comment by ronaldtse** [comment]
@opoudjis that's awesome. What am I doing wrong?

**Comment by ronaldtse** [comment]
Confirmed fixed, was using an old version apparently.
