### ISSUE TITLE
(ISO 6709) Style: "sourcecode" => "Code"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#686]
<img width="1425" alt="Screenshot 2022-05-20 at 6 35 09 PM" src="https://user-images.githubusercontent.com/11865/169510454-f0f2d51c-4e10-4acd-8adb-24d846d6b3a5.png">

**Comment by opoudjis** [comment]
This has already been addressed, and you can good and confirm it when you stop using an obsolete document to check my work.

**Comment by ronaldtse** [comment]
@opoudjis it is difficult to verify an issue unless the actual document has been updated. I am not seeing this issue fixed?

I am using the latest document at https://github.com/metanorma/iso-6709/commit/68f736a4c686e265123033c66deb2ee64fc3c867

<img width="823" alt="Screenshot 2022-05-21 at 11 58 59 AM" src="https://user-images.githubusercontent.com/11865/169634544-1a530383-1b02-4336-bd7f-f4ead6da6e37.png">

**Comment by ronaldtse** [comment]
I've also tried the metanorma-iso branch of `features/dis-20220516` but there is no change in this part. Which is the PR that I should use?

**Comment by ronaldtse** [comment]
Confirmed fixed. Thanks!
