### ISSUE TITLE
(ISO 6709) Incorrect spacing after "Code" style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#689]
<img width="796" alt="Screenshot 2022-05-23 at 11 16 31 AM" src="https://user-images.githubusercontent.com/11865/169736537-3c5277f8-a2aa-44a8-9416-87607f7bd7a0.png">

Source:
```adoc
[[ex_6-5_5]]
[example]
====
[source%unnumbered]
----
...CRS2d<EPSG:5345>/
----

Abbreviated notation of EPSG ID 5345, representing a projected 2D
POSGAR 2007/Argentina Zone 3 CRS, defined online by:
https://g.org/def/crs/EPSG/0/5345/gml or https://epsg.org/crs_5345/index.html
====
```

Original:

<img width="594" alt="Screenshot 2022-05-23 at 11 17 10 AM" src="https://user-images.githubusercontent.com/11865/169736640-4374bffc-e56c-48a6-a835-eba358c0b95c.png">

**Comment by opoudjis** [comment]
The original has a MANUAL CARRIAGE RETURN

....

!!!!!!!!!!


I am not doing manual carriage returns. That is offensive. I will probably do a manual Space After, but I'm surprised that Code isn't doing that already.

**Comment by ronaldtse** [comment]
Yes the original is… doing that. Thanks!

**Comment by opoudjis** [comment]
All I can do, for now, is insert margin-bottom:12pt for Code followed by Examplecontinued

**Comment by opoudjis** [comment]
<img width="1044" alt="Στιγμιότυπο 2022-05-24, 01 39 09" src="https://user-images.githubusercontent.com/1911039/169856380-2e7de1c9-f127-4cd9-8db2-eafd562b94da.png">

**Comment by ronaldtse** [comment]
Confirm fixed. <img width="849" alt="Screenshot 2022-05-25 at 6 54 02 AM" src="https://user-images.githubusercontent.com/11865/170144910-776d62af-c76c-4ae0-8508-0c93b01c1e41.png">
