### ISSUE TITLE
(ISO 6709) "Code" style should follow the normal text/EXAMPLE font size, not 8.5pt

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#690]
The first instance of monospace font is correct, it is 11pt.

The second instance, which is within a list item, has size of 8.5pt, despite its surrounding text being 11pt.

<img width="745" alt="Screenshot 2022-05-23 at 11 24 49 AM" src="https://user-images.githubusercontent.com/11865/169737381-e7bca9a5-105d-4639-88bb-5d29c07ab6cf.png">

```adoc
* character string delimiters and terminators -- `**monospace bold regular**` type.

Using the character string delimiters specified in
<<item_6-4-a;to!item_6-4-i>> the following structures are defined:

. [[item_6-6-3-a]]For one-dimensional spatial or temporal CRS identifiers
(CRS1d), the structure is: +
+
--
[source%unnumbered,subs="verbatim,quotes"]
----
**sign**[underline]#__One-dCoordinate__#**CRS1d<**[underline]#__CRS-identifier__#**>/**
----
```

**Comment by opoudjis** [comment]
Typo in stylesheet

**Comment by ronaldtse** [comment]
Confirm fixed. Thanks! <img width="879" alt="Screenshot 2022-05-25 at 9 28 29 AM" src="https://user-images.githubusercontent.com/11865/170159315-207895f0-ee69-406d-bd66-b2e64c196dfa.png">
