### ISSUE TITLE
PDF: display ISO editorial notes

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#695]
Follow-on from https://github.com/metanorma/metanorma-iso/issues/682

We are introducing `/admonition[@type = 'editorial']`. (Just ISO, for now.) This is to be rendered as a note, with green text.

**Comment by ronaldtse** [comment]
Sample rendering:
https://github.com/metanorma/metanorma-iso/issues/682

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/170208859-903939e1-5084-4f4c-ae03-ba0c79474426.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

**Comment by ronaldtse** [comment]
@Intelligent2013 can you change the editorial notes font size to same as the text around it? Thanks.
