### ISSUE TITLE
(ISO 6709) Locality references to a split list

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#697]
An additional issue of locality citations appear due to the list being "split into two":
<img width="324" alt="Screenshot 2022-05-25 at 6 52 17 AM" src="https://user-images.githubusercontent.com/11865/170144762-e892e3a4-3c9c-4ab4-ad36-35daac5fcbe1.png">

But I'm not sure what the best way to resolve it is.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-iso/issues/691#issuecomment-1136503076_

**Comment by opoudjis** [comment]
My default behaviour is prudent and correct: if the list is split in two, they are referenced as two distinct lists.

It is a pain to redress this programmatically, but: if there are two lists in a clause, and the start value of the second list is one after the final value of the first list, then we can treat the whole thing as one big list in the clause. We need to extend that to n lists in a clause

It's disgusting, but doable.
