### ISSUE TITLE
(ISO 6709) PDF: code style font size should be identical as that of surrounding text

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#698]
In list items, font size should be same as surrounding text:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/11865/170173823-f95b248f-f8fa-4744-9703-ab5c7deabdd2.png">

<img width="854" alt="Screenshot 2022-05-25 at 11 32 38 AM" src="https://user-images.githubusercontent.com/11865/170174021-d88fca29-c27f-42aa-b5de-d01306069035.png">

In EXAMPLEs, the font size should be the same as surrounding text:
<img width="818" alt="Screenshot 2022-05-25 at 11 30 57 AM" src="https://user-images.githubusercontent.com/11865/170173855-123377dc-74d4-4929-a4c1-34a57557d57b.png">
<img width="816" alt="Screenshot 2022-05-25 at 11 32 28 AM" src="https://user-images.githubusercontent.com/11865/170174005-bdaf6917-2f02-45fa-a328-3dbc59c7eaf6.png">

From: https://github.com/metanorma/iso-6709/issues/30

**Comment by Intelligent2013** [comment]
Fixed.

**Comment by ronaldtse** [comment]
Confirm fixed! Thanks!
