### ISSUE TITLE
(ISO 6709) Word: code style font size should be identical as that of surrounding text

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#700]
EXAMPLE has font size 10.
<img width="861" alt="Screenshot 2022-05-25 at 12 41 15 PM" src="https://user-images.githubusercontent.com/11865/170181206-142d4448-bad3-46d7-9dd1-3c3b2a90e395.png">

Text within EXAMPLE should also have font size 10
<img width="879" alt="Screenshot 2022-05-25 at 12 40 43 PM" src="https://user-images.githubusercontent.com/11865/170181144-9eb980ad-eec7-4aa7-9996-55db6a8e36f6.png">

**Comment by opoudjis** [comment]
Also implemented Notecontinued, Noteindent, Noteindentcontinued by analogy with Example.
