### ISSUE TITLE
(ISO 8601-1/Amd 1) Definition lists within a list item should inherit the font size, not reduce font size

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#701]
This table is being encoded with font size 10pt. Normal font size is 11pt.

<img width="655" alt="Screenshot 2022-05-25 at 4 46 07 PM" src="https://user-images.githubusercontent.com/11865/170221430-2e422c22-6d02-45de-a758-5c4143a3c5ec.png">

**Comment by opoudjis** [comment]
The formatted document you sent me from ISO editorial has the table as 10pt, and that is universally applied to tables in the CSS stylesheet. I require explicit confirmation, and will not action this otherwise.

**Comment by ronaldtse** [comment]
@opoudjis no, that "Table" style applies to real tables, not tables as definition lists.

Real table:
<img width="1223" alt="Screenshot 2022-05-25 at 7 12 19 PM" src="https://user-images.githubusercontent.com/11865/170249374-f5af57fa-5a43-4c16-af8d-a2a3170b8a71.png">

Definition list:
And my goodness, you are correct.
<img width="1179" alt="Screenshot 2022-05-25 at 7 14 10 PM" src="https://user-images.githubusercontent.com/11865/170249650-94020289-6dfe-4ac1-bddb-4c2676927b9a.png">

But the original content was this (this is an older template I guess, being from 2019):
<img width="1282" alt="Screenshot 2022-05-25 at 7 16 30 PM" src="https://user-images.githubusercontent.com/11865/170250028-d77298d4-9187-4a42-874b-893f09ac212e.png">

**Comment by ronaldtse** [comment]
Closing this. This is actually very strange. A definition list is NOT supposed to have a smaller font size. It's not a real Table.

**Comment by ronaldtse** [comment]
Agree with @opoudjis that if we change the styling, ISO/CS may reject the document.

I reiterate though: a definition list is a list. It should look like a list!

Until this issue comes again!
