### ISSUE TITLE
PDF: Approval group encoding

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#703]
Follow-on from https://github.com/metanorma/metanorma-iso/issues/683

There is now a bibdata/ext/editorialgroup/approvalgroup element, which by default contains the ID of the technical committee, but can contain a user-specified value. This value must be used to populate the "Committee identification" field on the cover page for DIS and FDIS drafts of ISO, instead of the current approach.

**Comment by Intelligent2013** [comment]
> To do: render digits from `approvalgrou`p in bold.

This was wrong assumption. The `SMART` and `TS` also should be in bold:
`ISO/SG SMART/SG TS/AG 1`

Another example with two SDOs:
`ISO/IEC SG SMART/SG TS/AG 1`

So, the algorithm is:
- split string by `/`.
- reverse resulted array of substrings,
- split each value by space and bold last value,
- reverse array again.

**Comment by Intelligent2013** [comment]
Updated:
- split string by `/`.
- except first item, split each value by space
- bold last value.

**Comment by Intelligent2013** [comment]
Done.
