### ISSUE TITLE
Support encoding of "Fast Track Procedure"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#704]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/11865/170273295-eb3ffc77-885b-421a-b10f-60158165dbf8.png">

ISO DIR specifies a "Fast Track Procedure" that is rendered in a document cover page.

Can we have a document attribute that describes this?
```
:iso-fast-track:
```

**Comment by opoudjis** [comment]
Document attribute will be `:fast-track:`, no good reason for the `iso-` prefix.

The attribute if present will be populated at `//bibdata/ext/fast-track`.

**Comment by opoudjis** [comment]
I have also defined i18n text for the label, as `fast-track-procedure`:

`<localized-string key="fast-track-procedure" language="en">Fast track procedure</localized-string>`

@Intelligent2013 You can now work on this.

**Comment by Intelligent2013** [comment]
ISO XSLT updated.
