### ISSUE TITLE
Encode "approval committee" as a separate XML element

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#705]
The TC/WG information shown here is incorrect.

This is the data encoded:

```adoc
:technical-committee-type: SG
:technical-committee-number: SMART
:technical-committee: SMART
:subcommittee-type: SG
:subcommittee-number: TS
:subcommittee: Technical solutions sub-group
:workgroup-type: AG
:workgroup-number: 1
:workgroup: Terminology
```

<img width="533" alt="Screenshot 2022-05-03 at 10 06 40 AM" src="https://user-images.githubusercontent.com/11865/166394844-928c44dc-8886-4716-baa0-5ee59bc9a760.png">

It should show as "ISO/SG SMART/SG TS/AG 1".

The approval group should be encoded separately in the Semantic XML.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-iso/issues/635#issuecomment-1115547793_

**Comment by ronaldtse** [comment]
This is related to #638

**Comment by opoudjis** [comment]
The foregoing now generates:
<img width="211" alt="Στιγμιότυπο 2022-05-29, 01 59 56" src="https://user-images.githubusercontent.com/1911039/170833184-92c1045f-47c0-477c-b631-7c49d66c9158.png">

in HTML

<img width="222" alt="Στιγμιότυπο 2022-05-29, 02 00 43" src="https://user-images.githubusercontent.com/1911039/170833214-61d485aa-90dd-467a-874d-3633ea1810a0.png">

in DOC

So this becomes a PDF issue to read the new structure.

**Comment by ronaldtse** [comment]
@opoudjis it seems that in DOC it says "ISO SG SMART" instead of "ISO/SG SMART"?

**Comment by opoudjis** [comment]
<img width="461" alt="Στιγμιότυπο 2022-05-29, 22 19 08" src="https://user-images.githubusercontent.com/1911039/170867803-7e9b0713-8c23-46e4-a494-9c757ab83455.png">

Fixed.

**Comment by ronaldtse** [comment]
Thank you @opoudjis !

**Comment by ronaldtse** [comment]
@Intelligent2013 this is ready for action, thanks.

**Comment by Intelligent2013** [comment]
@ronaldtse  I'm trying to generate presentation xml for testing but can't see the `approvalgroup`structure` (from https://github.com/metanorma/metanorma-iso/issues/638#issuecomment-1137420679) like this:
```xml
<approvalgroup>
	<technical-committee number="211">Geographic information/Geomatics</technical-committee>
	<subcommittee/>
	<workgroup number="9" type="WG"/>
</approvalgroup>
```

Could you provide the xml?

**Comment by Intelligent2013** [comment]
I've tried to switch to the branch `fix/approval-groups` by updating gemfile:
```
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "fix/approval-groups"
```

and now for adoc:
```
:technical-committee-type: SG
:technical-committee-number: SMART
:technical-committee: SMART
:subcommittee-type: SG
:subcommittee-number: TS
:subcommittee: Technical solutions sub-group
:workgroup-type: AG
:workgroup-number: 1
:workgroup: Terminology
:approval-technical-committee-number: SMARTA
:approval-technical-committee-type: SGA
:approval-technical-committee: SMARTA
:approval-subcommittee-number: 1
:approval-subcommittee-type: SGA
:approval-subcommittee: Technical solutions sub-group
:approval-workgroup-number: 11
:approval-workgroup-type: AGA
:approval-workgroup: Terminology A
```
presentation xml looks so:
```xml
<editorialgroup>
	<technical-committee number="SMART" type="SG">SMART</technical-committee>
	<subcommittee number="TS" type="SG">Technical solutions sub-group</subcommittee>
	<workgroup number="1" type="AG">Terminology</workgroup>
</editorialgroup>
<approvalgroup>
	<technical-committee number="SMARTA" type="SGA">SMARTA</technical-committee>
	<subcommittee number="1" type="SGA">Technical solutions sub-group</subcommittee>
	<workgroup number="11" type="AGA">Terminology A</workgroup>
</approvalgroup>
```

but there isn't `<approvalgroup>` element for ready to rendering data.

@opoudjis could you help me solve this puzzle?

**Comment by opoudjis** [comment]
... You want a prerendered version of the concatenated IDs, as well as its components?

I was assuming you were already assembling one for editorialgroup, and would also do one for approvalgroup. If you want me to, though, I can add a precomposed identifier in Presentation XML for both.

**Comment by Intelligent2013** [comment]
> I was assuming you were already assembling a rendering of the identifier for editorialgroup

It was in the previous versions of xslt. Now xslt reads precomposed identifier. (https://github.com/metanorma/metanorma-iso/issues/703)

Regarding:
> https://github.com/metanorma/metanorma-iso/issues/635#issuecomment-1115547793

> If you want me to, though, I can add a precomposed identifier in Presentation XML for both.

yes, please add them for both.

**Comment by opoudjis** [comment]
Adding these, just for ISO, as: `//editorialgroup[@identifier]`, `//approvalgroup[@identifier]`

**Comment by opoudjis** [comment]
For JTCs, we can't predict ahead of time that they are ISO/IEC, especially if a JTC is approving an ISO draft.

For that reason, we will need to add approval-agency as well as agency, in the document attributes.

**Comment by ronaldtse** [comment]
I know this is absolutely arbitrary but there are only two JTCs in ISO and IEC. They are ISO/IEC JTC 1 and ISO/IEC JTC 2. I agree with you that a generic solution is preferable though.

**Comment by Intelligent2013** [comment]
Done.
