### ISSUE TITLE
(ISO 8000-118) ISO House Style: reference to list item in clause "Clause 7 a)" should be "7 a)"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#709]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/11865/170851906-09ea9fc1-38c4-475f-bbaf-e83f6d52c3f4.png">

Reported by BSI in https://github.com/metanorma/iso-8000-118/issues/3:
> (28) Clause 7, the references here are wrong; this was pointed out in comments previously sent to the team (i.e. change “Clause 6 a)” to “6 a)” etc.)

**Comment by ronaldtse** [comment]
To be fair, this behavior is not defined in ISO House Style:
https://www.iso.org/ISO-house-style.html

<img width="602" alt="Screenshot 2022-05-30 at 1 21 50 AM" src="https://user-images.githubusercontent.com/11865/170883251-b5ec6578-8292-4822-917a-de6fec6b8101.png">

**Comment by opoudjis** [comment]
"Clause 7" + "a)" are generated separately and combined; to drop the "Clause" is going to be difficult, although I can see the human impulse to draw an analogy between 7 a) and 7.1. (It is a perverse analogy nevertheless.)
