### ISSUE TITLE
(ISO 8000-118) Problems with Word ISO Simple Template support

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#711]
Support for the ISO Edited DIS template is superb. But support for the ISO Simple Template is not there yet.
<img width="882" alt="Screenshot 2022-05-29 at 12 34 42 PM" src="https://user-images.githubusercontent.com/11865/170852406-ec9b6e16-b2cd-4764-b2cc-4d5e2672ed88.png">
<img width="697" alt="Screenshot 2022-05-29 at 12 35 30 PM" src="https://user-images.githubusercontent.com/11865/170852419-f6b370f3-0aae-43ef-8a4a-d1bb60c29b29.png">
<img width="736" alt="Screenshot 2022-05-29 at 12 35 43 PM" src="https://user-images.githubusercontent.com/11865/170852426-6a736210-410b-401f-b058-1253eb670cf2.png">
<img width="857" alt="Screenshot 2022-05-29 at 12 36 03 PM" src="https://user-images.githubusercontent.com/11865/170852436-3859ef94-8c01-4b97-8608-53bd46b301ea.png">

If we have #710 implemented then this issue is much less a concern.

**Comment by opoudjis** [comment]
> But support for the ISO Simple Template is not there yet.

I don't see how it can get there. The simple template is what it is...

**Comment by ronaldtse** [comment]
## Note

<img alt="Screenshot 2022-05-29 at 12 34 42 PM" width="882" src="https://user-images.githubusercontent.com/11865/170852406-ec9b6e16-b2cd-4764-b2cc-4d5e2672ed88.png"> 

ISO Simple Template uses the style "Note".

<img width="378" alt="Screenshot 2022-06-04 at 12 59 41 AM" src="https://user-images.githubusercontent.com/11865/171902395-c4669508-b5b2-485b-b916-912ccd005609.png">


## Example

ISO Simple Template uses "Example"
<img width="360" alt="Screenshot 2022-06-04 at 1 00 17 AM" src="https://user-images.githubusercontent.com/11865/171902480-dbfba0a0-5873-4890-b6cf-cd167d5510ff.png">


## Figure title

ISO Simple Template uses "Figure title".

<img width="558" alt="Screenshot 2022-06-04 at 1 00 33 AM" src="https://user-images.githubusercontent.com/11865/171902527-4a80fbaa-9019-4251-ba13-1d2148a4bcb6.png">

## Code

ISO Simple Template uses "Code".

<img width="554" alt="Screenshot 2022-06-04 at 1 01 41 AM" src="https://user-images.githubusercontent.com/11865/171902726-a5596042-eaf3-4388-a7a0-c9ed78ba1dc6.png">

## Table title

<img alt="Screenshot 2022-05-29 at 12 35 30 PM" width="697" src="https://user-images.githubusercontent.com/11865/170852419-f6b370f3-0aae-43ef-8a4a-d1bb60c29b29.png"> 

ISO Simple Template uses "Table title".

<img width="582" alt="Screenshot 2022-06-04 at 1 01 01 AM" src="https://user-images.githubusercontent.com/11865/171902624-a049179c-d994-4601-9289-cbf5e8b2d0a5.png">

Annex Tables use "Annex Table Title"
<img width="561" alt="Screenshot 2022-06-04 at 1 02 48 AM" src="https://user-images.githubusercontent.com/11865/171902894-f3d1d397-0ce5-4433-8c54-88dffd6c8261.png">



<img alt="Screenshot 2022-05-29 at 12 35 43 PM" width="736" src="https://user-images.githubusercontent.com/11865/170852426-6a736210-410b-401f-b058-1253eb670cf2.png">


## Bibliography

<img alt="Screenshot 2022-05-29 at 12 36 03 PM" width="857" src="https://user-images.githubusercontent.com/11865/170852436-3859ef94-8c01-4b97-8608-53bd46b301ea.png">

ISO Simple Template uses "Normal".

<img width="578" alt="Screenshot 2022-06-04 at 1 02 07 AM" src="https://user-images.githubusercontent.com/11865/171902810-23fbc856-765c-4a13-91d0-cd22f7d36e74.png">

**Comment by opoudjis** [comment]
> ISO Simple Template uses "Figure title".

No it doesn't, it uses "Figure Title". https://www.iso.org/iso-templates.html

**Comment by ronaldtse** [comment]
Reopened.

## Figure is using "Figure title", but should be "Figure Title".

Template:
<img width="615" alt="Screenshot 2022-07-05 at 2 37 23 AM" src="https://user-images.githubusercontent.com/11865/177199349-0da76749-ed86-44c4-9931-66a34f7121ec.png">

Generated:
<img width="618" alt="Screenshot 2022-07-05 at 2 37 13 AM" src="https://user-images.githubusercontent.com/11865/177199327-a62ffeee-e5c2-44e8-ad4e-e656e85af692.png">

## Figure itself should be in "Normal" style

In the template, the figure itself uses "Normal" style.
<img width="789" alt="Screenshot 2022-07-05 at 2 35 45 AM" src="https://user-images.githubusercontent.com/11865/177199181-a21d556c-6837-4104-a8a6-3687ebe3608f.png">

In the generated document, the figure uses "figure" style.
<img width="763" alt="Screenshot 2022-07-05 at 2 36 12 AM" src="https://user-images.githubusercontent.com/11865/177199223-a6c2be22-d5e2-4525-8b23-1562bb2b52d1.png">

## Figure title for pseudocode is now "sourcetitle" not "Figure Title"

The current style set for the Figure title is "sourcetitle", not "Figure Title". Note that this is a Pseudocode block
<img width="750" alt="Screenshot 2022-07-05 at 1 55 54 AM" src="https://user-images.githubusercontent.com/11865/177195363-12e1d601-3d2f-4689-b77e-c8a59e56566e.png">

## Source code is set to 11pt, but Pseudocode is set to 10pt.

Both probably should be at 11pt.

<img width="609" alt="Screenshot 2022-07-05 at 1 56 47 AM" src="https://user-images.githubusercontent.com/11865/177195455-9dbe1e70-add7-44ef-9dad-418ae831086f.png">

<img width="468" alt="Screenshot 2022-07-05 at 1 57 12 AM" src="https://user-images.githubusercontent.com/11865/177195501-528ae78d-2781-4a39-a5f9-a9a612eedb42.png">

**Comment by opoudjis** [comment]
We are clearly seeing a different template, my copy has "Table title":

<img width="826" alt="Στιγμιότυπο 2022-07-05, 15 55 08" src="https://user-images.githubusercontent.com/1911039/177259149-5dc10693-48c9-46f9-aaff-0ad8ad366ac3.png">

I'm using that as guide.

**Comment by opoudjis** [comment]
> Source code is set to 11pt, but Pseudocode is set to 10pt.
> Both probably should be at 11pt.

Absolutely not. Source code is in monospace font, Pseudocode is in normal font, and monospace font is bigger than normal font.

**Comment by opoudjis** [comment]
We're having trouble with Word's broken implementation of CSS:

Figure titles are based on List Paragraphs, because in the template, that's how they're autonumbered.

Normal lists are shrunk in the existing CSS, thanks to:

````
div.Note p.MsoListParagraph {
  font-size: 10pt; }
````

This is being applied to Figure Titles, even though they are not inside a Note div. And if I get rid of that rule, this applies:

````
div.Example p.MsoListParagraph {
  font-size: 20pt; }
````

Now, instances of p.MsoListParagraph in text are rendered correctly with 11pt, but the style pane thinks that that is a modification of the basic definition of the style. So inheritance of CSS works, but is also misapplied to any style based on the given style.

The ISO template uses Based On styles. The DIS style has a separate style for embedded styles, which addresses this issue separately. The solution going forward is:

* Avoid Based On styles in our own Word stylesheets, because they are buggy
* In a stylesheet where we are forced to use both someone else's stylesheets (with Based On styles) and style inheritance rules, remove style inheritance rules involving styles that are the basis of other styles, in favour of explicit CSS markup.

The inheritance rules in the Word stylesheets are:

* div.figdl p, table.figdl p
* td.Example p.MsoListParagraph
* div.Example p.MsoListParagraph
* div.Note p.MsoListParagraph
* div.Note span.stem
* div.Note p.Sourcecode

Since MsoListParagraph is the only style on which other styles will be based, that means that the rules

* td.Example p.MsoListParagraph
* div.Example p.MsoListParagraph
* div.Note p.MsoListParagraph

are replaced, at least within ISO, with explicit font size rules.

**Comment by opoudjis** [comment]
Have sent samples, please confirm

**Comment by opoudjis** [comment]
> > imple Template uses "Figure title".
> 
> No it doesn't, it uses "Figure Title". https://www.iso.org/iso-templates.html

You are confused.

**Comment by ronaldtse** [comment]
OK I confirm that the document you sent had the correct "Figure Title" style:
<img width="534" alt="Screenshot 2022-07-05 at 10 43 57 PM" src="https://user-images.githubusercontent.com/11865/177342187-051b6221-8c08-488f-a677-dd2052242519.png">
