### ISSUE TITLE
PDF: multi-level definition lists layout uses awkward column balance

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#713]
This encoding:

```adoc
==== Identifier(longitude, latitude, elevation, elevationType)

This function generates the natural location identifier from a geographic point
location representation.

Input::
latitude::: value from -90 to +90, in decimal form, representing an angular degree,
with a maximum of 6 decimal places
longitude::: value from -180 to 180, representing an angular degree, with
a maximum of 6 decimal places
elevation::: storey identifier or ground level distance
elevationType::: "storey" or "ground"

Output:: string
```

Produces this output:
<img width="673" alt="Screenshot 2022-05-30 at 10 37 59 AM" src="https://user-images.githubusercontent.com/11865/170907127-ce0aff48-54df-4860-b5b3-2d26c5d698fa.png">

The column balance is very strange:
1. It looks like the first column is given half the space, then the second and third share the same half
2. The 3rd column does not extend to the right most margin (see that the right text alignment occupies less space than the non-table text above)

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/171031753-5a502145-d559-4f5b-8c83-4698c297d3fc.png)

**Comment by Intelligent2013** [comment]
Currently, PDF renders wrong:
![image](https://user-images.githubusercontent.com/5559926/188328346-1d5396f1-4c8e-4dbc-8cea-cf29f4f8b531.png)

Will fix it.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/188383332-7d2ac7f2-0530-4a51-b76b-320c54dde771.png)
