### ISSUE TITLE
PDF: List captions

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#715]
Follow-on from https://github.com/metanorma/metanorma-iso/issues/663

I am implementing list captions on all of ol, ul, dl as a name element. You can use that to resolve the issue identified in that ticket.

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/171140427-64e9c096-95de-4c66-a581-309c3bb10f98.png)
