### ISSUE TITLE
(URGENT, ISO 6709) Edited DIS: "List Number X" and "List Continue X" should be font size 10

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#724]
## List Number X

In latest generated Edited DIS document:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/11865/172845844-92fdbaa1-142d-46e9-9a37-cd6b51034482.png">

In original ISO 6709 Final:
<img width="316" alt="Screenshot 2022-06-09 at 9 23 19 PM" src="https://user-images.githubusercontent.com/11865/172845946-87becef7-c591-440e-b974-a600dd89718e.png">

## List Continue X

In latest generated Edited DIS document:
<img width="403" alt="Screenshot 2022-06-09 at 9 23 44 PM" src="https://user-images.githubusercontent.com/11865/172846025-33841e26-4848-4864-b65f-ac1200d8cfab.png">

In original ISO 6709 Final:
<img width="393" alt="Screenshot 2022-06-09 at 9 23 58 PM" src="https://user-images.githubusercontent.com/11865/172846075-04ebef98-4bcd-4e8c-9782-e20478a1a24d.png">

**Comment by opoudjis** [comment]
Cannot replicate.

**Comment by ronaldtse** [comment]
@opoudjis you're right about 6709. I'm actually encountering this in another document. Let me check.

**Comment by ronaldtse** [comment]
I'm still seeing this in https://github.com/metanorma/iso-19135 . Can you check?

**Comment by ronaldtse** [comment]
@opoudjis I confirm that this issue is still around in iso-19135 with Git gems or published gems.

**Comment by opoudjis** [comment]
I don't know how, but the culprit is the following CSS rule, inherited from my defaults set in the original ISO stylesheet:

````
table.MsoISOTable p, table.MsoISOTableBig p {
  font-size: 10pt; }
````

I don't know why this rule is affecting the list; it points to a table not being closed properly. In any case, the blanket use of styled paragraphs in DIS means this rule can be done away with.
