### ISSUE TITLE
(URGENT, ISO 6709) Edited DIS: Broken "List Continue 2" style within Note

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#726]
Encoding:
```adoc
A register owner holds ultimate responsibility over the register.

[NOTE]
--
Some of these responsibilities include, but are not limited to, the following:

* management, such as the appointment of supporting roles of a register;
* content of the register;
* dissemination of the contents of the register.
--

```

Rendered as:
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/11865/172985376-d021d391-d5ae-45ed-b214-a9c48fba3685.png">

1. The proper style is "List Continue 2", not "List Continue 2 (-)".

<img width="279" alt="Screenshot 2022-06-10 at 12 38 03 PM" src="https://user-images.githubusercontent.com/11865/172985502-72f6b408-184f-49e1-9dec-a1ef4d255990.png">
 
2. It should be using the Cambria font instead of Arial.

**Comment by opoudjis** [comment]
Word in Greek OS was not showing me the indented list styles without "(-)" (shrunk font size).  Now that those list styles are displaying, using those for indentation by default.

**Comment by opoudjis** [comment]
Actually, the styles were exported all along, as MsoListContinue_n; they just weren't displaying in my Word.

**Comment by opoudjis** [comment]
Need to differentiate between the numbered lists and the embedded lists, which are also "-".

**Comment by ronaldtse** [comment]
I concede that "The proper style is "List Continue 2", not "List Continue 2 (-)"." is wrong.

But "It should be using the Cambria font instead of Arial." and that the font size should be 10 is correct.

Look at List Continue 1 (-) and List Continue 3 (-). They are identical in font size (10 pt) and font (Cambria). Only List Continue 2 (-) is strange.

**Comment by opoudjis** [comment]
So the distinction between indent and embedded lists was being correctly made to begin with, this was only an issue specific to the realisation of List Continue 2-.
