### ISSUE TITLE
(ISO 8601-1/Amd 1) Auto-numbering of NOTE not working in Amendment output

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#732]
Encoding:

```adoc
[change=replace,locality="clause=4.2.2,note=1"]
== 4.2.2
autonumber:note[1]

Replace "`NOTE`" with the following:

[quote]
____
[NOTE]
The calendar year used in the week calendar and the Gregorian calendar are
independent units and do not necessarily align. An identical day as referenced
in the week calendar and the Gregorian calendar can belong to different calendar
years in their respective calendars. For instance, the first day of 2019 Week 1
(a Monday) in the week calendar is actually 2018-12-31 in the Gregorian
calendar.
____
```

This is a "singular note" (i.e. not "NOTE 1" because it is the sole note in this clause).

I tried both `autonumber:note[1]` and `autonumber:note[0]` but it gave these outputs:

<img width="736" alt="Screenshot 2022-06-21 at 8 54 39 PM" src="https://user-images.githubusercontent.com/11865/174793458-eda85ec8-bf34-441e-9865-aef9cdae85f2.png">

<img width="741" alt="Screenshot 2022-06-21 at 8 54 33 PM" src="https://user-images.githubusercontent.com/11865/174793493-b67d5be0-eb3e-4a08-a47b-fdac688242be.png">

**Comment by opoudjis** [comment]
This was not a foreseen scenario. I will implement `autonumber:note[]` to address it (on the off chance that 0 is ever used by an SDO). We cannot assume the only note cited is unnumbered, because this could be a citation of the first of a sequence of notes.

**Comment by opoudjis** [comment]
In fact, `autonumber:note[]` works already.

**Comment by opoudjis** [comment]
Documentation lost, resubmitting.
