### ISSUE TITLE
(ISO 19135) Presentation XML: discrepancy between PDF/Word presentation of Requirement

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#735]
Encoding:
(document: https://github.com/metanorma/iso-19135/tree/main/sources/iso-19135-2021)

```adoc
[.requirement]
====
The register owner shall appoint a register manager.
====

[example]
A register owner can serve as the register manager, or appoint another
organization to serve as the register manager.

[.requirement]
====
The register owner shall appoint a control body.
====

[example]
The register owner can serve as the control body, or delegate that role to a
subgroup within an entity or to the register manager.

[.requirement]
====
The register owner shall appoint a register system manager.
====

[.requirement]
====
A register owner shall specify the criteria to qualify as a proposer.
====

[.requirement]
====
A register owner shall specify the register users eligible for access to the
register.
====
```

Word:
<img width="817" alt="Screenshot 2022-06-24 at 12 58 56 PM" src="https://user-images.githubusercontent.com/11865/175459489-62a292c4-9e23-40e4-93c8-17cdb447e1ad.png">

PDF:
<img width="685" alt="Screenshot 2022-06-24 at 12 56 22 PM" src="https://user-images.githubusercontent.com/11865/175459179-f98ac885-646a-4843-a4e4-1bc7ae495b2c.png">

Both Word/PDF rendering should be in accordance with the Presentation XML.

**Comment by Intelligent2013** [comment]
ISO xslt updated - styles added for the `requirement` element:

![image](https://user-images.githubusercontent.com/5559926/175572422-0350c000-b506-4c1e-9d29-2c0acb38d8cf.png)

**Comment by ronaldtse** [comment]
Closing, this is resolved.
