### ISSUE TITLE
(ISO 19144-2) Word: List of figures cannot be regenerated

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#736]
<img width="827" alt="Screenshot 2022-06-26 at 11 06 15 PM" src="https://user-images.githubusercontent.com/11865/175818081-48806f59-7091-4906-a267-b1ef26eb4a6a.png">

After clicking on Update field, this happens:
<img width="533" alt="Screenshot 2022-06-26 at 11 06 57 PM" src="https://user-images.githubusercontent.com/11865/175818088-b48bb70c-e227-4378-afb0-c5f12bea4ad7.png">

**Comment by opoudjis** [comment]
Style name for FigureTitle is Figuretitle in DIS: ToC directive needed to be updated.

**Comment by ronaldtse** [comment]
Confirm fixed, can regenerate properly.
<img width="908" alt="Screenshot 2022-07-04 at 2 12 57 PM" src="https://user-images.githubusercontent.com/11865/177085602-d2fdfd80-3251-4c36-b034-2dbdd216f267.png">
