### ISSUE TITLE
ISO templates no longer show "Fax", but plenty of code and tests reference "Fax"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#748]
Surely these codes and tests are either obsolete, unused or just broken. The generated documents do not show "Fax" at all. There is no point in keeping these. We need to remove them.

<img width="574" alt="Screenshot 2022-07-19 at 12 51 45 PM" src="https://user-images.githubusercontent.com/11865/179660781-f473ad18-7688-4862-880a-8191cc2c1931.png">

**Comment by opoudjis** [comment]
Were already removed in https://github.com/metanorma/metanorma-iso/issues/747
