### ISSUE TITLE
Linting and formatting XSL files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#750]
I did a save in `lib/isodoc/iso/iso.amendment.xsl` and it presented me with this diff, due to my editor's behavior in removing trailing whitespace.

Good coding practices includes linting/formatting of XSL/XML files.

@Intelligent2013 can we integrate our workflow with some XSL/XML listing tool that we can run to format these files before committing them?

```diff
        <xsl:output method="xml" encoding="UTF-8" indent="no"/>
-       
-       
+
+
 
        <xsl:key name="kfn" match="*[local-name() = 'fn'][not(ancestor::*[(local-name() = 'table' or local-name() = 'figure') and not(ancestor::*[local-name() = 'name'])])]" use="@reference"/>
-       
+
        <xsl:key name="attachments" match="iso:eref[contains(@bibitemid, '.exp')]" use="@bibitemid"/>
-       
-       
-       
+
+
+
        <xsl:variable name="namespace_full">https://www.metanorma.org/ns/iso</xsl:variable>
-       
+
        <xsl:variable name="debug">false</xsl:variable>
-       
+
        <xsl:variable name="docidentifierISO_undated" select="normalize-space(/iso:iso-standard/iso:bibdata/iso:docidentifier[@type = 'iso-undated'])"/>
        <xsl:variable name="docidentifierISO_">
                <xsl:value-of select="$docidentifierISO_undated"/>
@@ -27,7 +27,7 @@
                <xsl:call-template name="getLocalizedString">
                        <xsl:with-param name="key">all_rights_reserved</xsl:with-param>
                </xsl:call-template>
-       </xsl:variable> 
+       </xsl:variable>
```

**Comment by ronaldtse** [comment]
There does not seem to be many XSL linters but there are a few:
* https://github.com/greystate/XSLT-Lint (2017)
* https://gandhimukul.tripod.com/xslt/xslquality.html (2009)
* https://www.garshol.priv.no/download/xmltools/prod/XSLLint.html (2000)

Not sure how best we can integrate.

**Comment by Intelligent2013** [comment]
XSLT supports a feature to produce pretty-print XML output (`indent="yes"`) and Xalan supports it:
```xml
<xsl:output method="xml" indent="yes" encoding="UTF-8" xalan:indent-amount="2"/>

<xsl:strip-space elements="*"/>
```
The code above removes all white-spaces and build tree-view of the XML like this:
```xml
	<xsl:variable name="contents_">
		<xsl:variable name="bundle" select="count(//ieee:ieee-standard) &gt; 1"/>
		<xsl:for-each select="//ieee:ieee-standard">
			<xsl:variable name="num">
				<xsl:number level="any" count="ieee:ieee-standard"/>
			</xsl:variable>
			<xsl:variable name="docnumber">
				<xsl:value-of select="ieee:bibdata/ieee:docidentifier[@type = 'IEEE']"/>
			</xsl:variable>
			<!-- <xsl:variable name="current_document">
				<xsl:copy-of select="."/>
			</xsl:variable> -->
			<xsl:for-each select=".">
				<!-- xalan:nodeset($current_document) -->
				<doc num="{$num}" firstpage_id="firstpage_id_{$num}" title-part="{$docnumber}" bundle="{$bundle}">
					<!-- 'bundle' means several different documents (not language versions) in one xml -->
					<contents>
						<xsl:call-template name="processPrefaceSectionsDefault_Contents"/>
						<xsl:call-template name="processMainSectionsDefault_Contents"/>
						<xsl:apply-templates select="//ieee:indexsect" mode="contents"/>
						<xsl:call-template name="processTablesFigures_Contents"/>
					</contents>
				</doc>
			</xsl:for-each>
		</xsl:for-each>
	</xsl:variable>
```
But this code is very hard to human read due removed vertical whitespaces between comments/element, sequence of elements, etc.

Therefore, the redundant white-spaces should be processed in `merge.xsl`:
- remove horizontal white-space at start of text until new line
- if text contains only horizontal white-spaces, then remove them (no strip new line)
- two and more lines should be merged into one line.

**Comment by Intelligent2013** [comment]
Xalan included XSL checking feature. Xalan starts it before applying XSL to XML. But we need to check XSL _before_ any execution in the production mode. To do this:
- create `empty.xml` on-fly like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<empty xmlns="https://www.metanorma.org/ns/iso"><!-- for XSL checking in XALAN --></empty>
```
In xml specified SDO namespace, because XSL checks namespace match between xml and xsl.

- run XALAN with `empty.xml` and XSL:
```sh
java -jar xalan.jar -IN empty.xml -XSL iso.international-standard.xsl  > nul
```
(`nul` specified for resulted xml output. Java outputs the messages to the console pipe).

If output is empty, then no errors found and run next workflow actions. If output contains any string, then stop.

Example 1: let's add the wrong tag `xsl:templates` (instead of `xsl:template`):
```xml
<xsl:templates match="tag">
	<fo:inline><xsl:value-of select="."/></fo:inline>
</xsl:templates>
```
The checking shows the error:
```
file:///....iso.international-standard.xsl; Line #10200; Column #29; xsl:templates is not allowed in this position in the stylesheet!
```
Example 2: using non-existing variable:
```
<xsl:value-of select="$variable_abcdef"/>
```
The checking shows the error:
```
file:///...iso.international-standard.xsl; Line #1985; Column #47; org.apache.xml.utils.WrappedRuntimeException: Could not find variable with the name of variable_abcdef
```
Example 3: call non-existing template:
```
<xsl:call-template name="template_12345"/>
```
The checking shows the error:
```
file:///...iso.international-standard.xsl; Line #1987; Column #45; org.xml.sax.SAXException: ElemTemplateElement error: template_12345
```

**Comment by Intelligent2013** [comment]
Done.
