### ISSUE TITLE
Update ISO FDAM PDF layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#758]
There are some layout differences between our implementation and the official ISO FDAM PDF.

We need to update our layout to match.

<img width="1764" alt="Screen Shot 2022-08-14 at 2 37 45 AM" src="https://user-images.githubusercontent.com/11865/184506632-f48f2ebb-dab4-4bf0-9ca3-3dcb543cc996.png">
<img width="1801" alt="Screen Shot 2022-08-14 at 2 38 30 AM" src="https://user-images.githubusercontent.com/11865/184506650-56c45b7d-eb55-47d7-b083-1e7ac560573a.png">
<img width="1813" alt="Screen Shot 2022-08-14 at 2 38 42 AM" src="https://user-images.githubusercontent.com/11865/184506656-3c1f8902-67f2-4971-b267-b45059dde78d.png">
<img width="1752" alt="Screen Shot 2022-08-14 at 2 39 28 AM" src="https://user-images.githubusercontent.com/11865/184506679-7e48ba5a-f137-4736-bd73-1f38b0426c1d.png">

Please see https://github.com/CalConnect/iso-8601-1-amd1/issues/11 for the comparison documents.

**Comment by Intelligent2013** [comment]
@ronaldtse ISO XSLT updated, but still there are a few differences:
- original PDF:
![image](https://user-images.githubusercontent.com/5559926/184536797-2c8763d7-1db2-42f2-ae62-9d8d0e053523.png)
...
![image](https://user-images.githubusercontent.com/5559926/184536833-d138c837-ec74-41b0-b02e-cc3b6fbdda77.png)
...
![image](https://user-images.githubusercontent.com/5559926/184536864-67c6d793-8b77-4d68-bd7f-2e556038e181.png)

generated PDF:
![image](https://user-images.githubusercontent.com/5559926/184536752-13cf57aa-2569-4e09-a85c-7860ac23ff5c.png)
...
![image](https://user-images.githubusercontent.com/5559926/184536848-cf427c87-b7b5-4c51-b0aa-bf8b51f1e616.png)
...
![image](https://user-images.githubusercontent.com/5559926/184536875-10f89952-1e6f-46fe-8ed3-2fde18608554.png)



The reason in the presentation XML:
```xml
		<docidentifier type="ISO">ISO 8601-1:2019/FDAmd 1</docidentifier>
		<docidentifier type="iso-undated">ISO 8601-1/FDAmd 1</docidentifier>
		<docidentifier type="iso-with-lang">ISO 8601-1:2019/FDAmd 1(E)</docidentifier>
		<docidentifier type="iso-reference">ISO 8601-1:2019/FDAmd 1:2022(E)</docidentifier>

```
- original PDF:
![image](https://user-images.githubusercontent.com/5559926/184537035-010a0666-80ff-42af-b703-ff18eef5ace2.png)

generated PDF:
![image](https://user-images.githubusercontent.com/5559926/184537087-8a83df3d-297e-4ef5-bec8-2955db7e68bf.png)

The reason: the source data is `approvalgroup/@identifier`:
```xml
<approvalgroup identifier="ISO/TC 154/WG 5">
```

- original PDF:
![image](https://user-images.githubusercontent.com/5559926/184537113-2c9c9978-9f3a-46fe-a3ad-47fb266f85d6.png)

generated PDF:
![image](https://user-images.githubusercontent.com/5559926/184537130-c30e9b72-3007-45d3-a4ae-715e1ba8724b.png)

The reason: no voting dates in the adoc.



- original PDF:
![image](https://user-images.githubusercontent.com/5559926/184536911-c2f8a3a4-c030-4a70-962c-a4092c44c90c.png)

generated PDF:
![image](https://user-images.githubusercontent.com/5559926/184536922-1317e930-0dc7-429b-9909-ad98a760de1a.png)


The reason: no italic in adoc.

**Comment by Intelligent2013** [comment]
<img width="1813" alt="Screen Shot 2022-08-14 at 2 38 42 AM" src="https://user-images.githubusercontent.com/11865/184506656-3c1f8902-67f2-4971-b267-b45059dde78d.png">

@ronaldtse I don't see a difference between the original and generated PDF here.

**Comment by ronaldtse** [comment]
> I don't see a difference between the original and generated PDF here.

In our version we have "+ 41" (space between + and 41), in official version it is "+41" (no space).

**Comment by ronaldtse** [comment]
@Intelligent2013 could you try to fix up the ADoc source for the issues?

The one non-resolvable issue right now is the "FDAM" identifier. It is rather strange that ISO uses both "FDAM 1" and "FDAmd 1" abbreviations. 

The project page uses "FDAmd 1":
<img width="550" alt="Screen Shot 2022-08-15 at 2 09 04 AM" src="https://user-images.githubusercontent.com/11865/184549479-6382d47d-90fc-4209-91ac-4cf48997e4e7.png">

The filename is also "FDAmd 1":
<img width="315" alt="Screen Shot 2022-08-15 at 2 09 20 AM" src="https://user-images.githubusercontent.com/11865/184549487-98919e38-1050-4649-af74-1d917b056bc7.png">

But the document uses "FDAM 1".

I think we might have to distinguish this as yet another ISO identifier (with impact on pubid-iso too).

**Comment by Intelligent2013** [comment]
> - original PDF:
> ![image](https://user-images.githubusercontent.com/5559926/184537035-010a0666-80ff-42af-b703-ff18eef5ace2.png)
> 
> generated PDF:
> ![image](https://user-images.githubusercontent.com/5559926/184537087-8a83df3d-297e-4ef5-bec8-2955db7e68bf.png)
> 
> The reason: the source data is `approvalgroup/@identifier`:
> ```xml
> <approvalgroup identifier="ISO/TC 154/WG 5">
> ```

@ronaldtse the ` identifier="ISO/TC 154/WG 5"` created by metanorma. What is the best way to omit `/WG 5` - remove workgroup from adoc or metanorma-iso gem should hide workgroup information?

> In our version we have "+ 41" (space between + and 41), in official version it is "+41" (no space).

@ronaldtse  latest metanorma-iso doesn't put redundant space. So more issue here.


adoc updated for the voting dates and terms in italic.


I've found one more difference. Quoted standalone note should be render in normal font-size:
![image](https://user-images.githubusercontent.com/5559926/184551977-7c9fb477-9fec-4890-9436-63ffcb621993.png)

but in part of section - in smaller font-size:
![image](https://user-images.githubusercontent.com/5559926/184551988-31c83711-fbd0-487a-bdfe-b62f9e2a43f6.png)

Will fix ISO xslt.

**Comment by Intelligent2013** [comment]
> I've found one more difference. Quoted standalone note should be render in normal font-size:

ISO XSLT fixed.

**Comment by Intelligent2013** [comment]
All known XSLT issues fixed. There is the issue with FDAM/FDAmd identifier (https://github.com/metanorma/pubid-iso/issues/71), but it should not affect on the XSLT.
Closing.
