### ISSUE TITLE
Applying ISO 80000-1 numbering representation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#761]
In metanorma-bipm, we have implemented the English vs French decimal practices and number separation (https://github.com/metanorma/metanorma-bipm/issues/44, https://github.com/metanorma/isodoc/pull/223)

This is actually described in  ISO 80000-1:2009.

1. ISO requires its deliverables to produce number formats according to this guidance (space separation for groups of 3 digits, use decimal comma instead of decimal point)
2. However, some TCs explicitly reject some of these rules. ISO/TC 211 enforces use of the decimal point. ISO/TC 154/WG 5 enforces no grouping of digits.3. 

What's the best way of allowing such configuration to numbers?

#### 7.3.1 General

Numbers shall be printed in roman (upright) type, irrespective of the type used in the rest of the text.

No recommendation is made or implied about the font of roman type in which symbols for numbers are to be printed.

To facilitate the reading of numbers with many digits, these may be separated into groups of three, counting from the decimal sign towards the left and the right. No group shall contain more than three digits. Where such separation into groups of three is used, the groups shall be separated by a small space and not by a point or a comma or by any other means.

EXAMPLE 1 1 234,567 8 rather than 1 234,5678 0,567 8 rather than 0,5678

...

The separation into groups of three should not be used for ordinal numbers used as reference numbers, e.g. ISO 80000-1.

The year shall always be written without a space, e.g. 1935.

#### 7.3.2 Decimal sign

The decimal sign is either a comma or a point on the line. The same decimal sign should be used consistently within a document.

If the magnitude (absolute value) of the number is less than 1, the decimal sign shall be preceded by a zero.

...

**Comment by opoudjis** [comment]
I have implemented the means of doing this in https://github.com/metanorma/metanorma-standoc/issues/664
