### ISSUE TITLE
PDF: Terms in "ISO 10241-1 systematic order" renders terms structure in wrong style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#763]
In PDF the rendering of clause styles for terms that belong to systematic order is erroneous.

1. The Index should not show these hierarchical concepts:
<img width="671" alt="Screen Shot 2022-08-23 at 2 30 30 PM" src="https://user-images.githubusercontent.com/11865/186086731-8bf35ca2-db9d-4be6-bb86-d5e49ba27b67.png">

2. Here it treats 3.20 as a "grouping clause" which has a larger font size, and is no longer in the terms and definitions style. It should look just like any other term.
<img width="670" alt="Screen Shot 2022-08-23 at 2 31 08 PM" src="https://user-images.githubusercontent.com/11865/186086844-7e7758c3-2bcf-4dc7-baac-e5ac07a1be89.png">

NOTE: This task depends on completion of #762.

"Systematic order" means that a term can have a sub-term:
<img width="680" alt="Screen Shot 2022-08-23 at 2 33 50 PM" src="https://user-images.githubusercontent.com/11865/186087277-73f66fb9-b976-49fa-a0a0-7eff38093f5d.png">

**Comment by Intelligent2013** [comment]
@ronaldtse the Metanorma presentation xml looks strange:

- the `clause` is using instead of `terms` at top level,
- the term `time of day` enclosed in the `terms` (therefore 'term' `time of day` rendered as terms section title, not as the term.).

The fragment:
```xml
<clause id="tda" obligation="normative" displayorder="5">
	<title depth="1">3<tab/>Terms and definitions</title>
	...
	<term id="term-local-time">
		<name>3.19</name>
		<preferred>
			<strong>local time</strong>
		</preferred>
		...
	</term>
	<terms id="_time_of_day" obligation="normative">
		<title depth="2">3.20<tab/>time of day</title>
		<p id="_">time occurring within a <strong>term <tt>calendar day</tt> not resolved via ID <tt>calendar-day</tt>
			</strong>
		</p>
		<note id="_">
			<name>NOTE  1</name>
			<p id="_">Generally, time of day relates to the duration elapsed after the beginning of the day. However, this correlation breaks when changes occur in the time scale that applies to the time of day, such as time shifts and <strong>term <tt>leap second</tt>, display <tt>leap seconds</tt> not resolved via ID <tt>leap-second</tt>
				</strong>.</p>
		</note>
		<note id="_">
			<name>NOTE  2</name>
			<p id="_">This definition corresponds closely with the definition of “clock time” given in <xref target="IEV">clause “113-01-18”</xref>, except that the concepts of duration and time scale are not used in this definition.</p>
		</note>
		<term id="term-basis-time-of-day">
			<name>3.20.1</name>
			<preferred>
				<strong>basis time of day</strong>
```

**Comment by ronaldtse** [comment]
Got it, so it does depend on https://github.com/metanorma/metanorma-iso/issues/762

**Comment by Intelligent2013** [comment]
Issue fixed in https://github.com/metanorma/metanorma-iso/issues/762
Now PDF renders so:
![image](https://user-images.githubusercontent.com/5559926/188327231-2c8177bb-23a9-4734-9dc5-e94b17ef62aa.png)
...
![image](https://user-images.githubusercontent.com/5559926/188327315-c3526c3b-7f03-4d70-9df2-45ddb1ffe972.png)

Closing.
