### ISSUE TITLE
Requirements: formatting in ISO 19135

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#766]
## Requirements class

Looks like this:
<img width="827" alt="Screen Shot 2022-08-24 at 2 13 02 PM" src="https://user-images.githubusercontent.com/11865/186344069-18da60ae-7fca-4683-95e9-e1ea000b2a36.png">

Source:
```adoc
[requirements_class]
.Register management roles and responsibilities
====
[%metadata]
id:: /req/roles
subject:: register roles and responsibilities
description:: Roles and responsibilities for a register that conforms with this
document.
requirement:: /req/roles/register-owner/specify-register-specification
requirement:: /req/roles/register-owner/appoint-register-manager
requirement:: /req/roles/register-owner/appoint-control-body
requirement:: /req/roles/register-owner/appoint-register-system-manager
requirement:: /req/roles/register-owner/specify-proposer-criteria
requirement:: /req/roles/register-owner/specify-user-access-eligibility
requirement:: /req/roles/register-owner/specify-proposal-process
requirement:: /req/roles/register-owner/specify-approval-time-limit
requirement:: /req/roles/register-owner/specify-appeal-process
requirement:: /req/roles/register-owner/specify-appeal-time-limit
requirement:: /req/roles/register-owner/consider-user-needs
requirement:: /req/roles/register-owner/set-terms-conditions
requirement:: /req/roles/register-manager/manage-by-register-specification
requirement:: /req/roles/register-manager/distribute-proposal-process-information
requirement:: /req/roles/register-manager/accept-proposals
requirement:: /req/roles/control-body/conform-to-governance
requirement:: /req/roles/control-body/review-proposals-render-decisions
requirement:: /req/roles/register-system-manager/conform-to-governance
requirement:: /req/roles/proposer/meet-eligibility-criteria
requirement:: /req/roles/proposer/conform-to-governance
requirement:: /req/roles/register-user/conform-to-governance
====
```

Problems:
1. "Identifier" should be the first row (not "Id", but "Identifier")
2. Don't know why "subject" became "Target type" (it is not a Target type)
3. Key column and contents should align left.
4. Each requirement it contains should be displayed with the "Requirement X" as a link, and show the ID of that requirement
  * `| Requirement | Requirement X /req/roles/register-owner/specify-register-specification`
5. The "Requirement 1-1" label is wrong -- it is just Requirement 1, there is no such thing in "Requirement 1-1" in the document.
6. Description should just look like normal text.

## Requirements

<img width="824" alt="Screen Shot 2022-08-24 at 2 16 59 PM" src="https://user-images.githubusercontent.com/11865/186344709-131c3a92-e4e8-4dbe-bb14-55faf18f154d.png">

Source:

```adoc
[requirement]
.Register owner shall create a register specification
====
[%metadata]
id:: /req/roles/register-owner/specify-register-specification
subject:: register owner
description:: A register owner shall document the register's governance
procedures and requirements in a register specification
(<<register-specification>>).
====
```

Problems:
1. "Identifier" should be the first row (not "Id", but "Identifier")
2. Missing link back to Requirements class
3. Key column and contents should align left.
4. Description should just look like normal text.

**Comment by opoudjis** [comment]
I have to assume that these are general Modspec requirements, and not specific to ISO.

**Comment by opoudjis** [comment]
You know, things are going to be a lot smoother if the markup isn't utterly wrong.

I refer you to https://www.metanorma.org/author/ogc/topics/requirements/ . Ronald has suggested markup choices before I implemented it, and I disagreed with his choices, and I am allowed to disagree with his choices.

* All instances of `requirement::` and `requirement_class::` are to be replaced with `target::`
* The identifier for a requirement is marked up as `identifier::`, not `id::`; `id` as an attribute would end up confused with the Metanorma anchor for a block (as occurs elsewhere in Metanorma). Therefore, all instances of `id::` are to be replaced with `identifier::`

That takes care of the first problem:

Wrong markup:

`requirement::` should be `target::`
`requirement_class::` should be `target::`
`id::`should be `identifier::`

<img width="932" alt="Στιγμιότυπο 2022-08-25, 21 22 13" src="https://user-images.githubusercontent.com/1911039/186651939-2649f562-90e4-479f-8ecb-04d46cc7ea95.png">

**Comment by opoudjis** [comment]
> Don't know why "subject" became "Target type" (it is not a Target type)

For the past few years, the subject of a requirements class specifically has been "Target type":

https://www.metanorma.org/author/ogc/topics/requirements/#reqt_class

> subject
> (mandatory) The Target Type. Rendered as Target Type.

Your objection is invalid. It is a target type. That is what I have been told to implement for requirement classes.

**Comment by opoudjis** [comment]
> Key column and contents should align left.

All tables under ISO are centered in HTML. Making an exception for requirement tables is in my opinion a mistake. I'm doing it under protest.

Implementing by creating a global Modspec css style for isodoc in HTML. Leaving Word alone, the issue of centering does not arise there anyway.

**Comment by opoudjis** [comment]
> Each requirement it contains should be displayed with the "Requirement X" as a link, and show the ID of that requirement

`| Requirement | Requirement X /req/roles/register-owner/specify-register-specification`

> The "Requirement 1-1" label is wrong -- it is just Requirement 1, there is no such thing in "Requirement 1-1" in the document.

I am absolutely certain the hyperlinking of nested recommendations, and expectation of sensible identifiers, has never been implemented, and I am having to implement it from scratch. Not happy, this should be just a migration of code, not an implementation of new functionality.

**Comment by opoudjis** [comment]
> Missing link back to Requirements class

This was also never implemented before. This ticket is slipping in new development under the pretext of debugging.

**Comment by opoudjis** [comment]
Done. If there are outstanding issues, I will require a new ticket to be raised. Doing new release of mn-requirements, this has been a significant change to Modspec rendering.

**Comment by ronaldtse** [comment]
> Your objection is invalid. It is a target type. That is what I have been told to implement for requirement classes, because that's what Modspec calls them.

You are correct. Indeed Modspec does call the "standardization target" the "standardization target type". The actual physical thing (instance) that is being tested in a conformance test, is called the "standardization target" in ModSpec. This nomenclature is rather strange...

<img width="513" alt="Screen Shot 2022-08-26 at 10 59 15 AM" src="https://user-images.githubusercontent.com/11865/186808267-69b79712-6460-467d-a5e5-123c177a0f14.png">

**Comment by opoudjis** [comment]
modspec components need to maintain their anchor ids in the new rendering, so that xrefs to them can be updated.
