### ISSUE TITLE
HTML: (regression) Title intro and title main now missing long dash in between

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#767]
Now:
<img width="933" alt="Screen Shot 2022-08-26 at 10 29 37 AM" src="https://user-images.githubusercontent.com/11865/186803636-7e8392d5-22de-41ee-96d6-cbe5c1a3bd5f.png">

Before (it was 19135-1 before, but now just 19135, so the part title was removed):
<img width="916" alt="Screen Shot 2022-08-26 at 10 30 32 AM" src="https://user-images.githubusercontent.com/11865/186803738-ee642e7f-236d-44a4-be88-7f9d25e75beb.png">

**Comment by opoudjis** [comment]
Named HTML escapes like `&html;` no longer being recognised in HTML templates because of XHTML processing in Nokogiri 1.13. Need to be removed globally.
