### ISSUE TITLE
Requirements (ModSpec): for requirements/conformance tests, provide link back to the class

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#768]
A requirement should provide a link back to its requirements class(es). As in:

```
| Included in: | Requirements class 1 /req/xxx
```

A conformance test should provide a link back to its conformance class(es).

```
| Included in: | Conformance class 1 /conf/xxx
```

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-iso/issues/766#issuecomment-1227380406_

**Comment by opoudjis** [comment]
Also going to introduce proper i18n for labels in the mn-requirements gem, rather than expecting labels to be supplied by the calling gem. (They can still be overridden by the calling gem.)
