### ISSUE TITLE
Requirements (ModSpec): All ModSpec tables should be rendered as Tables in ISO

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#769]
ISO Directives does not permit "requirements" as a document element and we need to implement them as "tables". 

In OGC, "requirements" is a real element. In ISO, it has to be represented as tables.

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-iso/issues/766#issuecomment-1227151447_

**Comment by opoudjis** [comment]
This has already been done in Presentation XML, why has this ticket been assigned?
