### ISSUE TITLE
PDF: review layout of ISO DIS 8601-1/Amd 1

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#772]
Shared https://github.com/CalConnect/iso-8601-1-amd1/tree/main/submission/20210727-damd-proof

Compare with the Metanorma generated PDF:
https://github.com/CalConnect/iso-8601-1-amd1/tree/main/submission/20210708-DAmd/documents

**Comment by Intelligent2013** [comment]
@ronaldtse ISO XSLT updated (but not merged yet, https://github.com/metanorma/mn-native-pdf/tree/iso_dam)

There are a differences between original and generated PDFs:

- ### difference in document identifier:
Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/187070308-613ec317-9305-4d00-9e30-1db9bbb8dec9.png)
Original PDF:
![image](https://user-images.githubusercontent.com/5559926/187071286-58562a1e-b39d-4298-9888-f39c1461f463.png)


Reason in presentation XML: `<docidentifier type="ISO">ISO 8601-1:2019/DAmd 1</docidentifier>`

- ### editorial group is missing in rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/187070503-ecc6b013-8f8b-4ab8-9d4a-123be2aa4a49.png)

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/187070529-be498291-0046-4b79-90c3-d907ff356ff2.png)

Reason: `<approvalgroup identifier="ISO/TC 154/WG 5">` is missing in XML.

- ### Foreword section title
Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/187071241-6e7389d6-bdb6-4c17-bf4a-b0ab770918b0.png)

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/187071252-d764c57e-3428-4aee-9fbc-0cc11cd86a2d.png)

In FDAM original PDF there isn't such prefix before Foreword.
**Question**: should I put it specially for DAM stage via XSLT?

- ### different styles in the main section
Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/187071478-d579fc0f-9a7b-49b3-a577-e766dbb165c0.png)


Original PDF:
![image](https://user-images.githubusercontent.com/5559926/187071459-a99ef491-017d-47f5-b54c-356f2347a078.png)

There are differences in:
- section title - italic vs. bold
- left indent for amendment text
- smaller font-size for Notes

Currently, the styles in XSLT based on original FDAM PDF:
![image](https://user-images.githubusercontent.com/5559926/187071613-1a0404d6-8120-415b-99f8-ac9243240af3.png)

**Question**: should I  use the different styles for FDAM and DAM?

**Comment by ronaldtse** [comment]
## Difference in document identifier

This is an issue with https://github.com/metanorma/pubid-iso/issues/77 . We will deal with this separately.

## editorial group is missing in rendered PDF:

When the editorial group is provided, will the output be correct?

## Foreword section title

This seems to be an error in encoding on the ISO side, that is the French title name. We don't need to fix this.

## different styles in the main section

Again, this is an error on ISO side. We follow the FDIS styling.

**Comment by Intelligent2013** [comment]
> ### editorial group is missing in rendered PDF:
> When the editorial group is provided, will the output be correct?

The presentation XML in https://github.com/CalConnect/iso-8601-1-amd1/tree/main/submission/20210708-DAmd/documents is very old (version `1.8.6` vs. latest `2.1.7`). I've regenerated XML (preliminary change adoc `:docstage: 50` to `:docstage: 40`) and now the editorial group is present, but the issue from FAMD ticket https://github.com/metanorma/metanorma-iso/issues/758#issuecomment-1214435957 occurs:

![image](https://user-images.githubusercontent.com/5559926/187152607-6bc8381f-e5f8-48a6-bc08-cd64fe80b2ba.png)


> - original PDF:
> ![image](https://user-images.githubusercontent.com/5559926/184537035-010a0666-80ff-42af-b703-ff18eef5ace2.png)
> 
> generated PDF:
> ![image](https://user-images.githubusercontent.com/5559926/184537087-8a83df3d-297e-4ef5-bec8-2955db7e68bf.png)
> 
> The reason: the source data is `approvalgroup/@identifier`:
> ```xml
> <approvalgroup identifier="ISO/TC 154/WG 5">
> ```

> @ronaldtse the ` identifier="ISO/TC 154/WG 5"` created by metanorma. What is the best way to omit `/WG 5` - remove workgroup from adoc or metanorma-iso gem should hide workgroup information?

**Comment by Intelligent2013** [comment]
ISO XSLT with DAmd update here: https://github.com/metanorma/metanorma-iso/pull/773

**Comment by ronaldtse** [comment]
@Intelligent2013 actually at DIS stage the approval group is the TC.

**Comment by Intelligent2013** [comment]
Document update. Now it renders correctly:
![image](https://user-images.githubusercontent.com/5559926/187417322-f7718dc1-2c5d-4955-9185-1f9760b0741b.png)

**Comment by ronaldtse** [comment]
Thanks, closing. However, why do we need to add `approval-agency`?

**Comment by Intelligent2013** [comment]
> Thanks, closing. However, why do we need to add `approval-agency`?

@ronaldtse you are right, no need to add it. Default value 'ISO' added automatically into XML. Adoc updated.
