### ISSUE TITLE
Bibliography: Metrologia citation not rendering much information

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#775]
I suspect this is a relaton-rendering issue and a missing data issue?

The source:
```adoc
* [[[GUINOT,BIPM Metrologia 34 3 261]]], GUINOT, B. Application of general relativity to metrology. In: _Metrologia 34, 261-290_. 1997.
```

The rendering:
<img width="623" alt="Screen Shot 2022-08-30 at 12 46 54 PM" src="https://user-images.githubusercontent.com/11865/187351427-507f9607-9ab6-4e40-910f-98aadaf2e922.png">

The data:
```xml
<bibdata type="standard">
  <fetched>2022-08-30</fetched>
  <title format="text/plain" language="en" script="Latn">Application of general relativity to metrology</title>
  <title format="text/plain" language="en" script="Latn">Application of general relativity to metrology</title>
  <uri type="src">https://iopscience.iop.org/article/10.1088/0026-1394/34/3/9</uri>
  <uri type="doi">https://doi.org/10.1088/0026-1394/34/3/9</uri>
  <docidentifier type="BIPM">Metrologia 34 3 261</docidentifier>
  <date type="published">
    <on>1997-06-01</on>
  </date>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>{IOP} Publishing</name>
    </organization>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname language="en" script="Latn">Guinot</surname>
      </name>
    </person>
  </contributor>
  <language>en</language>
  <script>Latn</script>
  <abstract format="text/plain" language="en" script="Latn"/>
  <series>
    <title type="main" format="text/plain" language="en" script="Latn">Metrologia</title>
  </series>
  <ext>
    <doctype>article</doctype>
  </ext>
</bibdata>
```

Potential rendering (this is sloppy):
* GUINOT, B. Application of general relativity to metrology. In: _Metrologia Vol. 34, Issue 3, Page 261-290_. 1997. Available at: https://iopscience.iop.org/article/10.1088/0026-1394/34/3/9 (DOI: 10.1088/0026-1394/34/3/9)

I suppose that the DATA isn't even sufficient. There is no mention of the Volume, Issue or the Page Numbers. We must provide them properly.

**Comment by ronaldtse** [comment]
This is blocking https://github.com/CalConnect/iso-34010/issues/1

**Comment by opoudjis** [comment]
From memory, data about individual articles is simply not available to Relaton, and I'm not convinced it will become available.

If it will not become available, then Relaton generating Metrologia citations is pointless, and if anything we should remove Metrologia as a recognised Relaton prefix. The article should instead be marked up as AsciiBib or in span notation. (I'm about to expand it to deal with such citations: https://github.com/metanorma/metanorma-standoc/issues/668, although that's currently low in the list.)

Over and above that: if the item is marked with `bibitem/@type` =  `standard`, instead of `article`, then relaton-render, entirely correctly, will treat it as a standard and not an article. Standards do not have authors, journal titles, or page numbers. Therefore, relaton-bipm is in error in calling Metrologia articles standards.

This is nothing whatsoever to do with relaton-render, it is purely an issue of relaton-bipm, and whether it is an appropriate mechanism for publishing Metrologia citations. I am unassigning myself accordingly.

**Comment by andrew2net** [comment]
The new release v 1.13.3 produces CCTF/CGPM/CIPM documents with type= article.
Also fixed:
- An issue with the extent/locality. Now the documents contain the extent/locality elements with volume/issue/page types. So volume, issue, and page metadata are available for making strings like "Metrologia Vol. 34, Issue 3, Page 261-290".
- DOI identifiers are parsed now.

**Comment by opoudjis** [comment]
Now being rendered as:

Metrologia 34 3 261, GUINOT. Application of general relativity to metrology. Metrologia. vol. 34; no. 3; pp. 261–290. {IOP} Publishing. June 1, 1997. Metrologia 34 3 261. https://doi.org/10.1088/0026-1394/34/3/9.

There are things I have to fix here, such as suppressing the doc identifier for articles, and implementing the ISO rendering template for articles, but this is now correct, and @andrew2net, you are providing all information required.

**Comment by ronaldtse** [comment]
There are several rendering issues:
1. The data is missing the given name initial "GUINOT, B.", "B." is missing.
2. The publisher "{IOP} Publishing" is incorrect. The `{IOP}` syntax is a remnant of the BibTeX syntax to indicate that "IOP" should not be changed capitalization (different citation styles render capitalization differently). The proper rendering here is "IOP Publishing".
3. The "document identifier" (quoted, because there is no "defined document identifier") here is repeated as a prefix and as a suffix, which both are superfluous and should be removed ("Metrologia 34 3 261" should not be in the citation)
4. In ISO deliverables we should use the ISO 690 format, which renders it as:

"GUINOT, B. Application of general relativity to metrology. _Metrologia_. IOP Publishing, June 1, 1997. Vol. 34; no. 3; pp. 261–290. Available from: https://doi.org/10.1088/0026-1394/34/3/9."

* Place and publisher goes before location. Numeration and page number comes after.
* Series name should be emphasized for location purposes.
* DOI is to appear with "Available from"

<img width="612" alt="Screen Shot 2022-09-05 at 4 24 08 PM" src="https://user-images.githubusercontent.com/11865/188403465-d5c5af96-f78a-463c-874f-95ed8226b590.png">

**Comment by opoudjis** [comment]
Currently renders as:

`<formattedref><smallcap>Guinot, B</smallcap>. Application of general relativity to metrology. <em>Metrologia</em>. June 1, 1997, vol. 34; no. 3; p. 261. Available from: <span class="biburl"><link target="https://dx.doi.org/10.1088/0026-1394/34/3/9">https://dx.doi.org/10.1088/0026-1394/34/3/9</link></span>.</formattedref>`

This matches exactly what you asked for, so I'm closing this ticket.

I'm raising the bug with pages elsewhere.
