### ISSUE TITLE
(URGENT) Requirements should be rendered as real Tables in ISO documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#777]
Word:

<img width="446" alt="Screen Shot 2022-08-31 at 1 12 16 PM" src="https://user-images.githubusercontent.com/11865/187597416-3a941ce1-045a-4e83-bc74-00db1aa6f0c2.png">

PDF: 

<img width="614" alt="image" src="https://user-images.githubusercontent.com/11865/187597229-8158719e-1069-4ee5-a20c-971ef5a72781.png">

It should look like this instead, and the Requirements URIs should be shown:
<img width="519" alt="Screen Shot 2022-08-31 at 1 24 11 PM" src="https://user-images.githubusercontent.com/11865/187598708-6db3441a-3d95-452d-9415-18e43298b811.png">

NOTE: Notice this table is somehow split across two, this clearly is a bug.

**Comment by ronaldtse** [comment]
The "description" field should be shown explicitly, not a merge of two column cells.

**Comment by ronaldtse** [comment]
The table width should be max width.

**Comment by ronaldtse** [comment]
Sample of the desired rendering:

<img width="618" alt="Screen Shot 2022-08-31 at 1 19 45 PM" src="https://user-images.githubusercontent.com/11865/187598254-30d8ff5f-899b-4308-a550-0309a23a4a9a.png">

**Comment by ronaldtse** [comment]
Desired Requirements class rendering:

<img width="598" alt="Screen Shot 2022-08-31 at 1 49 22 PM" src="https://user-images.githubusercontent.com/11865/187603524-43630fb4-fb23-480e-a567-d5e4d709cd30.png">

**Comment by opoudjis** [comment]
You are working off obsolete versions of the code, which had not been merged, the requirement URIs are displaying now.

**Comment by opoudjis** [comment]
> NOTE: Notice this table is somehow split across two, this clearly is a bug.

I have enough to do already. I am not actioning this, and keeping tables on one page is an utterly unreasonable request, as you will find out soon enough if I implement it, and then you complain about it with a too-large table.

**Comment by opoudjis** [comment]
Provisions is only being implicitly specified, which is poor practice from both OGC and the ticket author.

**Comment by opoudjis** [comment]
This ticket is introducing the completely repulsive requirement of flavour-specific post-processing of modspec

**Comment by opoudjis** [comment]
Changes that turn out to have been ISO-specific, I have introduced to general Modspec in mn-requirements. This is a mess, and the outputs will need to be reviewed for OGC and for ISO.

**Comment by opoudjis** [comment]
Restoring as default behaviour for Modspec the OGC behaviour of identifier spanning both columns.

**Comment by opoudjis** [comment]
- [ ] The "Requirement 1: ..." text should become the Table caption.
- [ ] The "Identifier" field name should be shown explicitly. The value of the identifier should be shown in monospace font (probably should be encoded as such?)
- [ ] The "Description" field should be shown explicitly, not a merge of two column cells.
- [ ] The table width should be max width.
- [ ] Numbering of notes and examples in tables and notes by clause, as with rest of ISO (being under tables)
- [ ] Provisions grouping of included requirements

**Comment by ronaldtse** [comment]
## Table should use normal table style

Requirements are rendered in a table (which is good) but the borders are currently missing. In OGC, all tables are not rendered with borders because OGC applies background colors to headers and cells.

<img width="893" alt="Screen Shot 2022-09-01 at 12 43 39 AM" src="https://user-images.githubusercontent.com/11865/187733417-cce35ecc-f163-4899-ac2e-3317503a2afd.png">


## Requirements class rendering should render associated requirements ID only

The "red box" below is the actual requirements content of Requirement 1, but it should have been rendered as shown in the blue (the red box should be removed).

<img width="924" alt="Screen Shot 2022-09-01 at 12 44 38 AM" src="https://user-images.githubusercontent.com/11865/187733855-fa57f789-5ed6-4aa2-9295-f098545cc0b8.png">

**Comment by opoudjis** [comment]
All tables under ISO are max width already.

**Comment by opoudjis** [comment]
This ticket is now implemented, pending review from @ronaldtse

**Comment by ronaldtse** [comment]
## Need to set table cells as left align

<img width="553" alt="Screen Shot 2022-09-02 at 1 10 08 PM" src="https://user-images.githubusercontent.com/11865/188063289-486179c1-b4a9-49c4-8991-84a528e502cd.png">

## "Requirement" description should be called "Statement"

In a requirement, the phrase should be "statement" (I can change the encoding), because the statement is the "thing" to be complied with.

<img width="609" alt="Screen Shot 2022-09-02 at 1 10 54 PM" src="https://user-images.githubusercontent.com/11865/188063364-980c1707-7f9d-4b7c-98c5-6628864e2275.png">

In a requirements class, the term "Description" is correct, because it is the description of what the requirements class is.

## Citations of ModSpec instances outside ModSpec instances

Right now, they show up as "{modspec class name} {number}: {modspec instance id}" within ModSpec instances. This is good.

<img width="597" alt="Screen Shot 2022-09-02 at 1 14 59 PM" src="https://user-images.githubusercontent.com/11865/188063782-0497517d-c508-4c74-90b0-11eea0f1ee9b.png">

But in other body content, references look like this:

<img width="503" alt="Screen Shot 2022-09-02 at 1 15 41 PM" src="https://user-images.githubusercontent.com/11865/188063857-98f01ad6-acfb-4684-a649-15f84b9835cd.png">

Now, this is confusing. ModSpec instances are implemented as Tables, they should point to table references instead. However, the ideal way to point to them is to refer to them as "Requirement: 123" without the long identifier. I don't know what is the correct way of doing this.

**Comment by opoudjis** [comment]
> "Requirement" description should be called "Statement"

Note: not doing either in OGC, explicit label as Requirement or Statement is only done in ISO.

**Comment by opoudjis** [comment]
For this to work, am storing both Modspec xref including identifier, and excluding it (as `@anchors[id][:xref_bare]`)
