### ISSUE TITLE
(URGENT) Requirements linking should display "{provision class} N {provision identifier}"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#779]
Instead of this, 

<img width="635" alt="Screen Shot 2022-08-31 at 1 59 15 PM" src="https://user-images.githubusercontent.com/11865/187604943-fb433202-f633-48b7-b497-5607438a3c93.png">

It should show:
<img width="626" alt="Screen Shot 2022-08-31 at 1 59 57 PM" src="https://user-images.githubusercontent.com/11865/187605047-dba4a257-0089-48e4-9057-5d879608580a.png">

**Comment by opoudjis** [comment]
Is this a Modspec requirement or an ISO requirement.

**Comment by ronaldtse** [comment]
This should be for both OGC and ISO.

**Comment by opoudjis** [comment]
So dependencies and indirect dependencies are to be treated if possible consistently with other requirement links.

**Comment by opoudjis** [comment]
Currently modspec is treating links to targets and classes differently from other links it renders (the former include the requirement name as a Metanorma crossreference, the latter use just the identifier). Making consistent.
