### ISSUE TITLE
Requirements: in ISO, "Guidance" should appear last in table

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#790]
Right now "Guidance" appears before "Statement", but "Guidance" should always appear last.

```adoc
[requirement]
.Appointment of a register manager
====
[%metadata]
identifier:: /req/roles/register-owner/appoint-register-manager
subject:: register owner
description:: The register owner shall appoint a register manager.
guidance:: A register owner can serve as the register manager or appoint another
organization to serve as the register manager.
====
```

<img width="662" alt="Screen Shot 2022-09-08 at 10 46 10 PM" src="https://user-images.githubusercontent.com/11865/189152986-c13743af-8144-4227-b9ee-eb5dc1f62f1d.png">

**Comment by opoudjis** [comment]
Guidance is an adhoc classification that is completely new to me. I am not convinced this is a legitimate requirement, as opposed to the requirement being that descriptions not appear out of order. Is guidance a stable, ongoing Modspec tag, that will always appear last in all tables?

**Comment by ronaldtse** [comment]
"Guidance" is a new, optional attribute for ModSpec instances. This is because NOTEs and EXAMPLEs cannot be reasonably inserted in tables given that they are numbered within a clause, not within the requirement.

e.g.
<img width="530" alt="image" src="https://user-images.githubusercontent.com/11865/189804957-95299867-9e64-40a6-be63-7815a0dff661.png">
