### ISSUE TITLE
Requirement: cross-references within Requirement instances should use "title" instead of "identifier"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#793]
We have received feedback that it is preferable to show the requirement title rather than the requirement identifier in cross-references within requirement instances.

<img width="660" alt="Screen Shot 2022-09-12 at 11 14 27 AM" src="https://user-images.githubusercontent.com/11865/189567357-a153b40d-491f-40a5-8971-5eb8165f32b5.png">

Instead of "Requirement 82: /req/register-item/change-management", the idea is to display "Requirement 82: Individual management of register items", which is the requirement title.

This is the definition of Requirement 82.
<img width="678" alt="Screen Shot 2022-09-12 at 11 18 36 AM" src="https://user-images.githubusercontent.com/11865/189567773-8aba9fbb-b8f4-419c-b237-39dba65ccb34.png">

In addition, in the rendering of requirement instances like the Requirement (same example), the reference to the Requirements class can also refer to the title "Requirements class 15: Register item implementation and operations" instead of the identifier.

<img width="671" alt="Screen Shot 2022-09-12 at 11 16 08 AM" src="https://user-images.githubusercontent.com/11865/189567515-9bf9a56a-03c1-498b-bd89-5bc2c1891334.png">

Thanks.

**Comment by opoudjis** [comment]
Metanorma does not have the spare capacity to go backwards and forwards tinkering with rendering because external agencies are uncertain about what they want.

**Comment by opoudjis** [comment]
I am going to take this as ISO-only.

**Comment by ronaldtse** [comment]
@opoudjis that's correct. Thank you.

**Comment by opoudjis** [comment]
I am also not extending this to cross-references to requirements from elsewhere in the text: they remain link + identifier, as they are in OGC.
