### ISSUE TITLE
Unnumbered introduction with sub-clauses

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#795]
Source tickets: https://github.com/metanorma/mnconvert/issues/190, https://github.com/metanorma/mnconvert/issues/201

I review implementation of ISO to NISO STS XML (mnconvert) according to [Guidelines for coding IEC and ISO standards in NISOSTS.pdf](https://github.com/metanorma/mnconvert/files/9429314/Guidelines.for.coding.IEC.and.ISO.standards.in.NISOSTS.pdf).
In the section `4.2.4 Introduction` (page 16),  there is case for ISO document:
> b) Unnumbered introduction with sub-clauses: 
> If the introduction is not numbered but has sub-clauses, ...

Currently, if Introduction has sub-clauses, then the clauses have numbers `0. Introduction`, `0.1....`, `0.2 ...`, etc. (this case is `c) Introduction with numbered subclauses:` in the Guidelines)

Is there a possibility to turn off the numbering for the clauses/sub-clauses?

@ronaldtse common question - should we support this case?

Some month ago, we've added 'Floating titles' feature (https://www.metanorma.org/author/topics/document-format/sections/#floating-titles), but it seems this case is another.

**Comment by ronaldtse** [comment]
Looks like it is an elaborated use case from ISO, so perhaps we should have an option for this. Instead of an option on the document, perhaps it should be an option on the Introduction heading.

**Comment by ronaldtse** [comment]
Let me also ask ISO/CS directly about this. They may have an opinion.

**Comment by opoudjis** [comment]
You could, sadly, drive a truck through the wording of the current ISO/IEC DIR 2, 13.4:

https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor177

> The Introduction shall not have a clause number. If it is necessary to create numbered subdivisions, the subclauses are numbered 0.1, 0.2, … .

I interpreted that as a sane implementor, "any subdivisions must be numbered". ISO might interpret this with frivolous laxity, as "the numbering of subdivisions is at the whim of the author." If that is the case, 

1. I do not agree that Metanorma should indulge it
2. Metanorma should indeed indulge it only at the explicit request of ISO/CS, and
3. this kind of indulgence can only be realised with a document attribute flagging the suspension of numbering of the introduction in Presentation XML: it is emphatically not a Semantic XML concern, and as @Intelligent2013 correctly says, it has nothing to do with floating titles, which are explicitly outside of any title hierarchy.

This issue goes on hold pending ISO/CS response.

**Comment by ronaldtse** [comment]
I have sought confirmation from ISO.

-------
In ISO Directives Part 2, 13.4 "Numbering and subdivision” says:

"
The Introduction shall not have a clause number. If it is necessary to create numbered subdivisions, the subclauses are numbered 0.1, 0.2, … .
“

-------
In the “Guidelines for coding IEC and ISO standards in NISO STS” document, 4.2.4 “Introduction”, it says:

Under 4.2.4 the “ISO” section, it has 3 options:
"
a) Unnumbered introduction with no subclauses
b) Unnumbered introduction with sub-clauses:
If the introduction is not numbered but has sub-clauses, for the introduction use as above:
…
and for the sequence of the sub-clauses use:
...
and so on.
c) Introduction with numbered subclauses:
"

-----

Does this mean that the following cases are possible with the Introduction?

1. Introduction if without any subclause, is unnumbered
2. Introduction with subclauses can be numbered as “0 Introduction”, “0.1 …”, “0.2 …”? (I’ve seen in some documents?)
3. Introduction with subclauses can be numbered as “Introduction”, “0.1 …”, “0.2 …”? (I’ve seen in some documents?)
4. Introduction with subclauses can be complete unnumbered

**Comment by ronaldtse** [comment]
Reply from ISO/CS:

> Please follow the editorial rule in the ISO/IEC Directives, Part 2, i.e. do not number the Introduction; if subclauses are added, number them as 0.1, 0.2, etc.

So the “Introduction” should never be numbered as 0, and subclauses in the introduction are always numbered.
