### ISSUE TITLE
Embedding a 2nd-level definition list after the `description::` attribute of a Requirement leads to strange rendering

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#804]
```
[conformance_class]
====
[%metadata]
identifier:: xxx
description:: yyy
====
```

Works.

```
[conformance_class]
====
[%metadata]
identifier:: xxx
description:: yyy
Scope::: zzz
====
```

Spaghetti included in the description:

<img width="774" alt="Screen Shot 2022-09-29 at 3 18 37 PM" src="https://user-images.githubusercontent.com/11865/192965669-52560aad-2469-4f24-89c2-789eaa36eabd.png">

**Comment by opoudjis** [comment]
Ronald, OF COURSE it's nonsense. If you make up fantasy markup like this, you're going to get spaghetti, and you have been persisting in making up nonsense lately.

The Description `<dd>` is parsed as a block, and it is shoved somewhat brutally into a table structure. I have not implemented any notion of nesting within descriptions, I reject the implications of it, and I reject even more strongly that I should try and mind-read what the implications of it should be. Description should be marked up as an open block at most.

Do not call something a bug when you've never requested the behaviour.

**Comment by ronaldtse** [comment]
🤣  There was clearly an assumption that the definition list is one level, but that expectation is not expressed in the documentation. As creative as I am, clearly there are users that will run into it.

This means we should define appropriate behavior here or raise the appropriate errors.

**Comment by opoudjis** [comment]
So:

````
     [requirement,model=ogc]
      ====
      [%metadata]
      description:: Interpolated description
      scope::: random
      widgets::: randomer
      ====
````

is generating the Semantic XML:

````
<description><p id="_adcde73f-62d3-a19b-aa4c-0a4c3a77ad1e">Interpolated description</p>
<classification><tag>scope</tag><value>random</value></classification><classification><tag>widgets</tag><value>randomer</value></classification>
</description>
````

A year on, I'm not going to fight this novel requirement. classifications within descriptions need to be rendered like classifications outside of descriptions, whether that is as table or as definition list. Given that we are already within a table, I'm going to assume it to be definition list.

That is a Presentation XML manipulation.

**Comment by opoudjis** [comment]
The presentation is  as a definition list within a table; so the foregoing is now rendered as:

![Screenshot 2023-11-19 at 00 37 00](https://github.com/metanorma/metanorma-iso/assets/1911039/4980198c-6b9b-4798-ac1a-f0ad4a9b1716)
