### ISSUE TITLE
Do not enforce ban on "see" references to normative main clauses

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#807]
In ISO, "see" is not meant to be used for references to normative bibliographic entries (ISO/IEC DIR 2 15.5.3), or cross-references normative annexes (ISO/IEC DIR 2 20.2). However there is no good evidence that this ban applies to normative clauses in the main section of the standard (which is all of them), and ISO/IEC DIR 2 uses "see" for references to main clauses all the time.

On the other hand, https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-s-informative states:

> Unless there is a clear requirement (“shall”) or imperative language in the text, all document content is informative by default.

Right now, Metanorma assumes by default that document section content is normative, and it complains if "see" is used to cross reference any clause in the main section of the document. A rule saying "do not use _see_ to reference normative clauses in the main part of the document is not explicit in ISO/IEC DIR 2 now; only annexes and external references are spoken about.

https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-r-ref_within says that "see is used for informative cross-references, but it implies that main section text can indeed be informative:

> When referring to a specific element of the document, use only the element identifier (number or letter):
> 
> “…in accordance with Clause 7”
> “…as shown in Figure 4”
> “…the limits specified in Table 12”
> “…the method described in Annex B”
> “…calculated using Formula (5)”
> “…fulfilling list items a) to d) in 8.4.5”
> 
> It is permitted to refer to an element informatively without making it part of the sentence:
>
> “…the prepared sample (Figure 6)”
> “…using the syntax (see Annex C)”

We know that Terms & Definitions are officially meant to be normative. But "See 3.4.1" for terms is used all the time, and that indicates that ISO does NOT follow the rule about normative references to a main clause.

We have the following alternatives:

* Main clauses by default remain normative, complain about using "see" to reference them
* Main clauses by default become informative, complain about using "see" to reference them if they are explicitly made normative (but "see 3.4.1" would still be an error, and I would need to change code to make terms and definitions normative explicitly)
* Suppress the complaint about "see" to reference normative main clauses, since ISO does not seem to be following that rule itself.

The latter is my recommendation.

**Comment by opoudjis** [comment]
@ronaldtse for your decision

@manuelfuenmayor as discussed

**Comment by opoudjis** [comment]
@ronaldtse Reminder: this needs your decision.

**Comment by ronaldtse** [comment]
What's the context here? What exactly is the problem?

**Comment by opoudjis** [comment]
Suppress the complaint about "see" to reference normative main clauses, since ISO does not seem to be following that rule itself. Not clear that the rule was ever intended to apply to main content anyway.

**Comment by ronaldtse** [comment]
As you have pointed out, the "see" issue only happens to bib entries and annexes. ISO DIR 2 does not apply this check in the references to main content.

Let's get rid of this check for main content.
