### ISSUE TITLE
ISO XSLT: published documents determination

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#811]
Source: https://github.com/metanorma/pubid-iso/issues/125#issuecomment-1266741185

To do: 

~>  replace the test for published documents, from abbreviation = IS, to abbreviation attribute missing.~
> replace the test for published documents, from abbreviation = `IS`, to stage = 60.

**Comment by opoudjis** [comment]
abbreviation = TR is now going to happen for technical reports with status = 60, and I am still obligated to report it as the state abbreviation.

I think you should instead make the test be stage >= 60.

**Comment by opoudjis** [comment]
Who said anything about substages.

>:-|

**Comment by ronaldtse** [comment]
If there are no substages, how can this `stage >= 60` ever happen?

**Comment by ronaldtse** [comment]
And BTW the stage codes 90/95 have no effect on the PubIDs.

**Comment by opoudjis** [comment]
....

You're gonna cop it.

Who said **anything** about substages?

PRF, as 60.00, is treated the same as 60.60. stage is a separate element from substage, and the only place where they are being turned into floating point is you having them concatenate for urn_stage.

I do not give a crap whether the stage codes 90/95 have any effect on the PubIDs. They have an effect on the cover page, which is what is under discussion here. This is Alex's ticket, not Artur's.

**Comment by ronaldtse** [comment]
Thanks for the clarification that clears up my misplaced assumptions.

> I do not care whether the stage codes 90/95 have any effect on the PubIDs. They have an effect on the cover page, which is what is under discussion here.

Stage codes 90/95 have also no effect on the cover page of ISO deliverables.

**Comment by Intelligent2013** [comment]
> I think you should instead make the test be stage >= 60.

In this case PRF also will be treated as IS. But for PRF we have to render `PROOF/ÉPREUVE` in some places:
![image](https://user-images.githubusercontent.com/5559926/193868376-eadfb1ce-7df5-4b9e-bd0b-4062e8b45b3d.png)
...
![image](https://user-images.githubusercontent.com/5559926/193868527-9a4d5676-6ce1-4494-9b2d-4315062dc9a8.png)

It seems I have to return to the earlier version of ISO XSLT and determine stage abbreviation depends on stage and substage values (numbers)...
But this code is still workable, i.e. if abbreviation is empty, then it determines by stage/substage:
```xml
<xsl:variable name="abbreviation" select="normalize-space(/iso:iso-standard/iso:bibdata/iso:status/iso:stage/@abbreviation)"/>

<xsl:variable name="stage-abbreviation">
	<xsl:choose>
		<xsl:when test="$abbreviation != ''">
			<xsl:value-of select="$abbreviation"/>
		</xsl:when>
		<xsl:when test="$stage = 0 and $substage = 0">PWI</xsl:when>
		<xsl:when test="$stage = 0">NWIP</xsl:when> <!-- NWIP (NP) -->
		<xsl:when test="$stage = 10">AWI</xsl:when>
		<xsl:when test="$stage = 20">WD</xsl:when>
		<xsl:when test="$stage = 30">CD</xsl:when>
		<xsl:when test="$stage = 40">DIS</xsl:when>
		<xsl:when test="$stage = 50">FDIS</xsl:when>
		<xsl:when test="$stage = 60 and $substage = 0">PRF</xsl:when>
		<xsl:when test="$stage = 60 and $substage = 60">IS</xsl:when>
		<xsl:when test="$stage &gt;=60">published</xsl:when>
		<xsl:otherwise></xsl:otherwise>
	</xsl:choose>
</xsl:variable>
```
So may be no need to change anything in ISO XSLT.

**Comment by ronaldtse** [comment]
> In this case PRF also will be treated as IS. But for PRF we have to render PROOF/ÉPREUVE in some places:

@Intelligent2013 is correct here.

In the code:
```xml
		<xsl:when test="$stage &gt;=60">published</xsl:when>
```

The stages with numbers larger than 60 (i.e. 90, 95) are still considered "IS" though. Not sure what this line does.

There is a misunderstanding in this ticket:
1. There is a "stage" object from the PubID.
2. There is the "type-stage abbreviation" from the PubID.

When @opoudjis says "abbreviation is empty", he means the "type-stage abbreviation" is empty. i.e. the case where "ISO 12345" will have a "type-stage abbreviation" empty because the "IS" abbreviation is never displayed.

However, "ISO 12345" will still give you Stage 60, which has the abbreviation of "IS". The code is given here:
* https://github.com/metanorma/pubid-iso/blob/651d7ccb0baab7ae8aa9f57157415af2d0337e14/lib/pubid/iso/stage.rb

Also, BTW, very important for @opoudjis and @Intelligent2013:
* "PRF" is stage 50.00. "FDIS" can also be 50.00. There is no way to differentiate them according to stage code (this is official ISO). You can only differentiate these two by the abbreviations.
* "60.00" and "60.60" are both "IS".

**Comment by Intelligent2013** [comment]
> Does this mean I should now provide both, as distinct attributes?

@opoudjis I think yes. On my opinion, any data should be present in the explicitly form, without any assumptions based on background knowledge.

**Comment by opoudjis** [comment]
@Intelligent2013 It is going to be weeks until you see this, but I'm going to make `/bibdata/stage/status/@abbreviation` be the *untyped* abbreviation, and /bibdata/ext/stagename/@abbreviation` be the *typed* abbreviation. Hold off until this is implemented.

**Comment by Intelligent2013** [comment]
I've just generated the presentation XML for https://github.com/metanorma/mn-samples-iso/blob/main/sources/international-standard/rice-en.final.adoc:
```xml
<iso-standard xmlns="https://www.metanorma.org/ns/iso" type="presentation" version="2.4.2">
	<bibdata type="standard">
		<title language="en" format="text/plain" type="main">Cereals and pulses — Specifications and test methods — Rice (Final)</title>
...
		<status>
			<stage language="">60</stage>
			<stage language="en">International Standard</stage>
			<substage>60</substage>
		</status>
		<ext>
...
			<stagename>International Standard</stagename>
		</ext>
	</bibdata>
```
So, no `@abbreviation` at all.

Currently, in ISO XSLT:
```xml
	<xsl:variable name="stage" select="number(/iso:iso-standard/iso:bibdata/iso:status/iso:stage)"/>
	<xsl:variable name="substage" select="number(/iso:iso-standard/iso:bibdata/iso:status/iso:substage)"/>	
...
	<xsl:variable name="abbreviation" select="normalize-space(/iso:iso-standard/iso:bibdata/iso:status/iso:stage/@abbreviation)"/>
		
	<xsl:variable name="stage-abbreviation">
		<xsl:choose>
			<xsl:when test="$abbreviation != ''">
				<xsl:value-of select="$abbreviation"/>
			</xsl:when>
			<xsl:when test="$stage = 0 and $substage = 0">PWI</xsl:when>
			<xsl:when test="$stage = 0">NWIP</xsl:when> <!-- NWIP (NP) -->
			<xsl:when test="$stage = 10">AWI</xsl:when>
			<xsl:when test="$stage = 20">WD</xsl:when>
			<xsl:when test="$stage = 30">CD</xsl:when>
			<xsl:when test="$stage = 40">DIS</xsl:when>
			<xsl:when test="$stage = 50">FDIS</xsl:when>
			<xsl:when test="$stage = 60 and $substage = 0">PRF</xsl:when>
			<xsl:when test="$stage = 60 and $substage = 60">IS</xsl:when>
			<xsl:when test="$stage &gt;=60">published</xsl:when>
			<xsl:otherwise></xsl:otherwise>
		</xsl:choose>
	</xsl:variable>
```
I.e. if `status/stage/abbreviation` is empty, then the abbreviation determined by `stage` and `substage`.
Note: the value `published` is using just for cases when no need to use concrete abbreviation value in the XSLT, but the abbreviation shouldn't be empty.

Looks like no need to change anything in ISO XSLT.
