### ISSUE TITLE
Requirement: monospace text showing up as font-size 11, not font-size 10 as for normal tables

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#816]
Wrong font size 11:
<img width="695" alt="Screen Shot 2022-10-18 at 10 34 24 AM" src="https://user-images.githubusercontent.com/11865/196322132-f825efa4-689f-4125-aceb-319773278fcc.png">

Correct font size 10:
<img width="690" alt="Screen Shot 2022-10-18 at 10 34 38 AM" src="https://user-images.githubusercontent.com/11865/196322161-edd6dfdc-5dd9-422e-8fe7-e902c7a03735.png">

**Comment by opoudjis** [comment]
This is a feature of the built in styles of DIS: 

* there is no distinct style for smaller ISOCode
* there is no explicit font size for ISOCode, so ISOCode is *meant* to inherit font size from its surroundings
* however, the document ISO 6709 has associated with ISOCode:

````
	mso-ansi-font-size:11.0pt;
	mso-bidi-font-size:14.0pt;
 ````

which are enforcing 11pt.

I can manually shrink the font size, but that's a distortion I don't want to introduce. In reality, this is a problem the DIS stylesheet is not addressing (unlike for block styles, where there are smaller font variants).

I could introduce a stylesheet rule to shrink the font size for code in tables and quotes; or I could remove the mso-ansi-font-size and mso-bidi-font-size CSS attributes. (The former is an MSO synonym of font-size.) I'd be inclined to go to do the latter.

I will obligatorily mention that us tinkering with the DIS stylesheet is counterproductive, when the entire point of us adopting the DIS stylesheet was to have zero difference between what we generate and what ISO Editorial generates. I further will mention that you trying to make the document look nicer than what ISO have provided for, in a DRAFT format stylesheet, is an abuse of resources.

This is not a Metanorma bug. If all formatting is meant to be dictated by the stylesheet, and there should be no font size settings done by authors, this is an ISO Editorial oversight of neglecting to provide an ISOCode-- style. If ISO Editorial is meant to be manually setting font sizes, I want to hear that explicitly from them, as it contradicts the whole point of having a stylesheet.

In either  case, I will not implement anything without explicit instruction from ISO Editorial on how they format such cases internally. The entire point of the DIS stylesheets was that we generate identical output to them.

**Comment by ronaldtse** [comment]
I’ve sent an email seeking clarification.

**Comment by ronaldtse** [comment]
From ISO/CS:

As long as the font type is set to Courier New (or the “ISOCode” style is used), the code text will be correctly identified by the ISO/CS XML processing tools and the font size will be further adjusted per the defined template. In the generated PDF file, the font size of code text is 9pt.

**Comment by opoudjis** [comment]
This actually means that ISO do not care about the font size in the DIS documents they receive. We could try to shrink the font size to approximate it to print quality, as we do in general (9pt, in fact). But we must not do so by altering the stylesheet: the stylesheet really does have to be left alone. And this is not something ISO requires us to do, it's something we are electing to do.

So I will attempt to address this by inserting a span wrapper with the desired font size, but it becomes a less pressing concern.

**Comment by opoudjis** [comment]
It's a basic oversight in the DIS stylesheets: Code, Code-, Code-- as *paragraph* styles have smaller font sizes, 11pt > 9pt > 8pt, but this has not been extended to the character style ISOCode.

I'm going to implement this with the fake character style ISOCode-, ISOCodeitalic-, ISOCodebold-, and replace them with spans. That way, if ISO decided to introduce these character styles, we could adopt them; and the implementation can stay consistent with how we do other smaller character styles.

**Comment by opoudjis** [comment]
````

`ABC` DEF

|===
| `ABC` | DEF
|===
````

renders in Word DIS as:

![Screenshot 2023-11-18 at 23 15 40](https://github.com/metanorma/metanorma-iso/assets/1911039/182ab1a5-d1d6-4771-abab-504d02e09bb7)

It's a little hard to see, but ISOCode within a table, and any other class with a smaller font, is 9 pt instead of 11 pt.
