### ISSUE TITLE
(URGENT) BIPM citations using wrong source link (raw.githubcontent.com)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#817]
<img width="659" alt="Screen Shot 2022-10-18 at 8 51 39 PM" src="https://user-images.githubusercontent.com/11865/196434500-0a3ce02a-2190-4183-9ccb-b5542f066823.png">

The correct URL is:
* https://www.bipm.org/en/committees/cg/cgpm/26-2018

**Comment by andrew2net** [comment]
fixed in https://github.com/relaton/relaton-bipm/issues/38#issuecomment-1282632764

**Comment by ronaldtse** [comment]
Thanks @andrew2net , does @opoudjis need to update Metanorma to use those links (filter by type??)

**Comment by andrew2net** [comment]
@ronaldtse Nick asked me to make those links [here](https://github.com/relaton/relaton-bipm/issues/38#issuecomment-1259358420). I think he knows what to do with it.

**Comment by opoudjis** [comment]
The filter has already been implemented. Keep this ticket open so I can confirm it working.

**Comment by opoudjis** [comment]
Duplicates https://github.com/metanorma/bipm-si-brochure/issues/192
