### ISSUE TITLE
(URGENT) PDF: long URLs escapes page margins

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#820]
A picture worth a dozen words.

<img width="609" alt="Screen Shot 2022-10-18 at 9 00 56 PM" src="https://user-images.githubusercontent.com/11865/196436685-42ec2312-c35e-416c-b49d-e996e8b56b6d.png">

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

**Comment by Intelligent2013** [comment]
Same issue for `tt`:
![image](https://user-images.githubusercontent.com/5559926/196630194-36edecec-7106-4c5f-b556-5b264ce802aa.png)

**Comment by Intelligent2013** [comment]
Fixed (in https://github.com/metanorma/mn-native-pdf/tree/xslt_update, but not merged yet):
![image](https://user-images.githubusercontent.com/5559926/196659168-5d7d1d88-ccbf-4aa5-b27a-a6e45e722d01.png)

**Comment by Intelligent2013** [comment]
Done.
