### ISSUE TITLE
Extra horizontal whitespace before Clause 3 list items compared to ISO copy, should be removed

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#824]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/11865/197707194-12a55119-89d8-4925-a655-3df3695ffb56.png">

**Comment by opoudjis** [comment]
I will not action this without you naming a specific authoritative ISO document to reference. I have implemented the DIS stylesheet, and I'm not going to keep tweaking it without you giving a lot more information than this. I have zero confidence now that ISO is producing consistent output.

**Comment by ronaldtse** [comment]
This is from ISO 34000 when I submitted to FDIS.

**Comment by opoudjis** [comment]
Ok, please supply me with the ISO edited document you are comparing this to

**Comment by ronaldtse** [comment]
@opoudjis it is compared with the ISO editor's edits. There is not supposed to be any whitespace between the list item bullet and the text.

**Comment by ronaldtse** [comment]
Clarification: there is an extra blank "whitespace" character (horizontal whitespace) between the list label to the first word of that list item. That empty whitespace char should be removed.
