### ISSUE TITLE
From DIS stage onwards, display ISO Editor watermark

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#825]
ISO/DIS 19115-3
<img width="946" alt="Screen Shot 2022-10-25 at 4 06 22 PM" src="https://user-images.githubusercontent.com/11865/197718588-fa00ccfc-2b62-4559-9b21-26238583c3f6.png">

ISO/DIS 34000
<img width="939" alt="Screen Shot 2022-10-25 at 4 06 52 PM" src="https://user-images.githubusercontent.com/11865/197718695-37bc52ab-5e4d-4703-bd58-335181713f45.png">

ISO 8601-1/DAmd 1
<img width="782" alt="Screen Shot 2022-10-25 at 4 07 21 PM" src="https://user-images.githubusercontent.com/11865/197718797-94d66289-2b5e-45a5-81e2-0090dc86a7d4.png">

The editor watermark seems to have changed.

Previously, which is now implemented in our template, it was:
* "Edited DIS - MUST BE USED FOR FINAL DRAFT"

Now, it only shows:
* Edited DIS - MUST BE USED"

HOWEVER, as we have discovered, the "FOR FINAL DRAFT" line is actually just being hidden, look at DIS 34000:

Original:

<img width="804" alt="Screen Shot 2022-10-25 at 4 11 24 PM" src="https://user-images.githubusercontent.com/11865/197719779-3d0930f3-5f4f-41ec-b23a-55747886ece3.png">

Expanded vertically:
<img width="751" alt="Screen Shot 2022-10-25 at 4 11 41 PM" src="https://user-images.githubusercontent.com/11865/197719833-e339f133-7e5a-41af-8bfa-348836f66cf1.png">

Wow. The ISO Editors instead of removing the "FOR FINAL DRAFT" words, they just shrunk the "Word Art" box until those words disappeared.

What we need to do here is to copy one of the instances of these document headers/footers and include this word art "watermark" into ISO DIS/FDIS generated outputs.

**Comment by opoudjis** [comment]
In addition: instead of suppressing colour in published documents by stripping colour from the stylesheet, we will override the background, conditional on a document attribute `iso-word-bg-strip-color`, which by default is set to true.

**Comment by opoudjis** [comment]
Watermark in received documents is two lines, and truncated. Cannot replicate that, appears not to be supported in Word HTML; will extend Watermark frame instead to fit text.
