### ISSUE TITLE
HTML: preferred and admitted terms should not be indented

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#831]
From @reeseplews:

indented abbreviated terms
![SMART_Vocabulary_-_2022-10-26_11_09_25](https://user-images.githubusercontent.com/11865/197918302-83801eb0-2fa5-4cc6-b484-16eba2dbe575.png)

indented admitted terms
![SMART_Vocabulary_-_2022-10-26_11_09_04](https://user-images.githubusercontent.com/11865/197918288-015c4923-1c67-49cc-b6fb-0965b630df9f.png)

```
$ metanorma version
Metanorma 1.5.1
Metanorma::Cli 1.6.4
Metanorma::Standoc 2.2.6/IsoDoc 2.3.3
Metanorma::ISO 2.2.2
Metanorma::Iec 2.1.11
Metanorma::IEEE 0.1.1
Metanorma::Ietf 3.0.12
Metanorma::Generic 2.2.3
Metanorma::BIPM 2.1.11
Metanorma::CC 2.1.11
Metanorma::Csa 2.1.11
Metanorma::IHO 0.6.11
Metanorma::M3AAWG 2.1.11
Metanorma::UN 0.9.11
Metanorma::Ogc 2.2.5
Metanorma::ITU 2.1.11
```

**Comment by ReesePlews** [comment]
hello @opoudjis thank you for addressing this issue. i updated my metanorma install using   choco upgrade metanorma -y and the iso template is now showing as Metanorma::Standoc 2.2.6/IsoDoc 2.3.3  or Metanorma::ISO 2.2.2 (from the metanorma version command output). i confirm that the word file and pdf are fixed but i am having problems seeing the fixes in the HTML output. i have tried a browser in a private window and a different browser but there appears to be no change. when you have time, can you check this. thank you

**Comment by opoudjis** [comment]
Releases are fortnightly, and we've just had one. You're not going to see the change until next release, which is November 7, although you can  pull metanorma-iso from github if you want to see it sooner: set your Gemfile to:

gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso"

**Comment by ReesePlews** [comment]
thank you, i am new to metanorma, and i could not find anything called "*gem*" in my working folder nor my chocolatey folder,  (running on windows 10 with powershell) so i will just wait for the next release.  for my current needs it is working well. thank you.

**Comment by opoudjis** [comment]
Ok, not to stuff you around, but if you do do so, its contents need to be:

````
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso"
gem "sassc"
````

and you then need to issue the commands:

````
bundle update
bundle exec metanorma ....
````

with `bundle exec` prefixed to the metanorma command.

If that doesn't work out, then yeah, releases are every two weeks, and the code does tend to move fast! Please do let me know how you're going. I can't promise to respond to all tickets promptly, as there is a large backlog of work, but we do want to be helpful. I assume you're familiar with the documentation on metanorma.org?

**Comment by ReesePlews** [comment]
@opoudjis thank you for this additional information; have not tried it, when i can get back to this task, i will let you know if it works;

**Comment by opoudjis** [comment]
Next release is on Monday 7 Nov anyway, so if you don't get to it in a hurry, that will take care of this. But you will need to do this in general if you need to see changes before the release; and you may end up having to import an entire stack of gems, depending on where the update has been made (this is a complex bit of software: at most,

````
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc"
gem "isodoc", git: "https://github.com/metanorma/isodoc"
gem "metanorma", git: "https://github.com/metanorma/metanorma"
gem "sassc"
````

Which is why normally we tell people outside our team to wait till next release :)

**Comment by ReesePlews** [comment]
@opoudjis thank you for this additional information; i dont think i understand the underlying system enough to try and make these updates, so i will wait until the 7th. i appreciate the information you have provided. on the 7th will my installed version automatically use the updated templates or is a command needed for updating? there is no hurry for a reply.

**Comment by opoudjis** [comment]
You'll need to do an update command,  which is just "bundle update" in your working directory. Leave it till late on the 8th to be double sure...

**Comment by ronaldtse** [comment]
@opoudjis I have worked interactively with @ReesePlews to resolve this issue. He now has a full development chain setup and we have confirmed the issue is fixed.
