### ISSUE TITLE
PDF: Table with header row should not continue the first row if there is another header row following

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#833]
Original:
<img width="632" alt="Screen Shot 2022-10-27 at 11 40 43 AM" src="https://user-images.githubusercontent.com/11865/198185849-a0480a94-d886-4dc4-a6a3-5b622f57c3df.png">

Generated:
<img width="636" alt="Screen Shot 2022-10-27 at 11 39 52 AM" src="https://user-images.githubusercontent.com/11865/198185769-1abb180a-c496-4ea3-80e7-207ff1c78ad3.png">

**Comment by Intelligent2013** [comment]
In the presentation XML first table row marked up as table header (inside `thead`, not `tbody`):
```xml
<table id="tableA-1">
	<name>Table A.1 — Information security controls</name>
	<thead>
		<tr>
			<th valign="top" align="left">5</th>
			<th colspan="2" valign="top" align="left">Organizational controls</th>
		</tr>
	</thead>
	<tbody>
		<tr>
		...
		</tr>
		<tr>
			<th valign="top" align="left">6</th>
			<th colspan="2" valign="top" align="left">People controls</th>
		</tr>
```
therefore this row repeats on each page.


Adoc:
```
[[tableA-1]]
.Information security controls
[cols="a,a,a"]
|===
h| 5 2+h| Organizational controls

| 5.1 | Policies for information security | *Control*
...

h| 6 2+h| People controls
```

I'll try to modify the adoc.

**Comment by Intelligent2013** [comment]
Added `[%noheader]`  in https://github.com/metanorma/iso-27001/pull/4.
(found here https://docs.asciidoctor.org/asciidoc/latest/tables/add-header-row/#deactivate-the-implicit-assignment-of-header)

PDF renders now so:
![image](https://user-images.githubusercontent.com/5559926/198708707-685b28c5-f114-4fe0-a3e2-987442af14fb.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 . @metanorma/editors could you please help document this in metanorma.org ? Thanks!
