### ISSUE TITLE
PDF: Refine published layout using compare of documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#834]
Some of these may need help from @opoudjis . Document at: https://github.com/metanorma/iso-27001/

## TOC of introduction

Original:
<img width="586" alt="Screen Shot 2022-10-27 at 11 44 41 AM" src="https://user-images.githubusercontent.com/11865/198186331-dec61fd9-d062-4581-8591-69da365ea9b5.png">

Generated:
<img width="591" alt="Screen Shot 2022-10-27 at 11 44 28 AM" src="https://user-images.githubusercontent.com/11865/198186307-8929ff6e-0ce7-452b-8f9b-d916254fcfb0.png">

## Introduction layout

Original:
<img width="586" alt="Screen Shot 2022-10-27 at 11 44 02 AM" src="https://user-images.githubusercontent.com/11865/198186255-82d201ba-5ee9-4de9-be90-71862bdaefea.png">

Generated:
<img width="575" alt="Screen Shot 2022-10-27 at 11 44 10 AM" src="https://user-images.githubusercontent.com/11865/198186274-be46b67d-b141-483e-ac9e-343ecf277d70.png">

## Rendering of cross-reference ranges

Original:
<img width="555" alt="Screen Shot 2022-10-27 at 11 46 49 AM" src="https://user-images.githubusercontent.com/11865/198186564-0eb4d537-6837-4fb3-a2b5-9ec044b9733b.png">

Generated:
<img width="564" alt="Screen Shot 2022-10-27 at 11 46 28 AM" src="https://user-images.githubusercontent.com/11865/198186537-0908afdf-3fab-4c1b-9e47-11efcc13b169.png">

## Rendering of cross-reference ranges in external bibliographic item

Original: 
<img width="552" alt="Screen Shot 2022-10-27 at 11 49 58 AM" src="https://user-images.githubusercontent.com/11865/198186939-8955f14a-188e-4fac-98f4-136fa490efbb.png">

Generated:
<img width="584" alt="Screen Shot 2022-10-27 at 11 50 10 AM" src="https://user-images.githubusercontent.com/11865/198186963-db82144e-e3a6-4aee-a866-0df245408a36.png">

## Spacing

Original:
<img width="553" alt="Screen Shot 2022-10-27 at 11 49 10 AM" src="https://user-images.githubusercontent.com/11865/198186867-935d1eec-3777-44f4-a2a4-05b804ccb4c6.png">

Generated:
<img width="580" alt="Screen Shot 2022-10-27 at 11 48 55 AM" src="https://user-images.githubusercontent.com/11865/198186852-44686f81-0170-4a81-bde7-b50ce1ce9c88.png">

## Table border width

Original:
<img width="548" alt="Screen Shot 2022-10-27 at 11 50 42 AM" src="https://user-images.githubusercontent.com/11865/198187027-af548c15-2598-46ed-b927-78c7c529cc5a.png">

Generated:
<img width="580" alt="Screen Shot 2022-10-27 at 11 50 31 AM" src="https://user-images.githubusercontent.com/11865/198187004-b6e90d91-4bb1-43cb-b39b-ac14733971b8.png">

## Table continuation

Original:

<img width="541" alt="Screen Shot 2022-10-27 at 11 51 06 AM" src="https://user-images.githubusercontent.com/11865/198187059-dc963415-e99a-41cc-89b0-6ea305b04d59.png">

Generated:
<img width="577" alt="Screen Shot 2022-10-27 at 11 51 13 AM" src="https://user-images.githubusercontent.com/11865/198187089-431a7bd2-9b94-40b2-a881-0edd6df86c5c.png">

Also, the original preferred not to split a row, but the generated version splits rows:

<img width="622" alt="Screen Shot 2022-10-27 at 11 52 19 AM" src="https://user-images.githubusercontent.com/11865/198187232-74dd1839-cc74-4a1b-b567-a9979beac8a2.png">

**Comment by Intelligent2013** [comment]
> ## TOC of introduction
>
> Original:
> <img width="586" alt="Screen Shot 2022-10-27 at 11 44 41 AM" src="https://user-images.githubusercontent.com/11865/198186331-dec61fd9-d062-4581-8591-69da365ea9b5.png">
> 
> Generated:
> <img width="591" alt="Screen Shot 2022-10-27 at 11 44 28 AM" src="https://user-images.githubusercontent.com/11865/198186307-8929ff6e-0ce7-452b-8f9b-d916254fcfb0.png">

There are two options in practice:
- unnumbered: `Introduction` (this document 27001)
- numbered: `0 Introduction` (see example https://cdn.standards.iteh.ai/samples/76365/9153c2e641564b9d8e6eadd5855d622f/ISO-DIS-30422.pdf, found via Google by request `iso "0 introduction" 2021 pdf`)

Issue about Introduction clause/sub-clauses numbering raised here: https://github.com/metanorma/metanorma-iso/issues/795

To do in XSLT:
- [ ]  no need render any sub-clauses for Introduction in ToC.

**Comment by Intelligent2013** [comment]
> ## Introduction layout

Fixed (vertical space and font-size):
![image](https://user-images.githubusercontent.com/5559926/198378548-2c2313ac-36a1-49af-8c0f-fe9530d3ba6f.png)

**Comment by Intelligent2013** [comment]
> ## Rendering of cross-reference ranges in external bibliographic item

Source document.adoc updated in PR https://github.com/metanorma/iso-27001/pull/3.

Cross-reference ranges in PDF renders so now:
![image](https://user-images.githubusercontent.com/5559926/198381668-cbbd233a-6893-48db-b4cc-1ed2fe0918a8.png)
(note: `Clause` instead of `Clauses` relates to the issue `Rendering of cross-reference ranges`)

**Comment by Intelligent2013** [comment]
> ## Rendering of cross-reference ranges
> 
> Original:
> <img width="555" alt="Screen Shot 2022-10-27 at 11 46 49 AM" src="https://user-images.githubusercontent.com/11865/198186564-0eb4d537-6837-4fb3-a2b5-9ec044b9733b.png">
> 
> Generated:
> <img width="564" alt="Screen Shot 2022-10-27 at 11 46 28 AM" src="https://user-images.githubusercontent.com/11865/198186537-0908afdf-3fab-4c1b-9e47-11efcc13b169.png">

@opoudjis 1. please put `Clauses` instead of `Clause` for ranges (also, for table(s), annex(es), etc.)

2. Currently all phrase `Clause 4 to 10` points to `cls4` (`target="cls4"):
```xml
<xref target="cls4">
	<location target="cls4" connective="from"/>
	<location target="cls10" connective="to"/>Clause <span class="citesec">4</span> to <span class="citesec">10</span>
</xref>
```
Could you add the attributes `target` for each `span` like this:
```
<xref target="cls4">
	<location target="cls4" connective="from"/>
	<location target="cls10" connective="to"/>Clause <span class="citesec" target="cls4">4</span> to <span class="citesec" target="cls10">10</span>
</xref>
```
or make something similar? Thanks.

> ## Rendering of cross-reference ranges in external bibliographic item
> 
> Original: 
> <img width="552" alt="Screen Shot 2022-10-27 at 11 49 58 AM" src="https://user-images.githubusercontent.com/11865/198186939-8955f14a-188e-4fac-98f4-136fa490efbb.png">
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/5559926/198381668-cbbd233a-6893-48db-b4cc-1ed2fe0918a8.png)

The same issue as `1.`.

**Comment by Intelligent2013** [comment]
> ## Spacing

- [x] Fixed:
![image](https://user-images.githubusercontent.com/5559926/198582598-c5908f0a-c3aa-4e31-84c9-48e7cf92303d.png)

**Comment by Intelligent2013** [comment]
> ## Table continuation
>
>Original:
>
><img width="541" alt="Screen Shot 2022-10-27 at 11 51 06 AM" src="https://user-images.githubusercontent.com/11865/198187059-dc963415-e99a-41cc-89b0-6ea305b04d59.png">
>
>Generated:
><img width="577" alt="Screen Shot 2022-10-27 at 11 51 13 AM" src="https://user-images.githubusercontent.com/11865/198187089-431a7bd2-9b94-40b2-a881-0edd6df86c5c.png">


@ronaldtse initially, ISO XSLT rendered the continued table header as in original PDF (https://github.com/metanorma/mn-native-pdf/issues/177, from May 5, 2020, closed June 7, 2020), i.e. `Table N (continued)`.
But later (between June 7, 2020 and Sep 3, 2020), I've changed XSLT and now the table continued header contains full table caption and word `(continued)`. In the issue https://github.com/metanorma/metanorma-iso/issues/420 (from Sep 3, 2020, closed Sep 7, 2020) there is a screenshot with the full table caption.
I can't find the reason why I've made such changes. In the GH history https://github.com/metanorma/mn-native-pdf/commits/master?after=d7d2d76982f4c54a1d04ace1681e4e746b2402cb+384&branch=master&path%5B%5D=xslt_src&path%5B%5D=common.xsl&qualified_name=refs%2Fheads%2Fmaster there is a gap between `on Jul 16, 2020` and `on Feb 9, 2021`:
![image](https://user-images.githubusercontent.com/5559926/198701887-cb6a0657-9176-4e75-88ea-f683b9ee541b.png)

Would you like to revert back the changes and render `Table N (continued)`?

**Comment by Intelligent2013** [comment]
> Also, the original preferred not to split a row, but the generated version splits rows:
>
><img width="622" alt="Screen Shot 2022-10-27 at 11 52 19 AM" src="https://user-images.githubusercontent.com/11865/198187232-74dd1839-cc74-4a1b-b567-a9979beac8a2.png">

I have to try the widows/orphans control for the table cells.

**Comment by Intelligent2013** [comment]
> Also, the original preferred not to split a row, but the generated version splits rows:

Fixed:
![image](https://user-images.githubusercontent.com/5559926/198825618-fbe79ef6-6ade-4a21-a802-94689aac6e12.png)

One more issue occurs:
## Top border is very thin:
![image](https://user-images.githubusercontent.com/5559926/198825641-8291b538-4663-4289-8e1e-67627cef86d1.png)
And left part is showing only in 200% scale:
![image](https://user-images.githubusercontent.com/5559926/198825657-ebf2af0a-ed9d-4f7c-b9af-75dce16d0114.png)
Will fix it.

**Comment by Intelligent2013** [comment]
- [ ] Issue with part title, it renders without indent and `Part x`:
![image](https://user-images.githubusercontent.com/5559926/198830485-beceae07-71ca-4bc7-848d-dd9dfce356ef.png)

**Comment by Intelligent2013** [comment]
> Also, the original preferred not to split a row, but the generated version splits rows:

The fix works wrong for table with long text in the cell:
![image](https://user-images.githubusercontent.com/5559926/198830592-a519f637-a6a4-4af8-abd7-d516b6ce34b6.png)
Will revert back.

**Comment by Intelligent2013** [comment]
> ### Top border is very thin:

Fixed:
![image](https://user-images.githubusercontent.com/5559926/198833906-d4dd155f-6d51-47d3-ac48-e49cd8737214.png)

**Comment by Intelligent2013** [comment]
> Also, the original preferred not to split a row, but the generated version splits rows:

Fixed: if the paragraph in the table cell in `strong`, then XSLT sets the property `keep-with-next="always"`. It allows to keep the 'sub-headers' inside table cells with next text without split across pages:
![image](https://user-images.githubusercontent.com/5559926/198847945-9a347a5a-687c-4a0b-b72a-8461cdbaefd1.png)

**Comment by Intelligent2013** [comment]
The remaining issue is https://github.com/metanorma/metanorma-iso/issues/834#issuecomment-1295302894)
> ## Table continuation

**Comment by Intelligent2013** [comment]
> ## Table continuation

Fixed:
![image](https://user-images.githubusercontent.com/5559926/202867436-de54cda2-7b9b-4e2b-9668-a0846899fcf5.png)

The rest issues:

> ## Rendering of cross-reference ranges

> ## Rendering of cross-reference ranges in external bibliographic item

relate to https://github.com/metanorma/metanorma-iso/issues/836.
ISO XSLT should be checked additionally after fixing it. On hold.

**Comment by Intelligent2013** [comment]
> ## Rendering of cross-reference ranges
> ## Rendering of cross-reference ranges in external bibliographic item

Fixed:
![image](https://user-images.githubusercontent.com/5559926/203153269-0ae3f8ac-c2ac-4ef5-ab12-d589c39fd9c8.png)

...

![image](https://user-images.githubusercontent.com/5559926/203153374-3b8dd0f7-66ef-4c18-a091-4a6474718a90.png)

All done.
