### ISSUE TITLE
Plural form of localities for ranges

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#836]
Source issue: https://github.com/metanorma/metanorma-iso/issues/834

> ## Rendering of cross-reference ranges
> 
> Original:
> <img width="555" alt="Screen Shot 2022-10-27 at 11 46 49 AM" src="https://user-images.githubusercontent.com/11865/198186564-0eb4d537-6837-4fb3-a2b5-9ec044b9733b.png">
> 
> Generated:
> <img width="564" alt="Screen Shot 2022-10-27 at 11 46 28 AM" src="https://user-images.githubusercontent.com/11865/198186537-0908afdf-3fab-4c1b-9e47-11efcc13b169.png">

@opoudjis 1. please put `Clauses` instead of `Clause` for ranges (also, for table(s), annex(es), etc.)

2. Currently all phrase `Clause 4 to 10` points to `cls4` (`target="cls4"):
```xml
<xref target="cls4">
	<location target="cls4" connective="from"/>
	<location target="cls10" connective="to"/>Clause <span class="citesec">4</span> to <span class="citesec">10</span>
</xref>
```
Could you add the attributes `target` for each `span` like this:
```
<xref target="cls4">
	<location target="cls4" connective="from"/>
	<location target="cls10" connective="to"/>Clause <span class="citesec" target="cls4">4</span> to <span class="citesec" target="cls10">10</span>
</xref>
```
or make something similar? Thanks.

> ## Rendering of cross-reference ranges in external bibliographic item
> 
> Original: 
> <img width="552" alt="Screen Shot 2022-10-27 at 11 49 58 AM" src="https://user-images.githubusercontent.com/11865/198186939-8955f14a-188e-4fac-98f4-136fa490efbb.png">
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/5559926/198381668-cbbd233a-6893-48db-b4cc-1ed2fe0918a8.png)

The same issue as `1.`.

**Comment by opoudjis** [comment]
By the way, I provided singular and plural locality names in the i18n YAML files two years ago: https://github.com/metanorma/isodoc/commit/64e9bcc71e56ed33f7e00ef4b4c0a8b5249a00f0 . It's only getting used now.

I guess I was thinking ahead :)

**Comment by opoudjis** [comment]
The span markup you've pointed to is specific to ISO. To maintain discrete targets for each component of the range, I will need instead to embed xref in xref:

````
<xref target="cls4">
	<location target="cls4" connective="from"/>
	<location target="cls10" connective="to"/>Clause <span class="citesec"><xref target="cls4">4</xref></span> to <span class="citesec"><xref target="cls10">10</xref></span>
</xref>
````

**Comment by opoudjis** [comment]
<img width="1061" alt="Screen Shot 2022-11-15 at 02 11 25" src="https://user-images.githubusercontent.com/1911039/201695401-b15b20d1-5e7d-44f9-85b7-ab6656917170.png">

**Comment by Intelligent2013** [comment]
@opoudjis is there a way to move `Clauses ` inside first `xref` as in the original PDF (see initial post)?
Currently, `Clauses` isn't a link:
![image](https://user-images.githubusercontent.com/5559926/202861409-63b3eac5-bf9d-49d3-a881-01fe6887c52c.png)

Presentation XML:
```xml
any of the requirements specified in Clauses <xref target="cls4">
					<span class="citesec">4</span>
				</xref> to <xref target="cls10">
					<span class="citesec">10</span>
				</xref> is not acceptable when an
organization claims conformity to this document.</p>
```

And regarding 2nd issue - still `Clause` instead of `Clauses`:

>> ## Rendering of cross-reference ranges in external bibliographic item
>> 
>> Original: 
>> <img width="552" alt="Screen Shot 2022-10-27 at 11 49 58 AM" src="https://user-images.githubusercontent.com/11865/198186939-8955f14a-188e-4fac-98f4-136fa490efbb.png">
>> 
>> Generated:
>> ![image](https://user-images.githubusercontent.com/5559926/198381668-cbbd233a-6893-48db-b4cc-1ed2fe0918a8.png)
>
>The same issue as `1.`.



![image](https://user-images.githubusercontent.com/5559926/202861614-de38ecb4-b357-4b7b-b872-ccb737fa227a.png)


```xml
and aligned with those listed in <eref type="inline" style="short" bibitemid="iso27002" citeas="ISO/IEC 27002:2022" droploc="">
				<localityStack connective="from">
					<locality type="clause">
						<referenceFrom>5</referenceFrom>
					</locality>
				</localityStack>
				<localityStack connective="to">
					<locality type="clause">
						<referenceFrom>8</referenceFrom>
					</locality>
				</localityStack>
				<span class="stdpublisher">ISO/IEC</span>
				<span class="stddocNumber">27002</span>:<span class="stdyear">2022</span>,  <span class="citesec">Clause  <span class="citesec">5</span> to  <span class="citesec">8</span>
				</span>
			</eref>
```


My `Gemfile`:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "fix/plural-localities"
```

`Gemfile.lock`:
```
GIT
  remote: https://github.com/metanorma/isodoc
  revision: 9ba6ae6b0cf35ae5584ee603a36a202b0a115ccb
  branch: fix/plural-localities
  specs:
    isodoc (2.3.5)
,,,
```

**Comment by opoudjis** [comment]
>  is there a way to move Clauses inside first xref as in the original PDF (see initial post)?
Currently, Clauses isn't a link:

Done:

<img width="997" alt="Στιγμιότυπο 2022-11-21, 23 39 40" src="https://user-images.githubusercontent.com/1911039/203057628-21fd93b4-e362-4124-8db0-c35b9f781969.png">

**Comment by Intelligent2013** [comment]
Confirmed.

![image](https://user-images.githubusercontent.com/5559926/203153269-0ae3f8ac-c2ac-4ef5-ab12-d589c39fd9c8.png)

...

![image](https://user-images.githubusercontent.com/5559926/203153374-3b8dd0f7-66ef-4c18-a091-4a6474718a90.png)

@opoudjis thanks!
