### ISSUE TITLE
(URGENT) ModSpec instance should always show "guidance" below "statement"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#841]
This happens in https://github.com/metanorma/iso-19135 :

<img width="693" alt="image" src="https://user-images.githubusercontent.com/11865/200107539-baa9358f-4472-4897-b654-36ca1df6acd2.png">

**Comment by opoudjis** [comment]
I cannot replicate this:

<img width="1242" alt="Στιγμιότυπο 2022-11-07, 00 25 56" src="https://user-images.githubusercontent.com/1911039/200173495-8d6887ce-5c40-4370-9a33-93c715bfb511.png">

This was implemented in https://github.com/metanorma/metanorma-iso/issues/790, in mn-requirements 0.1.4.

I noticed that the Gemfile pulling from github is failing to find the latest check-in for mn-requirements 0.2.0 (I have no idea why, the gem released correctly). Pretty sure this will go away with 0.2.1

**Comment by ronaldtse** [comment]
Seems that I was using an older Git version! Sorry for the false alarm, closing.

<img width="664" alt="Screen Shot 2022-11-07 at 12 43 37 PM" src="https://user-images.githubusercontent.com/11865/200228195-41502122-0e20-4182-b6d7-65f236618c94.png">
