### ISSUE TITLE
ModSpec instances: the "statement" should just be called `statement::` instead of `description::`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#842]
Right now we use an encoding as follows:

```adoc
[requirement]
.Persistent identifiers do not change throughout the life of the register
====
[%metadata]
identifier:: /req/identifiers/ri-identifier-persistence
subject:: persistent identifier
description:: A persistent identifier within the register shall not change
throughout the lifetime of the register.
guidance:: While the register item pointed to by a persistent identifier may change,
the identifier always points to the same register item.
Even after the decommission of a register, the persistent identifiers for
register items within that register remain.
====
```

However, this is very confusing because in rendering, the `description::` field gets rendered as "Statement":
<img width="685" alt="Screen Shot 2022-11-05 at 3 16 23 PM" src="https://user-images.githubusercontent.com/11865/200107780-eda30b37-1deb-4241-96fe-660ff867cf07.png">

We should support the label of `statement::` instead of `description::` (keep `description` as an alias for compatibility purposes).

Document: https://github.com/metanorma/iso-19135/

**Comment by opoudjis** [comment]
If you want no differentiation between markup and rendering, you might prefer to use Word. And `description` is used already instead of `statement` as a label in classes, by your request. Which means you have already introduced the synonymy.

**Comment by ronaldtse** [comment]
Thanks @opoudjis for implementing this.
