### ISSUE TITLE
(URGENT) ModSpec rendering with `xref:...` broken, regardless of whether`[style=id%]` or `[]`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#846]
## With style=id

Source:
```adoc
. If `//characterEncoding` is provided

** Requirement: xref:https://standards.isotc211.org/19115/-1/1/req/metadata-xml/multilingual/character-set-code[style=id%]

** Conformance test: xref:https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/multilingual/character-set-code[style=id%]
```

There are 2 problems:
1. The resulting cross-reference is not linked properly
2. The rendering of the ID is broken

Word:
<img width="988" alt="Screen Shot 2022-11-09 at 9 33 16 AM" src="https://user-images.githubusercontent.com/11865/200714845-3422022c-c774-4ff1-9aac-ed324ecc6ce4.png">

In Word, these are links, but they don't link to anywhere:
<img width="1005" alt="Screen Shot 2022-11-09 at 9 34 36 AM" src="https://user-images.githubusercontent.com/11865/200715032-fafc7bcb-9943-4ee5-a1b6-0c0ef2ae1b77.png">

HTML:
<img width="1279" alt="Screen Shot 2022-11-09 at 9 35 21 AM" src="https://user-images.githubusercontent.com/11865/200715131-3a75fa3d-85f8-4f82-b72b-ee8e2e205f86.png">

These are links but the HREF is clearly wrong.

PDF:
<img width="1096" alt="Screen Shot 2022-11-09 at 9 31 22 AM" src="https://user-images.githubusercontent.com/11865/200714609-116c1490-50b2-417d-85f8-94f0153d0286.png">

In PDF, these links are not even links (i.e. they cannot be clicked on).

## Without style=id

Source:
```adoc
. If `//characterEncoding` is provided

** Requirement: xref:https://standards.isotc211.org/19115/-1/1/req/metadata-xml/multilingual/character-set-code[]

** Conformance test: xref:https://standards.isotc211.org/19115/-1/1/conf/metadata-xml/multilingual/character-set-code[]
```

PDF:
<img width="901" alt="Screen Shot 2022-11-09 at 9 44 44 AM" src="https://user-images.githubusercontent.com/11865/200716253-77f86597-c5b2-4595-a116-6cd8575f2360.png">

HTML:
<img width="854" alt="Screen Shot 2022-11-09 at 9 45 04 AM" src="https://user-images.githubusercontent.com/11865/200716292-08b796c6-d0cb-4b3e-8902-1e39d08a1d56.png">

## Proof that the identifiers exist

In case you wanted to verify that the ModSpec instance with that identifier exists, here they are rendered:

Requirement:
<img width="1201" alt="Screen Shot 2022-11-09 at 9 38 47 AM" src="https://user-images.githubusercontent.com/11865/200715540-c44cb1ea-d303-4739-a1b7-24624979c1c1.png">

Conformance test:
<img width="1195" alt="Screen Shot 2022-11-09 at 9 44 08 AM" src="https://user-images.githubusercontent.com/11865/200716177-0eeb5cad-55c2-4afa-b400-7af60a8f085f.png">

## Reference

See https://github.com/metanorma/iso-19115-3/pull/23

**Comment by ronaldtse** [comment]
Just tried this with the Git gems, still doesn't work:

```ruby
gem "metanorma-cli"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc"
#gem "mn-requirements", git: "https://github.com/metanorma/mn-requirements"
gem "isodoc", git: "https://github.com/metanorma/isodoc"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso"
gem "sassc"
```

**Comment by opoudjis** [comment]
My local compilation works, will revisit when release is done.

**Comment by opoudjis** [comment]
@ronaldtse Please confirm it works now.

**Comment by ronaldtse** [comment]
Confirmed works, closing.
