### ISSUE TITLE
(URGENT) PDF: table layout broken in ISO 19115-3

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#848]
Word:

<img width="546" alt="Screen Shot 2022-11-10 at 4 52 53 PM" src="https://user-images.githubusercontent.com/11865/201044779-887629cd-44d9-4ecb-8f9c-184dd32c84b0.png">

PDF (split into 3 pages):

<img width="567" alt="Screen Shot 2022-11-10 at 4 53 04 PM" src="https://user-images.githubusercontent.com/11865/201044816-36562ae6-d2e7-4e48-8b42-6c9b79d51940.png">
<img width="561" alt="Screen Shot 2022-11-10 at 4 53 13 PM" src="https://user-images.githubusercontent.com/11865/201044858-7dc53204-a5d9-43f3-8c60-29d8742b50fa.png">

**Comment by ronaldtse** [comment]
Another instance of table breaking page:

## Table rendered in margin
<img width="569" alt="Screen Shot 2022-11-10 at 4 53 53 PM" src="https://user-images.githubusercontent.com/11865/201045022-41d9dbee-7efe-4225-8c7a-c7ecd885de47.png">

<img width="555" alt="Screen Shot 2022-11-10 at 4 54 58 PM" src="https://user-images.githubusercontent.com/11865/201045277-ac67b0df-1ea0-4db9-9ca1-45735e341202.png">
<img width="579" alt="Screen Shot 2022-11-10 at 4 55 15 PM" src="https://user-images.githubusercontent.com/11865/201045329-bd866fd3-8ce0-4940-a3a3-c45057c57954.png">


## Table broke page split

<img width="579" alt="Screen Shot 2022-11-10 at 4 54 13 PM" src="https://user-images.githubusercontent.com/11865/201045095-a0d57593-3596-45b4-823f-673c4ec2ad67.png">
<img width="558" alt="Screen Shot 2022-11-10 at 4 54 48 PM" src="https://user-images.githubusercontent.com/11865/201045248-b41194fe-d428-4b24-8ee3-71c9e04b0754.png">

**Comment by Intelligent2013** [comment]
This occurs due `keep-with-next="always"` in each table's row:
```xml
<fo:table-row min-height="4mm" keep-with-next="always">
```
XSLT determines each row as sub-header's row. It seems this bug occurred by fixing the 'table continuation' issue in https://github.com/metanorma/metanorma-iso/issues/834.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/201170339-d2c95013-42c4-4776-9fc6-6c47cd9c86fb.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

**Comment by ronaldtse** [comment]
Confirm fixed. Thank you @Intelligent2013 !
