### ISSUE TITLE
(URGENT) PDF+Word: concept mentions cross-references showing extra space between parentheses

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#852]
<img width="1004" alt="Screen Shot 2022-11-17 at 8 28 19 PM" src="https://user-images.githubusercontent.com/11865/202446431-63256f72-3c09-450a-9c2d-cb58c0d468cf.png">

**Comment by Intelligent2013** [comment]
In the source presentation XML there line-breaks around `<span class="citesec">3.3.1</span>`:
```xml
<definition><p id="_1bc8afcb-d7ac-5e5c-e192-c5d7d6f0c957">set of <em>concepts</em> (<xref target="term-concept">
  <span class="citesec">3.3.1</span>
</xref>) structured according
to the concept relations among its concepts</p></definition>
```

In the generated XSL-FO also:
```xml
<fo:block text-align="justify" margin-bottom="8pt" id="_1bc8afcb-d7ac-5e5c-e192-c5d7d6f0c957">set of <fo:inline font-style="italic">concepts</fo:inline> (<fo:basic-link color="blue" text-decoration="underline" fox:alt-text="term-concept" internal-destination="term-concept">
  3.3.1
</fo:basic-link>) structured according
to the concept relations among its concepts</fo:block>
```

FOP reduces line break to space (https://stackoverflow.com/a/53523028).
From http://www.herongyang.com/XSL-FO/Block-Control-White-Space-Characters.html:
```
By default, white space characters are collapsed and linefeed characters are converted to space.
```

If we set `linefeed-treatment="ignore"`, then the space between `according` and `to` is disappear and spaces before `  3.3.1` remain:
![image](https://user-images.githubusercontent.com/5559926/202475626-3100db52-8d49-4fdd-a304-f7878b91a2dc.png)

`<xsl:strip-space elements="iso:xref"/>` solves the issue:

![image](https://user-images.githubusercontent.com/5559926/202479988-265963ed-329d-450b-8393-8d5c9931bd57.png)

**Comment by ronaldtse** [comment]
Actually this is also a Word problem:
<img width="707" alt="Screen Shot 2022-11-17 at 11 30 50 PM" src="https://user-images.githubusercontent.com/11865/202488411-dad137bd-1190-4fca-ae02-c546a32e4b7f.png">

What happened?

**Comment by Intelligent2013** [comment]
I've found the old presentation XML (was generated for another issue, Oct 23) - there aren't line breaks inside `xref`:
```xml
<definition><p id="_955b52d9-8330-8681-6efc-32fcbeff0f5e">set of <em>concepts</em> (<xref target="term-concept"><span class="citesec">3.1.1</span></xref>) structured according
to the concept relations among its concepts</p></definition>
```

**Comment by opoudjis** [comment]
What happened is that I tried to pretty print the XML output more consistently, and that's resulted in unwanted spaces.

**Comment by opoudjis** [comment]
The template for generating ToCs in Word needs to wrap styles containing space with `&quot;....&quot;`, individually.

Moreover, the first style listed must be a human readable localised style if present, rather than a CSS style, whether generic or target style. So:

`"Table title","Tabletitle","Annex Table Title","AnnexTableTitle","TableTitle","tabletitle"` works

`"TableTitle","tabletitle","Table title","Tabletitle","Annex Table Title","AnnexTableTitle"` fails

(TableTitle is the generic isodoc style, Table title is the DIS human readable style name)

**Comment by opoudjis** [comment]
No, I thought that it was that functionality https://github.com/metanorma/metanorma-iso/issues/513, but it isn't it, that does not put tags each to its own line.

**Comment by opoudjis** [comment]
Right: I've already fixed this in https://github.com/metanorma/metanorma-ieee/issues/170. @Intelligent2013, pull latest isodoc to confirm.

**Comment by Intelligent2013** [comment]
> Right: I've already fixed this in [metanorma/metanorma-ieee#170](https://github.com/metanorma/metanorma-ieee/issues/170). @Intelligent2013, pull latest isodoc to confirm.

@opoudjis no changes, unfortunately.

Resulted presentation xml:
```xml
<definition><p id="_1bc8afcb-d7ac-5e5c-e192-c5d7d6f0c957">set of <em>concepts</em> (<xref target="term-concept">
  <span class="citesec">3.3.1</span>
</xref>) structured according
to the concept relations among its concepts</p></definition>
```

Gemfile:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso"
gem "metanorma-utils", git: "https://github.com/metanorma/metanorma-utils"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc"
gem "isodoc", git: "https://github.com/metanorma/isodoc"
gem "mn-requirements", git: "https://github.com/metanorma/mn-requirements", branch: "main"
gem "sassc"
```

From `Gemfile.lock`:
```
GIT
  remote: https://github.com/metanorma/isodoc
  revision: 87b489deb6c0f55f4dfc4060b6644b8bedba91c3
  specs:
    isodoc (2.3.5)
...
```

The document source: https://github.com/metanorma/iso-19135/tree/main/sources/iso-19135-2021

**Comment by opoudjis** [comment]
OK, I'll deal with this on Tuesday....

**Comment by opoudjis** [comment]
Fix in https://github.com/metanorma/metanorma-ieee/issues/170 did not work. Will need to revert.

**Comment by opoudjis** [comment]
The issue is continued in https://github.com/metanorma/metanorma-ieee/issues/170
