### ISSUE TITLE
Issue regarding "page-break-before: always" on p.AnnexTableXXX

### ISSUE THREAD

**Issue by tbr** [metanorma/metanorma-iso#863]
Hi, I have a question regarding the ISO style that generates the .doc output. It seems to be inconsistent with ISO editorial styles and with the .pdf generated output.

The Word stylesheet sets an explicit "always" for page-break-before on AnnexTable captions. However, I believe this should not be the case. Moreover, in the .pdf output, there is also no page-break-before.

I have authored many ISO standards (under SC29 WG1) and to my knowledge, there should be not explicit page-break-before for table captions.

My request is to change this in the isodoc.scss and isodoc-dis.scss (or wherever is the correct place for .doc output).

PS: Thanks for the great work and effort on making metanorma! As project editor, I really welcome this way of working!

**Comment by ronaldtse** [comment]
Thanks @tbr for raising this issue. This might be a legacy carry over, but we import the Word CSS directly from ISO templates. We’ll check. 

On the other hand, are you using the Simple Template or the DIS template? They differ.

**Comment by tbr** [comment]
@ronaldtse Thanks for responding.

It is in all of the isodoc css and scss stylesheets (`isodoc.css`, `isodoc.scss`, `isodoc-dis.css`, and `isodoc-dis.scss`). If you took these directly from ISO, then I suppose they are correct and a page-break-before is indeed the thing. But, in practice on all the standards that I was project editor for, no page-break-before is done for annex table titles. So I wonder :)

Moreover, the PDF output also does not do the page-break-before (and is actually quite consistent with what ISO produces), meaning that this behavior differs from that of the DOC output.

**Comment by ronaldtse** [comment]
Thanks for check @tbr , I'm trying to find out where those lines come from...

**Comment by opoudjis** [comment]
The style is AnnexTableTitle, and there is indeed a page-break-before: always on it.

The style isn't used in ISO DIS. It is, as it happens, a style included in the stylesheet of the Simple Template that we have used, and it is defined in that way, as page-break-before—although that setting is actually overridden in the instance of the annex table in the template text.

I think what's actually happened is that this is an error in the Simple Template style definition, which ISO editorial silently emends; I can see it being introduced as a default, to crudely force the table to be on one page if it is large. But... it really doesn't make much sense, and we do not need to stick to the Simple Template as rigorously as we do to ISO DIS.

I'll remove it, it's not worth the disruption it introduces.

**Comment by ronaldtse** [comment]
Thank you @opoudjis ! (Can we link the PR/commit to this issue?)

**Comment by tbr** [comment]
Thanks a lot!
