### ISSUE TITLE
Issue regarding formula/equation label alignment in .doc output

### ISSUE THREAD

**Issue by tbr** [metanorma/metanorma-iso#864]
Hi all,

in ISO standards, the formula/equation labels that are at the right of a formula/equation is normally right aligned on the page (using right tab stop in Word). The .pdf output renders this correctly, but the .doc output does not. In .doc, the labels are not aligned at all (they just immediately follow the centered formula/equation).

I'm not sure where or how this can be fixed?

This is an example in Word (.doc):
<img width="852" alt="image" src="https://user-images.githubusercontent.com/690402/204487696-708d8cdf-2af6-4c2f-adaa-dec987bbcd21.png">

**Comment by opoudjis** [comment]
My apologies for delay. Fixed, will be available next release (in a week.)
