### ISSUE TITLE
(URGENT) PDF accessibility: words containing underscores being broken into multiple words in PDF content text

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#870]
This is from ISO 10303-50 (https://github.com/metanorma/iso-10303-detached-docs/tree/main/sources/iso-10303-50):

<img width="1188" alt="Screen Shot 2022-12-01 at 12 42 23 PM" src="https://user-images.githubusercontent.com/11865/204968326-7ade37f5-cee7-4e50-addb-95f4de3eeec4.png">

<img width="1157" alt="Screen Shot 2022-12-01 at 12 42 48 PM" src="https://user-images.githubusercontent.com/11865/204968238-fe1137d8-713d-4489-a963-783b5db09dee.png">

I remember we never had this problem before, it seems like a regression.

@Intelligent2013 can you add tests against this case?

**Comment by Intelligent2013** [comment]
@ronaldtse Apache FOP doesn't add line feed after the underscore character automatically, and may be cases when text renders overflowed:
![image](https://user-images.githubusercontent.com/5559926/205082406-923210a1-b6e4-40e4-9de9-368d192fb302.png)

therefore XSLT adds zero-width space after each `_`.

In Intermediate Format, the text `the_integers` represents as sequence of two `text`:
```xml
<font family="Noto Sans Mono"/>
<font family="Courier New"/>
<text x="13200" y="22132" next-is-space="true" foi:struct-ref="a12">the_</text>
<font family="Noto Sans Mono"/>
<font family="Courier New"/>
<text x="39600" y="22132" next-is-space="true" foi:struct-ref="a12">integers </text>
```

Each `text` has `next-is-space="true"`. Looks like Apache FOP adds it for zero-width space, and it treats as space in copy-paste and comparison feature: `the_ integers`

I'll think about workaround solution. May be we need to omit `next-is-space` for zero-width space... (except cases when `text` is the latest in the row).

**Comment by Intelligent2013** [comment]
Zero-width space removed from middle of words:
![image](https://user-images.githubusercontent.com/5559926/205375032-4a9bae48-a082-48f0-b8e4-8449911f06e3.png)

Next step: remove from end of line.

**Comment by Intelligent2013** [comment]
Actually there aren't spaces in the generated PDF:
- copied text doesn't contain space: `the_integers : elementary_space := make_elementary_space(es_integers);`
- there isn't `next-is-space="true"` for text `space(es_` in Apache FOP Intermediate Format XML:
```xml
<text x="290400" y="22132" foi:struct-ref="7d">make_</text>
<font family="Noto Sans Mono"/>
<font family="Courier New"/>
<text x="323400" y="22132" foi:struct-ref="7d">elementary_</text>
<font family="Noto Sans Mono"/>
<font family="Courier New"/>
<text x="396000" y="22132" foi:struct-ref="7d">space(es_</text>
<font family="Noto Sans Mono"/>
<font family="Courier New"/>
<text x="0" y="35332" next-is-space="true" foi:struct-ref="7d">integers);</text>
```

I think Acrobat adds space for line break in the comparison feature. For checking this assumption, I've created two Word documents with the same text, but with different font sizes.
24pt text doesn't fit on the line. There isn't space between `tex` and `t` on the next line, but Acrobat replaces line break to space:
![image](https://user-images.githubusercontent.com/5559926/205439801-ffcf25dd-fe07-4fd6-97e4-5626bd5aa924.png)

**Comment by Intelligent2013** [comment]
Issue partially fixed in mn2pdf v1.52 (https://github.com/metanorma/mn2pdf/releases/tag/v1.52):
> Zero-width space removed from middle of words:
> ![image](https://user-images.githubusercontent.com/5559926/205375032-4a9bae48-a082-48f0-b8e4-8449911f06e3.png)

**Comment by ronaldtse** [comment]
> I think Acrobat adds space for line break in the comparison feature. 

Is there a way to get rid of this problem?

**Comment by Intelligent2013** [comment]
> Is there a way to get rid of this problem?

At this moment I don't know the solution. I've asked here: https://community.adobe.com/t5/acrobat-discussions/redundant-space-character-in-the-compare-result/td-p/13393538

**Comment by ronaldtse** [comment]
Conclusion: This is an Adobe Acrobat "Compare PDFs" bug, it cannot be addressed in Metanorma.

**Comment by ronaldtse** [comment]
@stuartgalt : Does the PDF group (ISO/TC 171/SC 2) have some any spec for Compare PDFs?
