### ISSUE TITLE
Handling documents from ISO groups like "ISO/CASCO" that are not technical committees and don't have numbers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#872]
ISO/IEC 17025 is published by ISO/CASCO:
https://www.iso.org/standard/66912.html
<img width="671" alt="Screen Shot 2022-12-02 at 12 34 31 PM" src="https://user-images.githubusercontent.com/11865/205215464-83d4bf99-ea2b-4fcf-b766-e36c3170a2b5.png">

ISO/CASCO:
https://www.iso.org/committee/54998.html

Our current settings do not seem to support this:
<img width="654" alt="Screen Shot 2022-12-02 at 12 36 10 PM" src="https://user-images.githubusercontent.com/11865/205215665-214b8e1a-918b-423a-a5f5-7b09243a99e3.png">

We need to handle documents from ISO groups like "ISO/CASCO" that are not technical committees and don't have numbers.

Relevant document: https://github.com/metanorma/iso-17025

**Comment by ronaldtse** [comment]
In the IEC/ISO SMART terms document with the group called "IEC/ISO SMART SG", we did this:

```adoc
:technical-committee-type: SG
:technical-committee-number: SMART
:technical-committee: SMART
:subcommittee-type: SG
:subcommittee-number: TS
:subcommittee: Technical solutions sub-group
```

**Comment by opoudjis** [comment]
We'll address by wording it as "ISO technical committee or equivalent"; introducing "Other" as a technical-committee-type value; and allowing non-numeric values if this is not a tech committee:

````
:technical-committee-type: Other
:technical-committee-number: SMART
:technical-committee: SMART
:subcommittee-type: SG
:subcommittee-number: SG
:subcommittee: Technical solutions sub-group
````

(why TS?)

**Comment by opoudjis** [comment]
There is an inconsistency between HTML and PDF putting a "/" after the agency in editorial group identifiers, e.g. "ISO/TC 4", and DOC omitting it, "ISO TC 4". Resolving in favour of the former.

**Comment by ronaldtse** [comment]
> We'll address by wording it as "ISO technical committee or equivalent"; introducing "Other" as a *-type value (which is never used as a prefix); and allowing non-numeric values if this is not a tech committee:
> 
> ```
> :technical-committee-type: Other
> :technical-committee-number: SMART
> :technical-committee: SMART
> :subcommittee-type: Other
> :subcommittee-number: SG
> :subcommittee: Technical solutions sub-group
> ```

The abbreviation for the “Technical solutions sub-group” is “TS SG”.

**Comment by opoudjis** [comment]
Fine. Then

````
:technical-committee-type: Other
:technical-committee-number: SMART SG
:technical-committee: SMART
:subcommittee-type: Other
:subcommittee-number: TS SG
:subcommittee: Technical solutions sub-group
````

The TC/SC/WG pattern is {TYPE NUMBER}+. If you are not providing me alternate rules (and you are not), I'm not going to make them up. A situation where types are preposed in TC/SC/WG and postposed in other types is nonsense, and I'm not doing it.
