### ISSUE TITLE
(DUE: ISO 2022-12-05) ModSpec: support cross-reference style to show "Type type-num: Title"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#875]
Originally from https://github.com/metanorma/iso-19115-3/issues/24

In ISO 19115-3 modspec instances, the Requirements class and Conformance class references look like this:

<img width="932" alt="Screen Shot 2022-12-03 at 12 27 37 AM" src="https://user-images.githubusercontent.com/11865/205339417-5764a0b2-c0ee-465c-afb0-ace645078191.png">

* "Requirements class 1: Metadata core (ISO 19115-1)"
* "Conformance test A.1: Metadata basic data requirements"

I wish to reproduce this cross-reference format in the XML namespace tables, which are done manually (by Liquid):
<img width="908" alt="Screen Shot 2022-12-03 at 12 28 29 AM" src="https://user-images.githubusercontent.com/11865/205339555-feae3079-d82a-4cfc-b494-0f2b25d06738.png">

On https://www.metanorma.org/author/topics/document-format/xrefs/ we have these styles:
* short
* basic
* full
* id

Given code like this:
```adoc
xref:https://standards.isotc211.org/19115/-1/1/req/metadata-xml/application[style=full%]
```

I could not generate the format of:
* "Requirements class 1: Metadata core (ISO 19115-1)"

Can we implement one of the "styles" to reflect this format?

e.g.
* `xref:my-id[]`: "Table X, Requirement Y"
* `xref:my-id[style=short%]`: "Requirement Y"
* `xref:my-id[style=basic%]`basic: "Title"
* `xref:my-id[style=full%]`: "Requirement Y: Title"
* `xref:my-id[style=id%]`id: "my-id"

Or a new style?

**Comment by opoudjis** [comment]
This needs fuller analysis, but for now:

* Short = Type + Number, e.g. Clause 3.1 (default)
* Basic = Title, e.g. "Other considerations"
* Full = Type + Number + Title, e.g. Clause 3.1, "Other considerations"

But critically, this has only been implemented for clauses. For other assets, the title is not extracted for consideration in building xrefs.

It is also apparent that full style rendering needs to be specific to a flavour: you want X: Y, not X, Y.

I am going to generalise title extraction to all assets, not just clauses.

The removal of Table X as a prefix from xrefs to requirements renderings is an orthogonal issue, and I think I will need to add further options.

**Comment by opoudjis** [comment]
What has currently been implemented is:

General Modspec (OGC):
* `:xref_bare`: `Requirement X` (not used in OGC)
* `:xref`: `Requirement X: <tt>IDENTIFIER</tt>`

ISO Modspec:
* `:xref_bare`: `Table Y, Requirement X` (not used in OGC)
* `:xref`: `Table Y, Requirement X: <tt>IDENTIFIER</tt>`
* `:xref_reqt2reqt`: `Table Y, Requirement X` + Title (based on xref_bare)

reqt_ids, reqt_links_test1, reqt_links_class (listing of IDs used within modspec, to express graph of modspec dependencies) uses xref_reqt2reqt
So do nested requirement labels (so requirement within requirement class).

So Provisions, Classes, Tests etc links generated automatically within Requirement table renderings include Title, any other links should include identifier instead.

(I can't work out why the identifiers are NOT in there.)

**Comment by opoudjis** [comment]
They are not there because during Presentation XML authoring, recommendation xrefs are overwritten by the corresponding table xrefs; and the calculation of the table xrefs, of course, ignores identifiers. The xrefs of the ISO document generated outside of the Modspec requirements ignore all the identifiers and titles, and if we want table xrefs to look more like reqt xrefs, we will need to introduce a lot of options.

It's bad.

**Comment by opoudjis** [comment]
So. If I were to allow open flexibility on whether any Modspec xref will include any of:

* Title
* Reqt Number
* Identifier
* Table Wrapper

the interface would be unmanageable and unlearnable.

The good news is, I do not in fact need to offer this level of flexbility.

Modspec has two kinds of cross-reference: one automatically generated inside of requirements, and one external to requirements and the default. Currently, the former are populated with text within Modspec in ISO flavour, and then being overriden by table xrefs. But we can separate out the xref renderings as follows:

OGC
* Default: Reqt Number + Identifier
* Modspec: Reqt Number + Identifier

ISO
* Default: Table Number + Reqt Number
* Modspec: Reqt Number + Title

The solution then is to store and expose the modspec-internal xref rendering as an alternate style. This style should NOT be one of the existing styles, Full or Short: those have a well-defined meaning of ±Title, and that conflicts with the requirement here.

So

`xref:https://standards.isotc211.org/19115/-1/1/req/metadata-xml/application[style=modspec%]`

That will still require refactoring of ISO: I can no longer overwrite the cross-references of requirements in ISO with table requirements.

**Comment by ronaldtse** [comment]
The `style=modspec%` solution will work perfectly. Thank you.

**Comment by opoudjis** [comment]
Input:

````
== Scope

[requirement]
.Documentation of methods for constructing identifiers in the register specification
====
[%metadata]
identifier:: /req/identifiers/document-identifier-structure
subject:: register specification
description:: Methods for constructing identifiers used in the register shall be
documented in the register specification.
guidance:: The register specification can document the pattern used for
identifiers as part of describing methods to construct identifiers.
====

== Hello

xref:/req/identifiers/document-identifier-structure[style=modspec%]

xref:/req/identifiers/document-identifier-structure[style=id%]

xref:/req/identifiers/document-identifier-structure[]
````

Semantic XML:

````
<clause id="_hello" inline-header="false" obligation="normative">
<title>Hello</title>
<p id="_6bccf145-897f-b278-0d02-2e0bfbe6b5a2"><xref target="_22a5a9c4-21cd-9040-03cc-aadaa76fbaca" type="inline" style="modspec"/></p>

<p id="_c020c69f-1c0a-426d-2f4c-859c66c99567"><xref target="_22a5a9c4-21cd-9040-03cc-aadaa76fbaca" type="inline" style="id">/req/identifiers/document-identifier-structure</xref></p>

<p id="_2178f823-f888-6436-c46b-b4ad76194e33"><xref target="_22a5a9c4-21cd-9040-03cc-aadaa76fbaca" type="inline"/></p>
</clause>
````

Presentation XML:

````
<clause id="_hello" inline-header="false" obligation="normative" displayorder="2">
<title depth="1">2<tab/>Hello</title>
<p id="_6bccf145-897f-b278-0d02-2e0bfbe6b5a2"><xref target="_22a5a9c4-21cd-9040-03cc-aadaa76fbaca" type="inline" style="modspec"><span class="citetbl">Requirement 1: Documentation of methods for constructing identifiers in the register specification</span></xref></p>

<p id="_c020c69f-1c0a-426d-2f4c-859c66c99567"><xref target="_22a5a9c4-21cd-9040-03cc-aadaa76fbaca" type="inline" style="id">/req/identifiers/document-identifier-structure</xref></p>

<p id="_2178f823-f888-6436-c46b-b4ad76194e33"><xref target="_22a5a9c4-21cd-9040-03cc-aadaa76fbaca" type="inline"><span class="citetbl">Table 1, Requirement 1</span></xref></p>
</clause>
````
