### ISSUE TITLE
HTML: SVG images showing HTML escaped content

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#879]
Word rendering (good):
<img width="916" alt="Screen Shot 2022-12-05 at 6 33 45 PM" src="https://user-images.githubusercontent.com/11865/205616045-14244d5a-5e0d-4990-a4d4-24d4f3c3605d.png">

HTML rendering (escaped content):
<img width="708" alt="Screen Shot 2022-12-05 at 6 33 26 PM" src="https://user-images.githubusercontent.com/11865/205615970-d23f52fb-acc2-48d0-a7a1-8d1712356e32.png">

**Comment by opoudjis** [comment]
The text in the SVG is encoded as:

`<text font-family="Calibri" fill="#595959" style="white-space:pre;" text-anchor="start" x="23.0000" y="27.0000" font-size="10.0000"><![CDATA[&#171;ApplicationSchema&#187;]]></text>`

CDATA is expressly NOT meant to contain HTML escapes, so I need to work out how they got there to begin with.

**Comment by ronaldtse** [comment]
This document is ISO 19115-3:
* https://github.com/metanorma/iso-19115-3/

But I've already submitted this document to publication :wink:

**Comment by opoudjis** [comment]
This SVG is being generated by the emf2svg gem, which is encoding non-ascii characters as UTF-8:

`<![CDATA[\xC2\xABApplicationSchema\xC2\xBB]]>`

Escapes are respected in Presentation XML output, but not HTML output. That's just a matter of using the to_xml method (which outputs UTF-8 natively); there is no particular reason to use HTML escapes in HTML any more.
