### ISSUE TITLE
PDF: font size for monospace seems too large

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#886]
![image](https://user-images.githubusercontent.com/5559926/206526881-c8395862-57ee-4b1a-94b7-ba83be6e87a5.png)

**Comment by Intelligent2013** [comment]
Main text font size (for instance, 'EXPRESS specification'): 11pt (Times New Roman)
Source code font size (for instance, the text `SCHEMA  basis_schema`): 11pt (Courier New)

**Comment by Intelligent2013** [comment]
From ISO 6709 (https://github.com/metanorma/metanorma-iso/issues/680), generated by mn2pdf:
![image](https://user-images.githubusercontent.com/5559926/206528418-4b443ac1-dc3f-4377-afda-82957651b0c2.png)

Example text font size (for instance, `EXAMPLE 1`, or `A GPL representation of an elevation value`): 10pt
Source code in example font size (for instance, `+100.5CRS1d<ISOGR:256>/`): 10pt

**Comment by Intelligent2013** [comment]
From original ISO_10303-501_2000.pdf:
![image](https://user-images.githubusercontent.com/5559926/206529928-9a2d9f5a-e2a9-4cb2-b7c7-59142436969b.png)

Main text font size (for instance, `EXPRESS Specification`) : 11pt
Source code font size (for instance, `SCHEMA aic_edge_based_wireframe`): 10.1pt

**Comment by Intelligent2013** [comment]
From "ISO 6709 ed.3 - id.75147 Publication PDF (en).pdf":
- main text : 11pt
- source code in the main text: 9pt
- example: 10pt
- source code in the example: 9pt

Ok, will change to 9pt.

**Comment by ronaldtse** [comment]
Thanks!

**Comment by Intelligent2013** [comment]
There is a conflict with the old ticket `(ISO 6709) PDF: code style font size should be identical as that of surrounding text` https://github.com/metanorma/metanorma-iso/issues/698. The font size was 9pt already before.

**Comment by Intelligent2013** [comment]
Source code font size returned to 9pt.
