### ISSUE TITLE
Word: apply keep with next to table row if table has less than 10 rows

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#888]
ISO 19115-3 has many requirements tables and ultimately the editor decided that they split into pages too often and applied keep with next. 

We decided to adopt a rule that if the table has less than 10 rows, apply keep with next. 

Even this doesn’t take care of all the cases where a row can be very tall with long content, it still works better than nothing.

**Comment by opoudjis** [comment]
Also keep header row with next.

**Comment by ronaldtse** [comment]
I'm regenerating ISO 19115-3 with the latest code but am still seeing these:

<img width="643" alt="Screen Shot 2023-01-12 at 1 34 22 PM" src="https://user-images.githubusercontent.com/11865/211985675-c448b8e1-b9c3-4292-99c3-143f2d96d0db.png">

Is this really fixed?

**Comment by ronaldtse** [comment]
This is a normal table, so it's not specific to ModSpec tables:

<img width="622" alt="Screen Shot 2023-01-12 at 10 32 54 PM" src="https://user-images.githubusercontent.com/11865/212094070-e05d9f88-e83a-49d5-836b-7149a0b359b3.png">

**Comment by opoudjis** [comment]
You're right. The CSS keep-with-next property is being applied to `<td>`, but Word is ignoring it unless it is also applied to any paragraphs and divs within the `<td>`.
