### ISSUE TITLE
Terms and definitions: simplify specification of systematic vs mixed order headings

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#899]
ISO supports listing concepts in the following manners:
* [systematic order](https://www.metanorma.org/author/iso/topics/markup/#systematic-order)
* [mixed order](https://www.metanorma.org/author/iso/topics/markup/#mixed-order)

Both modes are supported by Metanorma, but the specification is a bit complex:
* To use systematic order, the non-leaf node must be applied the `[.term]` label
* To use mixed order (add a grouping), the non-leaf node does not need any label
* To add a non-term clause (applies to all children nodes), the node needs to be applied the `[.nonterm]` label.

To allow authors to easily specify hierarchical concepts and concept groupings, we have worked out that:

1. When there is only a heading and no body text, it means it is a concept grouping. No author intervention is necessary.
2. When there is a heading and any content, it is a term (hierarchical concept). No author intervention is necessary.
3. If the user wants a concept grouping but with content, the user must specify manually the `[.grouping]` (which is technically `[.nonterm]`, but it only applies to the node itself and not its children nodes).

ISO 10303-2 (https://github.com/metanorma/iso-10303-2/pull/120) can be used for experimenting this feature. Once this feature is available, we want to go back to update ISO 10303-2 to use this new simplified syntax.

**Comment by opoudjis** [comment]
Current behaviour:

````
=== A

==== B

Term

==== C

Term
````

A is a grouping.

> When there is only a heading and no body text, it means it is a concept grouping. No author intervention is necessary.

Satisfied.

````
=== A

Term

==== B

Term

==== C

Term
````

Current behaviour: A is a grouping by default. You want A to be a term with subterms by default, and to make the grouping behaviour to be made explicit with a [.grouping] attribute.

Well... OK, but I'm going to limit that behaviour to ISO and its descendants; there is very good reason not to want it to be the default in other flavours (which, after all, do not support subterms).

**Comment by opoudjis** [comment]
@ronaldtse https://github.com/metanorma/metanorma-iso/pull/911 , try it out.

**Comment by ronaldtse** [comment]
@opoudjis I noticed you edited the message and my response was insufficient. There is a problem:

> In ISO non-vocabulary, 1 and 2 are both grouping
> In ISO vocabulary, 1 and 2 are both systematic
> I am assuming that systematic terms are only permitted in vocabulary documents.

This is incorrect. Terms in systematic order are permitted in ALL ISO deliverables.

Which means there is no differential treatment of "ISO non-vocabulary" and "ISO vocabulary".

**Comment by opoudjis** [comment]
Well, that's not what was coded, but it's an easy enough fix.

**Comment by opoudjis** [comment]
I'm closing this, I believe we're otherwise in agreement.

**Comment by ronaldtse** [comment]
Thanks.
