### ISSUE TITLE
Word: "Published" stage document has duplicated identifiers on cover page top right corner

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#906]
<img width="607" alt="Screen Shot 2023-01-17 at 1 01 53 AM" src="https://user-images.githubusercontent.com/11865/212732058-654dafc7-d0ed-4513-9f29-119238b2de1f.png">

Document: https://github.com/metanorma/iso-19115-3/commit/807d02f59714ec3aa45568e6ac562db6e450bded

**Comment by opoudjis** [comment]
They aren't supposed to, no. Investigating, this may be a copy paste error in the handling of headers.

**Comment by opoudjis** [comment]
The "first page" directive on the header was being ignored; I'll just make all headers for the first section be the same first page headers (i.e. content-free).
