### ISSUE TITLE
problem with cross-references from within source blocks

### ISSUE THREAD

**Issue by jonsneyers** [metanorma/metanorma-iso#909]
Using the `{{{<<reference>>}}}` syntax within a source code block, the cross-reference does not get rendered properly: it shows up in the rendered source code as `<xref target="reference">`.

**Comment by ronaldtse** [comment]
@jonsneyers FYI I'm moving this issue to metanorma-iso.

**Comment by opoudjis** [comment]
That usage had slipped my mind too. And it is colliding with the update to source code highlighting which we have just done.

We have switched from coderay (which was not working well, is HTML-specific, and has a restricted repertoire of languages), to rouge. Rouge is far superior, and we're not going to go back on it.

The catch here is, Rouge's lexer is expecting to find only sourcecode, and no XML markup. 

I will do investigation; options include:

*  If there is any XML markup, no sourcecode highlighting
* Do something clever with inserting placeholders for all XML markup as comments in the sourcecode, and then substitute them back out again with the XML.

I'd rather do the latter, let me just see how feasible it is.

**Comment by opoudjis** [comment]
Mercifully, Rouge provides for escaping  the lexer into underlying (HTML) markup.

**Comment by opoudjis** [comment]
As you can see, this is fixed: this is the snippet from metanorma.org, with boldface and crossreferencing (rendered as underline), but still with source code highlighting.

<img width="673" alt="Στιγμιότυπο οθόνης 2023-01-21, 17 43 36" src="https://user-images.githubusercontent.com/1911039/213847447-1d620c6b-dee8-4f68-99d9-ddd5304eb5b2.png">


The fix will be available next Metanorma release, scheduled for late Monday.
