### ISSUE TITLE
XML/PDF/Word: Wrong PubID in ISO PDFs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#919]
PDF:
<img width="586" alt="Screenshot 2023-02-13 at 4 55 47 PM" src="https://user-images.githubusercontent.com/11865/218413642-8a73ff45-d4bb-4adb-a2d4-e7a2619da680.png">

Word:
<img width="766" alt="Screenshot 2023-02-13 at 4 57 37 PM" src="https://user-images.githubusercontent.com/11865/218414107-bbe1964b-d0fd-415d-97bd-5e527a13811b.png">

Correct PubID in the header is "ISO 44001:2017(E)".

See pubid-iso for the correct format options:
* https://github.com/metanorma/pubid-iso#using-format-options

```ruby
> pubid.to_s(:ref_num_short)
=> "ISO 8601-1:2019/DAM 1:2021(E)"
```

Document:
* https://github.com/metanorma/mn-samples-bsi/blob/main/sources/bs-iso-44001/iso-44001.adoc

**Comment by Intelligent2013** [comment]
From presentation xml:
```xml
<docidentifier type="ISO">ISO 44001:2017</docidentifier>
<docidentifier type="iso-reference">ISO 44001:2017(en)</docidentifier>
<docidentifier type="URN">urn:iso:std:iso:44001:stage-60.60:en</docidentifier>
<docidentifier type="iso-undated">ISO 44001</docidentifier>
<docidentifier type="iso-with-lang">ISO 44001:2017(E)</docidentifier>
```

Example from the mn-samples-iso presentation xml (https://github.com/metanorma/mn-samples-iso/tree/gh-pages/documents/international-standard) generated last month:
```xml
<docidentifier type="ISO">ISO 17301-1:2016</docidentifier>
<docidentifier type="iso-undated">ISO 17301-1</docidentifier>
<docidentifier type="iso-with-lang">ISO 17301-1:2016(E)</docidentifier>
<docidentifier type="iso-reference">ISO 17301-1:2016(E)</docidentifier>
<docidentifier type="iso-tc">17301</docidentifier>
```

Currently, ISO XSLT render `/iso-standard/bibdata/docidentifier[@type = 'iso-reference']` in the PDF.

@ronaldtse @opoudjis please confirm that we should use `<docidentifier type="iso-with-lang">` now instead of `<docidentifier type="iso-reference">`.

**Comment by Intelligent2013** [comment]
The comment from duplicate issue https://github.com/metanorma/metanorma-iso/issues/920#issuecomment-1427896922.

> So iso-with-lang, not iso-reference, is the right identifier to insert into the header.

**Comment by opoudjis** [comment]
I switched iso-reference with iso-with-lang in https://github.com/metanorma/metanorma-iso/issues/920, so this issue has been resolved.
