### ISSUE TITLE
XML/PDF/Word: Wrong PubID in ISO PDFs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#920]
This seems to be an XML issue and possibly present in all the output formats.

PDF:
<img width="586" alt="Screenshot 2023-02-13 at 4 55 47 PM" src="https://user-images.githubusercontent.com/11865/218413642-8a73ff45-d4bb-4adb-a2d4-e7a2619da680.png">

Word:
<img width="766" alt="Screenshot 2023-02-13 at 4 57 37 PM" src="https://user-images.githubusercontent.com/11865/218414107-bbe1964b-d0fd-415d-97bd-5e527a13811b.png">

Correct PubID in the header is "ISO 44001:2017(E)".

See pubid-iso for the correct format options:
* https://github.com/metanorma/pubid-iso#using-format-options

```ruby
> pubid.to_s(:ref_num_short)
=> "ISO 8601-1:2019/DAM 1:2021(E)"
```

Document:
* https://github.com/metanorma/mn-samples-bsi/blob/main/sources/bs-iso-44001/iso-44001.adoc

**Comment by opoudjis** [comment]
````
<docidentifier type="ISO">ISO 44001:2017</docidentifier>
<docidentifier type="iso-reference">ISO 44001:2017(en)</docidentifier>
<docidentifier type="URN">urn:iso:std:iso:44001:stage-60.60:en</docidentifier>
<docidentifier type="iso-undated">ISO 44001</docidentifier>
<docidentifier type="iso-with-lang">ISO 44001:2017(E)</docidentifier>
````

So iso-with-lang, not iso-reference, is the right identifier to insert into the header.

**Comment by Intelligent2013** [comment]
> So iso-with-lang, not iso-reference, is the right identifier to insert into the header.

@opoudjis are you sure? Why this issue occurred in the last days?
See https://github.com/metanorma/metanorma-iso/issues/919#issuecomment-1430213603

**Comment by ronaldtse** [comment]
I'm not sure exactly -- I think "ISO 44001:2017(E)" should become the "iso-reference" instead. ISO/CS has told us that "ISO 44001:2017(en)" is their error and should not be used.

**Comment by opoudjis** [comment]
@ronaldtse Do you want me switching the labels around?

**Comment by ronaldtse** [comment]
@opoudjis yes, can we do that? In any case we should not be using "ISO 44001:2017(en)" style IDs anymore.

**Comment by opoudjis** [comment]
In any case we should not be using "ISO 44001:2017(en)" style IDs anymore. Should I suppress it from Semantic XML output?

**Comment by ronaldtse** [comment]
Correct, please remove it from the semantic XML.

**Comment by opoudjis** [comment]
Actually, the alternation in pubid_iso is:

* ref_num_short -- instance reference number: 1 letter language code + short form (DAM) + dated
* ref_num_long -- instance reference number long: 2 letter language code + long form (DAmd) + dated

I'm assuming we still want the DAmd option, so I'm going to switch them around.

**Comment by ronaldtse** [comment]
> Actually, the alternation in pubid_iso is:
> 
> * ref_num_short -- instance reference number: 1 letter language code + short form (DAM) + dated
> * ref_num_long -- instance reference number long: 2 letter language code + long form (DAmd) + dated
> 
> I'm assuming we still want the DAmd option, so I'm going to switch them around.

ISO CS already clarified this too: the “DAmd” is also an error and should never be shown in the document. It is best to remove it altogether. Pubid still parses it but normalizes it now.
