### ISSUE TITLE
PDF: Cover page document identifier is likely always 2 separate lines

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#924]
Document:
* https://github.com/metanorma/mn-samples-bsi/blob/main/sources/bs-iso-44001/iso-44001.adoc

Left generated, right original:
<img width="1393" alt="Screenshot 2023-02-17 at 3 35 07 PM" src="https://user-images.githubusercontent.com/11865/219579966-4b9ca396-db19-4889-93e3-ff5420ed06e9.png">

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/219970380-299759c4-1bfe-4d78-9169-0a4f438cf9db.png)
