### ISSUE TITLE
PDF: In preliminary sections (Foreword), all links lost the blue styling

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#925]
Document:
* https://github.com/metanorma/mn-samples-bsi/blob/main/sources/bs-iso-44001/bs-iso-44001.adoc

Left generated, right original:
<img width="1570" alt="Screenshot 2023-02-17 at 3 36 21 PM" src="https://user-images.githubusercontent.com/11865/219580253-a49fce00-41c4-4a9e-8607-80772cbe6f49.png">

**Comment by Intelligent2013** [comment]
Presentation XML doesn't contains the `link` element:
```xml
<foreword id="_foreword" obligation="informative" displayorder="1">
	<title>Foreword</title>
	...
	<p id="_">... , Part 2 (see www.iso.org/directives).</p>
	<p id="_">... of patent declarations received (see www.iso.org/patents).</p>
	...
	<p id="_">... see the following URL: www.iso.org/iso/foreword.html.</p>
	...
</foreword>
```

The reason - there isn't link adoc markup:
```
== Foreword

....

...  Part 2 (see www.iso.org/directives).

...  of patent declarations received (see www.iso.org/patents).

...

... see the following URL: www.iso.org/iso/foreword.html.

...
```

https://github.com/metanorma/mn-samples-bsi/blob/main/sources.mnconvert/adoptions/bs-iso-44001/sections/00-01-foreword.adoc contains correct markup:
```
... Part 2 (see http://www.iso.org/directives[www.iso.org/directives])

... of patent declarations received (see http://www.iso.org/patents[www.iso.org/patents]).

... see the following URL: http://www.iso.org/iso/foreword.html[www.iso.org/iso/foreword.html].
...
```

Adoc updated in https://github.com/metanorma/mn-samples-bsi/pull/213.

Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/219938051-a7f881c2-abde-4734-8e46-f69897a63a33.png)

**Comment by Intelligent2013** [comment]
Done in last year.
