### ISSUE TITLE
Support for SOURCE to Figures or Tables

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#929]
A SOURCE can be assigned to a Figure or a Table:

[ISO Directives, Part 2](https://www.iso.org/sites/directives/current/part2/index.xhtml), 5.7:
> If it is considered necessary to repeat a requirement from an exterior source, its source shall be referenced precisely (see [10.1](https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor129)).

[ISO Directives, Part 2](https://www.iso.org/sites/directives/current/part2/index.xhtml), 10.1 Example 2
<img width="806" alt="image" src="https://user-images.githubusercontent.com/11865/221454901-dd86d257-2bfa-44c3-b218-0fa4dc28d5bc.png">

In ISO 20400 there is a Figure that contains SOURCE:

Original:
<img width="572" alt="Screenshot 2023-02-21 at 12 12 29 PM" src="https://user-images.githubusercontent.com/11865/220246014-aebf89e7-7c0b-4573-b09e-7300d7bf5b37.png">

When we generate it the SOURCE goes outside of the Figure. Presumably because it is encoded outside of the figure:

Generated:
<img width="596" alt="Screenshot 2023-02-21 at 12 12 32 PM" src="https://user-images.githubusercontent.com/11865/220246071-c72235fa-0af1-4e4c-81d1-656bcc4f1e2c.png">

Encoding:
```adoc
[[fig_B-1]]
.Overview of <<ISO_26000-2010>>
image::fig-b-1.svg[]

NOTE: Clause references refer to <<ISO_26000-2010>>.

[.source]
<<ISO_26000-2010>>
```

How do we handle this case?

Document:
* https://github.com/metanorma/mn-samples-bsi/pull/222

P.S. This SOURCE issue is also needed in BSI.

**Comment by ronaldtse** [comment]
As reported by @anermina this also occurs in IEC.

**Comment by opoudjis** [comment]
Already implemented in https://github.com/metanorma/metanorma-iec/issues/198
