### ISSUE TITLE
Line breaks in CJK text causing Metanorma to insert blank space

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#948]
Line breaks in AsciiDoc for CJK text should not be replaced by a blank space but just eliminated within text.

In English, replacing a line break by a space is acceptable because the line typically ends on a word boundary. However, in CJK text an extra space breaks the sentence.

```adoc
ISO/TC 211会議は通常、春と秋の年2回開催されている。2022年初頭、COVIDの開始ととも
に、ISOの会議はバーチャルのみとなったが、2022年春から、ISOは対面での会議開催を許
可した。2022年中、ISO/TC 211は対面及びバーチャル会議を2回開催した：
```

<img width="667" alt="Screenshot 2023-03-10 at 10 26 44 PM" src="https://user-images.githubusercontent.com/11865/224341234-c2f622ff-94fc-4759-abbd-2e5f20a822e1.png">

**Comment by ronaldtse** [comment]
@opoudjis then is this "document language"-specific? i.e. CJK there is no empty space between separate lines?

**Comment by opoudjis** [comment]
Yes, it is document language specific. What is the alternative?

If you get into some crap about documents being multilingual, then I will have to overhaul how `noko()` is invoked.
