### ISSUE TITLE
URGENT: Terms and definitions: when a definition contains a `stem` inline, the definition is missing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#964]
From https://github.com/metanorma/iso-10303-2/issues/134

Source:
```adoc
==== curve

set of mathematical points which is the image, in two- or three-dimensional space, of a continuous function defined over a connected subset of the real line stem:[R^{1}], and which is not a single point
```

Rendered as HTML:
<img width="145" alt="Screenshot 2023-03-30 at 9 35 57 AM" src="https://user-images.githubusercontent.com/11865/228705375-58d1d11a-20e8-4a1b-98fd-12bc970dc647.png">

Notice the `stem:[R^{1}]` item became the "symbol" for the term, which is wrong.

**Comment by opoudjis** [comment]
A stem expression in a para on its own is a candidate alt term, but the XPath to detect such an expression was naive.

**Comment by opoudjis** [comment]
We can drop it, but we thought it was opportune shorthand five years ago...

**Comment by ronaldtse** [comment]
@opoudjis let's drop it now we have a more "proper" `alt:[...]`. Thank you!

**Comment by opoudjis** [comment]
We had put this in place as a workaround because we had the notion that `alt:[stem:[t_A]]` was illegal syntax in Asciidoctor. vi may think so, but that syntax parses fine, at least now.
