### ISSUE TITLE
PDF: ISO 10303-104: latexmath expression not rendered as MathML when inside a definition list

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#969]
```adoc
[latexmath%unnumbered]
++++
D' =
\left( \begin{array}{cc}
      h \, D_m    &        h \, p \, D_m  \\[2mm]
      h \, p \, D_m  &  {\displaystyle (\frac{1}{12} h^3 + h \, p^2) \, D_m  }
\end{array} \right)
++++

where:

stem:[D_m]:: is the membrane elasticity matrix, which for a isotropic material has the form:
+
--
[latexmath%unnumbered]
++++
D_m =  \frac{E}{(1 - \nu^2)} \:
   \left( \begin{array}{ccc}
         1 & \nu & 0 \\[2mm]
         \nu &  1  & 0  \\[2mm]
         0 & 0 & {\displaystyle \frac{(1 - \nu)}{2} }
      \end{array}   \right)
++++
--
```

Renders this:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/11865/229767603-bde4bac8-e2b2-4d22-bf5f-71b6a79ad756.png">

Notice the second equation is not rendered in math.

However, if I pull out the equation into a separate paragraph, it renders correctly.

```adoc
[latexmath%unnumbered]
++++
D' =
\left( \begin{array}{cc}
      h \, D_m    &        h \, p \, D_m  \\[2mm]
      h \, p \, D_m  &  {\displaystyle (\frac{1}{12} h^3 + h \, p^2) \, D_m  }
\end{array} \right)
++++

[latexmath%unnumbered]
++++
D_m =  \frac{E}{(1 - \nu^2)} \:
   \left( \begin{array}{ccc}
         1 & \nu & 0 \\[2mm]
         \nu &  1  & 0  \\[2mm]
         0 & 0 & {\displaystyle \frac{(1 - \nu)}{2} }
      \end{array}   \right)
++++


where:

stem:[D_m]:: is the membrane elasticity matrix, which for a isotropic material has the form:
+
[latexmath%unnumbered]
++++
D_m =  \frac{E}{(1 - \nu^2)} \:
   \left( \begin{array}{ccc}
         1 & \nu & 0 \\[2mm]
         \nu &  1  & 0  \\[2mm]
         0 & 0 & {\displaystyle \frac{(1 - \nu)}{2} }
      \end{array}   \right)
++++
```

<img width="637" alt="Screenshot 2023-04-04 at 7 42 44 PM" src="https://user-images.githubusercontent.com/11865/229767917-5a1b4bce-01fe-418d-b977-a1656bb19c03.png">

**Comment by ronaldtse** [comment]
Maybe the issue is more pronounced:

```adoc
[latexmath%unnumbered]
++++
D' =
\left( \begin{array}{cc}
      h \, D_m    &        h \, p \, D_m  \\[2mm]
      h \, p \, D_m  &  {\displaystyle (\frac{1}{12} h^3 + h \, p^2) \, D_m  }
\end{array} \right)
++++


where:

stem:[D_m]:: is the membrane elasticity matrix, which for a isotropic material has the form:
+
[latexmath%unnumbered]
++++
D_m =  \frac{E}{(1 - \nu^2)} \:
   \left( \begin{array}{ccc}
         1 & \nu & 0 \\[2mm]
         \nu &  1  & 0  \\[2mm]
         0 & 0 & {\displaystyle \frac{(1 - \nu)}{2} }
      \end{array}   \right)
++++


where:

stem:[E]:: is Young's modulus;

stem:[nu]:: is Poisson's ratio.
```

Here, there are actually 2 nested "where"s:
* The first where for the latexmath block
* The second where for the formula inside the stem:[D_m] definition list

So I tried encoding this in 2 levels:

```adoc
[latexmath%unnumbered]
++++
D' =
\left( \begin{array}{cc}
      h \, D_m    &        h \, p \, D_m  \\[2mm]
      h \, p \, D_m  &  {\displaystyle (\frac{1}{12} h^3 + h \, p^2) \, D_m  }
\end{array} \right)
++++

where:

stem:[D_m]:: is the membrane elasticity matrix, which for a isotropic material has the form:
+
--
[latexmath%unnumbered]
++++
D_m =  \frac{E}{(1 - \nu^2)} \:
   \left( \begin{array}{ccc}
         1 & \nu & 0 \\[2mm]
         \nu &  1  & 0  \\[2mm]
         0 & 0 & {\displaystyle \frac{(1 - \nu)}{2} }
      \end{array}   \right)
++++

where:

stem:[E]:: is Young's modulus;

stem:[nu]:: is Poisson's ratio.
--
```

And the whole 2nd level just collapsed into text:
<img width="518" alt="Screenshot 2023-04-04 at 8 06 20 PM" src="https://user-images.githubusercontent.com/11865/229773271-f1365800-e5c4-4c67-8a7b-5e9f31688f6a.png">

**Comment by ronaldtse** [comment]
So I've fixed it in the presentation, but the encoding is technically inaccurate. Here we are looking at nested "where" statements where the second "where" applies to the contents of the first "where".

<img width="552" alt="Screenshot 2023-04-04 at 8 11 08 PM" src="https://user-images.githubusercontent.com/11865/229774307-5c39dfbc-9b77-453c-a116-13b46c342190.png">

**Comment by opoudjis** [comment]
The initial expression renders fine in HTML, so I'm afraid this is a PDF issue.

@Intelligent2013 I am attaching the Presentation XML. Sadly, this is doing something I thought I was preventing, it is nesting formulas ---

formula/dl/dd/formula/

PDF is failing to process the nested formula.

**Comment by ronaldtse** [comment]
Thanks for the investigation @opoudjis !

@Intelligent2013 could you please help here? Thanks.
