### ISSUE TITLE
Index title should always be centered

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#977]
Index title is always in the center (left original, right Metanorma):
<img width="1583" alt="Screenshot 2023-04-12 at 9 15 42 AM" src="https://user-images.githubusercontent.com/11865/231322102-b2262fa2-a627-4145-963e-0766ef926a28.png">

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/231397611-c268807b-d28b-44da-a9ab-bcb3803ae4bc.png)
