### ISSUE TITLE
PDF: Preface page number missing some page numbers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#988]
This issue was discovered in https://github.com/metanorma/iso-10303-detached-docs/issues/173:

The preface page number jumped from 'ii' to 'iv' without a blank page in between.

<img width="445" alt="Screenshot 2023-04-25 at 8 35 00 PM" src="https://user-images.githubusercontent.com/11865/234338966-dcc6f2f4-cd89-4453-a5e8-9a1d8d493e04.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/iso-10303-detached-docs/issues/174#issuecomment-1522069133_

**Comment by Intelligent2013** [comment]
I have to update ISO XSLT to process empty `clause type="toc"`:
```xml
	<preface>
		<clause type="toc" id="_27549cd1-1c48-4300-8b0f-837f229aae76" displayorder="1">
			<title depth="1">Contents</title>
		</clause>
		<abstract id="_abstract" displayorder="2">
			<title>Abstract</title>
...
```

**Comment by Intelligent2013** [comment]
@ronaldtse I've looked at the file name [READY-20230316-no-toc-iso-10303-50-ACTIONED.pdf](https://github.com/metanorma/iso-10303-detached-docs/files/11289746/READY-20230316-no-toc-iso-10303-50-ACTIONED.pdf)
What does mean `no-toc`? ToC removed manually? Then this is the reason why page `iii` is missing. PDF doesn't have auto-page-numbering feature. Page numbers are hard-coded text.

**Comment by Intelligent2013** [comment]
Issue with empty 2nd Contents solved:
![image](https://user-images.githubusercontent.com/5559926/234353834-d5b2c479-a487-48ff-95d5-750df5e8d47f.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 ah yes you are correct -- the TOC was manually removed... by me. Thank you!!!
