### ISSUE TITLE
PDF: ISO 10303-55 missing vertical space after definition list if the cell is tall

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#990]
Reported by @HamousSS in:
* https://github.com/metanorma/iso-10303-detached-docs/issues/182

The missing line break issue is demonstrated in this screenshot:
<img width="700" alt="Screenshot 2023-04-28 at 5 23 01 AM" src="https://user-images.githubusercontent.com/11865/234994323-f5af3e7d-0eb4-47f4-8f89-565a9c873141.png">

Interestingly the code looks like this, which contains a line break before "Formal propositions:"
```adoc
Attribute definitions:

*SELF\representation_item_relationship.relating_representation_item:*:: an instance of *procedural_shape_representation_sequence* defining the procedural representation of a model element.
*SELF\representation_item_relationship.related_representation_item:*:: an explicitly defined shape model element corresponding to the result of evaluating the procedural definition.

Formal propositions:

*WR1:*:: The instance of *representation_item* referenced by the attribute *SELF\representation_item_relationship.related_representation* shall not be of type *procedural_shape_representation_sequence*.

Informal propositions:

*IP1:*:: The explicit model element shall be the result of evaluating the procedurally defined model element with the current values of all its parameters.
```

This missing line break only appears in the PDF and Word versions:

Word:
<img width="814" alt="Screenshot 2023-04-28 at 5 25 40 AM" src="https://user-images.githubusercontent.com/11865/234994795-14a04061-6559-45cd-bb53-0be441d6921a.png">

HTML:
<img width="908" alt="Screenshot 2023-04-28 at 5 24 58 AM" src="https://user-images.githubusercontent.com/11865/234994660-997ed7f7-5428-46cf-a100-f7369072c5a6.png">

I think this has to do with the layout of definition lists in Word (but it shares code with HTML) and PDF. 

This is not a bug in the encoding but an issue with the PDF layout. We will investigate.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/235119610-d2a0c25c-4b92-4aa6-be98-0a71c3d0623b.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

**Comment by ronaldtse** [comment]
Confirmed using the Git version. 

<img width="525" alt="Screenshot 2023-05-07 at 11 58 30 AM" src="https://user-images.githubusercontent.com/11865/236656875-049d1828-1aca-4bec-9589-47c8771f9fbf.png">
