### ISSUE TITLE
ISO/TC 171/SC 2 feedback: Metanorma should not warn years (YYYY) as number pattern 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#995]
ISO DIR 2 specifically excludes year/date patterns from number grouping.

These false warnings are too annoying.

**Comment by opoudjis** [comment]
Absent `date:[]` markup, we don't know when a number is a date and when it is not. Do you want me to exclude say 1900 through 2050 from number pattern warnings?

**Comment by ronaldtse** [comment]
Then let’s do the explicit markup, as we have long suggested.

**Comment by opoudjis** [comment]
````
== Validation

`:validate-years:`:: If not set, four-digit numbers that could plausibly be years (between 1900 and 2050)
are not warned about. If set, they are included in validation.
````

**Comment by opoudjis** [comment]
Promoted relevant ticket for date:[] to In Progress
