### ISSUE TITLE
PDF tagging: poor tagging of ISO cover page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#999]
From:
* https://github.com/metanorma/mn2pdf/issues/201

The tagging of the cover page of ISO standards is really bad... 

For something fixed like the ISO cover page can probably get a professional remediator to manually tag the page for "best PDF/UA-1 compliance" and then give it back to you to reverse engineer...?

**Comment by Intelligent2013** [comment]
> For something fixed like the ISO cover page can probably get a professional remediator to manually tag the page for "best PDF/UA-1 compliance" and then give it back to you to reverse engineer...?

Yes, it would be very helpful. Thanks.

**Comment by Intelligent2013** [comment]
> The tagging of the cover page of ISO standards is really bad...

Actually, the tagging was set without any requirements, therefore we have such result.

**Comment by Intelligent2013** [comment]
ISO Cover page tags tree updated:
- table's tags removed
- tags structure flattened

There are empty tags. The fixing is planning in https://github.com/metanorma/metanorma-iso/issues/1003#issuecomment-1604320625.

PDF example: [rice-en.final.presentation.pdf](https://github.com/metanorma/metanorma-iso/files/11849137/rice-en.final.presentation.pdf)

**Comment by Intelligent2013** [comment]
Latest PDF: [rice-en.final.presentation.pdf](https://github.com/metanorma/metanorma-iso/files/11857241/rice-en.final.presentation.pdf)
